### ISSUE TITLE
Daggerfall Unity Update

### ISSUE THREAD

**Issue by madscientist16** [luxtorpeda-dev/packages#1003]
### Project Link

https://github.com/Interkarma/daggerfall-unity

### Project License

MIT License

### Steam App Ids

https://steamdb.info/app/1812390/

### Additional Context

It has a new release.
https://github.com/Interkarma/daggerfall-unity/releases/tag/v0.16.0-rc

**Comment by d10sfan** [comment]
Thanks for the issue, I've implemented the new version
