### ISSUE TITLE
WOLF3D/ecwolf: Error – choices array does not contain engine choice

### ISSUE THREAD

**Issue by InklingGirl** [luxtorpeda-dev/packages#1004]
### Game

_Wolfenstein 3D_

### Engine

`ecwolf`

### Linux Distribution

SteamOS

### Luxtorpeda Version

67.0.0

### Bug description

Pretty simply as the title says. Luxtorpeda v67.0.0 was installed via ProtonUp-Qt, but `ecwolf` does not launch.

### Steps To Reproduce

1. Install via ProtonUp-Qt Flatpak
2. Set Luxtorpeda as _Wolfenstein 3D_'s compatibility layer in Steam
3. Launch _Wolfenstein 3D_

### Expected Behavior

For `ecwolf` to launch.

### Additional Context

On a Steam Deck.

**Comment by d10sfan** [comment]
Are you using Wolfenstein 3D from steam, or a non-steam shortcut?

**Comment by InklingGirl** [comment]
It's from Steam.

**Comment by d10sfan** [comment]
Interesting, it's working ok for me.

Can you add `LUX_WRITE_LOGGING=1 %command%` to the launch options of the game, and  then try running it again?

Then if you go to desktop mode, there should be a file at ~/.local/state/luxtorpeda/luxtorpeda.log if you could attach it here. Thanks!

**Comment by InklingGirl** [comment]
[luxtorpeda.log](https://github.com/luxtorpeda-dev/packages/files/12740027/luxtorpeda.log)

**Comment by d10sfan** [comment]
Ah I see, it looks like you have a default choice and we've renamed a few of them. You should be able to remove the default choice (and then you can re-create it once you see the choices menu), by either canceling when it does the countdown, or removing the file in `~/.config/luxtorpeda/<app_id>/default_engine_choice.txt`

**Comment by InklingGirl** [comment]
Thank you, that fixed it! Also, I note that it gave me an option to choose `ecwolf` for WOLF3D or SoD, so I picked the former, but when I repeated this process for SoD in my Steam library Luxtorpeda gave me no such option & it just booted into `ecwolf`. Is that expected behaviour?

**Comment by InklingGirl** [comment]
Also, this can of course be closed.

**Comment by d10sfan** [comment]
Yes, I believe SoD on steam only provides one game asset, so there's only one option. 

And glad it's working for you now!
