### ISSUE TITLE
Stracciatella engine for Jagged Alliance 2 Gold

### ISSUE THREAD

**Issue by rea987** [luxtorpeda-dev/packages#1010]
### Project Link

https://ja2-stracciatella.github.io/

### Project License

https://github.com/ja2-stracciatella/ja2-stracciatella/blob/master/README.md

### Steam App Ids

- https://steamdb.info/app/1620/

### Additional Context

https://ja2-stracciatella.github.io/how-to-run/

luxtorpeda-dev currently supports Classic and Wildfire. Stracciatella installation guide points support for Gold. Can Gold version be included please? Cheers!

**Comment by d10sfan** [comment]
I've added that in https://github.com/luxtorpeda-dev/packages/commit/494ee741128c70262806e253c3d68d825801b19e, thanks. Let me know if you run into any issues.
