### ISSUE TITLE
I don't know if this ais an issue with open lara or the tool, but tomb raider I is missing the main menu background

### ISSUE THREAD

**Issue by F3arM3** [luxtorpeda-dev/packages#1011]
### Linux Distribution

Ubuntu 22.04.3 LTS

### Luxtorpeda Version

67.0.0

### Bug description

The main menu has no background, just the icons floating in a black void

### Steps To Reproduce

1. Install luxtorpeda with proton up qt
2. set it as configuration tool in tomb raider I
3. Launch the game

### Expected Behavior

There should be a picture of lara's face on the main menu

**Comment by d10sfan** [comment]
Thanks for the issue! This should be fixed in https://github.com/luxtorpeda-dev/packages/commit/3c82f25adf8e14e103d95332fad88ff034358988

Once the action build is complete (should be a few minutes after this commit), can you try again and see?

**Comment by F3arM3** [comment]
yep, that fixed it thanks
