### ISSUE TITLE
Dominatrix for SiN

### ISSUE THREAD

**Issue by Jpxe** [luxtorpeda-dev/packages#1013]
### Project Link

https://cohost.org/rohit/post/3207148-release-dominatrix

### Project License

Proprietary/Closed Source

### Steam App Ids

- https://steamdb.info/app/1313/

### Additional Context

For now it’s only on itch but the developer don’t mind putting it on GitHub so it should be possible to add to Luxtorpeda as soon as the binary is available here.
He might release the source in the future, at the moment it’s closed.

**Comment by rohit-n** [comment]
Just uploaded the binaries.

https://github.com/rohit-n/dominatrix/releases/tag/v1

**Comment by d10sfan** [comment]
@Jpxe I've added the port, thanks for the link!

Can you try this out and let me know if it works? I don't own the game, but this should work.

If it does not work, please provide a log showing what went wrong.

**Comment by rohit-n** [comment]
Thanks for adding my port, but I noticed that the entry says that the engine does not have controller support. This is not the case - it uses the SDL2 Game Controller API to handle gamepad input. There's even some features to make the game more playable on a controller, like a radial menu and on-screen keyboard for certain sections.

**Comment by Jpxe** [comment]
@d10sfan I encountered an error when launching it; "invalid gzip header." Here's the log file for more details: [testing_lux_sin_gold.log](https://github.com/luxtorpeda-dev/packages/files/13304714/testing_lux_sin_gold.log)

@rohit-n, I'm planning to give it a shot on my desktop using my DualSense and on my Steam Deck once it's up and running in Luxtorpeda. This will help ensure everything runs smoothly both within Luxtorpeda and the Steam runtime. We'll make sure to update the engine information on the webpage to reflect that the controller works seamlessly.

Quick question: Is there any advantage to checking the controller type or if the user is on a Steam Deck? Should we tweak the config files for different controller layouts, screen resolutions, and on-screen controllers, or does the engine handle it automatically? Also, any info on Steam Cloud saves compatibility?

**Comment by d10sfan** [comment]
@Jpxe Can you verify that the file size of the cached file is the same as if you download it yourself?

If it is, there may be something strange about how the archive was created.

**Comment by d10sfan** [comment]
@rohit-n 

It looks like the issue is that the archive is named .tar.gz but it isn't actually a gzip archive, but a .tar. 

https://stackoverflow.com/questions/15744023/how-to-extract-filename-tar-gz-file

```
file dominatrix-linux-v1-x86_64.tar.gz 
dominatrix-linux-v1-x86_64.tar.gz: POSIX tar archive (GNU)
```

If that's the case, could you re-upload it as a gzipped archive, with the .tar.gz extension? Then it should work.

**Comment by d10sfan** [comment]
If there's some testing on the controller once the archive issue is fixed, I can update the metadata, or feel free to open a pull request, related to the controller supported.

**Comment by Jpxe** [comment]
> @Jpxe Can you verify that the file size of the cached file is the same as if you download it yourself?
> 
> If it is, there may be something strange about how the archive was created.

I compared the cached file to the github download as well as the itch.io download and they all seem to be the same file:
```bash
[jpx@localhost 1313]$ pwd
/home/jpx/.cache/luxtorpeda/1313
[jpx@localhost 1313]$ diff dominatrix-linux-v1-x86_64.tar.gz github-dl-dominatrix-linux-v1-x86_64.tar.gz 
[jpx@localhost 1313]$ diff dominatrix-linux-v1-x86_64.tar.gz itch-dl-dominatrix-linux-v1-x86_64.tar.gz 
[jpx@localhost 1313]$ cmp dominatrix-linux-v1-x86_64.tar.gz github-dl-dominatrix-linux-v1-x86_64.tar.gz && cmp dominatrix-linux-v1-x86_64.tar.gz itch-dl-dominatrix-linux-v1-x86_64.tar.gz 
[jpx@localhost 1313]$ ls -lah
totalt 20M
drwxr-xr-x 1 jpx jpx  282 10 nov 07.26 .
drwxr-xr-x 1 jpx jpx  264 10 nov 07.23 ..
-rw-r--r-- 1 jpx jpx   64 10 nov 07.23 diminatrix-binaries.hash
-rw-r--r-- 1 jpx jpx 6,7M 10 nov 07.23 dominatrix-linux-v1-x86_64.tar.gz
-rw-r--r-- 1 jpx jpx 6,7M 10 nov 07.26 github-dl-dominatrix-linux-v1-x86_64.tar.gz
-rw-r--r-- 1 jpx jpx 6,7M 10 nov 07.26 itch-dl-dominatrix-linux-v1-x86_64.tar.gz
```



There seems to be a spelling error for the file `diminatrix-binaries.hash` here. I think it's in the metadata `"name": "diminatrix-binaries",` , on [line 8140 in packagessniper_v2.json](https://github.com/luxtorpeda-dev/packages/blob/de2b89371f7bf852277c1c562f990de6de64196b/metadata/packagessniper_v2.json#L8140C51-L8140C51).

**Comment by Jpxe** [comment]
> @rohit-n
> 
> It looks like the issue is that the archive is named .tar.gz but it isn't actually a gzip archive, but a .tar.
> 
> https://stackoverflow.com/questions/15744023/how-to-extract-filename-tar-gz-file
> 
> ```
> file dominatrix-linux-v1-x86_64.tar.gz 
> dominatrix-linux-v1-x86_64.tar.gz: POSIX tar archive (GNU)
> ```
> 
> If that's the case, could you re-upload it as a gzipped archive, with the .tar.gz extension? Then it should work.

I confirmed this as well

Doing a `tar -xzf` confirms the file is not compressed and gives an error:

```bash
[jpx@localhost 1313]$ tar -xzf dominatrix-linux-v1-x86_64.tar.gz 

gzip: stdin: not in gzip format
tar: Child returned status 1
tar: Error is not recoverable: exiting now
```

However using the command for extracting uncrompressed .tar files works:
```bash
[jpx@localhost 1313]$ tar -xf dominatrix-linux-v1-x86_64.tar.gz 
[jpx@localhost 1313]$ ls
2015  diminatrix-binaries.hash           github-dl-dominatrix-linux-v1-x86_64.tar.gz  ref_gl.so
base  dominatrix-linux-v1-x86_64.tar.gz  itch-dl-dominatrix-linux-v1-x86_64.tar.gz    sin
```

**Comment by rohit-n** [comment]
That's embarrassing.

I have re-uploaded the binaries. Let me know if the work.

https://github.com/rohit-n/dominatrix/releases/tag/v1

**Comment by d10sfan** [comment]
Thanks!

@Jpxe Could you retry and see if it works?

**Comment by Jpxe** [comment]
@d10sfan @rohit-n now it works!

**Comment by d10sfan** [comment]
Great!
