### ISSUE TITLE
no cutscenes in tomb raider I

### ISSUE THREAD

**Issue by F3arM3** [luxtorpeda-dev/packages#1021]
### Game

Tomb Raider I

### Engine

Open Lara

### Linux Distribution

Ubuntu 22.04.3 LTS

### Luxtorpeda Version

67.0.0

### Bug description

Tomb Raider I has no cutscenes when using open lara

### Steps To Reproduce

1. set up luxtorpeda in proton up qt
2. set tomb raider I to use luxtorpeda
3. launch the game

### Expected Behavior

I should see cutscenes of the core design logo, the explosion that frees natla and lara getting hired by her, lara shooting wolves, etc.

### Additional Context

I don't know if they are meant to be here, since they are present on the android version but not the browser version of open lara. if this isn't a bug please close this thread

**Comment by d10sfan** [comment]
@F3arM3 Can you provide a log of the run? The easiest way to do this is to run steam in terminal and  then copy and paste the output to a file.

This will see if there's any errors from the game engine.

**Comment by F3arM3** [comment]
I managed to get it running from terminal but I have no idea what you mean by a log of the run. can you tell me what I should look for and where I might find it?

**Comment by d10sfan** [comment]
When you run steam from the terminal, the output will be in the terminal window. scroll to where you started the game and copy and paste the output to a file and upload it here.

**Comment by d10sfan** [comment]
Did you exit steam first? You need to exit steam, then run steam via terminal, and then run the game.

**Comment by F3arM3** [comment]
it says the same thing, what command should I use? I have been using "steam steam://run/224960" to run tomb raider from terminal or the command "steam" which opens the app which has the same output in terminal and then opening tomb raider adds nothing to the terminal

**Comment by d10sfan** [comment]
If that is all you are getting in the terminal window, then it means steam is already running. You'll need to completely exit out of steam, then run steam through the terminal, then launche the game with steam.

**Comment by F3arM3** [comment]
[tomb.zip](https://github.com/luxtorpeda-dev/packages/files/13344051/tomb.zip)

**Comment by d10sfan** [comment]
Thanks, that looks like a good start. Did you try something that would start a cutscene?

**Comment by F3arM3** [comment]
there is supposed to be one before you even get to the main menu

**Comment by d10sfan** [comment]
Could you try loading a level where you expect one and then provide a log of that? Curious if there's any errors that show up

**Comment by d10sfan** [comment]
Thanks for the help here. The cutscenes should now work, you'll also need a client update for luxtorpeda as well (67.1.0).

The loading screens appear to be missing from the steam assets (the ones that are supposed to show up after the cutscene), but the title screen background works, so minor issue.

Let me know how it goes for you.
