### ISSUE TITLE
Engge> Engge2 update

### ISSUE THREAD

**Issue by xcom169** [luxtorpeda-dev/packages#1022]
### Project Link

https://github.com/scemino/engge2

### Project License

N/A

### Steam App Ids

https://store.steampowered.com/app/569860/Thimbleweed_Park/

### Additional Context

Engge has been replaced by Engge2 which is newer.

it would be nice if you added the engine and link to this issue to the wiki: https://github.com/dreamer/luxtorpeda/wiki/Game-engines

**Comment by d10sfan** [comment]
Do you know what the license for this engine is? I sadly don't feel comfortable with supporting unless we figure that out.

Note that the dreamer/luxtorpeda repo is old and not maintained, this fork is the one that is up to date.
