### ISSUE TITLE
 Knights and Merchants remake engine for Windows + Linux

### ISSUE THREAD

**Issue by xcom169** [luxtorpeda-dev/packages#1023]
### Project Link

https://github.com/Kromster80/kam_remake

### Project License

 AGPL 3

### Steam App Ids

- https://store.steampowered.com/app/253900/Knights_and_Merchants/

### Additional Context

Linux version will need to be installed in the same Proton prefix as the main game. No official Linux version released, but the engine work fine in Wine/Proton.

**Comment by d10sfan** [comment]
It does not look like there's a native version of this engine for Linux. The engines here all need to have native Linux versions, not running through wine, but thanks for the ticket.

If they add a Linux version in the future, I'll re-visit adding this engine.
