### ISSUE TITLE
Russian Doom (formerly International Doom 6.x)

### ISSUE THREAD

**Issue by mkasick** [luxtorpeda-dev/packages#1024]
### Project Link

https://github.com/Russian-Doom/russian-doom

### Project License

GPL-2.0

### Steam App Ids

- https://steamdb.info/app/2280/
- https://steamdb.info/app/2290/
- https://steamdb.info/app/2300/
- https://steamdb.info/app/2360/
- https://steamdb.info/app/2370/
- https://steamdb.info/app/2390/

### Additional Context

This is the official continuation of the Russian/International Doom 6.x project.  Specifically, it includes support for Heretic and Hexen, which was dropped with the International Doom 7.0 update (and broken since the release of inter-doom-common-12).

See https://www.doomworld.com/forum/topic/141262-russian-doom-63-october-29-2023/.

**Comment by d10sfan** [comment]
Thanks, this has been implemented, and Ive removed the broken inter-doom for hexen/heretic. Let me know how it goes for you
