### ISSUE TITLE
controller is still broken in tomb raider I

### ISSUE THREAD

**Issue by F3arM3** [luxtorpeda-dev/packages#1027]
### Game

Tomb Raider I

### Engine

Open Lara

### Linux Distribution

Ubuntu 22.04.3 LTS

### Luxtorpeda Version

67.1.1

### Bug description

like before the game is not picking up inputs B, R+L Shoulder, R+L Trigger, and the right analogue stick

### Steps To Reproduce

update to version 67.1.0 or later

### Expected Behavior

I should be able to roll, walk, look around, etc but it doesn't happen

### Additional Context

Same as this issue
https://github.com/luxtorpeda-dev/packages/issues/1026
Also it now no longer works with 67.0.0

**Comment by d10sfan** [comment]
You don't need to create a new ticket for this, can you provide a log?

**Comment by d10sfan** [comment]
duplicate
