### ISSUE TITLE
Steam Deck: Error on run: Path to Steam Linux Runtime not given.

### ISSUE THREAD

**Issue by Renari** [luxtorpeda-dev/packages#1028]
**Describe the bug**
When trying to run a game using nw.js I get the error `Error on run: Path to Steam Linux Runtime not given`.  I don't see anywhere to configure this and reading through the config guide and the wiki I'm not finding anything that says how or where you should configure this path.

**To Reproduce**
Steps to reproduce the behaviour:
1. Install steam linux runtime sniper
2. Try to launch game with nw.js
3. claims it cannot find runtime

**Comment by d10sfan** [comment]
What version of luxtorpeda are you using?

And do you have the steam linux runtime (scout) installed?

**Comment by Renari** [comment]
Yes I have all 3 versions of the steam linux runtime installed and I'm using Luxtorpeda 67.1.1.

**Comment by d10sfan** [comment]
Can you run steam in a terminal window, then try running the game again and attach the output here?

**Comment by Renari** [comment]
Ah, when lauching in desktop mode a dialog popped up asking to locate the runtime installation directory, after selecting it it seems everything is now working. I guess that dialog was unable to be opened in gamemode.

**Comment by d10sfan** [comment]
Interesting, that's the legacy way if it's unable to find it automatically, it's possible that it wasn't able to find it automatically if the tools were installed in a different steam storage.

But glad it's working for you now

**Comment by Renari** [comment]
I did have it installed in the default location `~/.steam/steam/steamapps/common/SteamLinuxRuntime`.
