### ISSUE TITLE
Jagged Alliance 2 Wildfire Classic DLC not being detected properly...

### ISSUE THREAD

**Issue by Ronald-Diemicke** [luxtorpeda-dev/packages#1032]
### Game

Jagged alliance 2 Wildfire w/ Classic DLC

### Engine

Jagged Alliance 2 Stracciatella

### Linux Distribution

Steamdeck

### Luxtorpeda Version

Latest

### Bug description

When using Jagged Alliance 2 Wildfire with the classic DLC, [Stracciatella](https://ja2-stracciatella.github.io/) is not detected and give the error msg "Error on run: Classic DLC for Wildfire not found. Both Wildfire and Classic DLC are required." Note that launching wildfire works fine.

### Steps To Reproduce

Install Jagged Alliance 2 Wildfire with Classic DLC
Change launcher to luxtorpeda
Run Wildfire, but choose Jagged Alliance 2 Classic

### Expected Behavior

Should install [Stracciatella](https://ja2-stracciatella.github.io/) automatically and run it.

**Comment by d10sfan** [comment]
Do you own the classic dlc for wildfire like the error says? And do you have it installed?

**Comment by d10sfan** [comment]
Also what happens if you choose the default launch option instead of classic?

**Comment by Ronald-Diemicke** [comment]
I own the classic DLC and it's installed; If I choose to only launch
Wildfire, it does pick up the correct launcher and seems to run fine.

**Comment by d10sfan** [comment]
Ok thanks, that was probably because the pathing is different on the classic option.
