### ISSUE TITLE
ironwail: Missing ironwail.pak 

### ISSUE THREAD

**Issue by mkasick** [luxtorpeda-dev/packages#1033]
### Game

Quake

### Engine

Ironwail

### Linux Distribution

Steam OS 3.5.7

### Luxtorpeda Version

v67.1.1

### Bug description

Ironwail includes its own PAK file ("Quake/ironwail.pak" in the source tree) that's supposed to be installed alongside the engine.  It includes map fixes and graphics lumps for the Mods and Skill menus.  However it's missing from the luxtorpeda distribution.

You should be able to copy ironwail.pak from the source tree to either the exedir ("ironwail") or the basedirs ("ironwail/share/quake", "ironwail/share/quake/rerelease") to fix this.  You can tell it's working by the inclusion of the "Mods" submenu in the main menu.

### Steps To Reproduce

Install Quake and run Ironwail or Ironwail Re-release as the engine.  Open the main menu, observe missing "Mods" submenu.

### Expected Behavior

"ironwail.pak" is included and the "Mods" submenu appears within the main menu.

**Comment by d10sfan** [comment]
Thanks for the issue, the ironwail.pak file is now included, let me know if you run into any issues.
