### ISSUE TITLE
Unreal Gold no longer runs - “Unreal Linux Not Found” error

### ISSUE THREAD

**Issue by Arkaium** [luxtorpeda-dev/packages#1035]
### Linux Distribution

Steam OS 3.5.7

### Luxtorpeda Version

67.1.1

### Bug description

Unreal Gold no longer starts, both 32bit and 64bit option (I assume if they worked I’d use the latter on Steam Deck) give this error:

“Error on run: Unreal Linux not found.”

### Steps To Reproduce

Running the game using Luxtorpeda. Either option (32 or 64-bit) give this error.

### Expected Behavior

The game used to load on earlier versions on Steam OS.

**Comment by d10sfan** [comment]
Ah ok, let me know if you continue to have issues, in this issue, and I can take a look.
