### ISSUE TITLE
Can you add Tomb1main aka tr1x as a selectable engine for tomb raider

### ISSUE THREAD

**Issue by F3arM3** [luxtorpeda-dev/packages#1040]
### Project Link

https://github.com/LostArtefacts/TR1X

### Project License

Public Repository

### Steam App Ids

224960

### Additional Context

Another open source tomb raider project based on a reverse engineered version of th original engine so it more closely resembles the ps1 game. Also it still being supported and supports the unfinished business levels

I hope it is possible to add this in such a way that you can choose between the engines

**Comment by d10sfan** [comment]
I don't support reverse engineering projects because of the possible legal issues with them: https://github.com/luxtorpeda-dev/packages/blob/master/docs/Creating_a_Package.md#creating-a-package

So because of that I won't be adding it. Thanks for the issue though!
