### ISSUE TITLE
DREAMM as the default engine for Star Wars: Dark Forces

### ISSUE THREAD

**Issue by ThrashPanda666** [luxtorpeda-dev/packages#1044]
### Project Link

https://aarongiles.com/dreamm/

### Project License

Unknown

### Steam App Ids

http://steamdb.info/app/32400

### Additional Context

I've tested Dark Forces through the selectable DREAMM on luxtorpeda and it is playable.

**Comment by d10sfan** [comment]
@ThrashPanda666 See if this works, I don't own the game, but this should make it the engine for that game.

If you have issues, let me know. Thanks!
