### ISSUE TITLE
Prboom+ no miusic

### ISSUE THREAD

**Issue by F3arM3** [luxtorpeda-dev/packages#1045]
### Game

Doom

### Engine

PRBoom+

### Linux Distribution

Ubuntu 22.04.3 LTS

### Luxtorpeda Version

67.1.2

### Bug description

No music

### Steps To Reproduce

select pr boom as engine to run doom in

### Expected Behavior

music

**Comment by d10sfan** [comment]
@F3arM3 Did you follow this step in the description of the engine?

Pick FluidSynth in in-game options to hear music. 

As well, can you provide a log file?

**Comment by d10sfan** [comment]
I've confirmed I can hear the music, so make sure that you pick FluidSynth, and if that does not work, please provide a log file.

**Comment by F3arM3** [comment]
that worked
