### ISSUE TITLE
R.E.L.I.V.E Engine for Oddworld: Abe's Oddysee and Oddworld: Abe's Exoddus

### ISSUE THREAD

**Issue by KayKay91** [luxtorpeda-dev/packages#1046]
### Project Link

https://aliveteam.github.io/

### Project License

GPL-compatible

### Steam App Ids

https://store.steampowered.com/app/15710/Oddworld_Abes_Exoddus/
https://store.steampowered.com/app/15700/Oddworld_Abes_Oddysee/

### Additional Context

The engine by default will launch in windowed.

**Comment by d10sfan** [comment]
Please see https://github.com/luxtorpeda-dev/packages/issues/737

Since this is a reverse engineering project, I tend to avoid those, so I won't plan on adding it.

Thank you for the ticket though.
