### ISSUE TITLE
Add Syberia 1/2 (but only from the MacOS release files)

### ISSUE THREAD

**Issue by neuromancer** [luxtorpeda-dev/packages#1051]
ScummVM support [Syberia 1](https://wiki.scummvm.org/index.php?title=Syberia) and [Syberia 2](https://wiki.scummvm.org/index.php?title=Syberia_II), but only using the MacOS versions. This requires [to force Steam to the files download from MacOS, even from Linux](https://wiki.scummvm.org/index.php?title=Download_for_other_OS_from_Steam_HOWTO). Is this something luxtorpeda can do?

**Comment by d10sfan** [comment]
The way the compatibility tool works is that steam lets you decide that it's a Linux tool going to Windows, so its hardcoded to that currently.

So not sure of an easy way to do this. Do you know what's special about the Mac version versus Windows? Is that planned to be supported in the Future?

**Comment by d10sfan** [comment]
There may be a way to have an extra tool folder with the vdf saying mac to Linux

You could try that and restart steam and see if it works

**Comment by neuromancer** [comment]
The MacOS release of Syberia was easier to reverse engineer that the Windows release. Unfortunately, no one is working on the reimplementing the Windows versions right now :disappointed: . I will try your recommendation and report back my results here.
