### ISSUE TITLE
Odamex SDL version conflict

### ISSUE THREAD

**Issue by Fireb3rt** [luxtorpeda-dev/packages#1052]
### Game

Doom 2

### Engine

Odamex

### Linux Distribution

Arch Linux

### Luxtorpeda Version

v67.2.0

### Bug description

Attempting to launch the Odamex engine for Doom 2 crashes on startup with this error: 
> Odamex 10.3.0 Fatal Error
SDL version conflict (2.26.5 vs 2.28.5 dll)
Last SDL Error:
Invalid audio device ID

### Steps To Reproduce

1. Open Doom 2 with Luxtorpeda
2. Choose "Odamex" engine

### Expected Behavior

Doom 2 is loaded

**Comment by d10sfan** [comment]
I believe this is fixed now, can you confirm?
