### ISSUE TITLE
Meta issue: review all the ports from MacSourcePorts.com

### ISSUE THREAD

**Issue by neuromancer** [luxtorpeda-dev/packages#1057]
There are a lot of projects in [MacSourcePorts](https://www.macsourceports.com/) that are open-source and could be added to luxtorpeda (except the ones that are based on decompiled code). We should review this long list and create individual issues for the missing one.

**Comment by d10sfan** [comment]
Thanks, I took a quick scan of this list and didn't see anything that either wasn't already supported, a non-steam game, or a decompilation project. But let me know if there's anything I missed, thanks!
