### ISSUE TITLE
GZDoom for Beyond Sunset

### ISSUE THREAD

**Issue by rea987** [luxtorpeda-dev/packages#1062]
### Project Link

https://github.com/coelckers/gzdoom

### Project License

GPLv3

### Steam App Ids

https://steamdb.info/app/1665260/

### Additional Context

https://steamcommunity.com/app/1665260/discussions/0/3418808914584936632/

**Comment by d10sfan** [comment]
Added in https://github.com/luxtorpeda-dev/packages/commit/a37e445d1767363f1ee9d5860fd0096bfa28bef3
