### ISSUE TITLE
Unreal Tournament GOTY: Cannot use text input for menus, console, and chat.

### ISSUE THREAD

**Issue by Shockwave508** [luxtorpeda-dev/packages#1064]
### Game

Unreal Tournament: Game of the Year Edition

### Engine

ut99

### Linux Distribution

SteamOS v3.5.13 Preview

### Luxtorpeda Version

v68.0.0

### Bug description

I cannot seem to use my Steam Deck's on-screen keyboard to interact with menus, use console commands, and use text chat.

### Steps To Reproduce

Try typing into any text field in-game with the keyboard, and note how it fails to register.

### Expected Behavior

Any and all text fields would behave normally, no matter what.

### Additional Context

This issue did not occur with Unreal Gold.

**Comment by d10sfan** [comment]
Does adding SteamDeck=0 %command% to the launch options in steam help? This sounds like that bug again, that isn't our bug, but something wrong in SteamOS or SDL.

**Comment by d10sfan** [comment]
There's an open ticket on the steamos repo about it, that should point to it being fixed in the future. I am thinking about enabling that for the client in general, but not sure if there's any bad side effects to doing so.
