### ISSUE TITLE
Unreal Tournament 2004: Use 333Networks master-servers instead of OpenSpy?

### ISSUE THREAD

**Issue by Shockwave508** [luxtorpeda-dev/packages#1065]
Given how 333Networks has its own server-list, and incorporates OpenSpy's listings into it, would it be feasible to switch to the former in the future? The following would need to be changed in UT2004.ini: 

> [IpDrv.MasterServerLink]
> LANPort=11777
> LANServerPort=10777
> MasterServerList=(Address="ut2004master.333networks.com",Port=28902)
> MasterServerList=(Address="ut2004master.errorist.eu",Port=28902)

The second listed server is in case the first one goes down somehow; they are one and the same.
https://333networks.com/instructions/ut2004

**Comment by d10sfan** [comment]
Thanks for the suggestion, this will be live shortly. Note that this would require you to either manually edit your config, or to reset it to let it recreate it.
