### ISSUE TITLE
AvP crashes on launch with german language - probably umlauts related

### ISSUE THREAD

**Issue by frostworx** [luxtorpeda-dev/packages#107]
I also built the binary with debug mode based on the sources here:
https://github.com/neuromancer/avp
and the binary has the same problem.
Also opened an issue here
https://github.com/neuromancer/avp/issues/8

**Comment by d10sfan** [comment]
I switched the avp build to use https://github.com/neuromancer/avp as it seems a bit more up to date. I had a question related to the engine itself which I'll ask in the ticket.

I'll close this for now, and if there's a resolution in the engine itself, I'll make sure to update it here as well.

**Comment by d10sfan** [comment]
@frostworx 

Solved in https://github.com/luxtorpeda-dev/packages/commit/bf973030aa41a957ca25dbdf621cfa355558293c

The next time you run the game under Luxtorpeda (Runtime), this should be fixed.

**Comment by frostworx** [comment]
thx for the fix @d10fan.

Just wanted to test it with luxtorpeda-37, but I only get
```
$ ~/.steam/steam/compatibilitytools.d/luxtorpeda/luxtorpeda manual-download 3730
update_packages_json. "~/.cache/luxtorpeda/packages.json" does not exist
update_packages_json. downloading new packages.json
update_packages_json. new downloaded hash does not match
read err: Os { code: 2, kind: NotFound, message: "No such file or directory" }
Error: Custom { kind: Other, error: "missing info about this game" }
```

_(a 0 byte packages-temp.json)_ appears and vanishes in `~/.cache/luxtorpeda/` while the command is running.

**Comment by d10sfan** [comment]
@frostworx Could you try by launching the game through steam and picking luxtorpeda (runtime)? I'll look into that, looks like the package.json isn't working quite right for the original.

**Comment by d10sfan** [comment]
@frostworx I fixed the issue with the hash error. Note that the one you are downloading currently will use the older one, called "original". I believe the download will use the newer runtime if you put runtime_ in front of it,  but let me know if not.

**Comment by frostworx** [comment]
@d10sfan:
I can confirm that `"Luxtorpeda (Runtime)"` downloads `avp-3730-7.tar.xz` _(md5 f7c48107fd964996b8239288427db8ea)_
and the game starts correctly in german. "Luxtorpeda" (Original) pulls  `avp-3730-5.tar.xz` _(abaf974363a8926e76de17d71e2433f3)_, which does not work with german language.

**Comment by d10sfan** [comment]
@frostworx Ok, the original one is in a freeze, meaning that the plan is to eventually deprecate it and replace with the runtime.

For your manual way of doing it with the tinker tool, does runtime_manual-download work to download the runtime version?

**Comment by frostworx** [comment]
starting the luxtor tool with args `runtime_manual-download 3730`
leads to a `Download of avp Error: Progress not implemented`
with following stdout
```
run with runtime cmd: "runtime_manual-download"
update_packages_json. found hash: blah
update_packages_json. found hash and remote hash:  blah
user_packages_file not found
active_dialog_command. using gtk.
show license warning. dialog was accepted
progress_command ["--progress", "--title=Download Progress", "--percentage=100", "--text=Downloading..."]
download_all. warning: progress not started
starting download on: 0 avp
download_all. warning: progress not updated
download target: "https://github.com/luxtorpeda-dev/packages/releases/download/avp-5/avp-3730-5.tar.xz"
download 1%: 64437 out of 6346376
download of avp error: Progress not implemented
download. warning: progress not closed
active_dialog_command. using gtk.

```

**Comment by d10sfan** [comment]
@frostworx What version of the client are you running?

**Comment by frostworx** [comment]
`luxtorpeda-37` as written above, @d10sfan

**Comment by d10sfan** [comment]
@frostworx Ah ok, I think the runtime version needs to have further support for the manual download. I'll look into that in the future. But good to hear that the runtime version of avp works for you.

I created https://github.com/luxtorpeda-dev/luxtorpeda/issues/94 to track that.

**Comment by d10sfan** [comment]
@frostworx You will probably also need to have an option in the tinker tool for using the runtime version as well. Let me know in that other ticket if you have any questions related to that.

**Comment by d10sfan** [comment]
@frostworx Ok, this version automatically uses the runtime, it's just a different compatibility tool. Eventually runtime will replace the original one. Already original will get no updates.

So you won't have to do anything if you don't want to, as eventually runtime will become the default. And best of luck to you

**Comment by frostworx** [comment]
Same to you, thx, @d10sfan

**Comment by frostworx** [comment]
Just added and tested `Luxtorpeda (Runtime)` support to steamtinkerlaunch.
- [simple commit](https://github.com/frostworx/steamtinkerlaunch/commit/ad1ea91b96f7fa9ae746ab164f27032d340fecdf)
- [wiki](https://github.com/frostworx/steamtinkerlaunch/wiki/Luxtorpeda)
