### ISSUE TITLE
openage

### ISSUE THREAD

**Issue by JoshuaFern** [luxtorpeda-dev/packages#1084]
### Project Link

https://github.com/SFTtech/openage

### Project License

GPL3+

### Steam App Ids

https://steamdb.info/app/221380/
https://steamdb.info/app/813780/
https://steamdb.info/app/1017900/
https://steamdb.info/app/356500/

### Additional Context

I have not tested any of this, but the project looks promising and says the Steam releases will work: https://github.com/SFTtech/openage/blob/master/doc/media_convert.md

**Comment by d10sfan** [comment]
Thanks, I'll take a look when I have a chance

**Comment by d10sfan** [comment]
It looks like at this point the project is too early to support, as there's no real gameplay. I'll keep an eye on it for the future though. Thanks!
