### ISSUE TITLE
Woof! source port for DOOM

### ISSUE THREAD

**Issue by vaibhavrmahadevan** [luxtorpeda-dev/packages#1094]
### Project Link

https://github.com/fabiangreffrath/woof

### Project License

GNU General Public License v2+

### Steam App Ids

https://steamdb.info/app/2280/
https://steamdb.info/app/2300/
https://steamdb.info/app/2290/
https://steamdb.info/app/9160/

**Comment by d10sfan** [comment]
Thanks for the request, I'll take a look when I have a chance.

**Comment by d10sfan** [comment]
Added in a recent commit
