### ISSUE TITLE
Gentool for Command & Conquer generals 

### ISSUE THREAD

**Issue by Eonfge** [luxtorpeda-dev/packages#1151]
### Feature Request

Most C&C games don't actually run well on Windows without some additional tools, tools that also fix the multiplayer and that address some outstanding balance issues and bugs.

### Solution

Include the community toolkit with luxtorpeda. It would still rely on Wine to do the heavy lifting, but it will give improved compatibility.

### Additional Context

http://www.gentool.net/

**Comment by d10sfan** [comment]
Just got this added, let me know if there's any issues
