### ISSUE TITLE
Blade Runner (Classic)

### ISSUE THREAD

**Issue by NerosTie** [luxtorpeda-dev/packages#1154]
### Project Link

https://www.scummvm.org/

### Project License

GPL 3

### Steam App Ids

https://steamdb.info/sub/596994/

### Additional Context

The original version of Blade Runner is bundled with the Enhanced Edition and it works with ScummVM. I think it just needs to be linked to the "Classic" subfolder.

**Comment by d10sfan** [comment]
@NerosTie Do you own the game for testing? If so, I can try putting out a update that should support it.

**Comment by NerosTie** [comment]
Yes I own the game

**Comment by d10sfan** [comment]
Ok great! I'll let you know once Ive had a chance to update

**Comment by d10sfan** [comment]
This should be supported now. Let me know if you run into any issues

**Comment by NerosTie** [comment]
It doesn't work unfortunately: "No such file or directory (os error 2)"

**Comment by d10sfan** [comment]
Can you try it again? It should work now, I forgot to add the steam id to the list that causes it to automatically update the download.

**Comment by NerosTie** [comment]
Yes it works but it launches ScummVM (then you have make a choice again) and not directly the game, is it the expected behavior?

**Comment by d10sfan** [comment]
I think that's to be expected since it found multiple options, although not sure the mechanism it uses to decide to go straight into a game. If you end up finding a solution to that, feel free to open a PR or make a note here and I can add it.
