### ISSUE TITLE
STAR WARS™ Dark Forces (Classic, 1995)

### ISSUE THREAD

**Issue by RibhuNoodleBoodle** [luxtorpeda-dev/packages#1161]
### Project Link

https://github.com/luciusDXL/TheForceEngine

### Project License

GPL-2.0

### Steam App Ids

https://store.steampowered.com/app/32400/STAR_WARS_Dark_Forces_Classic_1995/

**Comment by d10sfan** [comment]
This project is a reverse-engineering one using the original binary so will unable to support it. Thanks for the request though.
