### ISSUE TITLE
Quake 4 & Prey 2006

### ISSUE THREAD

**Issue by d10sfan** [luxtorpeda-dev/packages#1163]
Add using https://github.com/glKarin/com.n0n3m4.diii4a/issues/96

Need to copy and set the openal from the sniper runtime folder
Then put the libraries in the right spots for the game and launch

Test with both, replace the current binaries, since they aren't as good as this.

Mark this as in progress engine

**Comment by lvonasek** [comment]
Note that this version does not include features like multiplayer and some graphical effects. There are also minor game bugs.

**Comment by d10sfan** [comment]
Progress tracked in https://github.com/luxtorpeda-dev/packages/pull/1175

**Comment by rea987** [comment]
@d10sfan Though it is nice to have modern source ports for Prey and Quake 4, this engine (idTech4A++ (Harmattan Edition)) isn't online compatible with vanilla games. Quake 4 still has a slim but active multiplayer scene. Prey's mp masterserver is offline but it's still possible to host online server. In fact, TAW clan hosts an online Prey server time to time to enjoy the game's mp. Is that possible to get vanilla Linux versions of the games as an option, please? Thanks a ton!

**Comment by d10sfan** [comment]
> @d10sfan Though it is nice to have modern source ports for Prey and Quake 4, this engine (idTech4A++ (Harmattan Edition)) isn't online compatible with vanilla games. Quake 4 still has a slim but active multiplayer scene. Prey's mp masterserver is offline but it's still possible to host online server. In fact, TAW clan hosts an online Prey server time to time to enjoy the game's mp. Is that possible to get vanilla Linux versions of the games as an option, please? Thanks a ton!

I thought about that, but is there any benefit to running the native games over running then via Proton? Quake 4 in particular has a bug in it where the framerate on almost every launch is restricted to 40-ish FPS, which makes it not very playable.

**Comment by rea987** [comment]
Well, as a native Linux gaming enthusiast, I would love to have the ability of playing the game natively whenever possible. I heard that Quake 4 has some fps issues which is most likely related with smp but it works fine for me on Ubuntu based distros. How about making the Harmattan port default and vanilla version secondary, so the user can troubleshoot on his own?

**Comment by Double-0-seven7** [comment]
> > @d10sfan Though it is nice to have modern source ports for Prey and Quake 4, this engine (idTech4A++ (Harmattan Edition)) isn't online compatible with vanilla games. Quake 4 still has a slim but active multiplayer scene. Prey's mp masterserver is offline but it's still possible to host online server. In fact, TAW clan hosts an online Prey server time to time to enjoy the game's mp. Is that possible to get vanilla Linux versions of the games as an option, please? Thanks a ton!
> 
> I thought about that, but is there any benefit to running the native games over running then via Proton? Quake 4 in particular has a bug in it where the framerate on almost every launch is restricted to 40-ish FPS, which makes it not very playable.

Quake 4 works fine with some ini/config tinkering , and I think i actually got better performance on the native build then Proton but I cant 100 percent confirm that.
At least the Proton way also got that bug because i always got around 40-50 fps there at least.

**Comment by d10sfan** [comment]
Never got Quake 4 to run well consistently with the closed source engine, so anything you can provide could be useful. 

I added both back as options @rea987 @Double-0-seven7, let me know in this issue if there's any new issues.

**Comment by jopadan** [comment]
Trying to run Quake4 after compile on Linux-6.15.0 x86_64 AVX I get the following error:
```sh
ERROR: entityDef not found: player_viewweapon
```

**Comment by d10sfan** [comment]
@jopadan What do you mean by compile? And what option are you using to play quake 4?
