### ISSUE TITLE
Doom Retro/Woof issues

### ISSUE THREAD

**Issue by Duffking** [luxtorpeda-dev/packages#1169]
### Game

Doom

### Engine

Doom Retro/Woof

### Linux Distribution

Steam Deck

### Luxtorpeda Version

68.1.0

### Bug description

Doom Retro: Does not launch due to an SDL Mixer error.
Woof: Launches, but has an error message about FluidSynth.

### Steps To Reproduce

Doom Retro:
1. Update to latest Doom Retro
2. Launch
3. Window appears saying "The wrong version of SDL2_mixer.so was found. Doom Retro requires v2.6.2". Won't launch as a result and force quits instead

Woof:
1. Fresh install Woof
2. Launch
3. Window appears saying "Error loading FluidSynth soundfont:". Engine still launches, but Fluidsynth is not able to be selected, only Midi Emulation. Subsequent launches do not show the error, but same behaviour in-engine. Clearing out the config folder + install folder and re-downloading makes the error come up again, though.

### Expected Behavior

Both launch without errors

**Comment by d10sfan** [comment]
Thanks for the issue, I'll look into this as soon as I can.

**Comment by d10sfan** [comment]
Doom Retro & Woof should now be fixed. let me know how it goes for you
