### ISSUE TITLE
Doom Retro requires SDL v.2.28.5.

### ISSUE THREAD

**Issue by Dumbisted** [luxtorpeda-dev/packages#1229]
### Game

- Doom II
- The Ultimate Doom(Probably shares the same problem)

### Engine

Doom Retro

### Linux Distribution

SteamOS

### Luxtorpeda Version

v70.0.0

### Bug description

Prompt as the title says. 

### Steps To Reproduce

Launch Doom Retro engine from Luxtorpeda.

### Expected Behavior

Run without any problem; and expected SDL2 to be updated automaticly after "updating" Luxtorpeda from a previous version

### Additional Context

I "updated" luxtorpeda from previous versions through ProtonUp-Qt; Could this has somehow prevented SDL2 from updating?

**Comment by d10sfan** [comment]
Doom retro has a requirement in their source code that the built version is the same as the runtime version. Not entirely sure why but that basically means each time the sniper runtime updates, doom retro comes up with that complaint.

I should be able to fix it by re building it with latest sniper again. I'll look into that sometime next week when I can.

**Comment by d10sfan** [comment]
I think I've fixed it. If you launch it again it should download a new version can you try that out and see if to works?

**Comment by Dumbisted** [comment]
It's working now, appreciated for your efforts!

**Comment by d10sfan** [comment]
Great!
