### ISSUE TITLE
Failing to scale dosbox-staging to screen

### ISSUE THREAD

**Issue by valzi** [luxtorpeda-dev/packages#1246]
### Linux Distribution

SteamOS

### Luxtorpeda Version

70

### Bug description

When I run a variety of non-Steam (GOG) DOS games (Might and Magic: Worlds of Xeen is an example) in Luxtorpeda and select Dosbox Staging, the display uses a very tiny corner of my screen instead of scaling.

This does not happen for every GOG DOS game. Magic Carpet 2 works perfectly.

### Steps To Reproduce

1. Install Worlds of Xeen with GOG on a windows PC.
2. Move folder to Steam Deck.
3. Add dosbox.exe to Steam.
4. Add launch options from windows shortcut to Steam
5. Force luxtorpeda 70 compatibility mode.
6. Run game in game mode.

### Expected Behavior

Game scaled up to use more than approximately 1/8th of the screen.

### Additional Context

I'd love to know how to configure each game I add to luxtorpeda. I can't seem to find documentation for this. Is it possible?

**Comment by d10sfan** [comment]
Note that playing GOG games isn't officially supported with lux, although it can work as you can see.

It sounds like either the game has an incorrect config, or dosbox staging isn't seeing the config and going with some sort of defaults. 

It's possible that the file is in the wrong spot for this version to see it. You may want to look at the console/log output of dosbox-staging to see if you see anything there.

In terms of configuring the games, there should be a dosbox config file in the games, or you can set one in your user profile directory, the same as if you installed it yourself.
