### ISSUE TITLE
Doom 3 BFA does not launch Classic Doom (1 and 2)

### ISSUE THREAD

**Issue by TheEpicNoobZilla** [luxtorpeda-dev/packages#1252]
### Linux Distribution

Fedora 40 KDE

### Luxtorpeda Version

70.0.0

### Bug description

When launching the game with Doom BFA (aka classic rbdoom) i cannot launch Doom 1 or 2 due to missing wads that this source port ships (ua.wad, newport.wad and mlbls.wad) when i downloaded the latest stable version and manually placed wads inside classic/base/wads i can launch Both doom 1 and 2 via BFA edition. RBDoom 3 BFG does not need those wads so it can launch all 3 games without any issues

### Steps To Reproduce

1. Launch Doom 3 BFG
2. Choose classic-rbdoom-3-bfg
3. try to launch Doom 1 or 2
4. See what wads are missing

### Expected Behavior

Launches doom 1 or 2

**Comment by d10sfan** [comment]
Thanks for the report! Can you try again, about 30 minutes after this comment has been posted? It should be fixed now.

**Comment by TheEpicNoobZilla** [comment]
Now they work. The only thing that's annoying me is enabled dev mode (dev options for all games)

**Comment by d10sfan** [comment]
That's part of the wad it looks like, but glad it's working for you now
