### ISSUE TITLE
Pharaoh (1999) - Akhenaten

### ISSUE THREAD

**Issue by NerosTie** [luxtorpeda-dev/packages#1259]
### Project Link

https://github.com/dalerank/Akhenaten

### Project License

AGPL-3.0 

### Steam App Ids

https://steamdb.info/app/564530/

**Comment by d10sfan** [comment]
Thanks for the request, I'm working on it in https://github.com/luxtorpeda-dev/packages/pull/1260, to replace the old engine that's no longer in dev
