### ISSUE TITLE
Descent and Descent 2: Music not downloaded

### ISSUE THREAD

**Issue by knightcole** [luxtorpeda-dev/packages#1262]
### Game

Descent and Descent 2

### Engine

dxx-rebirth and dxx-redux

### Linux Distribution

Void Linux

### Luxtorpeda Version

70.1.1

### Bug description

After downloading either engine with Luxtorpeda, I noticed that no music was playing for both Descent games. I checked the game directory and found that both d1xr-sc55-music.dxa and d2xr-sc55-music.dxa were HTML documents stating that the page was not found. I guess that whatever website was hosting the music is down.

### Steps To Reproduce

1. Launch Descent
2. Choose either DXX-Rebirth or DXX-Redux
3. Click "OK" to continue and launch the game.
4. Everything works except the music.
5. Repeat with Descent 2.

### Expected Behavior

Music playing during gameplay.

### Additional Context

I found [this Github repo](https://github.com/pudlez/dxx-addons) which is effectively a new host for the music. Perhaps it would be worth changing the download links to point to its [release links](https://github.com/pudlez/dxx-addons/releases/tag/v1.0)?

**Comment by d10sfan** [comment]
Thanks for the links, I've updated it, can you see if that works now?

**Comment by knightcole** [comment]
> Thanks for the links, I've updated it, can you see if that works now?

The download for Descent still generated a "Not found" HTML document.

**Comment by d10sfan** [comment]
Strange it's working ok for me, Can you try deleting your ~/.cache/luxtorpeda folder and re-trying?

**Comment by knightcole** [comment]
That fixed it. Thank you!
