### ISSUE TITLE
Re-Volt: Music doesn't play without tweaks

### ISSUE THREAD

**Issue by Shockwave508** [luxtorpeda-dev/packages#1273]
### Game

Re-Volt

### Engine

RVGL

### Linux Distribution

SteamOS v3.5.19 Stable

### Luxtorpeda Version

v70.1.1

### Bug description

Initial installation of RVGL fails to play music at all.

### Steps To Reproduce

1. Install Re-Volt and RVGL.
2. Start the game.

### Expected Behavior

Music should already be playing in the main menu and elsewhere.

### Additional Context

Given how everything is case-sensitive on Linux, renaming "Track##.ogg" to "track##.ogg" got the music working as-intended.

**Comment by d10sfan** [comment]
Can you try the latest version? I've added some changes that makes it so that the music is lower-cased before starting the game.
