### ISSUE TITLE
Star Wars: Dark Forces

### ISSUE THREAD

**Issue by diogo-tomas** [luxtorpeda-dev/packages#1282]
### Project Link

https://theforceengine.github.io/

### Project License

GPL-2.0

### Steam App Ids

https://steamdb.info/app/32400/

**Comment by d10sfan** [comment]
This project is unsupportable because it's a reverse engineering project, not a source port or re-creation. Those have questionable legal problems, so prefer not to support them

See https://github.com/luxtorpeda-dev/packages/issues?q=the+force+engine
