### ISSUE TITLE
Dhewm3: Mod Binaries

### ISSUE THREAD

**Issue by Shockwave508** [luxtorpeda-dev/packages#1289]
### Project Link

https://github.com/dhewm/dhewm3

### Project License

GPL-3.0 License

### Steam App Ids

https://steamdb.info/app/9050/
https://steamdb.info/app/9070/

### Additional Context

Currently Luxtorpeda doesn't include the mod binaries for Dhewm3, which lets this sourceport run the following mods:

- The Lost Mission
- Classic Doom 3: Knee-Deep in the Dead
- Denton's Enhanced Doom 3
- Fitz Packerton
- Hard Corps
- LibreCoop
- Perfected Doom 3 (starting with v1.5.4)
- Sikkmod (Base/ROE, starting with v1.5.4)
- Scarlet Rivensin: The Ruiner

**Comment by d10sfan** [comment]
Note that if this is done, you'd still need to download the assets manually, but the mod libraries would be there so it should work.

**Comment by Shockwave508** [comment]
Precisely the intention, instead of users having to manually hunt down Dhewm3's mod binaries.

**Comment by d10sfan** [comment]
@Shockwave508 I believe this is working now. The mods are downloaded and extracted to the correct location, and I was able to successfully test loading one of the mods that have support. Thanks for the suggestion!
