### ISSUE TITLE
Quake 2 Remastered

### ISSUE THREAD

**Issue by jobukkit** [luxtorpeda-dev/packages#1318]
### Project Link

https://github.com/yquake2/yquake2remaster

### Project License

GPLv2

### Steam App Ids

https://store.steampowered.com/app/2320/Quake_II/

### Additional Context

Currently, when trying to launch the remastered version of Quake 2 through Luxtorpeda it just crashes after choosing an engine, so you have to choose "Play Quake II (Original)" when launching.

There's an experimental version of Yamagi for the remastered version that Luxtorpeda could support.

**Comment by d10sfan** [comment]
@jobukkit I'm a bit unclear on this project, does it support loading and running the new graphics and content? The README makes it seem like not yet.

**Comment by rea987** [comment]
@d10sfan It looks like there are 2 forks of Q2PRO to support remastered content;

All remastered content:
https://github.com/Paril/q2pro

Remastered content with vanilla experience:
https://github.com/skullernet/q2pro-rerelease-dll

Can these be added?

**Comment by d10sfan** [comment]
https://github.com/skullernet/q2pro-rerelease-dll is just the dll, not an actual engine. For q2pro, I can look into that when I have a chance.
