### ISSUE TITLE
HyperBowl

### ISSUE THREAD

**Issue by matrixx2k** [luxtorpeda-dev/packages#1319]
### Project Link

https://github.com/technicat/hyperbowl

### Project License

MIT license

### Steam App Ids

https://steamdb.info/app/847530/

### Additional Context

There's a native Linux port on the game's GitHub page. The Steam release doesn't include the Linux version and while the Windows version works, it has issues. For example, you're unable to select any of the options when pausing the game, including the ability to quit the game.

**Comment by d10sfan** [comment]
Thanks for the request, I've added it. Let me know if you have  any issues.
