### ISSUE TITLE
dsda-doom not launching for Heretic

### ISSUE THREAD

**Issue by SkylarLK** [luxtorpeda-dev/packages#1332]
### Linux Distribution

SteamOS 3.5.19

### Luxtorpeda Version

v70.1.1

### Bug description

When launching Heretic: Shadow of the Serpent Riders through Steam with Luxtorpeda on my Steam Deck, clicking the button to launch the game through DSDA-Doom closed/crashed the Luxtorpeda launcher and the Steam process. Looking in the folder, it appears Luxtorpeda has downloaded DSDA-Doom but won't launch it.

### Steps To Reproduce

1. On the Steam Deck, install this version of Luxtorpeda through ProtonUp-Qt.
2. On either desktop mode or game mode, set a fresh install of Heretic: Shadow of the Serpent Riders to Luxtorpeda and launch.
3. Click dsda-doom and then click OK to run.
4. WIt will close out of the Heretic Luxtorpeda launcher

### Expected Behavior

It downloads dsda-doom and launches Heretic through it.

### Additional Context

I noticed that Hexen does not show dsda-doom as an option.

**Comment by d10sfan** [comment]
I think this is fixed now, can you try it again? Thanks!

**Comment by SkylarLK** [comment]
I did. Now, instead of it crashing, it says "No such file or directory (os error 2)" despite the presence of files in the dsda-doom directory in the game directory.

**Comment by d10sfan** [comment]
Can you try again in a few minutes from this comment? It should work now
