### ISSUE TITLE
Daikatana: Add community multiplayer maps (pak9.pak)

### ISSUE THREAD

**Issue by Shockwave508** [luxtorpeda-dev/packages#1333]
### Project Link

https://bitbucket.org/daikatana13/daikatana/wiki/Downloads

### Project License

GPL-3.0 License(??)

### Steam App Ids

https://store.steampowered.com/app/242980/

### Additional Context

The only thing missing from the Daikatana unofficial patch is the set of community multiplayer maps bundled in pak9.pak, which is accessible from the project's download page.

**Comment by d10sfan** [comment]
This should be done now, let me know if you run into any issues.
