### ISSUE TITLE
Daikatana: Remove redundant MP3 soundtrack after package install

### ISSUE THREAD

**Issue by Shockwave508** [luxtorpeda-dev/packages#1334]
### Game

Daikatana

### Engine

Unofficial Patch 1.3

### Linux Distribution

SteamOS v3.6.12 Beta

### Luxtorpeda Version

v70.1.1

### Bug description

The redundant MP3 music still persists in the game's install directory after Luxtorpeda installs the OGG soundtrack.

### Steps To Reproduce

1. Install Unofficial Patch 1.3 through Luxtorpeda.

### Expected Behavior

The MP3 music should be automatically removed after the OGG music is installed, except for the following files:

- deadly.mp3
- Katana1.mp3

**Comment by d10sfan** [comment]
What's the issue with the existing mp3 files?

**Comment by Shockwave508** [comment]
The MP3 files that come with the game are of lower-quality/lower-bitrate than the OGG files downloaded through Luxtorpeda

**Comment by d10sfan** [comment]
What does the files being there affect? as in, is the game defaulting to using those, or something else?
