### ISSUE TITLE
RealRTCW 5.0

### ISSUE THREAD

**Issue by rea987** [luxtorpeda-dev/packages#1344]
### Project Link

https://github.com/wolfetplayer/RealRTCW

### Project License

GPL-3.0

### Steam App Ids

https://steamdb.info/app/1379630/

### Additional Context

RealRTCW 5.0 has been released and it appears that the project links to pre-compiled Arch and openSUSE packages for the v5.0. Can these be adopted for Luxtorpeda?

https://aur.archlinux.org/packages/realrtcw/

https://build.opensuse.org/package/show/games/realrtcw

**Comment by d10sfan** [comment]
This project was added a while back but removed because the built version on GitHub with steam assets didn't work because it assumed that the steam sdk was available. Do you see any reason that anything has changed?
