### ISSUE TITLE
Quake 3 Arena: r_mode -2 is forced, not allowing for custom resolutions

### ISSUE THREAD

**Issue by mvoolt** [luxtorpeda-dev/packages#1348]
### Game

Quake 3 Arena [2200]

### Engine

ioquake3

### Linux Distribution

Nobara Linux 40

### Luxtorpeda Version

v70.1.1

### Bug description

r_mode -2 is forced on all engines via packagessniper_v2.json, not allowing for custom resolutions

### Steps To Reproduce

1. Launch Q3A
2. Change resolution, windowed/fullscreen mode
3. Relaunch game

### Expected Behavior

Upon relaunching game, I'm expecting my game to be at 1024x768 windowed but instead its at 1440x900 windowed

**Comment by d10sfan** [comment]
You should be able to set a custom width and height in the config file, are you not able to do that?

**Comment by mvoolt** [comment]
No, I've r_customheight, r_customwidth set and r_mode set to -1 in q3config.cfg and it still wants to do 1440x900, even appending r_mode in command arguments via Steam doesn't work, I've not tried other source ports but it's probably same case

**Comment by d10sfan** [comment]
I added a new launch option for ioquake3 for legacy resolution, can you see if using that fixes what you're seeing? You'll probably need to remove your quake3 config to let the game re-generate it.
