### ISSUE TITLE
GZDoom is incompatible with new ID24 content of Doom + Doom II

### ISSUE THREAD

**Issue by rea987** [luxtorpeda-dev/packages#1354]
### Game

Doom + Doom II

### Engine

GZDoom

### Linux Distribution

Ubuntu Mate 22.04.5 LTS

### Luxtorpeda Version

71.0.0

### Bug description

ID24 is new specification and standard for Doom mapping. It was first used there for the Legacy of Rust expansion.

https://doomwiki.org/wiki/ID24

Currently, GZDoom doesn't support ID24, thus ID24 content such as Ghoul enemy doesn't appear in the game.

It's safe to remove GZDoom package for Legacy of Rust expansion as there is currently no source port supporting it.

### Steps To Reproduce

-

### Expected Behavior

-

### Additional Context

-

### Relevant log output

```shell
-
```

**Comment by rea987** [comment]
Never mind, just found a port replacing ID24 content.

https://www.doomworld.com/forum/topic/147764-actors-id24-to-gzdoom-port/

**Comment by d10sfan** [comment]
Interesting does that look like you can copy that file in the right spot and itll work? Are you able to replicate that?

**Comment by rea987** [comment]
id24res.wad needs to be put GZDoom config folder. Then putting -file id24res.wad should run it. However it gives an error indicates that it requires GZDoom 4.11 or newer.

**Comment by d10sfan** [comment]
Sounds like for now, I can remove it from use.

If/when gzdoom and/or mesa gets fixed, I can update to newer versions of gzdoom.

**Comment by d10sfan** [comment]
I've removed it for now, since it's not working. Thanks for letting me know
