### ISSUE TITLE
GZDoom v4.12.2 with default Vulkan renderer for Legacy of Rust

### ISSUE THREAD

**Issue by rea987** [luxtorpeda-dev/packages#1360]
### Project Link

https://github.com/ZDoom/gzdoom/

### Project License

GPL v3

### Steam App Ids

https://steamdb.info/app/2280/

### Additional Context

Latest release of GZDoom (v4.12.2) appears to run with Vulkan renderer as default that seems to be not affected by the following OpenGL issue. During the first 2 levels of Legacy of Rust, the game stayed between 240-260 mb ram usage, including level transitions.

https://gitlab.freedesktop.org/mesa/mesa/-/issues/9953

Latest release of GZDoom appears to rendering new Legacy of Rust enemies just fine. iwads and command;

- doom2.wad (rerelease)
- id1.wad
- id1-res.wad
- id1-weap.wad

`gzdoom -iwad doom2.wad -file id1.wad id1-res.wad id1-weap.wad`

**Comment by d10sfan** [comment]
This should be complete now, I've updated to gzdoom, forced vulkan. Let me know if you run into any issues.
