### ISSUE TITLE
Reset ut2004 CD key?

### ISSUE THREAD

**Issue by TRPB** [luxtorpeda-dev/packages#1363]
### Linux Distribution

NixOS

### Luxtorpeda Version

71

### Bug description

when I pasted my CD key it included an extra character (I think) and now my game won't launch

I cannot find the location this is stored to reset it.

I have removed:

- `~/.config/luxtorpeda`
- `~/.ut2004`

 and reinstalled the game in steam. Launching via luxtorpeda again it doesn't give the the CD key option. I have no idea how to reset it

### Steps To Reproduce

Launch game

Enter invalid CD key

### Expected Behavior

There should be some way to reset it

**Comment by d10sfan** [comment]
Since this is more of a packages question moved it there.

There's a setup file in the ut2004 steam directory. I believe it's in the System directory.

Can you try deleting that and then running the game again? That should force it to ask you to enter the CD key again
