### ISSUE TITLE
Backyard Baseball 97

### ISSUE THREAD

**Issue by HellsBells24** [luxtorpeda-dev/packages#1387]
### Project Link

https://github.com/scummvm/scummvm

### Project License

GPL-3.0

### Steam App Ids

https://steamdb.info/app/3170540/

### Additional Context

I honestly don't know if this is possible, but I know the Backyard Sports games (at least the earlier ones) which were released earlier this year on Steam are playable with ScummVM.

**Comment by d10sfan** [comment]
Does this game work with the default scummvm option if you select it?

**Comment by HellsBells24** [comment]
Yes, though I changed screen resolution and such after the face


Sent with Proton Mail secure email.

**Comment by HellsBells24** [comment]
Well ScummVM is opening with Backyard Baseball as a selectable option, but every time I try to play it it crashes.

**Comment by d10sfan** [comment]
Was it working when it was a default option?

**Comment by HellsBells24** [comment]
On the standalone ScummVM flatpack, yes. For some reason not when launched with Luxtopeda, though
Sent from Proton Mail Android
-------- Original Message --------On 11/6/24 3:54 PM, d10sfan - notifications at github.com  wrote:
Was it working when it was a default option?

**Comment by d10sfan** [comment]
Ah I thought you had said it worked when ran using the default options. So you haven't tried that previously?

**Comment by HellsBells24** [comment]
I'm sorry, I guess I'm confused. When you say "the default options," are you saying ScummVM was previously usable with Luxtopeda?
My interpretation of "default options" was "Can I use ScummVM to play Backyard Baseball independent of Steam." In which case yes.
I had never tried to run BB with Luxtorpeda because I wasn't aware that ScummVM was already present in Luxtorpeda.

**Comment by d10sfan** [comment]
Ah sorry I had meant when a game does not have a direct engine attached to it in luxtorpeda, you can still assign it as the compatibility tool, and then it'll come up with a list of options, like scummvm.

If it works with flatpak but not here, not sure what's going on but I can look when I can. I'll need to buy the game first at some point.

**Comment by d10sfan** [comment]
Looking at this, this is because the game on steam is an unsupported version for scummvm:

```
Your game version appears to be unknown. Please, report the following data to the
ScummVM team along with the name of the game you tried to add and its version,
language, etc.:
  SCUMM gameid 'baseball', file 'baseball.he0', MD5 'b855daca2b7c40fc45592cdf5ce54f86'
```

They've updated in November to support it with a warning, but they haven't created a release for that yet. Whenever that is done, the next version here will support that as well.

**Comment by d10sfan** [comment]
scummvm just updated, if you pick scummvm from the default engine options does that work for you now?
