### ISSUE TITLE
Jedi Knight: Dark Forces 2

### ISSUE THREAD

**Issue by shmabler** [luxtorpeda-dev/packages#1389]
### Project Link

https://github.com/shinyquagsire23/OpenJKDF2

### Project License

"Permission to use, copy, modify, and/or distribute this software for any purpose without fee is hereby granted."

### Steam App Ids

https://store.steampowered.com/app/32380/STAR_WARS_Jedi_Knight_Dark_Forces_II
https://store.steampowered.com/app/32390/STAR_WARS_Jedi_Knight__Mysteries_of_the_Sith

**Comment by d10sfan** [comment]
This project uses reverse engineering techniques which have gotten projects shut down before. Because of that won't be able to support it. Thank you for the interest though
