### ISSUE TITLE
Star Wars: Dark Forces

### ISSUE THREAD

**Issue by cyberconan** [luxtorpeda-dev/packages#1403]
### Project Link

https://theforceengine.github.io/

### Project License

GPL-2.0 license 

### Steam App Ids

https://steamdb.info/app/32400/

### Additional Context

Thanks!

**Comment by d10sfan** [comment]
Thanks for the interest! Sadly, I can't support this project as it uses reverse engineering, and that's unclear from a legal standpoint, which we've seen with the re3 project. See https://github.com/luxtorpeda-dev/packages/issues?q=dark+forces for more information.
