### ISSUE TITLE
[Blake Stone] Game fails to run at all.

### ISSUE THREAD

**Issue by Shockwave508** [luxtorpeda-dev/packages#1434]
### Game

Blake Stone: Aliens of Gold/Planet Strike

### Engine

bstone

### Linux Distribution

SteamOS v3.6.21 Beta

### Luxtorpeda Version

v71.0.0

### Bug description

Both Blake Stone games refuse to start at all.

### Steps To Reproduce

1. Attempt to run Aliens of Gold or Planet Strike.
2. Insta-crash!

### Expected Behavior

Games should start without such a fuss.

### Relevant log output

```shell
BStone v1.2.13+ac86299e75e3fffae4bf60a20b92b510b1de2684
=======================================================

<<< Start up SDL system manager.
Compiled version: 2.30.10
Linked version: 2.30.10
<<< Start up SDL audio manager.
Built-in drivers:
  "pulseaudio"
  "alsa"
  "dsp"
  "disk"
  "dummy"
Devices:
  1. "Razer BlackShark V2 HS BT"
  Frequency: 48000 Hz
  Channels: 2
  2. "ACP/ACP3X/ACP6x Audio Coprocessor Speaker"
  Frequency: 48000 Hz
  Channels: 2
  3. "ACP/ACP3X/ACP6x Audio Coprocessor Headphones"
  Frequency: 48000 Hz
  Channels: 2
>>> SDL audio manager started up.
Start up SDL event manager.
<<< Start up SDL video manager.
  Modes:
    1280x800 60 Hz
    160x256 59 Hz

Start up SDL mouse manager.
Start up SDL window manager.
Start up OpenGL current context.
>>> SDL video manager started up.
>>> SDL system manager started up.
Looking for game content.
Shut down SDL system manager.
Shut down SDL video manager.
Shut down OpenGL current context.
Shut down SDL window manager.
Shut down SDL mouse manager.
Shut down SDL event manager.
Shut down SDL audio manager.
[ERROR] (jm_free.cpp:754:find_contents) Content not found.
[ERROR] (bstone_sys_message_box_sdl2.cpp:93:show)
(bstone_sys_exception_sdl2.cpp:26:sdl2_ensure_result)
(bstone_sys_exception_sdl2.cpp:15:sdl2_fail) No message system available
```

**Comment by d10sfan** [comment]
There was an issue with the new build which I've fixed. Can you see if this fixes it for you?

With this, I was able to play the game with the Apogee Throwback Pack.

If this does not work for you, link the game or games you're trying to play.

**Comment by Shockwave508** [comment]
Got it working now, after moving the bstone executable to the games' root directories.

**Comment by d10sfan** [comment]
What game are you playing? It shouldn't be necessary to manually move the binary around

**Comment by d10sfan** [comment]
Can you send me links to those games on steam?

**Comment by Shockwave508** [comment]
Aliens of Gold: 358190
Planet Strike: 358310

**Comment by d10sfan** [comment]
Thanks! I'll see if I can replicate this

**Comment by d10sfan** [comment]
https://store.steampowered.com/app/358190/Blake_Stone_Aliens_of_Gold/

https://store.steampowered.com/app/358310/Blake_Stone_Planet_Strike/

**Comment by d10sfan** [comment]
Tested both and they work fine on my end without any changes.
