### ISSUE TITLE
engge is no longer necessary, it was merged in ScummVM

### ISSUE THREAD

**Issue by neuromancer** [luxtorpeda-dev/packages#1448]
[Engge is now part of ScummVM](https://wiki.scummvm.org/index.php?title=Thimbleweed_Park). The old repository is no longer maintained, so very recommended to remove it and use ScummVM 2.9.0 instead.

**Comment by d10sfan** [comment]
Ah thanks for the heads up. I'll take a look at that soon.

**Comment by d10sfan** [comment]
I swapped to using scummvm for the game, let me know if you run into any issues. Thanks!
