### ISSUE TITLE
Rune doesn't launch

### ISSUE THREAD

**Issue by rea987** [luxtorpeda-dev/packages#166]
**Rune doesn't launch**
Luxtorpeda script for Rune fails to download the game

**To Reproduce**
Steps to reproduce the behaviour:
1. Install Rune Classic on Steam.
2. Attempt to launch the game

**Expected behaviour**
The script downloads Linux version of the game.

**Additional context**
Terminal output just after attempting to launch the game for the first time (I suspect a file name issue as the original file features a `+` in its name):

https://gist.github.com/rea987/6883b4ef6d79f55975a4eda8bb921c49

**Comment by d10sfan** [comment]
@rea987 It looks like the 7z file isn't the right size, around 280 mb instead of the 480 or so I believe it is. Can you try deleting the cached version in ~/.cache/luxtorpeda/210950 and seeing if that works? It should then redownload it and run from there.

**Comment by rea987** [comment]
After clearing  ~/.cache/luxtorpeda/210950 and ~/.local/share/Steam/steamapps/common/Rune Classic, I redownloaded the game and attempted to launch it.

1) Download the Windows version;
https://gist.github.com/rea987/b944c423e0e01377f35be952d829606b

2) Attempting to install Linux version via Luxtorpeda:
https://gist.github.com/rea987/d646e1791cfdf7603980346d62ac2e38

3) This resulted endless installation of the Linux version that I needed to quit after a while. When I checked the System Monitor, I detected that luxtorpeda was still running that I needed to manually kill.
https://gist.github.com/rea987/3585c06c606959ea8b62c114cd8aded4

4) 2nd attempt to launch the game to install the Linux version resulted proper installation prompt but it too failed to install the Linux version;
https://gist.github.com/rea987/959069fa019c214e5bae035beedfa605

Point I would like to add;

I misnamed the directory and archive as rune+ho**n**; I renamed and reuploaded it to Internet Archive as _rune_hov_, I suggest using it;
https://archive.org/download/Rune_Halls_of_Valhalla_Linux/rune_hov.7z

**Comment by d10sfan** [comment]
@rea987 

It looks like it's having issues downloading the full archive, as it's showing as 157 mb here:

```
Scanning the drive for archives:
1 file, 163741696 bytes (157 MiB)

Extracting archive: System/rune%2Bhon.7z
ERROR: System/rune%2Bhon.7z
System/rune%2Bhon.7z
Open ERROR: Can not open the file as [7z] archive


ERRORS:
Unexpected end of archive
```

If you try to download it using a normal browser does that work as expected? This is still using the other (rune+hov.7z) for now, as that worked for me and another person who tested it as well.

Also, what type of distro and other system info are you on?

**Comment by rea987** [comment]
It looks like due to slow download speed of archive.org, I assumed that the Linux version installation stuck. Patiently waiting the installation to complete solved the issue. Though, due to unpredictability of the download speed of archive.org, that might be an issue with other users as well; 87 kbps average download speed was quite annoying; either moving the file elsewhere or make a warning before the installation would be beneficial.

The points that I would like to touch upon:

1) rune+hon was a typo; it supposed to be rune+hov. I suggest using rune_hov.7z that I uploaded.
https://archive.org/download/Rune_Halls_of_Valhalla_Linux/rune_hov.7z

2) On fully updated Linux Mint 19.3 (Ubuntu 18.04.4 based), the first launch returned `Could not find libpulsedsp.so` error. Installing `libpulsedsp:i386` solved the issue.

3) Using padsp results unbearably delayed sound output. On the other hand, osspd provides near perfect OSS translation. I suggest adding osspd-pulseaudio to the launch script as a first option. Though, osspd-pulseaudio is broken on Ubuntu since 20.04.
https://bugs.launchpad.net/ubuntu/+source/osspd/+bug/1857810

4) An AMD user reported that icculus' lauch script to avoid speeding issue doesn't solve the problem for him. I suspect that might be an AMD specific issue. Is there a way to implement framerate limiter to Luxtorpeda. Such as libstrangle?

https://gitlab.com/torkel104/libstrangle
https://www.reddit.com/r/linux_gaming/comments/kkjmba/i_preserved_long_lost_linux_native_releases_of/gha6h6r/

5) Custom masterserver for multiplayer doesn't seem to affect ~/.loki/rune/System/Rune.ini, thus servers aren't listed.

**Comment by d10sfan** [comment]
Ok I'll take a look at those when I have a chance.

**Comment by d10sfan** [comment]
@rea987 

For the custom masterserver, that should be fixed now, although you will need to remove your ~/.loki/rune/System folder and remove the ready file and linuxdata folder in the Rune Classic steam installation directory to see the changes.

For padsp, there's a note in the packages list that the system uses padsp, so it expects it to be installed. It isn't something I can provide as part of this so it'd require a system installation like you had done.

i haven't seen an issue with the audio so far and haven't used osspd before. Would you feel comfortable with creating a pull request to change the way the run script launches the game? You can see it here: https://github.com/luxtorpeda-dev/packages/blob/master/engines/rune/assets/run-rune.sh

For a framerate limiter, you may be able to combine luxtorpeda with libstrangle (using the command line options in steam). Can you try that and let me know if that works?

**Comment by rea987** [comment]
> For padsp, there's a note in the packages list that the system uses padsp, so it expects it to be installed. It isn't something I can provide as part of this so it'd require a system installation like you had done.
>
> i haven't seen an issue with the audio so far and haven't used osspd before. Would you feel comfortable with creating a pull request to change the way the run script launches the game?

I retried padsp by purging osspd and rebooting the system to make sure nothing interferes with pulseaudio, unfortunately there is still very noticeable 1 second sound delay. I ended up deleting `pulseaudiolib="" ... LD_PRELOAD="$LD_PRELOAD $pulseaudiolib"` lines from `run-rune.sh` within `rune-210950-2.tar.xz` to be able to use osspd once again. I say it's fine, anyone happens to deliberately install and use osspd would detect the sound issue and edit the launch script on his own. I might try to make a pull request in the future when I figure out scripting basics.

> For a framerate limiter, you may be able to combine luxtorpeda with libstrangle (using the command line options in steam). Can you try that and let me know if that works?

Yes, after building and installing libstrangle as it's described in the GitLab page, I am able to limit the framerate with following launch option;

`__GL_THREADED_OPTIMIZATION=1 strangle 119 %command%`

> For the custom masterserver, that should be fixed now, although you will need to remove your ~/.loki/rune/System folder and remove the ready file and linuxdata folder in the Rune Classic steam installation directory to see the changes.

Yes, custom masterserver seems to be added. However, when I try to list the servers for the first time, the game freezes for 80 seconds, the returns to normal. The doesn't repeat again. Increasing download speed for custom content such as maps and mods should be applied in both `Rune.ini` and `User.ini` within `~/.loki/rune/System`

https://www.pcgamingwiki.com/wiki/Rune#Faster_download_speed_in_online_multiplayer

**Comment by d10sfan** [comment]
@rea987 I've added change that should have a default for the User.ini file as well for the download speed. This will cause the User.ini file to be in linuxdata/System/User/ini, then the User.ini file inside the ~/.loki folder will be used for overrides. You'll need to clear the state to see the changes (remove the ready file in the game's installation folder and remove ~/loki/rune)

I'm closing this for now, but feel free to comment/request a re-open if you have a pull request for the parts discussed above or if you run into an issue.
