### ISSUE TITLE
Shockolate

### ISSUE THREAD

**Issue by ShFil119** [luxtorpeda-dev/packages#169]
* Project link: https://github.com/Interrupt/systemshock
* Project license: GPLv3
* Does it work on 64-bit only Linux: YES
* Is source code available?: YES
* Is source code stored in Git?: YES
* List of Steam AppIds of supported games:
    - https://steamdb.info/app/410710/

**Comment by d10sfan** [comment]
@ShFil119 Does Shockolate project work for enhanced, or only classic version on steam?

**Comment by d10sfan** [comment]
`iirc you're better off using classic edition assets, as EE reorganizes them in a way not recognized by the original source that shockolate is based on`

**Comment by d10sfan** [comment]
Tracking progress for classic in https://github.com/luxtorpeda-dev/packages/pull/190
