### ISSUE TITLE
Daikatana

### ISSUE THREAD

**Issue by ShFil119** [luxtorpeda-dev/packages#170]
* Project link: https://bitbucket.org/daikatana13/daikatana/src/master/
* Project license: Unknown
* Does it work on 64-bit only Linux: MAYBE
* Is source code available?: NO
* Is source code stored in Git?: NO
* List of Steam AppIds of supported games:
    - https://steamdb.info/app/242980/

## Additional information

https://www.gamingonlinux.com/articles/you-can-play-controversial-fps-daikatana-on-linux-now-thanks-to-a-fan-patch-endorsed-by-john-romero.7674

**Comment by d10sfan** [comment]
Added support in https://github.com/luxtorpeda-dev/packages/pull/188

Let me know if you run into issues.
