### ISSUE TITLE
Kingpin: Life of Crime

### ISSUE THREAD

**Issue by ghost** [luxtorpeda-dev/packages#171]
* Project link: https://icculus.org/~ravage/kingpin/
* Project license: Unknown
* Does it work on 64-bit only Linux: MAYBE
* Is source code available?: NO
* Is source code stored in Git?: NO
* List of Steam AppIds of supported games:
    - https://steamdb.info/app/38430/

**Comment by rea987** [comment]
Kingpin is one of the earliest ports of LIFLG, hence its sound system is much primitive comparing to later ports. Expectedly, it uses OSS API for sound but best I can tell is that implementation of OSS relies kernel modules. I could never get sound from the native port via alsa-oss (aoss) or osspd. To be fair, I haven't tried it with padsp but I doubt the result would be different. I conducted some investigation on OSS implementation on different Linux games;

Enemy Territory, RTCW and Q3:
https://annihil.com/topic/4/et-sdl-sound-setup
https://github.com/g00dy22/et-sdl-sound

Soldier of Fortune:
https://www.gamingonlinux.com/forum/topic/2936/post_id=28363

**Comment by Frenzied-Pop** [comment]
I'm guessing compile the game code against one of the Quake 2 Engines?
https://github.com/QuakeTools/Kingpin-SDK-v1.21

**Comment by d10sfan** [comment]
Closing in the hopes that the remaster supports Linux. If not, can re-visit this.
