### ISSUE TITLE
Freespace 2

### ISSUE THREAD

**Issue by ShFil119** [luxtorpeda-dev/packages#174]
* Project link: https://icculus.org/~ravage/freespace2/
* Project license: Unknown
* Does it work on 64-bit only Linux: MAYBE
* Is source code available?: NO
* Is source code stored in Git?: NO
* List of Steam AppIds of supported games:
    - https://steamdb.info/app/273620/

**Comment by d10sfan** [comment]
This one is already supported. Please see https://luxtorpeda-dev.github.io/packages.html

**Comment by ShFil119** [comment]
My bad.
