### ISSUE TITLE
Investigate realrtcw steam release support (For upstream)

### ISSUE THREAD

**Issue by d10sfan** [luxtorpeda-dev/packages#181]
https://steamcommunity.com/app/1379630/discussions/0/2946999778479046517/?tscn=1604293020

**Comment by Frenzied-Pop** [comment]
Is this what you were looking into?
https://aur.archlinux.org/packages/realrtcw/

**Comment by d10sfan** [comment]
> Is this what you were looking into?
> https://aur.archlinux.org/packages/realrtcw/

No, more of seeing if it'd be possible to add native steam support in the upstream package. Currently, only the non-steam one has support.
