### ISSUE TITLE
Sonic CD

### ISSUE THREAD

**Issue by ShFil119** [luxtorpeda-dev/packages#184]
* Project link: https://github.com/Rubberduckycooly/Sonic-CD-11-Decompilation
* Project license: Unknows
* Does it work on 64-bit only Linux: YES
* Is source code available?: YES
* Is source code stored in Git?: YES
* List of Steam AppIds of supported games:
    - https://steamdb.info/app/200940/

**Comment by JuanVCS** [comment]
Do you need a steam key for this game?

**Comment by d10sfan** [comment]
> Do you need a steam key for this game?

I don't currently own this game. I was going to wait for a sale, or if you don't mind and have a steam key for it, that'd be great.

**Comment by JuanVCS** [comment]
How could I get it to you then?

**Comment by d10sfan** [comment]
> How could I get it to you then?

I'm on discord as d10sfan#2119. You can also join the luxtorpeda discord, that's shared between this project and dosbox-staging, as well (https://discord.gg/prBCtumDav)

**Comment by d10sfan** [comment]
Added in https://github.com/luxtorpeda-dev/packages/pull/201

**Comment by NerosTie** [comment]
Why Sonic CD has been removed and tagged with "wontfix"? (there is a new release btw)

**Comment by d10sfan** [comment]
@NerosTie I removed the engines that were based on reverse engineering, after the trouble with re3. 

If you're interested in those you can use the user packages feature and compile them yourself.

**Comment by bruno-fs** [comment]
> If you're interested in those you can use the user packages feature and compile them yourself.
@d10sfan Is there a way to maintain a user modified `metadata/packages.json` with local changes not being overridden on luxtorpeda updates?

**Comment by d10sfan** [comment]
@bruno-fs Yes, this can be done with user-packages, you can see an example here: https://github.com/luxtorpeda-dev/luxtorpeda/issues/65#issuecomment-808634850
