### ISSUE TITLE
Vanilla Conquer (Command & Conquer™ Remastered Collection)

### ISSUE THREAD

**Issue by ShFil119** [luxtorpeda-dev/packages#185]
* Project link: https://github.com/TheAssemblyArmada/Vanilla-Conquer
* Project license: GPL-3.0 
* Does it work on 64-bit only Linux: YES
* Is source code available?: YES
* Is source code stored in Git?: YES
* List of Steam AppIds of supported games:
    - https://steamdb.info/app/1213210/

**Comment by d10sfan** [comment]
@ShFil119 From my understanding on that project, they have support for graphics and such for the original (non-remastered games) and for the remastered games library support, but not graphics at this point. Is that correct?
