### ISSUE TITLE
Unreal Tournament: Game of the Year Edition (v469a)

### ISSUE THREAD

**Issue by rea987** [luxtorpeda-dev/packages#191]
* Project link: https://github.com/OldUnreal/UnrealTournamentPatches
* Project license: *Mixed* (See LICENSE.md)
* Does it work on 64-bit only Linux: *MAYBE*
* Is source code available?: *YES*
* Is source code stored in Git?: *YES*
* List of Steam AppIds of supported games:
    - https://steamdb.info/app/13240/

## Additional information

This is open source and backwards compatible successor of v436 and v451 that is released with the blessing of Epic. v469a on Linux uses SDL2 and updated ALAudio which are compatible with modern distros SDL and PulseAudio that makes the game not needing PASDP and SDLCL.

https://github.com/OldUnreal/UnrealTournamentPatches

**Comment by d10sfan** [comment]
Thanks for the ticket, I had added 469a a while back but had forgotten to add it to the packages list. I've done so now, so you should be able to use it.
