### ISSUE TITLE
Update VkQuake to 1.05.2

### ISSUE THREAD

**Issue by NerosTie** [luxtorpeda-dev/packages#193]
Just noticed that VkQuake has not been updated.

Current version: 1.04.1 (15 Jan. 2020)
Last version: 1.05.2 (11 Jan. 2021)

Is it possible to update it? 
Thanks!

PS: is it also possible to add other engines like Darkplaces (recommended engine to run the mod "Quake 1.5")?

**Comment by d10sfan** [comment]
Moved this one to the packages repo. I'll look into upgrading it. I don't own the game, so if you're comfortable, I'll provide an archive here to test it once it's ready.

**Comment by d10sfan** [comment]
For darkplaces, if you create a package request below and fill in the information, I'll look into it: https://github.com/luxtorpeda-dev/packages/issues/new?assignees=&labels=package+request&template=package-request.md&title=

**Comment by d10sfan** [comment]
@NerosTie I've updated the vkQuake as a pull request and attached the binaries below. Inside the dist.zip is a vkquake-2310.tar.xz file. If you copy that into the ~/.cache/luxtorpeda/2310 directory and overwrite the cached file in there, and then launch from steam, that should cause the new version to load. If you do that and everything looks good, I'll make it the live release.
[dist.zip](https://github.com/luxtorpeda-dev/packages/files/5825463/dist.zip)

**Comment by d10sfan** [comment]
Added support for vkquake update in https://github.com/luxtorpeda-dev/packages/pull/194
