### ISSUE TITLE
Darkplaces-2017 for Quake I

### ISSUE THREAD

**Issue by NerosTie** [luxtorpeda-dev/packages#197]
* Project link: http://icculus.org/twilight/darkplaces/files/
* Project license: GPLv2
* Does it work on 64-bit only Linux: YES
* Is source code available?: YES
* Is source code stored in Git?: NO
* List of Steam AppIds of supported games:
https://store.steampowered.com/app/2310/QUAKE/
https://store.steampowered.com/app/9040/QUAKE_Mission_Pack_1_Scourge_of_Armagon/
https://store.steampowered.com/app/9030/QUAKE_Mission_Pack_2_Dissolution_of_Eternity/

## Additional information

I suggest to take [darkplacesengine20170829beta1.zip](http://icculus.org/twilight/darkplaces/files/darkplacesengine20170829beta1.zip) which is the recommended version to run the famous mod [Quake 1.5](url) and `20170829beta1` is the one in AUR. (2018 versions have issues).
I also suggest to name it `Darkplaces-2017`.

Because there is a capital letter in the folder "Id1", the command `-game Id1` must be specified.

The command should look like this:
```./darkplaces-linux-x86_64-sdl -game Id1```

**Comment by NerosTie** [comment]
There are also 2 Missions Packs:
https://store.steampowered.com/app/9040/QUAKE_Mission_Pack_1_Scourge_of_Armagon/
https://store.steampowered.com/app/9030/QUAKE_Mission_Pack_2_Dissolution_of_Eternity/

Mission Pack 1 add the folder `hipnotic`
To run it: `./darkplaces-linux-x86_64-sdl -game Id1 -game hipnotic`

Mission Pack 2 add the folder `rogue`
To run it: `./darkplaces-linux-x86_64-sdl -game Id1 -game rogue`

PS: these 2 packs are missing in [the list ](https://luxtorpeda-dev.github.io/packages.html) of supported games with `vkquake`

**Comment by d10sfan** [comment]
For this, would prefer to have the game to continue, as it'll make it easier to create and debug the engine, since I'm building it from scratch (compared to the other where I was upgrading an existing one).

I'll be on the lookout for it on sale, one of the few id games I seem to not own :)

**Comment by NerosTie** [comment]
Can't you use the binaries in the archive?

**Comment by d10sfan** [comment]
> Can't you use the binaries in the archive?

If it's an open source project, I prefer to compile it from source. That helps to keep it in a known compatibility state, and normally (doesn't seem like it as much here) it ends p being easier to keep up to date in case of any changes.

**Comment by d10sfan** [comment]
I now own the original quake (not the expansions) so I'll work on this when I get a chance. For the expansions, I'll need some help for testing, unless I end up buying them at some point.

**Comment by d10sfan** [comment]
I've added the mission packs to vkquake and added darkplaces-2017 as an option for quake and the mission packs.
