### ISSUE TITLE
Vkquake2 for Quake II

### ISSUE THREAD

**Issue by NerosTie** [luxtorpeda-dev/packages#198]
* Project link: https://github.com/kondrak/vkQuake2
* Project license: GPLv2
* Does it work on 64-bit only Linux: YES
* Is source code available?: YES
* Is source code stored in Git?: YES
* List of Steam AppIds of supported games:
https://store.steampowered.com/app/2320/QUAKE_II/
https://store.steampowered.com/app/2340/QUAKE_II_Mission_Pack_Ground_Zero/
https://store.steampowered.com/app/2330/QUAKE_II_Mission_Pack_The_Reckoning/

## Additional information

You will need a file called `gamex64.so` in the `baseq2` folder. 

I found one in a package from Yamagi Quake 2: https://deponie.yamagi.org/quake2/debs/amd64/yamagi-quake2_5.00-1_amd64.deb Then `data.tar.gz → usr → lib → games → yamagi-quake2 → baseq2 → game.so`

You need to rename it to `gamex64.so` and put it in the `baseq2` folder.

Or just take it from here, it's the same:
[gamex64.tar.gz](https://github.com/luxtorpeda-dev/packages/files/5826692/gamex64.tar.gz)

There are 2 Missions Packs:

Quake II Ground Zero adds the folder `rogue`, command line to add: `+set game rogue`

Quake II The Reckoning adds the folder `xatrix`, command line to add: `+set game xatrix`

**Comment by d10sfan** [comment]
It looks like yamagi quake 2 has support incoming for vulkan. We could wait for that to come into a release, unless there's a particular feature that vkQuake2 provides over yamagi quake.

**Comment by NerosTie** [comment]
I can't tell. Maybe there are people who have a preference for one or the other. There is also the question of mods, vkquake2 is more close to the original source code. Vkquake2 is an engine in active dev, it has its place, I think.

**Comment by d10sfan** [comment]
Ok makes sense, I'll take a look at vkquake2 when I have a chance, as an additional option.

**Comment by d10sfan** [comment]
Tracking progress in pull request - https://github.com/luxtorpeda-dev/packages/pull/203
