### ISSUE TITLE
Alive_Reversing for Abe's Exoddus and Abe's Oddysee

### ISSUE THREAD

**Issue by NerosTie** [luxtorpeda-dev/packages#204]
* Project link: https://github.com/AliveTeam/alive_reversing
* Project license: I don't find it
* Does it work on 64-bit only Linux: YES
* Is source code available?: YES
* Is source code stored in Git?: YES
* List of Steam AppIds of supported games:
- https://store.steampowered.com/app/15700/Oddworld_Abes_Oddysee/
- https://store.steampowered.com/app/15710/Oddworld_Abes_Exoddus/

## Additional information

Tested and it works very well. The engine is not complete but very playable and in active dev. 
You don't need to download SDL2 to build it, it's for Windows users.

**Comment by d10sfan** [comment]
Added in https://github.com/luxtorpeda-dev/packages/pull/210
