### ISSUE TITLE
Quake 1 Not launching,

### ISSUE THREAD

**Issue by hexdsl** [luxtorpeda-dev/packages#207]
**Describe the bug**
Click play. Then it says running. Then it says play and nothing happens.

terminal does a lot of scrolling but it seems that this is the error:

     ERROR-OUT BEGIN
     QUAKE ERROR: W_LoadWadFile: couldn't load gfx.wad
     Basedir is: share/quake
     Check that this has an id1 subdirectory containing pak0.pak and pak1.pak, or use the -basedir command-line option to specify 
     another directory.

**Comment by NerosTie** [comment]
It works for me.

It looks like your `share/quake/id1` is empty, you should have a folder `music`, a file `config.cfg` and 2 symlinks to `pak0.pak` and `pak1.pak`

**Comment by d10sfan** [comment]
I moved the ticket to the packages repo, as this is where any questions/issues/requests for engines should go.

For the issue:

* What version of luxtorpeda do you have?
* Please send a  full log from the start of the game request to the error you posted (should mostly be showing what luxtorpeda is extracting and running, can be helpful to see if it's missing a step)
* What distro and version are you running on and are you using flatpak or another non-normal way of launching Steam?
* What does your directory listing look like for the game?

**Comment by d10sfan** [comment]
I just tried it (just got the first quake) and it worked ok for me as well. Make sure you pick Quake in the possible options, not sure what'd happen for the others.

**Comment by d10sfan** [comment]
Also, what file system type are you on? If you are on NTFS for example, that probably will not work.

**Comment by hexdsl** [comment]
Hello again all. 

Today downloaded Lutorpeda-dev freshly, purged the one installed, deleted quake and reinstalled it (making sure to delete the folder in case a remnant was left) 

Im on ext4, arch Linux. Games work fine on my machine, all vulkan stuff is installed fine (Doom eternal was my test lol) 

Anyway, I still get no quake when i press play. 

here is all the output, would like to know whats gone wobbly, :D 

`GameAction [AppID 2310, ActionID 5] : LaunchApp changed task to ShowLaunchOption with ""
GameAction [AppID 2310, ActionID 5] : LaunchApp waiting for user response to ShowLaunchOption ""
GameAction [AppID 2310, ActionID 5] : LaunchApp continues with user response "0"
GameAction [AppID 2310, ActionID 5] : LaunchApp changed task to ProcessingInstallScript with ""
update_packages_json. found hash: 49b2399864abf6d10ff02ffaeadbfdc8344c8886
update_packages_json. found hash and remote hash: 49b2399864abf6d10ff02ffaeadbfdc8344c8886 49b2399864abf6d10ff02ffaeadbfdc8344c8886
vkquake-2310-4.tar.xz found in cache (skip)
quake-campaign-soundtrack.tar.xz found in cache (skip)
GameAction [AppID 2310, ActionID 5] : LaunchApp changed task to SynchronizingCloud with ""
GameAction [AppID 2310, ActionID 5] : LaunchApp changed task to SiteLicenseSeatCheckout with ""
GameAction [AppID 2310, ActionID 5] : LaunchApp changed task to CreatingProcess with ""
GameAction [AppID 2310, ActionID 5] : LaunchApp waiting for user response to CreatingProcess ""
GameAction [AppID 2310, ActionID 5] : LaunchApp continues with user response "CreatingProcess"
Game update: AppID 2310 "", ProcID 10490, IP 0.0.0.0:0
ERROR: ld.so: object '/home/hexdsl/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
ERROR: ld.so: object '/home/hexdsl/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
update_packages_json. found hash: 49b2399864abf6d10ff02ffaeadbfdc8344c8886
update_packages_json. found hash and remote hash: 49b2399864abf6d10ff02ffaeadbfdc8344c8886 49b2399864abf6d10ff02ffaeadbfdc8344c8886
creating: "/run/user/1000/luxtorpeda/2310.pid"
steam_app_id: "2310"
original command: ["/home/hexdsl/.local/share/Steam/steamapps/common/Quake/Winquake.exe"]
working dir: Ok("/home/hexdsl/.local/share/Steam/steamapps/common/Quake")
tool dir: "/home/hexdsl/.local/share/Steam/compatibilitytools.d/luxtorpeda"
json:
{
    "game_name": "Quake",
    "download": [
        {
            "name": "vkquake",
            "url": "https://github.com/luxtorpeda-dev/packages/releases/download/vkquake-4/",
            "file": "vkquake-2310-4.tar.xz"
        },
        {
            "name": "Quake Soundtrack",
            "url": "https://luxtorpeda.gitlab.io/files/idstuff/quake/",
            "file": "quake-campaign-soundtrack.tar.xz"
        }
    ],
    "command": "./vkquake.sh",
    "information": {
        "store_link": "https://store.steampowered.com/app/2310/",
        "engine_name": "vkQuake",
        "engine_link": "https://github.com/Novum/vkQuake",
        "version": "1.05.2",
        "comments": "Single-player only for now, fixed music",
        "author": "dreamer",
        "author_link": "https://github.com/dreamer",
        "license": "GPLv2",
        "license_link": "https://github.com/Novum/vkQuake/blob/master/LICENSE.txt"
    }
}
installing: vkquake-2310-4
install: "license"
install: "license/..LICENSE"
install: "license/LICENSE.vkquake"
install: "vkquake"
install: "vkquake.sh"
install: "share"
install: "share/quake"
install: "share/quake/id1"
install: "share/quake/id1/pak1.pak"
install: "share/quake/id1/pak0.pak"
install: "share/quake/default.lux.cfg"
installing: quake-campaign-soundtrack
install: "quake_campaign_soundtrack_readme.txt"
install: "share/quake/id1/music/track08.ogg"
install: "share/quake/id1/music/track10.ogg"
Starting app 2310
>>> Adding process 10490 for game ID 2310
GameAction [AppID 2310, ActionID 5] : LaunchApp changed task to WaitingGameWindow with ""
>>> Adding process 10491 for game ID 2310
GameAction [AppID 2310, ActionID 5] : LaunchApp changed task to Completed with ""
install: "share/quake/id1/music/track06.ogg"
install: "share/quake/id1/music/track02.ogg"
install: "share/quake/id1/music/track07.ogg"
install: "share/quake/id1/music/track04.ogg"
install: "share/quake/id1/music/track03.ogg"
install: "share/quake/id1/music/track11.ogg"
install: "share/quake/id1/music/track05.ogg"
install: "share/quake/id1/music/track09.ogg"
run: "./vkquake.sh" with args: [] []
ERROR: ld.so: object '/home/hexdsl/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
ERROR: ld.so: object '/home/hexdsl/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
Command line: ./vkquake -fitz -basedir share/quake
Found SDL version 2.0.14
Detected 12 CPUs.
Quake 1.09 (c) id Software
GLQuake 1.00 (c) id Software
FitzQuake 0.85 (c) John Fitzgibbons
FitzQuake SDL port (c) SleepwalkR, Baker
QuakeSpasm 0.93.2 (c) Ozkan Sezer, Eric Wasylishen & others
vkQuake 1.05.2 (c) Axel Gneiting & others
Host_Init
Playing shareware version.

ERROR-OUT BEGIN


QUAKE ERROR: W_LoadWadFile: couldn't load gfx.wad

Basedir is: share/quake

Check that this has an id1 subdirectory containing pak0.pak and pak1.pak, or use the -basedir command-line option to specify another directory.

dropping: "/run/user/1000/luxtorpeda/2310.pid"
>>> Adding process 10498 for game ID 2310
>>> Adding process 10499 for game ID 2310
Game removed: AppID 2310 "", ProcID 10490
Uploaded AppInterfaceStats to Steam
Exiting app 2310
No cached sticky mapping in ActivateActionSet.`

**Comment by d10sfan** [comment]
@hexdsl What does your directory listing look like for the Quake game directory?

There should be an Id1 directory and then the following files inside it:

```
total 51720
-rwxr-xr-x 1 d10sfan d10sfan     2009 Jan 21 13:38 config.cfg
drwxr-xr-x 2 d10sfan d10sfan     4096 Jan 21 13:38 glquake
-rwxr-xr-x 1 d10sfan d10sfan 18689235 Jan 21 13:38 PAK0.PAK
-rwxr-xr-x 1 d10sfan d10sfan 34257856 Jan 21 13:38 PAK1.PAK
-rwxr-xr-x 1 d10sfan d10sfan       51 Jan 21 16:50 steam_autocloud.vdf
```

And then you should also see share/quake/id1, with the following files:

```
total 124
-rw-r--r-- 1 d10sfan d10sfan   2660 Jan 21 16:53 config.cfg
drwxr-xr-x 2 d10sfan d10sfan   4096 Jan 21 16:50 music
lrwxrwxrwx 1 d10sfan d10sfan     21 Jan 21 16:50 pak0.pak -> ../../../Id1/PAK0.PAK
lrwxrwxrwx 1 d10sfan d10sfan     21 Jan 21 16:50 pak1.pak -> ../../../Id1/PAK1.PAK
```

One ones that are important is PAK0.PAK in the Id1 directory (this is the data that comes from steam) and the pak0.pak and pak1.pak in the share/quake/id1 directory, which is a link installed by the vkquake package.

**Comment by hexdsl** [comment]
Heres what i have. 

```
/home/hexdsl/.local/share/Steam/steamapps/common/Quake/id1 = 
total 51M
drwxr-xr-x 3 hexdsl hexdsl 4.0K Jan 22 18:24 ./
drwxr-xr-x 6 hexdsl hexdsl 4.0K Jan 22 18:24 ../
drwxr-xr-x 2 hexdsl hexdsl 4.0K Jan 22 18:24 glquake/
-rwxr-xr-x 1 hexdsl hexdsl 2.0K Jan 22 18:24 config.cfg*
-rwxr-xr-x 1 hexdsl hexdsl  18M Jan 22 18:24 PAK0.PAK*
-rwxr-xr-x 1 hexdsl hexdsl  33M Jan 22 18:24 PAK1.PAK*
-rwxr-xr-x 1 hexdsl hexdsl   51 Jan 22 18:24 steam_autocloud.vdf*
```

/home/hexdsl/.local/share/Steam/steamapps/common/Quake/share/quake/id1 = 

```
total 16K
drwxrwxr-x 3 hexdsl hexdsl 4.0K Jan 22 18:24 ./
drwxrwxr-x 3 hexdsl hexdsl 4.0K Jan 22 18:24 ../
drwxr-xr-x 2 hexdsl hexdsl 4.0K Jan 22 18:24 music/
-rw-r--r-- 1 hexdsl hexdsl 2.5K Jan 22 18:24 config.cfg
lrwxrwxrwx 1 hexdsl hexdsl   21 Jan 22 18:24 pak0.pak -> ../../../Id1/PAK0.PAK
lrwxrwxrwx 1 hexdsl hexdsl   21 Jan 22 18:24 pak1.pak -> ../../../Id1/PAK1.PAK
```

Again, these have been made by steam, i removed and re-installed everything to confirm it wasnt anything i did and there wasnt any old files around. :D

**Comment by d10sfan** [comment]
Strange on my system the I in Id1 (the directory from steam) is capitalized. A note is that that appears to be the correct name ("Id1" not "id1") inside Steam: https://steamdb.info/depot/2311/

Can you try renaming "/home/hexdsl/.local/share/Steam/steamapps/common/Quake/id1" to "/home/hexdsl/.local/share/Steam/steamapps/common/Quake/Id1" and see if it works then?

**Comment by NerosTie** [comment]
What happens if you run the game from the folder with: 

`sh vkquake.sh`

and/or:

`./vkquake -fitz -basedir share/quake "$@"`

?

Also, when you share a log, please make a file and upload it here.

**Comment by hexdsl** [comment]
Okay renaming `id1` to `Id1` fixes the issue. I reinstalled this game TWICE and still it defaulted it `id1` 

perhaps other people are having this issue? maybe the setup script could check when it installs the engine?? 

anyway thanks for help

**Comment by d10sfan** [comment]
Good to hear! Not sure why Steam would be installing it as id1 instead of Id1. It may be worth creating a ticket on https://github.com/ValveSoftware/steam-for-linux. Could be something to do with a incompatibility with something unique to your system.

Do other games that lux-dev supports work for you?

**Comment by NerosTie** [comment]
> I reinstalled this game TWICE and still it defaulted it id1

How is it even possible??

`Id1` is clearly capitalized:
https://steamdb.info/depot/2311/

How can you have something else?

**Comment by hexdsl** [comment]
I do not know, you are pressing X to doubt. but here it is... https://youtu.be/XpGDtAcAQqY 

i dont THINK im doing anything i shouldnt be. but here it is.

**Comment by NerosTie** [comment]
First time I see something like this oO

What is the App ID? Right click → properties → bottom left
It should be "2310" and it should be what you have.

Other idea: 
What do you have here? : https://store.steampowered.com/account/remotestorageapp/?appid=2310

I suspect the cloud save to rename the folder. Can you uninstall the game, delete the folder, uncheck "Steam Cloud" in properties then redownload the game?

**Comment by hexdsl** [comment]
that link you gave me looks like this 
![image](https://user-images.githubusercontent.com/2613799/105611516-cd4c7f00-5dad-11eb-98cd-fb18b863b0c4.png)

yes, i have app id 2310. (if is it app **I**d  lol)

**Comment by hexdsl** [comment]
Uninstalled without steam cloud selected. its now correctly capitalised.  ive never even looked in this folder before all this so i guarantee it wasnt something i did. Wonder if there was a 'bug' when i first played it?

**Comment by NerosTie** [comment]
So it was the cloud save... I don't know what happened, it's a really strange behavior... You should now find a way to delete the cloud save. I'm not sure how to do it though, maybe you can try to delete the file in `steam/userdata/[SteamID]/2310/`

It could be interesting to open an issue here too: https://github.com/ValveSoftware/steam-for-linux/issues

https://steamdb.info/app/2310/ufs/

`id1` is not listed as a path for `savefiles` 🤷

**Comment by d10sfan** [comment]
Wonder if you've played the game on Windows before? That might cause the steam cloud to insert the data in id1/* since Windows doesn't care about case sensitivity. And then steam for some reason lowercased the directory as well?
