### ISSUE TITLE
Solarus for Ocean's Heart

### ISSUE THREAD

**Issue by NerosTie** [luxtorpeda-dev/packages#209]
* Project link: https://www.solarus-games.org/en
* Project license: GPLv3
* Does it work on 64-bit only Linux: YES
* Is source code available?: YES
* Is source code stored in Git?: YES https://gitlab.com/solarus-games/solarus
* List of Steam AppIds of supported games:
https://store.steampowered.com/app/1393750/Oceans_Heart/

## Additional information

To run the game: `solarus-run data.solarus`

**Comment by d10sfan** [comment]
Implemented in PR https://github.com/luxtorpeda-dev/packages/pull/234

Needs testing (as I don't own the game), so will continue conversation there
