### ISSUE TITLE
Xash3D FWGS

### ISSUE THREAD

**Issue by PopeRigby** [luxtorpeda-dev/packages#225]
* Project link: https://github.com/FWGS/xash3d-fwgs
* Project license: GPLv3 (I think)
* Does it work on 64-bit only Linux: No
* Is source code available?: Yes
* Is source code stored in Git?: Yes
* List of Steam AppIds of supported games:
    - https://steamdb.info/app/70
    - https://steamdb.info/app/50
    - https://steamdb.info/app/130

**Comment by d10sfan** [comment]
It looks like there currently isn't a license on this project.

What's the benefit of this engine over the native version already provided?

**Comment by PopeRigby** [comment]
> It looks like there currently isn't a license on this project.

Yeah I'm not really sure about the license, I asked for clarification though.

> What's the benefit of this engine over the native version already provided?

Here's the list of features: https://www.moddb.com/engines/xash3d-engine/features/xash3d-engine-v095-features

**Comment by d10sfan** [comment]
A possibility for this one could be to reference their AppImage, instead of compiling it myself (like most of the engines here are done). The one that is available on the latest release does not work for me. Does it work for you? And if so, what are the commands you use to launch the various games?

**Comment by rea987** [comment]
> What's the benefit of this engine over the native version already provided?

**Xash3D FWGS** is able to run Half-Life mods which are Windows exclusive due to not providing .so library. It has `-dll` and `-vguiloader` arguments that successfully run mods that aren't compatible with existing Linux version of Half-Life. Here are some examples that I managed to run;

**Half-Life: Absolute Zero:**
https://www.reddit.com/r/linux_gaming/comments/jdcsun/halflife_absolute_zero_ceased_development_final/

**Sweet Half-Life:**
https://github.com/FWGS/xash3d/issues/296#issuecomment-354368969

Though, I am not able to run mods via latest v0.20 release that are provided as AppImages. Aforementioned arguments do not work with them. Hence, I use "deprecated" v0.19.2 release:

https://github.com/FWGS/xash3d/releases

> It looks like there currently isn't a license on this project.

Deprecated seems to under GPLv3 and MIT licenses.

https://github.com/FWGS/xash3d#license

**Comment by d10sfan** [comment]
So it sounds like Absolute Zero would be the game to make work for this request? Does 0.19.2 work with the games listed in the original comment? 

There's some discussion about that version of the engine here: https://github.com/luxtorpeda-dev/packages/issues/88

**Comment by rea987** [comment]
> So it sounds like Absolute Zero would be the game to make work for this request?

It does. I can play Proton and Xash3D FWGS v0.19.2 side by side to compare.

> Does 0.19.2 work with the games listed in the original comment?

https://github.com/luxtorpeda-dev/packages/issues/225#issue-795543725

Yes; HL, HL:OF, HL:BS work with v0.19.2. Yet I don't see a point of porting games with existing official native versions.

About the mod support of engine versions; following list is mentioned in https://github.com/luxtorpeda-dev/packages/issues/88#issuecomment-662327437

https://github.com/FWGS/xash3d-fwgs/blob/master/Documentation/supported-mod-list.md

- Last time the list was updated is 15 Nov 2019
- Xash3D FWGS v0.19.2 was released in 14 Jul 2018
- Xash3D FWGS v0.20 was released in 3 Dec 2019

I am not entirely certain about which version supports which mod but my initial attempts were failed with v0.20. Perhaps, arguments were changed but I am not certain.

What I can offer is to check Half-Life mods on Steam and see if they run fine with Xash3D FWGS v0.19.2.

**Comment by d10sfan** [comment]
Ok that'd be helpful.

**Comment by d10sfan** [comment]
Added in https://github.com/luxtorpeda-dev/packages/pull/233

This is for Absolute Zero. This uses the built version of xash3d from the github release. It'll ask at start where the Half Life installation is and then get everything setup.

**Comment by rea987** [comment]
> What I can offer is to check Half-Life mods on Steam and see if they run fine with Xash3D FWGS v0.19.2.

Following are the Half-Life mods on Steam that lack Linux support. MP mods shall not be considered as even if they work with Xash3D FWGS, they wouldn't be compatible with Steam versions. Only remaining mods are **Halfquake Trilogy** and **Half-Life: Before**; former doesn't work with Xash3D FWGS and latter barely works with Xash3D FWGS with broken weapon animations. Thus, I give up on that.

https://store.steampowered.com/app/644320/Halfquake_Trilogy/
https://store.steampowered.com/app/632730/Base_Defense/
https://store.steampowered.com/app/1066610/Digital_Paintball_Redux/
https://store.steampowered.com/app/1283930/HalfLife_Restored/
https://store.steampowered.com/app/261980/HalfLife_Before/
https://store.steampowered.com/app/90044/Zombie_Panic/

Lastly, Xash3D FWGS v0.19.2 is the latest release of the engine that support utilizing Windows .dll on non-Windows systems in some form; later releases do not feature such option. There are number of mods can be compiled for Xash3D FWGS 0.20 but neither of them exists on Steam as far as I am aware.

https://github.com/FWGS/xash3d-fwgs/issues/310#issuecomment-774327730

**Comment by d10sfan** [comment]
@rea987 Did you verify that each of these work with xash3d? Can you provide commands for each one to load them using xash3d (similar to the absolute zero command)?

And this would be the .19.2 version that absolute zero uses

**Comment by rea987** [comment]
> Did you verify that each of these work with xash3d

Do you mean the Steam GoldSrc mods that I listed or the mods that I mentioned in the end of the post? No, I didn't verify either.

I only checked aforementioned Halfquake Trilogy and Half-Life: Before. Halfquake seems to use many custom tools and UIs that I'd be surprised if that ever works. HL: Before might work if weapons models somehow switched to stock HL ones, not sure how to do that. But the mod is so mediocre that I don't think it'd worth the effort.

Source code of Xash3D FWGS mods that I mentioned are in **Half-Life SDK for Xash3D** as branches that seem to be maintained somewhat regularly. There are over 40 of them and most of them are among the best mods

https://github.com/FWGS/hlsdk-xash3d

> And this would be the .19.2 version that absolute zero uses

Those mods with source codes should be compatible with v0.20 as they share the same code base with current version;  when they are compiled, they are shipped with .so libraries. The pre-compiled mods like "Poke646 Port for Linux (Xash3D Only!)" that were released before v.0.20 isn't compatible with v.0.20. So, I can say when compiled, those mods may or may not work with v0.19.2 but should work with v.0.20.

Pre-compiled Poke646 that works only with v0.19.2:
https://www.moddb.com/mods/poke646-anniversary-edition/downloads

**Comment by d10sfan** [comment]
Can you check to see which of those mods on steam work with 0.19.2 and what the commandz would be?

**Comment by rea987** [comment]
https://github.com/luxtorpeda-dev/packages/issues/225#issuecomment-774349932

Among those Steam mods, only Half-Life: Before can be played with Xash3D FWGS v0.19.2 with broken weapon animations and sounds. It may or may not related with Cyrillic texts on some weapon names in `models` folder.

> Can you check to see which of those mods on steam work with 0.19.2 and what the commands would be?

`LC_ALL=C ./xash3d.sh -game before -dll dlls/spirit.dll -clientlib cl_dlls/client.so`

**Comment by d10sfan** [comment]
Ah ok, I misunderstood that comment. So since that on seems to be broken with xash3d and the rest do not work, it sounds like there's nothing left to do for this engine. Is that correct?

**Comment by rea987** [comment]
> So since that on seems to be broken with xash3d and the rest do not work, it sounds like there's nothing left to do for this engine. Is that correct?

Yes, unless source codes of those mods are found and compiled against Xash3D FWGS, there's not much to do at this point.
