### ISSUE TITLE
Dear Esther (original version)

### ISSUE THREAD

**Issue by rea987** [luxtorpeda-dev/packages#229]
* Project link: *https://archive.org/details/dear_esther_linux*
* Project license: *Proprietary*
* Does it work on 64-bit only Linux: *MAYBE*
* Is source code available?: *NO*
* Is source code stored in Git?: *NO*
* List of Steam AppIds of supported games:
    - https://steamdb.info/app/203810/

## Additional information

I preserved the Linux version from Humble Bundle on Internet Archive since it is no longer available elsewhere. **dearesther-linux-06082013-bin** is the native version. The game might need following fixes;

https://www.pcgamingwiki.com/wiki/Dear_Esther#Native_Linux_version_.28.22Native_.bin.22_version.29_fails_to_launch_on_unsupported_localizations

https://www.pcgamingwiki.com/wiki/Dear_Esther#Native_Linux_version_.28.22Native_.bin.22_version.29_fails_to_launch_on_older_AMD_or_Intel_GPUs_with_open_source_drivers

**Comment by d10sfan** [comment]
It'd be better if there was a publicly available binary of the release or an open source project. Linking the original humble bundle release may be problematic. 

One possibility could be enough scripts where you could download Dear Esther, put the humble bundle version in the right spot, and it'd handle making it launchable through Steam, although that'd require  you to have it both in Steam and humble bundle which may not be common.

**Comment by d10sfan** [comment]
It may also be worth contacting icculus who did the port and seeing if they'd be interesting in providing the binaries for use (similar to how prey is available for example). That'd most likely require some sort of agreement with the original developers though.

**Comment by rea987** [comment]
Replacing `~/.local/share/Steam/steamapps/common/Dear Esther/bin`, `/.local/share/Steam/steamapps/common/Dear Esther/dearesther/bin` directories and adding Linux binary/launch script has made the Steam version able to launch the native Linux version. I can upload assetless version if that's all right.

**Comment by d10sfan** [comment]
Can you see about attempting to contact icculus to see thoughts on the Dear Esther port? I could also do it instead if you'd prefer.

**Comment by rea987** [comment]
> Can you see about attempting to contact icculus to see thoughts on the Dear Esther port? I could also do it instead if you'd prefer.

Unlike Prey, icculus was hired to make a Linux port of Dear Esther as a complete pack instead of an installer. Also, since the release of Dear Esther Landmark Edition, The Chinese room has a predatory tendency towards the original game and its Linux releases. They kinda delisted the original game from Steam while letting Humble Store Widget keep selling the original version as DRM-Free as well as Steam version; including Humble Bundle's Linux version. Later on, for no reason, sale of Linux version was stopped whereas Humble Store Widget is still selling the original version's DRM-Free and Steam version for Windows and Mac. Long story in short, it is unlikely that icculus can provide Linux libraries even if he wanted. Feel free to contact him as you know how to handle software much better than me.

By the way, zipped assetless version of Dear Esther that contain only Linux libraries, binaries, launch script and config is around 10 mb. I can upload it to here or Internet Archive right away.

**Comment by d10sfan** [comment]
Ok thanks for the info. I'll contact icculus and see if there's anything that can be done. In the meantime, I'll close this ticket. I'll re-open if I hear anything else.
