### ISSUE TITLE
Engge for Thimbleweed Park

### ISSUE THREAD

**Issue by NerosTie** [luxtorpeda-dev/packages#230]
* Project link: https://github.com/scemino/engge
* Project license: MIT
* Does it work on 64-bit only Linux: YES
* Is source code available?: YES
* Is source code stored in Git?: YES
* List of Steam AppIds of supported games:
https://store.steampowered.com/app/569860/Thimbleweed_Park/
https://store.steampowered.com/app/1305720/Delores_A_Thimbleweed_Park_MiniAdventure/ (see [here](https://github.com/scemino/engge/issues/132))

**Comment by d10sfan** [comment]
It looks like both of these have native support on Steam and the engine only supports the first game from what I can tell from that ticket.

What's the benefit of this engine over the existing Linux support?

**Comment by NerosTie** [comment]
It is open-source and will be more future-proof than the official engine (how many games with native support are broken?). I'm sure some people will be interested, like me!

**Comment by d10sfan** [comment]
Makes sense I'll take a look when I have a chance

**Comment by d10sfan** [comment]
Added in https://github.com/luxtorpeda-dev/packages/pull/318
