### ISSUE TITLE
Machinarium (original version)

### ISSUE THREAD

**Issue by rea987** [luxtorpeda-dev/packages#237]
* Project link: *https://amanita-design.net/games/machinarium.html*
* Project license: *Proprietary*
* Does it work on 64-bit only Linux: *YES*
* Is source code available?: *NO*
* Is source code stored in Git?: *NO*
* List of Steam AppIds of supported games:
    - https://steamdb.info/app/40700

## Additional information

Machinarium is a point & click game from Amanita Design. It has a Flash based original version and custom engine The Definitive Version which replaced the original version. Linux release of original version was provided as retail patches by the developer. Linux version has never released on Steam but it uses the same assets of the Windows release of the original version. Thankfully, repos of the original version is still available on Steam.

Previously, I prepared a guide to install and run the Linux version;

https://www.reddit.com/r/linux_gaming/comments/df19al/guide_machinarium_linux_version_from_steam_version/

Unfortunately, both Steam and SteamCMD's `download_depot` function is broken since early 2020. Thankfully **DepotDownloader** which requires Mono on Linux can download existing old repos of Steam games.

https://github.com/SteamRE/DepotDownloader
https://github.com/SteamRE/DepotDownloader/releases/tag/DepotDownloader_2.3.6 (latest version 2.4.0 doesn't work with Mono)

`mono DepotDownloader.dll -app 40700 -depot 40701 -manifest 5535572193145000279 -os windows -username <Steam username> -password <Steam password>`
(it will ask 2 factor auth code if Steam Guard is active)

I additionally tried **Ruffle** as a Flash Player Projector replacement but it hasn't matured enough to be fully compatible with Machinarium; opening inventory removes the cursor from the game.

**Comment by d10sfan** [comment]
It seems like there's a few various issues at play here:

* Downloaded game on steam does not have the right data
* Use of flash, which at least at the browser level is end of life

For the downloading of the game on steam, it looks like the Windows depos are the correct ones, which helps, although I don't think we can automate the download of the assets this way, mainly because I don't feel people would be comfortable giving their steam login information.

I could do something where it assumes you take care of the depot change, and then from there, I can download and extract the patches. 

The other issue is the use of Flash. Not sure if most recent OSes support it and if so, how long that would last. It'd be best if a flash replacement could be found that could help with that issue.

**Comment by rea987** [comment]
> Downloaded game on steam does not have the right data

> I don't think we can automate the download of the assets this way, mainly because I don't feel people would be comfortable giving their steam login information.

The problem with the download method is Valve broke `download_depot` function on Steam and SteamCMD as I mentioned earlier. Due to an additional setting, called `CUserAppManager::BIsManifestAvailableForUser`, `download_depot` can no longer downloads old ManifestID's by normal users. I investigated to see if there's a workaround, fix or update on that but as the community settled on DepotDownloader, there's no Steam/SteamCMD solution in the horizon.

https://www.reddit.com/r/Steam/comments/f3iasm/its_no_longer_possible_to_downpatch_a_game_since/fhlii2b/

Alternatively I can upload Humble Bundle copy of the game whose Linux release is no longer on sale anywhere if that's fine by you.

> Use of flash, which at least at the browser level is end of life

> if a flash replacement could be found that could help with that issue.

I suggested **Flash Player Projector**, not browser plug-in; Flash Player Projector is 64 bit and still works on modern distros without an issue.

https://www.adobe.com/support/flashplayer/debug_downloads.html

I tried couple other Flash Player replacements;

**Ruffle:**
Nightly builds of Ruffle runs the game but it glitches when user interacts with the inventory, even the character itself disappeared in some point of the first level.

https://ruffle.rs/
https://github.com/ruffle-rs/ruffle

**Lightspark:**
I compiled and installed Lightspark which couldn't even run the game.

https://lightspark.github.io/
https://github.com/lightspark/lightspark

**Comment by d10sfan** [comment]
Here are the steps that would be required to make this work. Does this make sense?

* Manual user input to download the swf and put it in an expected place.
* lux client downloads flash projector to put in the correct place
* Then, runs the game using the flash projector

**Comment by rea987** [comment]
> Manual user input to download the swf and put it in an expected place.

This assumes user to download game assets with DepotDownloader via Mono, then download and apply retail Linux patches, finally extract .swf from the binary. Honestly, that's too much pre-step for an automated tool only to run a Flash based game. I say, let us postpone it indefinitely until `download_depot` function of Steam client is restored.

**Comment by d10sfan** [comment]
Ok, I'll close this for now and if the situation improves, let me know in the ticket.
