### ISSUE TITLE
NBlood for Blood

### ISSUE THREAD

**Issue by NerosTie** [luxtorpeda-dev/packages#238]
* Project link: https://github.com/nukeykt/NBlood
* Project license: ?
* Does it work on 64-bit only Linux: YES
* Is source code available?: YES
* Is source code stored in Git?: YES
* List of Steam AppIds of supported games:
https://store.steampowered.com/app/299030/Blood_One_Unit_Whole_Blood/
https://store.steampowered.com/app/1010750/Blood_Fresh_Supply/

**Comment by d10sfan** [comment]
@NerosTie The AUR seems to thnk this is licensed via GPL: https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=nblood

Is that correct?

**Comment by NerosTie** [comment]
https://github.com/nukeykt/NBlood/releases

Inside there is a file saying the license is GPL v2.

**Comment by d10sfan** [comment]
Added in https://github.com/luxtorpeda-dev/packages/pull/250

Note that I've tested with Blood Fresh Supply, but not the other. It should work, but if there's any issues, feel free to comment here.
