### ISSUE TITLE
VoidSW for Shadow Warrior Classic

### ISSUE THREAD

**Issue by NerosTie** [luxtorpeda-dev/packages#239]
* Project link: 
https://voidpoint.io/terminx/eduke32
http://eduke32.com/
* Project license: GNU GPL + BUILD
* Does it work on 64-bit only Linux: YES
* Is source code available?: YES
* Is source code stored in Git?: YES
* List of Steam AppIds of supported games:
https://store.steampowered.com/app/238070/Shadow_Warrior_Classic_1997/
https://store.steampowered.com/app/225160/Shadow_Warrior_Classic_Redux/

## Additional information

VoidSW is a flag when building eduke32, see the PKGBUILD from AUR:
https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=eduke32-git

**Comment by JoshuaFern** [comment]
Another title that might be supported is https://store.steampowered.com/app/358400/Shadow_Warrior_Classic/

**Comment by NerosTie** [comment]
@d10sfan "238070" is "Free to Play", you can test with it.

**Comment by d10sfan** [comment]
Added in https://github.com/luxtorpeda-dev/packages/pull/249

Looks like the 238070 does not work with voidsm, at least from what I tried. This adds support for 225160 and should work for the various launch options (tested with the main game and the two expansion packs).
