### ISSUE TITLE
EDuke32 for Duke Nukem 3D, Ion Fury, NAM, WWII GI

### ISSUE THREAD

**Issue by NerosTie** [luxtorpeda-dev/packages#240]
* Project link: 
http://eduke32.com/
https://wiki.eduke32.com/wiki/Frequently_Asked_Questions
* Project license: GNU GPL
* Does it work on 64-bit only Linux: YES
* Is source code available?: YES
* Is source code stored in Git?: YES
https://voidpoint.io/terminx/eduke32
* List of Steam AppIds of supported games:
https://store.steampowered.com/app/359850/ (not available anymore)
https://store.steampowered.com/app/225140/ (not available anymore)
https://store.steampowered.com/app/434050/Duke_Nukem_3D_20th_Anniversary_World_Tour/
https://store.steampowered.com/app/562860/Ion_Fury/
https://store.steampowered.com/app/329650/NAM/
https://store.steampowered.com/app/376750/World_War_II_GI/

**Comment by d10sfan** [comment]
The only one of these I own is Ion Fury

@NerosTie Will you be able to provide what the commands for each of those games would be to launch then with this engine?

**Comment by NerosTie** [comment]
EDuke32, by default, knows where are the files from a Steam installation.

A setup window is displayed and you can choose what you want to launch:

![Screenshot_20210204_185050](https://user-images.githubusercontent.com/4572452/106934031-e9d7a800-6719-11eb-846a-360c25df5b4f.png)

So just running the eduke32 binary would be enough.

If you want to run directly a game, it's a command like this:

```eduke32 -fury -nosetup```

https://wiki.eduke32.com/wiki/Command_line_options

It depends what you think it's better: display the configuration page or launch it directly?

**Comment by NerosTie** [comment]
Actually, the main difficulty if you want to launch them directly would be the addons with Duke Nukem 3D.

![Screenshot_20210204_190949](https://user-images.githubusercontent.com/4572452/106936247-a3d01380-671c-11eb-9334-3f7acc17ed10.png)

Can Luxtorpeda launch different commands when selecting an option?

**Comment by d10sfan** [comment]
Yes, it can detect based on the original options which one was selected, and  then launch the appropriate one. So it'd be best if it skipped the engine's launcher and went straight into the game. 

So it'd help if you could provide commands for each game, or at least the ones you have and I can implement those.

**Comment by NerosTie** [comment]
I'll use `usecwd` to put `eduke32.cfg` and `settings.cfg` in the working directory to avoid conflicts between games.
The setup window is shown only the first time.

### **For Duke Nukem 3D Megaton Edition only: **
(I'm not even sure if it's possible with 20th Anniversary World Tour)

Duke Nukem 3D (Classic):
`eduke32 -j gameroot -usecwd -nosetup`

Duke It Out in D.C:
`eduke32 -j gameroot -j gameroot/addons/dc -usecwd -nosetup -addon 1`

Duke: Nuclear Winter:
`eduke32 -j gameroot -j gameroot/addons/nw -usecwd -nosetup -addon 2`

Duke Carribean: Life's A Beach:
`eduke32 -j gameroot -j gameroot/addons/vacation -usecwd -nosetup -addon 3`

Ion Fury:
`eduke32 -usecwd -nosetup`

NAM:
`eduke32 -j NAM -nam -usecwd -nosetup`

World War II GI
`eduke32 -j WW2GI -ww2gi -usecwd -nosetup`

**Comment by JoshuaFern** [comment]
It might also be possible to support Shadow Warrior Classic Redux (225160) as hinted by the [FAQ](https://wiki.eduke32.com/wiki/Frequently_Asked_Questions)

There's also:
https://store.steampowered.com/app/238070/Shadow_Warrior_Classic_1997/
https://store.steampowered.com/app/358400/Shadow_Warrior_Classic/

While being affiliated with eduke32, Shadow Warrior appears to use another engine called "voidsw" in which case this should probably be split into a new issue.

**Comment by d10sfan** [comment]
@NerosTie Do you own Megaton edition? It does not look like it's available to buy anymore. And you're saying that 20th Anniversary World Tour does not work with eduke32?

**Comment by NerosTie** [comment]
Yes, I own Megaton edition. About 20 Anniversary, I don't own it but I downloaded it from _"somewhere"_ and it seems that it doesn't work with EDuke32 but maybe I'm wrong.

**Comment by d10sfan** [comment]
Added in https://github.com/luxtorpeda-dev/packages/pull/252

I only own Ion Fury, so was able to test the engine itself with that, although the rest should be added. Let me know in this ticket if there's any issues.
