### ISSUE TITLE
Rednukem for Redneck Rampage

### ISSUE THREAD

**Issue by NerosTie** [luxtorpeda-dev/packages#241]
* Project link: https://github.com/nukeykt/NBlood
* Project license: ?
* Does it work on 64-bit only Linux: YES
* Is source code available?: YES
* Is source code stored in Git?: YES
* List of Steam AppIds of supported games:
~~https://store.steampowered.com/app/359850/ (not available anymore)~~
~~https://store.steampowered.com/app/225140/ (not available anymore)~~
~~https://store.steampowered.com/app/434050/Duke_Nukem_3D_20th_Anniversary_World_Tour/~~
~~https://store.steampowered.com/app/329650/NAM/~~
~~https://store.steampowered.com/app/376750/World_War_II_GI/~~
~~https://store.steampowered.com/app/646030/Redneck_Rampage_Possum_Bayou/ (not sure if compatible)~~
~~https://store.steampowered.com/app/580930/Redneck_Deer_Huntin/ (not sure if compatible)~~

https://store.steampowered.com/app/565550/Redneck_Rampage/
https://store.steampowered.com/app/580940/Redneck_Rampage_Rides_Again/

**Comment by d10sfan** [comment]
@NerosTie 
Can you provide the commands to use this engine for each of these games?

**Comment by NerosTie** [comment]
I think it's not really useful to have EDuke32 and Rednukem for Duke Nukem 3D, NAM and WWII GI, because it's basically the same base code and Rednukem is only useful for Redneck Rampage.
Possum Bayou is still not released (and probably never) and Deer Huntin' is not compatible.

Commands:

Redneck Rampage:
`rednukem -j Redneck -usecwd -nosetup`

Redneck Rampage Rides Again:
`rednukem -j AGAIN -usecwd -nosetup`

**Comment by d10sfan** [comment]
Added in https://github.com/luxtorpeda-dev/packages/pull/253

I haven't tested it because I don't personally own these games, so comment here if you run into issues.
