### ISSUE TITLE
BuildGDX for Witchaven

### ISSUE THREAD

**Issue by rea987** [luxtorpeda-dev/packages#242]
* Project link:

https://m210.duke4.net/
https://m210.duke4.net/index.php/42

* Project license: *GPL3* & *Apache*
* Does it work on 64-bit only Linux: *YES*
* Is source code available?: *YES*

* Is source code stored in Git?: *YES*

https://gitlab.com/m210/BuildGDX
https://gitlab.com/users/m210/projects

* List of Steam AppIds of supported games:
    - https://steamdb.info/app/299030
    - https://steamdb.info/app/1010750
    ~~- https://steamdb.info/app/359850 (unavailable)~~
    ~~- https://steamdb.info/app/225140 (unavailable)~~
    ~~- https://steamdb.info/app/434050 (not compatible with most recent BuildGDX version [v1.15])~~
    ~~- https://steamdb.info/app/329650~~
    ~~- https://steamdb.info/app/358400~~
    ~~- https://steamdb.info/app/238070~~
    ~~- https://steamdb.info/app/565550~~
    ~~- https://steamdb.info/app/580940~~

## Additional information

From `readme.txt`:

> ﻿BuildGDX is a port of Build Engine games based on libGDX framework for Java.
>
> It currently supports the following games:
> Duke Nukem 3D + World Tour Edition + official addons
> Blood + Cryptic Passage
> Shadow Warrior + addons
> Redneck Rampage + Route 66 + Rides Again
> Powerslave / Exhumed
> Witchaven 1 + 2
> TekWar
> Legend of the Seven Paladins
> with more games coming in the future releases.

- The port requires `openjdk-8-jre` on Linux, I cannot make it work with higher such as openjdk-10 or openjdk-11.
- Due to being based on Blood code, it's probably the most faithful port of Blood.
- ~~The latest version compatible with Duke Nukem 3D: 20th Anniversary World Tour on Linux was v1.12 that I cannot locate. v1.15 cannot launch that version of DN3D on Linux.~~

**Comment by d10sfan** [comment]
There's some requests earlier for other engines for these games. Is there a reason to add this one as well?

Java-based may be an issue just because I'm not sure if the steam runtime has the necessary tools to handle that.

**Comment by d10sfan** [comment]
Also, if you can lookup what the license is and provide that.

**Comment by rea987** [comment]
> There's some requests earlier for other engines for these games. Is there a reason to add this one as well?

- For **NAM** and **Redneck Rampage**; _EDuke32_ would be better due to not relying on Java.
- For **Duke Nukem 3D: 20th Anniversary World Tour**, latest version of BuildGDX (v1.15) and available older versions cannot run it on Linux for the time being. This shall be dropped too.
- For **Shadow Warrior**, there exists an official native source port on the store anyway.
- For **Blood**, although _NBlood_ had positive feedbacks, Blood veterans claim that BuildGDX is closest port to original Blood (DOSBox version) that gives authentic physics and weapon handling, most probably because of being started as a Blood engine project, _BloodGDX_. Hence I insist considering BloodGDX.

> Java-based may be an issue just because I'm not sure if the steam runtime has the necessary tools to handle that.

Users shall be assumed to have `openjdk-8-jre` installed already. `BuildGDX.jar` should be put in a game's folder and it shall be run with `java -jar BuildGDX.jar` command. Though, I also have no idea how Steam interacts with that either.

> Also, if you can lookup what the license is and provide that.

That's the tricky part. Cause both [BuildGDX](https://gitlab.com/m210/BuildGDX) and [BloodGDX](https://gitlab.com/m210/BloodGDX) say `No license. All rights reserved.` at the top of the project. However, the source code of BuildGDX has GPL3 and Apache attached; BloodGDX has GPL3 attached. So, I say it's GPL3 and Apache.

https://gitlab.com/m210/BuildGDX/-/blob/master/apache.txt
https://gitlab.com/m210/BuildGDX/-/blob/master/gpl3.txt

https://gitlab.com/m210/BloodGDX/-/blob/master/gpl3.txt

**Comment by d10sfan** [comment]
Ok, can you update the original ticket with only the games that this engine should be used with, along with the license information?

**Comment by ribhutheincompetent** [comment]
>For Shadow Warrior, there exists an official native source port on the store anyway

Don't wanna sound shady here but isn't the Classic Collection... like _free_? A free linux game, in general, doesn't sound like a bad motivation.

**Comment by rea987** [comment]
From BloodGDX `readme.txt`:

> -------------------------------------
> How to add cutscenes to GOG and Steam versions of Blood:
> -------------------------------------

> Easy way - download BuildGDX Pack:
> https://steamcommunity.com/sharedfiles/filedetails/?id=1602966657
>
> Hard way:
> — Download and install IZArc2Go: http://www.izarc.org/downloads
> (you can also use your favorite CD images manager like Daemon Tools)
> 
> — In the game folder, find game.gog file and rename it to game.bin.
> 
> — Open game.bin in IZArc.
> 
> — Extract "movie" folder into the game folder.

I used **gCDEmu** on Linux to mount game.gog (game.bin) image in order to extract movie directory.

**Comment by d10sfan** [comment]
@rea987 NBlood has been added as an engine for Blood

There's a possible issue with this being java based mostly because of flatpak, as well as dependence on an older version of java. Can you provide what the setup process would be for this normally (such as where to put the files, how to run, etc)?

As well, what are the launch commands for the game?

And the add cutscenes piece, can you describe how this would work on Steam? And for both version of it.

**Comment by rea987** [comment]
> There's a possible issue with this being java based mostly because of flatpak, as well as dependence on an older version of java.

Given the flatpak and java situation and considering that NBlood runs just fine, I say BuildGDX shall be dropped.

> And the add cutscenes piece, can you describe how this would work on Steam? And for both version of it.

**Blood: One Unit Whole Blood:**
- `~/.local/share/Steam/steamapps/common/One Unit Whole Blood/game.gog` needs to be mounted. I used **gCDEmu** for that, perhaps it can be mounted with a terminal command. The file can be renamed as game.bin if needed.
- `movie` folder of the mounted imaged needed to be copied in `~/.local/share/Steam/steamapps/common/One Unit Whole Blood`
- NBlood plays movies properly.

**Blood: Fresh Supply:**
This one is tricky. Fresh Supply has original videos in .ogv format but renaming them doesn't do the trick since original game and NBlood use .smk and .wav files for movies. Worst; unlike One Unit Whole Blood, Fresh Supply doesn't offer the original game image to extract movies. The only viable way that I see is to use the file `movie` folder of _BloodSteamFix_ provided in following page;

https://steamcommunity.com/sharedfiles/filedetails/?id=1602966657

**Comment by d10sfan** [comment]
Ok, I think with NBlood working, I can close this for now, like you mentioned.

If there ends up being a reason for supporting this, feel free to comment.

**Comment by ToughGuyKunio** [comment]
One reason to consider supporting this engine is for Witchaven I ([1655410](https://steamdb.info/app/1655410/)) and Witchaven II: Blood Vengeance ([1655430](https://steamdb.info/app/1655430/)). I don't belive there's any other engine for these games?

**Comment by d10sfan** [comment]
@ToughGuyKunio Does BuildGDX provide already built versions of their engine, the jar files?

And have you been able to run buildgdx with those games?

For this to work, the user would have to have java installed on their system globally.

**Comment by ToughGuyKunio** [comment]
Jar file is here: https://m210.duke4.net/index.php/downloads/send/8-java/54-buildgdx

I'll test it, I have only been able to launch the GUI so far, seems to expect files in a specific directory or something, I'll get back to it

**Comment by rea987** [comment]
@d10sfan @ToughGuyKunio

BuildGDX hasn't been updated since I created this ticket, hence information that I have is still valid.

1) BuildGDX does require OpenJDK 8 LTS to function on Linux properly. Most distros use OpenJDK 11 or later. There exists a standalone OpenJDK project that ships OpenJDK 8 LTS builds which run BuildGDX fine.

https://github.com/adoptium/temurin8-binaries/releases/download/jdk8u302-b08/OpenJDK8U-jdk_x64_linux_hotspot_8u302b08.tar.gz
https://github.com/adoptium/temurin8-binaries/releases/
https://github.com/adoptium/temurin8-binaries
https://github.com/adoptium/
https://adoptopenjdk.net/

2) Current version of BuildGDX can partially locate a Build engine games in Steam directory. User needs to correct the path manually.

3) Current version of BuildGDX has no `path` argument to provide game location; also unlike eDuke32 it either has no skip launcher option or the option doesn't work.

**Comment by rea987** [comment]
Just tried BuildGDX v1.15 with Witchaven (GOG copy) via Adoptium's OpenJDK 8 build; it works just fine but despite running the jar at the game directory, it still require manually locating the game location in the launcher. Both Enhanced and Original version of Witchaven seem to be compatible with BuildGDX.

- Make `BuildGDX.jar` executable.
- `.../jdk8u302-b08/bin/java -jar BuildGDX.jar`
- Choose Witchaven
- Choose Folder > Enhanced/GAME/WHAVEN
- Play Witchaven

 
![resim](https://user-images.githubusercontent.com/1547646/130080846-84f6df4a-9bc0-4014-8526-7e677431a9ae.png)
![resim](https://user-images.githubusercontent.com/1547646/130081127-af53f79e-0f90-4f66-ab91-04f8ab15aa5f.png)
![resim](https://user-images.githubusercontent.com/1547646/130081361-2d33364b-574e-4a2a-a76f-393f8f320a5d.png)

**Comment by rea987** [comment]
**WitchavenGDX**'s source code is available but I haven't seen any ready to go build or building instructions.

https://gitlab.com/m210/WitchavenGDX

**Comment by d10sfan** [comment]
Because of the terminal-recall engine, I messed with openjdk and got that to work. So that way system-wide java is no longer required. Whenever I am able to get these games, I'll work on implementing this.

**Comment by d10sfan** [comment]
This is complete in https://github.com/luxtorpeda-dev/packages/pull/513

It will create a config file in the place that the buildgdx launcher is looking in, so that you don't have to manually find it. There does not appear to be any command line switches, so if you want to switch between original and the enhanced version, you'll either have to manually change the path, or delete the file and pick whichever one from the steam options.

I also added powerslave, blood fresh supply, and nam as options to use buildgdx.

**Comment by rea987** [comment]
Can BuildGDX support for Blood: One Unit Whole Blood be added?

https://store.steampowered.com/app/299030/Blood_One_Unit_Whole_Blood/

**Comment by d10sfan** [comment]
@rea987 I don't own that one, so don't have a way to test it. If you can provide the proper paths to the game data, or provide a pull request with that game supported, then it could be added.
