### ISSUE TITLE
X-Com: UFO Defense doesn't start on second launch

### ISSUE THREAD

**Issue by linuxgaming** [luxtorpeda-dev/packages#247]
**Describe the bug**
When I select the engine on the first launch, the game starts and plays well. But on the second launch it's stuck at "preparing to launch" window. Deleting .config/luxtorpeda/7760/engine_choice.txt fixes the problem (for one launch).

**To Reproduce**
Steps to reproduce the behaviour:
1. Launch the game and select either engine
2. Save and quit the game
3. Launch the game again - it doesn't work

**Expected behaviour**
The game should launch using the previously selected engine.

**Additional context**
Experienced on an up-to-date Arch Linux, not tested elsewhere.

**Comment by d10sfan** [comment]
I'm unable to replicate this on my system. When I launch the game, I get the engine chooser and then if I re-launch I get the engine chooser again and everything runs as normal.

Some additional information would be needed:

* What does "it dosen't work" mean - As in does the engine chooser not show up and nothing happens, or does it show up and then the game does not load?
* How was luxtorpeda installed, as in what directory and what version are you using?
* How are you using Steam? Direct with the system or using something like flatpak?
* Please also provide logs, once of the success case where it launches, and one where it fails. As well, it'd be helpful if you can test with another game that has multiple engine choices.

**Comment by linuxgaming** [comment]
1. On the second launch nothing happens, loading is stuck on steam's message "preparing to launch" in a small window
2. Downloaded and unpacked to ~/.steam/steam/compatibilitytools.d/, version 23 from 24.09.2020
3. Direct, no flatpak
4. Where can I find logs? Steam doesn't dump anything to steam-7760.log and there's nothing in .config/luxtorpeda/
5. I tested The Ultimate Doom and it worked as you described, asking for the engine on the second launch
6. After testing Doom, I tested XCOM again (and failed), and now neither of them launches, even after deleting .config/luxtorpeda

**Comment by d10sfan** [comment]
The easiest way to get logs would be to open up Terminal and then launch steam that way (closing steam beforehand). Then the steam logs will also contain luxtorpeda logs in the Terminal window and you can copy that into a file and attach it here.

**Comment by linuxgaming** [comment]
After further investigation I realised it's actually a steam bug. Clicking "Play" doesn't actually launch the game for some reason, but clicking it again works, as seen on this video: https://youtu.be/phljeBl6ykY
Sorry for taking your time!
