### ISSUE TITLE
Commander Genius for Commander Keen

### ISSUE THREAD

**Issue by rea987** [luxtorpeda-dev/packages#251]
* Project link:

https://clonekeenplus.sourceforge.io/
https://clonekeenplus.sourceforge.io/download.php

* Project license: *GPLv2*
* Does it work on 64-bit only Linux: *YES*
* Is source code available?: *YES*
* Is source code stored in Git?: *YES*

https://gitlab.com/Dringgstein/Commander-Genius

* List of Steam AppIds of supported games:
    - https://steamdb.info/app/9180/

## Additional information

id Software 2D platformer classic.

**Comment by d10sfan** [comment]
Thanks for the request, I just got the steam version since it was a dollar, so will work on this soon.

**Comment by d10sfan** [comment]
Added in https://github.com/luxtorpeda-dev/packages/pull/254
