### ISSUE TITLE
Duke Nukem II

### ISSUE THREAD

**Issue by Frenzied-Pop** [luxtorpeda-dev/packages#257]
* Project link: https://github.com/lethal-guitar/RigelEngine
* Project license: *GNU General Public License v2.0*
* Does it work on 64-bit only Linux: YES
* Is source code available?: YES
* Is source code stored in Git?: YES
* List of Steam AppIds of supported games:
    - https://steamdb.info/app/240180/

## Additional information
RigelEngine

## Build Info
sudo apt install libboost-program-options-dev
git clone https://github.com/lethal-guitar/RigelEngine
cd RigelEngine
git submodule update --init --recursive
cd ..
cmake RigelEngine -DCMAKE_BUILD_TYPE=Release
make all // need to find just RigelEngine target

## Installation Info
move /src/**RigelEngine** to /Duke Nukem 2/**RigelEngine**

**Comment by d10sfan** [comment]
Looks like this one is not for sale anymore. Do you own this game?

**Comment by Frenzied-Pop** [comment]
Yes

**Comment by d10sfan** [comment]
Added in https://github.com/luxtorpeda-dev/packages/pull/302

Untested since I don't have access to this game, so let me know if you run into issues.

**Comment by Frenzied-Pop** [comment]
Works great. Thank you!
