### ISSUE TITLE
Blake Stone

### ISSUE THREAD

**Issue by Frenzied-Pop** [luxtorpeda-dev/packages#258]
* Project link: https://github.com/bibendovsky/bstone
* Project license: GNU GENERAL PUBLIC LICENSE Version 2
* Does it work on 64-bit only Linux: YES
* Is source code available?: *YES*
* Is source code stored in Git?: *YES*
* List of Steam AppIds of supported games:
    - https://steamdb.info/app/238050/ Apogee Throwback pack (Bad Launcher)
    - https://steamdb.info/app/358190/ Aliens of Gold (Original)
    - https://steamdb.info/app/358310/ Planet Strike (Sequel)
    
## Additional information
BStone engine

## Build Info
// dependencies: SDL2
git clone https://github.com/bibendovsky/bstone
cmake bstone -DCMAKE_BUILD_TYPE=Release
make

Installation Info for Throwback Pack
move /src/**bstone** to /The Apogee Throwback Pack/Blake Stone/**bstone**
move /src/**bstone** to /The Apogee Throwback Pack/Planet Strike/**bstone**

**Comment by aukondk** [comment]
It's worth noting that the first Blake Stone game is also available on its own on Steam.
https://steamdb.info/app/358190/

**Comment by d10sfan** [comment]
Added in https://github.com/luxtorpeda-dev/packages/pull/296

I only have the pack so if there's any issues with the original games let me know.
