### ISSUE TITLE
Rise of the Triad

### ISSUE THREAD

**Issue by Frenzied-Pop** [luxtorpeda-dev/packages#259]
* Project link: https://github.com/LTCHIPS/rottexpr
* Project license: GNU GENERAL PUBLIC LICENSE Version 2
* Does it work on 64-bit only Linux: YES
* Is source code available?: YES
* Is source code stored in Git?: YES
* List of Steam AppIds of supported games:
    - https://steamdb.info/app/238050/

## Build Info
git clone https://github.com/LTCHIPS/rottexpr
cd ./rottexpr/src/
make

## Installation Info
2 Distinct directories

/The Apogee Throwback Pack/Rise of the Triad/**rott**
/The Apogee Throwback Pack/Extreme Rise of the Triad/**rott**

## Additional information
Part of the Apogee Throwback Pack

**Comment by d10sfan** [comment]
Added in https://github.com/luxtorpeda-dev/packages/pull/294
