### ISSUE TITLE
Wolfenstein 3D / Spear of Destiny / Super Noah's Ark 3D

### ISSUE THREAD

**Issue by Frenzied-Pop** [luxtorpeda-dev/packages#260]
* Project link: https://bitbucket.org/ecwolf/ecwolf/src/master/ |  https://maniacsvault.net/ecwolf/
* Project license: https://maniacsvault.net/ecwolf/wiki/Source_code   Explains it better than I can here
* Does it work on 64-bit only Linux: YES
* Is source code available?: YES
* Is source code stored in Git?: YES
* List of Steam AppIds of supported games:
    - https://steamdb.info/app/2270/ (Wolfenstein 3D)
    - /Wolfenstein 3D/base/**ecwolf**
    - https://steamdb.info/app/9000/ (Wolfenstein 3D: Spear of Destiny)
    - /Spear of Destiny/base/**ecwolf**
    - https://steamdb.info/app/371180/ (Super 3-D Noah's Ark)
    - /Super 3-D Noah's Ark/**ecwolf**

## Build Info
git clone https://bitbucket.org/ecwolf/ecwolf/src/master/
cmake master -DCMAKE_BUILD_TYPE=Release
make

## Install Info
move ecwolf and ecwolf.pk3 to the install data directory

## Additional information
ecwolf engine recognizes the following file extensions as different content, and offers a pop-up asking what you'd like to play if you have multiple missions in the same folder (Spear of Destiny)

wl6 - Wolfenstein 3D
sod - Spear of Destiny
sd2 - Spear of Destiny - Mission Pack 1
sd3 - Spear of Destiny - Mission Pack 2
n3d - Super Noah's Ark 3D

Running ./**ecwolf** in a directory with files with the wl6 will load the original Wolfenstein 3D

Blake Stone and Rise of the Triad works in a similar same way

**Comment by d10sfan** [comment]
Is there a non-retroarch source repository for this engine?

**Comment by d10sfan** [comment]
Also related, it'd help if you had the commands to launch each of these games with this engine.

**Comment by Frenzied-Pop** [comment]
> Also related, it'd help if you had the commands to launch each of these games with this engine.

./ecwolf in the same directory as the data files. The engine looks for a known game extension and creates a game selection prompt.

**Comment by d10sfan** [comment]
What does the game selection prompt do? We normally try to go directly in the game, unless this prompt has additional help (such as configuration).

**Comment by Frenzied-Pop** [comment]
In the Spear of Destiny folder it asks you what mission pack do you want to play. You get the option to make that mission pack the default, and to skip the mission select pop-up altogether. The other games are separate (i.e. Noah is it's own install) so you'd never see the prompt.

**Comment by d10sfan** [comment]
Added in https://github.com/luxtorpeda-dev/packages/pull/297

Only tested with the original game. If you have any issues with the others, let me know.
