### ISSUE TITLE
Master Levels for Doom II

### ISSUE THREAD

**Issue by Frenzied-Pop** [luxtorpeda-dev/packages#261]
* Project link: https://github.com/coelckers/gzdoom | https://heptapod.host/jp-lebreton/wadsmoosh/
* Project license: GPLv3 | MIT
* Does it work on 64-bit only Linux: YES
* Is source code available?: YES
* Is source code stored in Git?: YES
* List of Steam AppIds of supported games:
    - https://steamdb.info/app/9160/

## Additional information
Collected fan levels. The default installation runs the "Doom It" map selector executable. Each level is loaded separate, and upon completion the player goes to level E1L2 of Doom 2 (For the level I tested).

## WadSmoosh - Works, Includes Map Author Names
1. wget https://heptapod.host/jp-lebreton/wadsmoosh/-/archive/branch/default/wadsmoosh-branch-default.tar.gz
2. tar -xvzf wadsmoosh-branch-default.tar.gz
3. cd wadsmoosh-branch-default
3. cp -rfv  "$diststart/common/dist/master/wads/*.wad "source_wads/"
4. cp -rfv  "$diststart/common/dist/masterdoom2/doom2.wad "source_wads/"
5. python3 wadsmoosh.py // maybe just python, no python3?
6. Press Y then Enter // sed this out? i.e. sed '??? and insert # to comment out the confirmation
7. When it closes, you should have a file in the WadSmoosh folder called **doom_complete.pk3**.
## GZDoom Build Info
8. https://github.com/luxtorpeda-dev/packages/blob/master/engines/gzdoom/build.sh
## Installing Files
9. cp -rfv "source/build"/{gzdoom,soundfonts,*.pk3} "$diststart/common/dist/"
10. cp -rfv doom_complete.pk3 "$diststart/common/dist/"
## Final command line 
11. Launch GZDoom with: gzdoom -iwad doom_complete.pk3

## Some of the JSON, still needs Wadsmoosh part
https://github.com/luxtorpeda-dev/packages/blob/master/metadata/packages.json

 "9160": {
        "game_name": "Master Levels for DOOM II",
        "download": [
            {
                "name": "gzdoom",
                "url": "https://github.com/luxtorpeda-dev/packages/releases/download/gzdoom-5/",
                "file": "gzdoom-common-5.tar.xz",
                "cache_by_name": true
            },
                "command": "./run-gzdoom.sh",
                "command_args": [
                    "-iwad",
                    "doom_complete.pk3"
        "information": [
            {
                "store_link": "https://store.steampowered.com/app/9160/",
                "engine_name": "gzdoom",
                "engine_link": "https://github.com/coelckers/gzdoom",
                "version": "4.5.0",
                "comments": "",
                "author": "dreamer/d10sfan",
                "author_link": "https://github.com/dreamer",
                "license": "GPLv3",
                "license_link": "https://github.com/coelckers/gzdoom/blob/master/LICENSE"
            },
        ]
    },

**Comment by aukondk** [comment]
One option could be to run [Wadsmoosh](https://heptapod.host/jp-lebreton/wadsmoosh) on the wad files included which will produce an IWAD with 2 episodes, Hell on Earth and Master levels. The master levels could then be played one after another, level titles and credits included. GZDoom only.
Wadsmoosh is MIT licenced so it could be modified to not include the Doom 2 HoE levels, or maybe make each map a separate episode.

**Comment by Frenzied-Pop** [comment]
Thanks for the tip! @aukondk 
I updated the issue with some pseudo/placeholder steps based on wadsmoosh. It always bothered me that the Plutonia and TNT Doom maps got more attention than this collection.

**Comment by d10sfan** [comment]
@Frenzied-Pop FOr the wadsmoosh part, is there a way of running this command without having user input? If not, this will be required to setup in such a way where you would need to  manually do that and put it in the right place and then the game would launch from there.

**Comment by d10sfan** [comment]
Added here: https://github.com/luxtorpeda-dev/packages/commit/69d56e666cc209072e04c165ec0d74066aef2ada
