### ISSUE TITLE
Duke Nukem I

### ISSUE THREAD

**Issue by Frenzied-Pop** [luxtorpeda-dev/packages#262]
* Project link: https://gitlab.com/silwol/freenukum
* Project license: GNU Affero General Public License v3.0
* Does it work on 64-bit only Linux: MAYBE
* Is source code available?: YES
* Is source code stored in Git?: YES
* List of Steam AppIds of supported games:
    - https://steamdb.info/app/240160/

## Additional information
Freenukem engine

## Build Info
// dependencies: cargo, SDL?
git clone https://gitlab.com/silwol/freenukum
cd freenukum
cargo build --release

## Installation Issues
It has a deliberate process of importing from either a .zip file of the shareware distribution. It is not steam aware. Will reach out to the developer.

**Comment by d10sfan** [comment]
Looks like this one is not for sale anymore. Do you own this game?

**Comment by Frenzied-Pop** [comment]
Yes

**Comment by d10sfan** [comment]
It looks like for this one, the steam version is not supported. Is that correct?

If so, this one wouldn't be able to be packaged, unless the developer changes that.

**Comment by Frenzied-Pop** [comment]
The current code imports the maps from a zip or 1 other format. It's not like most of the other engines that you move the executable in the directory and run it. To make matters worse, it's not for sale anymore.
