### ISSUE TITLE
Final Fantasy 8

### ISSUE THREAD

**Issue by Frenzied-Pop** [luxtorpeda-dev/packages#263]
* Project link: https://github.com/MaKiPL/OpenVIII-monogame | https://github.com/Sebanisu/OpenVIII
* Project license: MIT License
* Does it work on 64-bit only Linux: YES
* Is source code available?: YES
* Is source code stored in Git?: YES
* List of Steam AppIds of supported games:
    - https://steamdb.info/app/39150/ (FINAL FANTASY VIII)
    - https://steamdb.info/app/1026680/ (FINAL FANTASY VIII - REMASTERED) They keep saying remaster. I don't think they know what that means.

## Additional information
OpenVIII-monogame or OpenVIII

"Unable to compile on Ubuntu"
https://github.com/MaKiPL/OpenVIII-monogame/issues/149

The github includes a script, linuxAutoBuild.sh. It's overkill, and I think it has not been tested in some time. This is my own version, it can probably still stand some tweaking. **Both scripts error out.**

## DOTNET on Linux
https://www.nuget.org/ has some dotnet resources used in this project

## Build Info
sudo apt install mono-devel nuget snapd
sudo snap install dotnet-sdk --classic
nuget install MonoGame.Framework.DesktopGL
nuget install MonoGame.Framework.DesktopGL.Core
nuget install MonoGame.Framework.OpenGL
nuget install MonoGame.Content.Builder // For MonoGame.Content.Builder.targets
nuget netfx-4.7.2-devpack // For dotnet Target Framework - dependency issues needs KB2919355 (exists) and KB2919442 (doesn't)
git clone https://github.com/makipl/openviii
cd openviii
dotnet msbuild OpenVIII.sln /target:OpenGLLinux /property:Configuration=DebugLinux /property:Platform=x64

 //error at line 137, swapped text with
`<Import Project="..\MonoGame.Content.Builder.3.7.0.9\build\MonoGame.Content.Builder.targets" /> `

**Comment by d10sfan** [comment]
Does this support both the original and remastered?

**Comment by Frenzied-Pop** [comment]
From https://makipl.github.io/OpenVIII-monogame/
Is Steam version enough to play with OpenVIII? Can I use PC2000 version?
Yes. The Steam release is the best option to be used with OpenVIII. Other than that we also fully support the first PC release.

It looks like he wrote that before the "remaster". There should be some large data file that's constant between all 3 versions. PC2000, Steam (Normal) and Steam Remaster. Still digging into what is available.

**Comment by d10sfan** [comment]
This one requires research (similar to Flotilla FNA) for building with MonoGame and providing necessary dependencies.

How playable is this engine? I'd also need to know if the remastered version worked or only the original.

**Comment by d10sfan** [comment]
It looks like at the moment the engine isn't ready for packaging.

One of the big things there is that the Linux directory path is hardcoded (https://github.com/MaKiPL/OpenVIII-monogame/issues/181) which would make it difficult to package this for wide use.

If that changes, let me know so I can re-open.
