### ISSUE TITLE
Myst III

### ISSUE THREAD

**Issue by Frenzied-Pop** [luxtorpeda-dev/packages#264]
* Project link: https://github.com/residualvm/residualvm
* Project license: GPLv2
* Does it work on 64-bit only Linux: MAYBE
* Is source code available?: YES
* Is source code stored in Git?: YES
* List of Steam AppIds of supported games:
    - https://steamdb.info/app/925930/

## Additional information
ResidualVM, same engine as The Longest Journey which is already in Luxtorpeda

**Comment by NerosTie** [comment]
ResidualVM will be merged soon with ScummVM, I think it's better the wait a little bit (same thing for "The Longest Journey")

**Comment by JoshuaFern** [comment]
I have curated a list of games that work with ScummVM/ResidualVM on Steam, it may be helpful: https://store.steampowered.com/curator/35667778/

**Comment by d10sfan** [comment]
You can do this today by opening the game and then picking from scummvm, residualvm, and dosbox-staging. These are the "default" game engines. Once scummvm has a new release that contains residualvm, then I can switch to that, along with adding any requested games. PRs are always welcome as well for adding a scummvm/residualvm game as an "official" supported one, which would be a change to packages.json.
