### ISSUE TITLE
Blendo Games (Flotilla, Gravity Bone, Thirty Flights of Loving, Quadrilateral Cowboy)

### ISSUE THREAD

**Issue by JoshuaFern** [luxtorpeda-dev/packages#265]
* Project link: https://github.com/blendogames?tab=repositories
* Project license: Various
* Does it work on 64-bit only Linux: MAYBE
* Is source code available?: YES
* Is source code stored in Git?: YES
* List of Steam AppIds of supported games:
    - https://steamdb.info/app/55000/
    - https://steamdb.info/app/214700/
    - https://steamdb.info/app/974090/
    - https://steamdb.info/app/240440/

## Additional information
The developer Blendo Games releases the source code for most of their games.

55000 is free, I personally own 214700 and 974090 but not 240440.

**Comment by d10sfan** [comment]
Some of these games are windows or windows & mac only. Do the sources have build support for Linux for all of these?

**Comment by JoshuaFern** [comment]
I've never built or even played most of these games, however it looks promising to me.

Flotilla was ported to FNA last year.

Gravity Bone and Thirty Flights of Loving both run on idTech2 - They say "The linux version should be buildable, but we haven't tested it for the release."

Quadrilateral Cowboy runs on the idTech4 engine.

**Comment by d10sfan** [comment]
Both Gravity Bone and Thirty Flights are missing support for Linux. There's a fork someone made (https://github.com/AimHere/thirty-flights-of-linux) but it seems to be outdated. From their description, it looks like it's more than just the make file, as there's some Windows-specific code in the source code. 

If someone would be interested in updating the fork and/or helping to maintain it, I'd be happy to add it to the list. Those games need to be ported first before they can be usable in luxtorpeda. I could look at adding support, but that'd take a fair amount of time, so help would be appreciated.

**Comment by d10sfan** [comment]
Quadrilateral Cowboy looks simple enough since it's idtech-4 based and already has Linux support, although that one is officially supported.

Flotilla is FNA/mono based (https://github.com/FNA-XNA/FNA/wiki/3:-Distributing-FNA-Games#gnulinux), so there's be some research involved as to the building process. I've used mono itself a few years ago, but never have used FNA. I'll look when I have a chance.

**Comment by JoshuaFern** [comment]
I'm a bit confused, the project you linked was released 8 years ago but the source code for both Gravity Bone and Thirty Flights were only released in 2020.

**Comment by d10sfan** [comment]
> I'm a bit confused, the project you linked was released 8 years ago but the source code for both Gravity Bone and Thirty Flights were only released in 2020.

The source code was released on their website many years ago from my understanding. The release to github was more recent.

**Comment by d10sfan** [comment]
Closing for now, due to many of these having officially supported native versions. For the ones that are Windows only, if there ends up being an upstream project to make these work on Linux, let me know and I'll work on implementing it.
