### ISSUE TITLE
Blood / Duke Nukem 3D / Shadow Warrior / Redneck Rampage / NAM / WW2GI

### ISSUE THREAD

**Issue by Frenzied-Pop** [luxtorpeda-dev/packages#266]
* Project link: https://github.com/coelckers/Raze/
* Project license: GPLv2
* Does it work on 64-bit only Linux: YES
* Is source code available?: YES
* Is source code stored in Git?: YES
* List of Steam AppIds of supported games:
    - https://steamdb.info/app/359850/ (Duke Nukem 3D)
    - /??? Get from eduke installer
    - https://steamdb.info/app/225140/ (Duke Nukem 3D: Megaton Edition)
    - /Duke Nukem 3D/gameroot/**raze**
    - https://steamdb.info/app/434050/ (Duke Nukem 3D: 20th Anniversary World Tour)
    - /Duke Nukem 3D Twentieth Anniversary World Tour/**raze**
    - https://steamdb.info/app/299030/ (Blood: One Unit Whole Blood)
    - /One Unit Whole Blood/**raze**
    - https://steamdb.info/app/1010750/  (Blood: Fresh Supply)
    - /Blood/**raze**
    - https://steamdb.info/app/238070/ (Shadow Warrior Classic (1997))
    -/Shadow Warrior Original/gameroot/**raze**
    - https://steamdb.info/app/225160/ (Shadow Warrior Classic Redux)
    - /Shadow Warrior Classic/gameroot/**raze**
    - https://steamdb.info/app/565550/ (Redneck Rampage)
    - /Redneck Rampage/Redneck/**raze**
    - https://steamdb.info/app/580940/ (Redneck Rampage Rides Again)
    - /??? Get from eduke installer
    - https://steamdb.info/app/329650/ (NAM) - _No music, eduke32 plays the midis_
    - /Nam/NAM/**raze**
    - https://steamdb.info/app/376750/ (World War II GI)
    - /??? Get from eduke installer

## Additional information
Raze Engine - This engine has everything build engine related on Steam
The build creates 2 files the raze executable and raze.pk3

## Build Info
sudo apt install libvpx-dev
// Requires Zmusic
git clone https://github.com/coelckers/ZMusic.git
mkdir ZMusic/build
cd ZMusic/build
cmake .. -DCMAKE_BUILD_TYPE=Release
cmake --build ./
sudo make install

git clone https://github.com/coelckers/Raze/
cmake Raze -DCMAKE_BUILD_TYPE=Release
make raze raze_pk3

**Comment by NerosTie** [comment]
I tested this engine last week, it's very good. It's GZDoom but for games made with the Build engine.

It's difficult to find all the commands to launch the games, that's why I didn't open an issue.

> Does it work on 64-bit only Linux: MAYBE

Why "maybe"? Of course it's 64 bits.

**Comment by d10sfan** [comment]
I'd need a list of commands needed to launch each one, which will help alot for games I do not own.

**Comment by Frenzied-Pop** [comment]
> I'd need a list of commands needed to launch each one, which will help alot for games I do not own.

I've edited the listings above with the working directories. Had audio issues with 2 of the games, rest were 10/10 (That I had access to)

**Comment by d10sfan** [comment]
Tracking progress here: https://github.com/luxtorpeda-dev/packages/pull/275

**Comment by d10sfan** [comment]
Implemented here: https://github.com/luxtorpeda-dev/packages/pull/275
