### ISSUE TITLE
Master of Orion 1

### ISSUE THREAD

**Issue by Frenzied-Pop** [luxtorpeda-dev/packages#268]
* Project link: https://gitlab.com/KilgoreTroutMaskReplicant/1oom
* Project license: GPLv2
* Does it work on 64-bit only Linux: YES
* Is source code available?: YES
* Is source code stored in Git?: YES
* List of Steam AppIds of supported games:
    - https://steamdb.info/app/410970/

## Additional information
1oom engine

## Build Info
sudo apt install libsdl1.2-dev libsdl-mixer1.2-dev libsdl2-dev libsdl2-mixer-dev libsamplerate-dev autoreconf
git clone https://gitlab.com/KilgoreTroutMaskReplicant/1oom
cd 1oom
autoreconf -fi
mkdir build-native
cd build-native
../configure && make -j 3

## Install Info
move /1oom/build-native/src/**1oom_classic_sdl2** to /Master of Orion 1/data/**1oom_classic_sdl2**

## Game Play
The start window is tiny.  Press alt-enter to toggle full-screen

**Comment by d10sfan** [comment]
Have you been able to hear music in this port? If so, what OS do you have and do you have timidity installed?

**Comment by Frenzied-Pop** [comment]
This is the console output from my last session
![MOO1](https://user-images.githubusercontent.com/79120763/109393039-8cd0ab80-78ed-11eb-8f57-dc9dbb08a8f1.png)

I heard the music and sounds in the startup movie. I heard the music at the main screen. I only had game sounds (no music) when I was playing the game. It plays VERY soft music with DOSBox-Staging. You can just hear some ambient noises.

**Comment by d10sfan** [comment]
Added in https://github.com/luxtorpeda-dev/packages/pull/272
