### ISSUE TITLE
Entropy : Zero

### ISSUE THREAD

**Issue by rea987** [luxtorpeda-dev/packages#269]
* Project link:

https://store.steampowered.com/app/714070/Entropy__Zero/
https://www.entropyzeromod.com/entropy-zero

* Project license: *SOURCE 1 SDK LICENSE*

https://github.com/z33ky/source-sdk-2013/blob/master/LICENSE

* Does it work on 64-bit only Linux: *MAYBE*
* Is source code available?: *YES*
* Is source code stored in Git?: *YES*

https://github.com/z33ky/source-sdk-2013

* List of Steam AppIds of supported games:
    - https://steamdb.info/app/714070/

## Additional information

Entropy : Zero is a Half-Life 2 : Episode 2 mod. Installation instruction is available in `readme.txt` within `ez1-v4.linux3.tar.xz`.

https://github.com/z33ky/entropy-zero/releases/download/ez1-v4.linux3/ez1-v4.linux3.tar.xz
https://github.com/z33ky/entropy-zero/releases/

**Comment by rea987** [comment]
Up to date installation instructions:

https://steamcommunity.com/app/714070/discussions/0/1479857071249933307/?tscn=1614222778#c3113647550045963591

**Comment by d10sfan** [comment]
Added in https://github.com/luxtorpeda-dev/packages/commit/87cbec8857caaf502d4fca4f9c81c1cbefd7f1cb

Also added Minerva Metastasis
