### ISSUE TITLE
Hexen: Deathkings of the Dark Citadel

### ISSUE THREAD

**Issue by Frenzied-Pop** [luxtorpeda-dev/packages#271]
* Project link: gzdoom / doomsday / Chocolate Doom / prboom-plus
* Project license: GPLv2 / GPLv3
* Does it work on 64-bit only Linux: YES
* Is source code available?: YES
* Is source code stored in Git?: YES
* List of Steam AppIds of supported games:
    - https://steamdb.info/app/2370/

## Additional information
Standalone Expansion to Hexen 1 

## Installation / Configuration
/Hexen Deathkings of the Dark Citadel/base/
HEXDD.WAD and HEXENDK.EXE

This directory contains the classic Hexen WAD and EXE as well.

**Comment by d10sfan** [comment]
Have you tried this one? There was an issue report a while back about possible issues with at least gzdoom:

https://github.com/dreamer/luxtorpeda/issues/36

**Comment by Frenzied-Pop** [comment]
It works. I dropped these gzdoom files from my Final Doom installation into the base directory of Hexen Deathkings. 

brightmaps.pk3
game_support.pk3
lights.pk3
game_widescreen_gfx.pk3
gzdoom
gzdoom.pk3

gzdoom detecting classic Hexen and the expansion
![HEXENDK](https://user-images.githubusercontent.com/79120763/109368982-d62ae780-7868-11eb-840b-26979f205c02.png)

From the gzdoom compatibility info file
![HEXENDK2](https://user-images.githubusercontent.com/79120763/109369068-1ab68300-7869-11eb-9099-8ead146cb934.png)

If this becomes an issue, this exists.
https://www.moddb.com/downloads/hexen-dotdc-steamupdate

**Comment by d10sfan** [comment]
Thanks for the update, added in https://github.com/luxtorpeda-dev/packages/pull/274

**Comment by Frenzied-Pop** [comment]
The installer is working, it either needs to go one folder further into ./base/ so gzdoom can see the HEXEN.WAD and HEXDD.WAD or the files can be somehow specified like gzdoom -file ./base/HEXEN.WAD
I modified run-gzdoom.sh to try to just add the wads, but I'm not having any luck.

https://zdoom.org/wiki/Installation_and_execution_of_ZDoom

**Comment by d10sfan** [comment]
What's the issue? Is it not loading correctly? I tried loading it and it worked ok for me with gzdoom

**Comment by Frenzied-Pop** [comment]
Did you have gzdoom in the same directory as the wads?

**Comment by d10sfan** [comment]
For me gzdoom is in the game directory and then the WAD is in the base directory, like the other games.

Can you send a screenshot of what your directory listing looks like? As well as a log from launching steam in Terminal and choosing gzdoom for this game?

**Comment by Frenzied-Pop** [comment]
I changed my script to this, works fine
LD_LIBRARY_PATH="lib:$LD_LIBRARY_PATH" && cd ./base && ../gzdoom "$@"

This is what I get if I don't add the cd ./base part
![HEXENDK](https://user-images.githubusercontent.com/79120763/109398416-ded3fa00-790a-11eb-971a-8096c1ca7342.png)

**Comment by d10sfan** [comment]
Can you provide the luxtorpeda logs? That'll help see where the problem might be.

**Comment by Frenzied-Pop** [comment]
creating: "/run/user/1000/luxtorpeda/2370.pid"
steam_app_id: "2370"
original command: ["/home/timhale/.steam/debian-installation/steamapps/common/Hexen Deathkings of the Dark Citadel/base/dosbox.exe", "base\\hexendk.exe", "-conf", "base\\hexen.conf", "-fullscreen", "-exit"]
working dir: Ok("/home/timhale/.steam/debian-installation/steamapps/common/Hexen Deathkings of the Dark Citadel")
tool dir: "/home/timhale/.steam/debian-installation/compatibilitytools.d/luxtorpeda"
engine choice complete
json:
{
    "game_name": "HeXen: Deathkings of the Dark Citadel",
    "download": [
        {
            "name": "gzdoom",
            "url": "https://github.com/luxtorpeda-dev/packages/releases/download/gzdoom-5/",
            "file": "gzdoom-common-5.tar.xz",
            "cache_by_name": true
        }
    ],
    "information": [
        {
            "store_link": "https://store.steampowered.com/app/2360/",
            "engine_name": "gzdoom",
            "engine_link": "https://github.com/coelckers/gzdoom",
            "version": "4.5.0",
            "comments": "",
            "author": "dreamer/d10sfan",
            "author_link": "https://github.com/dreamer",
            "license": "GPLv3",
            "license_link": "https://github.com/coelckers/gzdoom/blob/master/LICENSE"
        },
        {
            "store_link": "https://store.steampowered.com/app/2360/",
            "engine_name": "doomsday",
            "engine_link": "https://github.com/skyjake/Doomsday-Engine",
            "version": "v2.3.0",
            "comments": "",
            "author": "d10sfan",
            "author_link": "https://github.com/d10sfan",
            "license": "GPLv3/LGPLv3",
            "license_link": "https://github.com/skyjake/Doomsday-Engine"
        }
    ],
    "command": "./run-gzdoom.sh",
    "command_args": [
        "-iwad",
        "base/HEXDD.WAD"
    ]
}
install: "run-gzdoom.sh"
install: "gzdoom"
install: "gzdoom.pk3"
install: "brightmaps.pk3"
install: "soundfonts"
install: "soundfonts/gzdoom.sf2"
install: "lib"
install: "lib/libfluidsynth.so.2"
install: "lib/libzmusic.so"
install: "lib/libfluidsynth.so.2.3.3"
install: "lib/libfluidsynth.so"
install: "game_widescreen_gfx.pk3"
install: "game_support.pk3"
install: "lights.pk3"
install: "license"
install: "license/licenses.legal.txt"
install: "license/licenses.zmusic.txt"
install: "license/fluidsynth.LICENSE"
install: "license/LICENSE.gzdoom"
install: "license/..LICENSE"
install: "license/licenses.bsd.txt"
install: "license/licenses.dumb.txt"
install: "license/licenses.gplv3.txt"
run: "./run-gzdoom.sh" with args: ["-iwad", "base/HEXDD.WAD"] ["base\\hexendk.exe", "-conf", "base\\hexen.conf", "-fullscreen", "-exit"]
GZDoom g4.5.0-1-g0bb8235 - 2019-09-10 12:53:16 +0200 - SDL version
Compiled on Oct 31 2020

M_LoadDefaults: Load system defaults.
dropping: "/run/user/1000/luxtorpeda/2370.pid"

**Comment by d10sfan** [comment]
@Frenzied-Pop Can you try again? I pushed this up: https://github.com/luxtorpeda-dev/packages/commit/6577dc0333f4e4995bdba75cc31b744c0e92ce66

I couldn't replicate the issue on my system, but this adds both iwads to the load command for gzdoom.

**Comment by Frenzied-Pop** [comment]
./gzdoom -iwad base/HEXEN.WAD -file base/HEXDD.WAD
does the trick

**Comment by d10sfan** [comment]
Ok, added in https://github.com/luxtorpeda-dev/packages/commit/5a343b827ba7f238e5a1c598b8b8c02be08af92e
