### ISSUE TITLE
Half-Life 2: Year Long Alarm

### ISSUE THREAD

**Issue by rea987** [luxtorpeda-dev/packages#276]
* Project link:

https://store.steampowered.com/app/747250/HalfLife_2_Year_Long_Alarm/
https://www.aspaceman.com/year-long-alarm

* Project license: *Unknown*
* Does it work on 64-bit only Linux: *NO*
* Is source code available?: *NO*
* Is source code stored in Git?: *NO*
* List of Steam AppIds of supported games:
    - https://steamdb.info/app/747250/

## Additional information

A free Half-Life 2 mod on Steam. Installation method:

https://steamcommunity.com/id/realtunya/recommended/747250

**Comment by d10sfan** [comment]
Added in https://github.com/luxtorpeda-dev/packages/commit/1181b21cdccd8d6bd0b2864065889092ee07f980
