### ISSUE TITLE
Better designed packages list

### ISSUE THREAD

**Issue by rea987** [luxtorpeda-dev/packages#277]
https://luxtorpeda-dev.github.io/packages.html

Current packages list is getting hard to read as it gets larger and longer. It would be much better to have spreadsheet-like look that lines separates stripes and rows. Thank you!

**Comment by d10sfan** [comment]
Done in https://github.com/luxtorpeda-dev/packages/commit/4a5efadf102cc3a8e6c0c828ef8d15dc42d04f88

Added bootstrap table use so the CSS and layout should look better.
