### ISSUE TITLE
Resistance Element for Source

### ISSUE THREAD

**Issue by rea987** [luxtorpeda-dev/packages#278]
* Project link:

https://store.steampowered.com/app/1054600/Resistance_Element/

* Project license: *Unknown*
* Does it work on 64-bit only Linux: *NO*
* Is source code available?: *NO*
* Is source code stored in Git?: *NO*
* List of Steam AppIds of supported games:
    - https://steamdb.info/app/1054600/

## Additional information

Resistance Element is a free Source mod on Steam. As it is stated in the store page;

`You do not need to have Source SDK 2013 or Half-Life 2 : Episode 2 installed to play Resistance Element.`

I am able run the mod by editing `gameinfo.txt` and copying Linux libraries from Source SDK 2013. Steps:

1) Install **Resistance Element**
2) Install **Source SDK Base 2013 Singleplayer** (`upcoming` branch)
3) Copy `~/.local/share/Steam/steamapps/common/ResistanceElement/ResistanceElement` to `~/.local/share/Steam/steamapps/sourcemods`
4) Within `~/.local/share/Steam/steamapps/sourcemods/ResistanceElement`, apply following;

`$ LANG=en_US.UTF-8 bash`
`$ find ./ | sort -r | sed 's/\(.*\/\)\(.*\)/mv "\1\2" "\1\L\2"/' |sh`

5) Change line 37 and 38 of `~/.local/share/Steam/steamapps/sourcemods/ResistanceElement/gameinfo.txt`

`		SteamAppId		243730	// Source SDK Base 2013 Sp, mounts all needed GCFs (240=CS:S, 220=HL2)`
`		//SteamAppId	1054600	// Resistance Element AppId`

6) Copy `client.so` and `server.so` from `~/.local/share/Steam/steamapps/common/Source SDK Base 2013 Singleplayer/sourcetest/bin` to `~/.local/share/Steam/steamapps/sourcemods/ResistanceElement/bin`
7) Launch the mod.

**Comment by d10sfan** [comment]
Added in https://github.com/luxtorpeda-dev/packages/pull/280
