### ISSUE TITLE
Entropy : Zero Manhack Bug

### ISSUE THREAD

**Issue by Kern3l-Panic** [luxtorpeda-dev/packages#279]
**Describe the bug**
When I enter the firing range and equip the manhack I can deploy it infinitely despite the ammo meter saying "1"

**To Reproduce**
Steps to reproduce the behaviour:
1. Enter the firing range from the menu
2. Equip the manhack weapon
3. Deploy it infinitely even though it's only at "1" in the inventory

**Expected behaviour**
I expect that I should only be able to have a limited amount of manhacks at a time.

**Screenshots**
None

**Additional context**
To fix the issue, I contacted the creator of the port and they said to keep the "weapon_manhacktoss.txt" at original values and then to add the "default_clip" change under "clip_size" to the file. Result taken from lines 15-19:

    "clip_size"			"-1"
    "default_clip"		"1"
    "clip2_size"			"-1"
    "primary_ammo"		"Manhack"
    "secondary_ammo"	"None"

I tested this fix out and it worked for me.

**Comment by d10sfan** [comment]
Added in https://github.com/luxtorpeda-dev/packages/commit/9fbfcda3dd5978e1ef448242bcd8a02ddb4d344f
