### ISSUE TITLE
Runelite for Old School RuneScape (OSRS)

### ISSUE THREAD

**Issue by JoshuaFern** [luxtorpeda-dev/packages#281]
* Project link: https://github.com/runelite/runelite
* Project license:  BSD-2-Clause
* Does it work on 64-bit only Linux: MAYBE
* Is source code available?: YES
* Is source code stored in Git?: YES
* List of Steam AppIds of supported games:
    - https://steamdb.info/app/1343370/

## Additional information
Old School RuneScape for Steam has a unique feature to login using your Steam account. This feature is unimplemented in Runelite so you would need to login using a typical email/password. See: https://support.runescape.com/hc/en-gb/articles/360013472137-Add-a-login-email-to-a-Steam-created-account

**Comment by d10sfan** [comment]
Added in https://github.com/luxtorpeda-dev/packages/pull/301

Only tested up to the login page as it seems to require a subscription. Steam overlay won't work due to needing to reset the library path, so that the appimage is able to run.

**Comment by JoshuaFern** [comment]
Unfortunately I won't be able to use this on Flatpak'd Steam because you can't run an AppImage inside of a Flatpak.

**Comment by d10sfan** [comment]
It looks like the project does not recommend building an "unofficial client", as you can see here: https://github.com/runelite/runelite/wiki/FAQ#will-using-runelite-get-me-banned

I could use the jar they provide instead of the appimage, although that would require you to have java installed in your flatpak environment. Not sure if that'd be possible/feasible.

**Comment by JoshuaFern** [comment]
We don't have to build anything, the AppImage already has JRE in it. We can just extract the AppImage and run it with the included Java. I've already tested doing this in a Flatpak and it works fine.

To extract an AppImage: `chmod +x RuneLite.AppImage && ./RuneLite.AppImage --appimage-extract` this extraction process works even in a Flatpak.
The files will be extracted into `./squashfs-root/` the game can then be started with `./squashfs-root/RuneLite`

**Comment by d10sfan** [comment]
Ah ok thanks, that works!

I pushed up a change to do this: https://github.com/luxtorpeda-dev/packages/commit/12764bd03a150558d3a5a3df491b4a082a0956a3

Now it'll ask you on launch if you want the app image directly or an extracted version

**Comment by JoshuaFern** [comment]
Seems to be working for me now.

To get past the login page you need to switch worlds to a free world, the world switch button is in the bottom left corner of the login screen.
