### ISSUE TITLE
Master of Magic

### ISSUE THREAD

**Issue by SantiagoPaak** [luxtorpeda-dev/packages#283]
* Project link: https://github.com/dosbox-staging/dosbox-staging
* Project license: GPLv3
* Does it work on 64-bit only Linux: YES
* Is source code available?: YES
* Is source code stored in Git?: YES
* List of Steam AppIds of supported games:
    - https://store.steampowered.com/app/1146370/Master_of_Magic/

## Additional information

The game comes with a launcher that lets you select between three versions of the game (Master of Magic Official Release, Master of Magic Community Patch, and Master of Magic Caster of Magic DLC), each in its own folder. The launcher is unnecessary for the game to work and it works on Linux but it throws error messages.
It is then loading a Windows version of DOSBOX to load each version of the game, running the executable MAGIC.EXE. CPU Cycles are set at 10000.

**Comment by Frenzied-Pop** [comment]
I'll submit the dosbox-staging configuration info and test it if @d10sfan is OK with it. Master of Orion 1 would be a good example to base this off of. There are 4 game launch options to figure out in the complete version.

**Comment by d10sfan** [comment]
> I'll submit the dosbox-staging configuration info and test it if @d10sfan is OK with it. Master of Orion 1 would be a good example to base this off of. There are 4 game launch options to figure out in the complete version.

Yes, that works for me. Feel free to create a pull request when you're ready. Thanks :)

**Comment by Frenzied-Pop** [comment]
The default dosbos-staging settings aren't going to work. The game uses a custom launcher. The complete version of the game (minus the Windows version) directory structure looks like this.

/.steam/debian-installation/steamapps/common/Master of Magic/Master of Magic Caster of Magic DLC/dosboxMOM.conf
/.steam/debian-installation/steamapps/common/Master of Magic/Master of Magic Community Patch/dosboxMOM.conf
/.steam/debian-installation/steamapps/common/Master of Magic/Master of Magic Official Release/dosboxMOM.conf

I'm not sure how to pick for the user. The Master of Magic Official Release directory is mandatory. We could set
 "use_original_command_directory": false  // There are no examples of this

Then, set the command to run the base game.

The addition to packages.json could look like this

"1146370": {
        "game_name": "Master of Magic",
        "download": [
            {
                "name": "dosbox-staging",
                "url": "https://github.com/luxtorpeda-dev/packages/releases/download/dosbox-staging-4/",
                "file": "dosbox-staging-common-4.tar.xz",
                "cache_by_name": true
            }
        ],
        "download_config": {
            "dosbox-staging": {
                "extract_location": "../dosbox-staging"
            }
        },
        "choices": [
            {
                "name": "dosbox-staging", 
                "command": "../dosbox-staging/run-dosbox-staging.sh -conf ./Master of Magic Official Release/dosboxMOM.conf",
                "use_original_command_directory": false,
                "download": [
                "dosbox-staging"
                ]
            }
        ],
        "information": [
            {
                "store_link": "https://store.steampowered.com/curator/35328265/",
                "engine_name": "dosbox-staging",
                "engine_link": "https://github.com/dosbox-staging/dosbox-staging",
                "version": "0.76.0",
                "comments": "",
                "author": "d10sfan",
                "author_link": "https://github.com/d10sfan",
                "license": "GPLv2",
                "license_link": "https://github.com/dosbox-staging/dosbox-staging/blob/master/COPYING"
            }
        ]
    },

**Comment by d10sfan** [comment]
@Frenzied-Pop For that you could create custom scripts for these to cd into the right directories if that is needed, or provide the correct config file using the right command line switches. For these changes, you'll also want to change the env shell script for dosbox-staging to add the app id for master of magic as well. You can see how that works, it can be done to the same pull request.

**Comment by d10sfan** [comment]
Added in https://github.com/luxtorpeda-dev/packages/commit/bc094a3e80605dad00124947e699b3f357a2de0a
