### ISSUE TITLE
Quake I not running

### ISSUE THREAD

**Issue by FurtadoPires** [luxtorpeda-dev/packages#284]
**Describe the bug**
Quake I (steam) is not running when select Luxtorpeda as compatibility tool, when I try to launch the game just close.

**To Reproduce**
Steps to reproduce the behaviour:
1. Install the game
2. Select Luxtorpeda as compatibility tool
3. Try to run Quake

**Expected behaviour**
Game running with native packages

**Additional context**
Manjaro Gnome (using wayland)
Drivers: Mesa 20.3.3

**Comment by d10sfan** [comment]
@FurtadoPires 

Does this work in x11 on your system?
Can you run Steam in Terminal and then run the game and put the output in a file attached here? This will help see what issues may have happened.

**Comment by FurtadoPires** [comment]
> @FurtadoPires
> 
> Does this work in x11 on your system?
> Can you run Steam in Terminal and then run the game and put the output in a file attached here? This will help see what issues may have happened.

Same problem with x11, any way I can get some logs to post here?

**Comment by d10sfan** [comment]
@FurtadoPires Yes, I mentioned that in my reply, see here:
Can you run Steam in Terminal and then run the game and put the output in a file attached here? This will help see what issues may have happened.

**Comment by FurtadoPires** [comment]
[Quake 1 Luxtorpeda.log](https://github.com/luxtorpeda-dev/packages/files/6085202/Quake.1.Luxtorpeda.log)

**Comment by d10sfan** [comment]
@FurtadoPires What version of luxtorpeda-dev are you using? As well, can you send what your packages.json looks like? This would be at ~/.cache/luxtorpeda/packages.json

And what selection on the steam prompt do you pick? You should see first where you pick from the list that steam provides, and then you should see a list of engine choices from luxtorpeda.

**Comment by FurtadoPires** [comment]
[packages.json.txt](https://github.com/luxtorpeda-dev/packages/files/6085279/packages.json.txt)

I'm using [Version 24](https://github.com/luxtorpeda-dev/luxtorpeda/releases/tag/v24)

**Comment by d10sfan** [comment]
It looks like there's an empty default choice. Can you remove this file: ~/.config/luxtorpeda/2310/default_engine_choice.txt and try again?

**Comment by FurtadoPires** [comment]
> It looks like there's an empty default choice. Can you remove this file: ~/.config/luxtorpeda/2310/default_engine_choice.txt and try again?

Worked with vkQuake, but not with the other 2 options
Worked:
[Quake I playquake_vkquake.log](https://github.com/luxtorpeda-dev/packages/files/6085501/Quake.I.playquake_vkquake.log)

Didn't Work:
[Quake I playquake_darkplaces2017.log](https://github.com/luxtorpeda-dev/packages/files/6085503/Quake.I.playquake_darkplaces2017.log)
[Quake I playquake_quakespasm-spiked.log](https://github.com/luxtorpeda-dev/packages/files/6085504/Quake.I.playquake_quakespasm-spiked.log)

**Comment by d10sfan** [comment]
That looks to be because of this: thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: InvalidArchive("Could not find central directory end")', src/package.rs:541:27

You'll need to remove the cached files from that launch attempt. That could either be because of an internet issue or if you exited the game before luxtorpeda-dev had a chance to complete the download & installation.

**Comment by FurtadoPires** [comment]
> That looks to be because of this: thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: InvalidArchive("Could not find central directory end")', src/package.rs:541:27
> 
> You'll need to remove the cached files from that launch attempt. That could either be because of an internet issue or if you exited the game before luxtorpeda-dev had a chance to complete the download & installation.

Where are the files that I need to delete in order to download again? I think it didn't downloaded correctly because the link may be offline

**Comment by d10sfan** [comment]
That would be ~/.cache/luxtorpeda/2310/

**Comment by FurtadoPires** [comment]
It worked, now all of them are working perfectly.

It would be possible to make Luxtorpeda do some kind of hash comparative to make sure the files are ok? I wouldn't know the problem was with my local files if I haven't open this report.

Anyway I'll be closing this one, thank you for the help (and this project).

**Comment by d10sfan** [comment]
Ok good to hear. I'll take that into consideration.
