### ISSUE TITLE
Quake IV not running

### ISSUE THREAD

**Issue by FurtadoPires** [luxtorpeda-dev/packages#285]
**Describe the bug**
Quake IV (steam) is not running when select Luxtorpeda as compatibility tool, when I try to launch the game just close.

**To Reproduce**
Steps to reproduce the behaviour:
1. Install the game
2. Select Luxtorpeda as compatibility tool
3. Try to run Quake

**Expected behaviour**
Game running with native packages

**Additional context**
Manjaro Gnome (using wayland)
Drivers: Mesa 20.3.3

**Comment by d10sfan** [comment]
@FurtadoPires 

Does this work in x11 on your system?
Can you run Steam in Terminal and then run the game and put the output in a file attached here? This will help see what issues may have happened.

**Comment by FurtadoPires** [comment]
> @FurtadoPires
> 
> Does this work in x11 on your system?
> Can you run Steam in Terminal and then run the game and put the output in a file attached here? This will help see what issues may have happened.

Same problem with x11

**Comment by FurtadoPires** [comment]
[Quake IV Luxtorpeda.log](https://github.com/luxtorpeda-dev/packages/files/6085205/Quake.IV.Luxtorpeda.log)

**Comment by d10sfan** [comment]
@FurtadoPires It looks like there's an issue possibly with the download or execution of the quake 4 run file. 

What does the directory listing for your Quake 4 installation look like? 

As well, what does the linuxdata/bin folder look like?

**Comment by FurtadoPires** [comment]
> @FurtadoPires It looks like there's an issue possibly with the download or execution of the quake 4 run file.
> 
> What does the directory listing for your Quake 4 installation look like?
> 
> As well, what does the linuxdata/bin folder look like?


[Quake IV Directory Tree.log](https://github.com/luxtorpeda-dev/packages/files/6085261/Quake.IV.Directory.Tree.log)

**Comment by d10sfan** [comment]
It looks like the bin folder is missing. Can you remove the ready file and then try again? It may take some time for the first launch so give it a bit of time to load

**Comment by FurtadoPires** [comment]
> It looks like the bin folder is missing. Can you remove the ready file and then try again? It may take some time for the first launch so give it a bit of time to load

Worked at first when I deleted the ready file, but crashed again after I change the resolution and restart the game

[Quake 4 post resolution change.log](https://github.com/luxtorpeda-dev/packages/files/6085407/Quake.4.post.resolution.change.log)

**Comment by d10sfan** [comment]
It looks like this is the issue there: Fatal Error: Unable to initialize OpenGL

Did you set the resolution to one that is listed in that part of the log?

You may want to reset the configuration and then try again, since it looks like the game itself is there as expected.

**Comment by FurtadoPires** [comment]
> It looks like this is the issue there: Fatal Error: Unable to initialize OpenGL
> 
> Did you set the resolution to one that is listed in that part of the log?

Yes I first tried 1600x900

So I tried those steps:
1 - Change the resolution again editing "Quake4Config.cfg" since I couldn't launch the game - Didn't work
2 - Uninstalled the game and deleted the Quake 4 folder, them installed again - Didn't work
3 - Change the compatibility tool to Proton and launched the game, them change the resolution again to a valid one, them tried to launch using Luxtorpeda again - Same problem

Is Luxtorpeda using a different config file than the default one?

**Comment by d10sfan** [comment]
@FurtadoPires Quake 4 stores it's config in the user directory like this: ~/.quake4/q4base/Quake4Config.cfg

Check there for any configuration you may need to do.

**Comment by FurtadoPires** [comment]
> 
> 
> @FurtadoPires Quake 4 stores it's config in the user directory like this: ~/.quake4/q4base/Quake4Config.cfg
> 
> Check there for any configuration you may need to do.

So change the configuration files didn't work. I even tried to delete everything from the game folder and inside the cache directory, so now I don't know why I still getting the message

`Fatal Error: Unable to initialize OpenGL`

**Comment by d10sfan** [comment]
Did you try deleting that configuration file and trying again?

That error sounds like something to do with your system

**Comment by FurtadoPires** [comment]
I've tried to delete everything inside ~/.cache/luxtorpeda/2210 and /common/Quake4/ and download again, but still have the same problem.

It works if I choose proton though

**Comment by d10sfan** [comment]
Did you try deleting the Quake4Config.cfg file and trying to launch the game again?

**Comment by FurtadoPires** [comment]
> Did you try deleting the Quake4Config.cfg file and trying to launch the game again?

Yes, the game just generates the file again. I suspect that luxtorpeda may be using the configs from elsewhere, because even after download everything again, the problem remains.

Fortunatelly other games using luxtorpeda are working fine, so it's just this game for me

**Comment by d10sfan** [comment]
The game would generate the file yes, but it should be using that one. luxtorpeda does not change the game's behavior in that regard. If you're having issues with the sdl not launching error, then it sounds like an incompatibility with your system and this port.

**Comment by FurtadoPires** [comment]
It may be a problem with the game being x86 and my system being x64, anyway I'm giving up because I don't have the knowledge to debug / workaround further than what I've already tried.

Do you want me to close this issue, or let it open in hope that someone will find a fix?

**Comment by d10sfan** [comment]
There may be some libraries missing from your system. I'll go ahead and close this for now, and someone can always comment if there's any further tips or information.
