### ISSUE TITLE
Half-Life: Before

### ISSUE THREAD

**Issue by rea987** [luxtorpeda-dev/packages#286]
* Project link:

https://store.steampowered.com/app/261980/HalfLife_Before/
https://www.moddb.com/mods/half-life-before

* Project license:

Mod: Unknown
Xash3D FWGS v0.19.2: GPLv3
https://github.com/FWGS/xash3d/blob/master/COPYING
Spirit of Half-Life 1.2: Unknown

* Does it work on 64-bit only Linux: *NO*
* Is source code available?: *YES*

https://github.com/FWGS/xash3d
https://www.moddb.com/mods/spirit-of-half-life/downloads/sohl-v12-with-source-code
https://www.moddb.com/mods/spirit-of-half-life/downloads/spirit-of-half-life-12-crossplatform

* Is source code stored in Git?: *YES*
* List of Steam AppIds of supported games:
    - https://steamdb.info/app/261980/

## Additional information

I finally managed to make Half-Life: Before run via Xash3D FWGS v0.19.2 thanks to Spirit of Half-Life (SoHL) mod. It tuns out HL:B was made with SoHL.

https://www.moddb.com/mods/spirit-of-half-life

Steps:
1) Download and extract `xash3d_fwgs_linux_0.19.2.tar.xz`:
https://github.com/FWGS/xash3d/releases

2) Copy `~/.local/share/Steam/steamapps/common/Half-Life/valve` folder into `xash3d_fwgs_linux_0.19.2` directory.

3) Download and extract `halflife_before1.1.zip`:
https://www.moddb.com/mods/half-life-before/downloads/half-life-before-full-version-11

4) Extract the .zip, copy `before` folder into `xash3d_fwgs_linux_0.19.2` directory.

5) Download and extract "Spirit of Half-Life 1.2 crossplatform v1.0.1" release:
https://www.moddb.com/mods/spirit-of-half-life/downloads/spirit-of-half-life-12-crossplatform

6) Copy `.../Spirit/cl_dlls/client.so` and `.../Spirit/dlls/spirit.so` to `.../before/cl_dlls` and `.../before/dlls` directories respectively.

7) Edit `.../before/liblist.gam`; change `gamedll "dlls/spirit.dll"` line as `gamedll "dlls/spirit.so"`

8) Launch Xash3D FWGS:

`LC_ALL=C ./xash3d.sh -game before -dll dlls/spirit.so -clientlib cl_dlls/client.so`

**Comment by d10sfan** [comment]
Do you have an example of this where you use the assets from the steam download instead of using moddb or the half-life before?

Also, for the sprint of half-life... moddb does not seem to work for downloading from the lux-client, since they require a browser session. Do you know another way of getting this download or another download  that would work for this?

**Comment by rea987** [comment]
I found GitHub branch of SoHL 1.2:

https://github.com/nekonomicon/hlsdk-xash3d/tree/sohl1.2

Can this be compiled and used instead?

**Comment by d10sfan** [comment]
I'm hesitant to compile hlsdk-xash3d and host those binaries, so another source would be preferred.

**Comment by rea987** [comment]
I shall reupload pre-compiled Mod DB version of SoHL 1.2 to archive.org if that's all right for you.

**Comment by d10sfan** [comment]
Yes, I think that should be ok.

**Comment by rea987** [comment]
https://archive.org/details/SoHL1.2
https://archive.org/download/SoHL1.2/Spirit.1.zip

**Comment by d10sfan** [comment]
Added in https://github.com/luxtorpeda-dev/packages/pull/293

**Comment by rea987** [comment]
I notice "May need to create hl.exe file inside installed directory for Steam to launch game." information in the package list. Creating a dummy text file named `hl.exe` within `~/.local/share/Steam/steamapps/common/Half-Life` solves the launch issue. Can't this be included in the script?

**Comment by d10sfan** [comment]
No, because this issue happens before luxtorpeda is able to be launched. It's happening inside steam.
