### ISSUE TITLE
libpulsedsp.so location in OpenSUSE

### ISSUE THREAD

**Issue by rKsanu2MMYvypWePtQWM** [luxtorpeda-dev/packages#290]
Hello,
I tried running UT99 but I couldn't, since the script looks for libpulsedsp.so where it doesn't exist in OpenSUSE. The package which contains libpulsedsp.so (pulseaudio-utils-32bit) puts libpulsedsp.so into /usr/lib/pulseaudio (/usr/lib/pulseaudio/libpulsedsp.so). In fact, lib32 or i386 directories don't even exist in OpenSUSE.

Thanks!

**Comment by d10sfan** [comment]
I just pushed a change that should look for pulseaudio in that path as well: https://github.com/luxtorpeda-dev/packages/pull/291

You should see it the next time you try to launch the game. Can you see if that works? Update in the ticket if that works or not.

If it does not work, also please attach a log of steam running and attempting to launch the game.

**Comment by rKsanu2MMYvypWePtQWM** [comment]
The pulseaudio error was fixed, though now I'm getting `steamapps/common/Unreal Tournament/linuxdata-469b/ut: line 68: cd: too many arguments`. It's definitely because of the space in between Unreal Tournament. 
However, the game won't start anyways since iconv cannot be initialized. I tried after installing all iconv packages in OpenSUSE to no avail.

For the log to work I just hardcoded the directory into the line 68 so it would get closer to starting. I hope this is still within your realm and not some kind of misconfiguration. However, I did run the linux version a month or two ago by manually adding Linux binaries and it worked fine (I don't remember if the music played though)

[log.txt](https://github.com/luxtorpeda-dev/packages/files/6133216/log.txt)

**Comment by d10sfan** [comment]
The cd too many arguments is normal, at least I'm always getting that as well.

For the iconv error, you're getting that after installing it?

**Comment by rKsanu2MMYvypWePtQWM** [comment]
> The cd too many arguments is normal, at least I'm always getting that as well.
> 
> For the iconv error, you're getting that after installing it?

Yes, the error didn't change after I installed iconv packages. I see that the iconv.so is a php7 extension inside /usr/lib64/php7/extensions/, is that correct? Maybe this is completely different iconv than the game wants, or it's the same issue with different than standard location.

**Comment by d10sfan** [comment]
Not sure if that's the right one, so that may be your issue. That sounds like a library issue of some sort on your system.

What version are you attempting to run?

**Comment by rKsanu2MMYvypWePtQWM** [comment]
469b or 496b, can't remember which way the digits go

**Comment by d10sfan** [comment]
Ok, not sure on this one. It's probably a dependency issue with your system, but I don't know much about opensuse. If you do find a solution, please comment it here so I can add it to the notes for the future.

**Comment by rKsanu2MMYvypWePtQWM** [comment]
https://github.com/OldUnreal/UnrealTournamentPatches/issues/159
this helped me with iconv. I hope this helps for others with the same issue. Though I don't understand why it didn't work without localization files instead of just the devel-32bit package...
