### ISSUE TITLE
ECWolf cfg file data path stuck on first game used.

### ISSUE THREAD

**Issue by aukondk** [luxtorpeda-dev/packages#298]
**Describe the bug**
When playing more than one game with ECWolf, the first game launched will generate ecwolf.cfg with the path to its data directory. If you run another game from steam it will not change the path and will run with the first game's data files.

**To Reproduce**
Steps to reproduce the behaviour:
1. Launch a game (eg Wolf3d) with luxtorpeda-dev and exit.
2. Launch another ECWolf game (eg Spear of Destiny).
3. ECWolf will run Wolf3d.
4. Delete .config/ecwolf/ecwolf.cfg
5. Launch the second game again.
6. Second game will launch correctly.

**Expected behaviour**
ECWolf should run with data corresponding to the game launched.

**Additional context**
If you specify a config file with "--config wolf3d.cfg" for example, it will create that file and not make an ecwolf.cfg in the home config. That might be a good start.

**Comment by d10sfan** [comment]
Note: when checking this, check into bstone

**Comment by d10sfan** [comment]
https://github.com/luxtorpeda-dev/packages/commit/9e0d50c5b1860cbb0249359e5285cc6ddd929fc0 should fix this.
The next launch you should see this change.
