### ISSUE TITLE
Spear of Destiny mission pack selection

### ISSUE THREAD

**Issue by aukondk** [luxtorpeda-dev/packages#299]
**Describe the bug**
ECWolf currently launches the first extra mission pack by default rather than original missions

**To Reproduce**
Steps to reproduce the behaviour:
1. Launch SoD with luxtorpeda-dev
2. Steam asks which mission pack to load.
3. Select original
2. Data for first extra mission pack is loaded

**Expected behaviour**
Data for original game missions should be loaded.

**Screenshots**
![image](https://user-images.githubusercontent.com/2167753/111072115-70319780-84d9-11eb-8448-44d3dd5096d7.png)

**Additional context**
ECWolf will ask which pack to use if run from command line.

Running "ecwolf --data SOD" will load files with SOD extension. SOD for original, SD2 and SD3 for each mission pack.

The Steam launch dialog (pictured above) links to DOS executables which copy the data files with extensions SD1, SD2 or SD3 to .SOD before running the game as that is the only way the DOS executable can run extra levels. 

ECWolf can't run the SD1 files so if someone has already used the DOS version to run the mission packs then SD1 needs to be copied back to the SOD extension.

**Comment by d10sfan** [comment]
@aukondk Can you send me a steam log of attempting to launch each of these launch options?  This will help me determine what arguments  can be used to load the correct game.

**Comment by aukondk** [comment]
> @aukondk Can you send me a steam log of attempting to launch each of these launch options? This will help me determine what arguments can be used to load the correct game.

I recorded both with proton and with luxtorpeda. Probably more than you need now I think about it.
[sod error.log](https://github.com/luxtorpeda-dev/packages/files/6140993/sod.error.log)

**Comment by d10sfan** [comment]
@aukondk For those, did you try letting it start the game after selecting? I don't see the ecwolf being launched part. 

Also, you don't need to do proton, only the luxtorpeda launching.

**Comment by aukondk** [comment]
Sorry, that was the error.log.
This is the output when running Steam from the command line.
[sodlog.txt](https://github.com/luxtorpeda-dev/packages/files/6141690/sodlog.txt)

**Comment by d10sfan** [comment]
Ok, I pushed up a change: https://github.com/luxtorpeda-dev/packages/commit/f184d00d53b50369e3290cbd90ef0e1810c05b08

You should see it next time you launch the game. Let me know if it works, as I do not have own this game currently.

If it does not work, please provide the log like you just did which will help determine where the issue is.

**Comment by aukondk** [comment]
@d10sfan Seems to be working now. Thanks!
