### ISSUE TITLE
Prey (2006)

### ISSUE THREAD

**Issue by d10sfan** [luxtorpeda-dev/packages#3]
* Project link: N/A
* Project license: Proprietary
* Does it work on 64-bit only Linux: NO
* Is source code available?: NO
* Is source code stored in Git?: NO
* List of Steam AppIds of supported games:
    - https://steamcommunity.com/app/3970

## Additional information

This adds Prey 2006 (using the official binaries): https://gitlab.com/d10sfan/luxtorpeda-prey2006. SDLCL is used for this one as well.

There's a problem, possibly due to this game being 32 bit, where it will load fine through the command line but through luxtorpeda it'll freeze on the loading screen. I created another compatibility tool, just a simple shell script that went to the proper directory of the game and execute the run shell script, and that worked fine, so it seems to be something related to the luxtorpeda integration.

Something strange related to the CD Key was in steam the cd key seemed to have the last two numbers chopped off. I was able to get it from the original key, but something to look out for.

Also, this was a nice guide to get the game to work nicely with my ultrawide screen: https://steamcommunity.com/sharedfiles/filedetails/?id=1275016430

```
"3970": {
        "game_name": "Prey 2006",
        "download": [
            {
                "name": "Prey",
                "url":  "https://d10sfan.gitlab.io/luxtorpeda-prey2006/",
                "file": "prey2006-3970.tar.xz"
            }
        ],
        "command": "./run-prey.sh"
    }
```

```
| [Prey (2006)](https://steamcommunity.com/app/3970)          | [Original Port](https://icculus.org/prey/)                            |                     | CD Key from Steam might be truncated. Configuration updates that may be helpful: https://steamcommunity.com/sharedfiles/filedetails/?id=1275016430
```

**Comment by d10sfan** [comment]
CD Key is in base/preykey

**Comment by d10sfan** [comment]
Added with version 14

**Comment by rea987** [comment]
As of 30th Jan 2021, Prey (2006) fails to launch via luxtorpeda-dev on Mint 19.3.

Game installation + package installation + 1st launch attempt:
https://gist.github.com/rea987/888b44bde0289a7cf23abfe0a0065fc4

2nd launch attempt:
https://gist.github.com/rea987/54bc461a2b1c1a9406b59086e2014560

Usual retail Linux installation of Prey can be launched in the same system even with SDLCL. Removing existing `~/.prey` doesn't have an effect.

**Comment by d10sfan** [comment]
Can you create a new ticket for this? That'll make it easier to track
