### ISSUE TITLE
OpenHexagon

### ISSUE THREAD

**Issue by JoshuaFern** [luxtorpeda-dev/packages#304]
* Project link: https://github.com/SuperV1234/SSVOpenHexagon
* Project license: AFL v3
* Does it work on 64-bit only Linux: Yes
* Is source code available?: Yes
* Is source code stored in Git?: Yes
* List of Steam AppIds of supported games:
    - https://steamdb.info/app/1358090/

## Additional information

Steam doesn't have the native Linux version yet.

**Comment by d10sfan** [comment]
Added in https://github.com/luxtorpeda-dev/packages/pull/305

**Comment by JoshuaFern** [comment]
Thanks, it's working great here.
