### ISSUE TITLE
Blake Stone games

### ISSUE THREAD

**Issue by rea987** [luxtorpeda-dev/packages#307]
* Project link: *https://github.com/bibendovsky/bstone#bstone*
* Project license: *GPLv2*
* Does it work on 64-bit only Linux: *YES*
* Is source code available?: *YES*
* Is source code stored in Git?: *YES*

https://github.com/bibendovsky/bstone

* List of Steam AppIds of supported games:
    - https://steamdb.info/app/358190/
    - https://steamdb.info/app/358310/

## Additional information

I noticed that only [The Apogee Throwback Pack](https://store.steampowered.com/app/238050/The_Apogee_Throwback_Pack/) release of BS was listed in the packages list, therefore I wanted to point standalone releases on Steam.

**Comment by d10sfan** [comment]
Those are both listed and supported: https://luxtorpeda-dev.github.io/packages.html
