### ISSUE TITLE
The Binding of Isaac + Wrath of the Lamb DLC

### ISSUE THREAD

**Issue by rea987** [luxtorpeda-dev/packages#322]
* Project link: *https://edmundmcmillen.tumblr.com/*
* Project license: *Unknown*
* Does it work on 64-bit only Linux: *YES*
* Is source code available?: *NO*
* Is source code stored in Git?: *NO*
* List of Steam AppIds of supported games:
    - https://steamdb.info/app/113200/

## Additional information

Flash game, Linux builds and .swf is still available on Humble Store. As Linux builds are bundled with outdated Flash, I suggest shipping it with latest 64 bit standalone Flash Player. Users can be asked to provide HB's swf.zip. I also tried it with flash alternative Ruffle; it worked but some functions are missing and graphical fidelity is lacking.

The Binding of Isaac + Wrath of the Lamb DLC:
https://www.humblebundle.com/store/the-binding-of-isaac-wrath-of-the-lamb-dlc

Flash Player Projector (64-bit):
https://fpdownload.macromedia.com/pub/flashplayer/updaters/32/flash_player_sa_linux.x86_64.tar.gz
https://www.adobe.com/support/flashplayer/debug_downloads.html

Command:
`./flashplayer the_binding_of_isaac_wrath_of_the_lamb-linux-1.48-1355426233.swf`

**Comment by d10sfan** [comment]
If you could create one ticket for these missing steam binaries type games, that would help. One for each game would get unsustainable.
