### ISSUE TITLE
Botanicula

### ISSUE THREAD

**Issue by rea987** [luxtorpeda-dev/packages#323]
* Project link: *https://amanita-design.net/games/botanicula.html*
* Project license: *Unknown*
* Does it work on 64-bit only Linux: *YES*
* Is source code available?: *NO*
* Is source code stored in Git?: *NO*
* List of Steam AppIds of supported games:
    - https://steamdb.info/app/207690/

## Additional information

Linux builds are still available on Humble Store, GOG and itch.io. Users can be asked to provide HB's tar.gz, GOG's .sh or itch.io's .zip release.

https://www.humblebundle.com/store/botanicula-collectors-edition
https://www.gog.com/game/botanicula
https://amanitadesign.itch.io/botanicula

**Comment by d10sfan** [comment]
If you could create one ticket for these missing steam binaries type games, that would help. One for each game would get unsustainable.
