### ISSUE TITLE
Humble Bundle / Store / Widget games

### ISSUE THREAD

**Issue by rea987** [luxtorpeda-dev/packages#324]
Steam Games Missing Linux Ports:
https://www.gamingonlinux.com/wiki/Steam_Games_Missing_Linux_Ports

## The Binding of Isaac + Wrath of the Lamb DLC

* Project link: *https://edmundmcmillen.tumblr.com/*
* Project license: *Unknown*
* Does it work on 64-bit only Linux: *YES*
* Is source code available?: *YES*
* Is source code stored in Git?: *YES*
* List of Steam AppIds of supported games:
    - https://steamdb.info/app/113200/

### Additional information

Flash game, Linux builds and .swf is still available on Humble Store. As Linux builds are bundled with outdated Flash, I suggest shipping it with latest 64 bit standalone Flash Player. Users can be asked to provide HB's swf.zip. I also tried it with flash alternative Ruffle; it worked but some functions are missing and graphical fidelity is lacking.

The Binding of Isaac + Wrath of the Lamb DLC:
https://www.humblebundle.com/store/the-binding-of-isaac-wrath-of-the-lamb-dlc

Flash Player Projector (64-bit):
https://fpdownload.macromedia.com/pub/flashplayer/updaters/32/flash_player_sa_linux.x86_64.tar.gz
https://www.adobe.com/support/flashplayer/debug_downloads.html

Command:
`./flashplayer the_binding_of_isaac_wrath_of_the_lamb-linux-1.48-1355426233.swf`

## Botanicula

* Project link: *https://amanita-design.net/games/botanicula.html*
* Project license: *Unknown*
* Does it work on 64-bit only Linux: *YES*
* Is source code available?: *NO*
* Is source code stored in Git?: *NO*
* List of Steam AppIds of supported games:
    - https://steamdb.info/app/207690/

### Additional information

Linux builds are still available on Humble Store. Users can be asked to provide HB's tar.gz release.

https://www.humblebundle.com/store/botanicula-collectors-edition

## Draw a Stickman: EPIC

* Project link: *https://drawastickman.com/epic1*
* Project license: *Unknown*
* Does it work on 64-bit only Linux: *MAYBE*
* Is source code available?: *NO*
* Is source code stored in Git?: *NO*
* List of Steam AppIds of supported games:
    - https://steamdb.info/app/248650/

### Additional information

Linux builds are still available on Humble Store. Users can be asked to provide HB's release.

https://www.humblebundle.com/store/draw-a-stickman-epic

## Fractal

* Project link: *https://cipherprime.com/games/fractal/*
* Project license: *Unknown*
* Does it work on 64-bit only Linux: *MAYBE*
* Is source code available?: *NO*
* Is source code stored in Git?: *NO*
* List of Steam AppIds of supported games:
    - https://steamdb.info/app/61310/

### Additional information

Linux builds are still available on Humble Store. Users can be asked to provide HB's release.

https://www.humblebundle.com/store/fractal

## McPixel

* Project link: *http://mcpixel.net/*
* Project license: *Unknown*
* Does it work on 64-bit only Linux: *MAYBE*
* Is source code available?: *NO*
* Is source code stored in Git?: *NO*
* List of Steam AppIds of supported games:
    - https://steamdb.info/app/220860/

### Additional information

Linux builds are still available on Humble Store. Users can be asked to provide HB's release. Likely to be a Flash or Air game.

https://www.humblebundle.com/store/mcpixel

## Paper Sorcerer

* Project link: *http://www.ultrarunaway.com/paper-sorcerer.html*
* Project license: *Unknown*
* Does it work on 64-bit only Linux: *MAYBE*
* Is source code available?: *NO*
* Is source code stored in Git?: *NO*
* List of Steam AppIds of supported games:
    - https://steamdb.info/app/263560/

### Additional information

Linux builds are still available on Humble Store. Users can be asked to provide HB's release.

https://www.humblebundle.com/store/paper-sorcerer

## Potatoman Seeks the Troof

* Project link: *http://www.pixeljam.com/potatoman/*
* Project license: *Unknown*
* Does it work on 64-bit only Linux: *MAYBE*
* Is source code available?: *NO*
* Is source code stored in Git?: *NO*
* List of Steam AppIds of supported games:
    - https://steamdb.info/app/328500/

### Additional information

Linux builds are still available on Humble Store. Users can be asked to provide HB's release. Likely to be a Flash or Air game.

https://www.humblebundle.com/store/potatoman-seeks-the-troof

## Regency Solitaire

* Project link: *http://www.greyaliengames.com/regencysolitaire/index.php*
* Project license: *Unknown*
* Does it work on 64-bit only Linux: *MAYBE*
* Is source code available?: *NO*
* Is source code stored in Git?: *NO*
* List of Steam AppIds of supported games:
    - https://steamdb.info/app/351090/

## Additional information

Linux builds are still available on Humble Store. Users can be asked to provide HB's release.

https://www.humblebundle.com/store/regency-solitaire

## Scoregasm

* Project link: *http://charliesgames.com/Scoregasm/*
* Project license: *Unknown*
* Does it work on 64-bit only Linux: *MAYBE*
* Is source code available?: *NO*
* Is source code stored in Git?: *NO*
* List of Steam AppIds of supported games:
    - https://steamdb.info/app/202410/

### Additional information

Linux builds are still available on Humble Store. Users can be asked to provide HB's release.

https://www.humblebundle.com/store/scoregasm

## Shadowgrounds & Shadowgrounds Survivor

* Project link: *https://www.shadowgroundsgame.com/*
* Project license: *SHADOWGROUNDS & SHADOWGROUNDS SURVIVOR SOURCE CODE LICENSE*

https://github.com/vayerx/shadowgrounds/blob/linux/LICENSE.txt

* Does it work on 64-bit only Linux: *MAYBE*
* Is source code available?: *YES*
* Is source code stored in Git?: *YES*

https://github.com/vayerx/shadowgrounds

* List of Steam AppIds of supported games:
    - https://steamdb.info/app/2500/
    - https://steamdb.info/app/11200/

### Additional information

Linux builds are still available on Humble Store. Users can be asked to provide HB's .bin release.

https://www.humblebundle.com/store/shadowgrounds
https://www.humblebundle.com/store/shadowgrounds-survivor

HB's .bin releases require libglade2-0:i386 to be installed. However, I am unable to run either of `shadowgrounds-bin` and `shadowgrounds-launcher` due to zlib dependency error. If source code can be compiled, user wouldn't need to provide HB builds. Following is the build instructions of the source code;

https://github.com/vayerx/shadowgrounds/wiki/Build

There is also a fork claiming to be the SDL2 port of the games;

https://github.com/Chaduke/shadowgrounds-SDL2

## Vessel

* Project link: *https://store.steampowered.com/app/108500/Vessel/*
* Project license: *Unknown*
* Does it work on 64-bit only Linux: *NO*
* Is source code available?: *NO*
* Is source code stored in Git?: *NO*
* List of Steam AppIds of supported games:
    - https://steamdb.info/app/108500/

## Additional information

Linux builds are still available on Humble Store. Users can be asked to provide HB's bin release.

https://www.humblebundle.com/store/vessel

**Comment by d10sfan** [comment]
Closing in favor of the user-packages support (https://github.com/luxtorpeda-dev/luxtorpeda/issues/65), which allows users to use luxtorpeda as a override launcher for steam games, which could be used to tell steam to launch the humble bundle games instead.
