### ISSUE TITLE
Half-Life: Before two additional entries

### ISSUE THREAD

**Issue by Kern3l-Panic** [luxtorpeda-dev/packages#325]
**Describe the bug**
I have three entries for one game. Half-Life: Before, Before and Spirit of Half-Life. Only Half-Life: Before should exist in my library.

**To Reproduce**
Steps to reproduce the behaviour:
1. Install Half-Life: Before
2. Scroll through Steam Library and see the unnecessary two additional entries being Before and Spirit of Half-Life

**Expected behaviour**
I expect there to only be one entry, not three

**Additional context**
To fix this, I just changed `Half-Life/before/liblist.gam` and `Half-Life/Spirit/liblist.gam` both to `liblist.gam.bak`. Now Half-Life: Before is the only entry that shows up instead of all three. I tested the game and it still works as it did before the fix.

**Comment by d10sfan** [comment]
Ok, this change should do that: https://github.com/luxtorpeda-dev/packages/commit/5f7430e8482b5b74b0084340fcc57be0e5e6f554

You'll need to re-install the game to see this and delete the ready file. Let me know if this works for you.

**Comment by Kern3l-Panic** [comment]
I reinstalled the game and this fix removes the additional entry of Spirit of Half-Life but not Before. I checked the directory, `Half-Life/before` and liblist.gam exists instead of liblist.gam.bak.

**Comment by d10sfan** [comment]
This should take care of that as well: https://github.com/luxtorpeda-dev/packages/commit/14987929925f96c2a3f8c157f06cc7e786b193da

See if that works for you.
