### ISSUE TITLE
Koi Farm

### ISSUE THREAD

**Issue by NerosTie** [luxtorpeda-dev/packages#328]
* Project link: https://github.com/jobtalle/Koi
* Project license: https://github.com/jobtalle/Koi/blob/master/LICENSE.md
* Does it work on 64-bit only Linux: YES
* Is source code available?: YES
* Is source code stored in Git?: YES
* List of Steam AppIds of supported games:
https://store.steampowered.com/app/1518810/Koi_Farm/

## Additional information

https://www.gamingonlinux.com/2021/04/koi-farm-the-relaxing-koi-breeding-game-releases-the-source-code

**Comment by JoshuaFern** [comment]
This is a web game, doesn't that mean Lux would have to package an entire browser? That's a lot to compile.

There's several Windows-only web games on Steam that are bundled with CEF, many of which don't work well with Proton. Is it feasible to simply include a Linux CEF and have it working?

**Comment by d10sfan** [comment]
It's electron based so its the browser and the node portion which can control the behavior of the game if they added pieces there. 

CEF by itself maybe not, since it may use electron's controls for different behavior, such as saves, handling the window, etc.

**Comment by d10sfan** [comment]
Added in https://github.com/luxtorpeda-dev/packages/pull/390
