### ISSUE TITLE
Resistance Element map crash

### ISSUE THREAD

**Issue by rea987** [luxtorpeda-dev/packages#329]
**Resistance Element crashes in re05 map**
In re05 map, when the player enters hotel area, killing or getting near to the single barnacle at the entrance crashes the game with following error:

`apartment_baddie3 - npc_fastzombie_torso: UTIL_SetModel: not precached: models/zombie/fast_torso.mdl`

**To Reproduce**
Steps to reproduce the behaviour:
1. Launch the game
2. Load re05 map via in-game console: `map re05`
3. Get outside of the building, after dealing with 3 barnacles and bunch of zombies, follow alley, then turn right.
4. Enter hotel area that has a single barnacle at the entrance.
5. Kill or try to get pass the barnacle.

**Expected behaviour**
The game to not crash when killing or getting pass the barnacle.

https://youtu.be/XWMy-9id9X0?t=1631

**Screenshots**
![resim](https://user-images.githubusercontent.com/1547646/114160652-d28e8400-992f-11eb-8c0e-61555838f1f7.png)

**Additional context**

1. Barnacles in general may not be the issue since killing 3 other barnacles in earlier stages of the map doesn't crash the map.
2. The turret nearby 3 aforementioned barnacles works but has no affect on enemies.
3. Brief Google search of the error returns following;

https://www.google.com/search?q=npc_fastzombie_torso%3A+UTIL_SetModel%3A+not+precached%3A+models%2Fzombie%2Ffast_torso.mdl

It looks like model precached is likely a model issue of Source 1 engine;

https://steamcommunity.com/sharedfiles/filedetails/?id=212352894

It may or may not be solved by targetting correct model directory but that exceeds my Source engine knowledge unfortunately.

4. `resistanceelement.fgd` in the game directory features `\` symbol in the directory addresses which might not be compatible with Linux.

**Comment by d10sfan** [comment]
This change should fix it: https://github.com/luxtorpeda-dev/packages/commit/0c945424692cffb88799da8594946fa30f2b6f4b

Looks like this game needed the episodic libraries, instead of the source sdk 2013 ones. On the next launch it'll ask for the half life installation path.

**Comment by rea987** [comment]
Resistance Element doesn't launch on Mint 19.3 and Ubuntu 20.04 after the last update.

https://gist.github.com/rea987/468df48e54af3f99766e05bc54e5c7d4

- Clean game installation
- HL2, HL2:E1, HL2:E2, Source 2013 SDK Base SP (upcoming) installed and selected
- Clean ~/.cache/luxtorpeda directory

**Comment by d10sfan** [comment]
@rea987 Thanks for reporting this, that looked to be a unrelated issue due to steam cloud saves renaming the folder.

I've put in a workaround here: https://github.com/luxtorpeda-dev/packages/commit/c4f5a5086d2322c72e3ec4efe6ed0343f0f3b9f5

So now it'll handle either folder case.
