### ISSUE TITLE
Upgrade to openxcom extended v7

### ISSUE THREAD

**Issue by ScrambleTheRamble** [luxtorpeda-dev/packages#330]
**Is your feature request related to a problem? Please describe.**
More recent game mods require a newer version of OpenXcom Extended than the current 6.5.7 version. Please update the version used by Luxtorpeda to v7.

**Comment by d10sfan** [comment]
For future reference, package related items should go in this repository.

It does not look like the developers have tagged a version for the release, but I can update to the latest commit in their branch. I'll work on that when I have a chance.

**Comment by d10sfan** [comment]
Closing with https://github.com/luxtorpeda-dev/packages/pull/331

Once that pull request is merged (after I test it), the update will the available.

Thanks for the heads up on the new version.
