### ISSUE TITLE
Raze for Duke Nukem 3D: 20th Anniversary World Tour

### ISSUE THREAD

**Issue by rea987** [luxtorpeda-dev/packages#334]
* Project link: *https://github.com/coelckers/Raze*
* Project license: *BUILD SOURCE CODE LICENSE & GPLv2*

https://github.com/coelckers/Raze/blob/master/build-doc/buildlic.txt

* Does it work on 64-bit only Linux: *YES*
* Is source code available?: *YES*
* Is source code stored in Git?: *YES*
* List of Steam AppIds of supported games:
    - https://steamdb.info/app/434050/

## Additional information

Putting Luxtorpeda's exiting Raze build in DN3D:WT directory and running with `LD_LIBRARY_PATH=<...>/dist/lib make Raze recognize and run 20th Anniversary World Tour edition.

![resim](https://user-images.githubusercontent.com/1547646/114407145-c82eed00-9bb0-11eb-94c7-144abc29708b.png)

**Comment by d10sfan** [comment]
Does the run-raze.sh script work with this game?

**Comment by rea987** [comment]
> Does the run-raze.sh script work with this game? The one that is included in the raze distribution. This would not require doing LD_LIBRARY_PATH as it already handles that.

You're right, simply launching `run-raze.sh` script runs the game without a problem.

**Comment by d10sfan** [comment]
Ok, this commit should take care of this.
