### ISSUE TITLE
Shadowgrounds & Shadowgrounds Survivor

### ISSUE THREAD

**Issue by rea987** [luxtorpeda-dev/packages#335]
* Project link: *https://www.shadowgroundsgame.com/*
* Project license: *SHADOWGROUNDS & SHADOWGROUNDS SURVIVOR SOURCE CODE LICENSE*

https://github.com/vayerx/shadowgrounds/blob/linux/LICENSE.txt

* Does it work on 64-bit only Linux: *MAYBE*
* Is source code available?: *YES*
* Is source code stored in Git?: *YES*

https://github.com/vayerx/shadowgrounds

* List of Steam AppIds of supported games:
    - https://steamdb.info/app/2500/
    - https://steamdb.info/app/11200/

## Additional information

Following is the build instructions of the source code;

https://github.com/vayerx/shadowgrounds/wiki/Build

There is also a fork claiming to be the SDL2 port of the games;

https://github.com/Chaduke/shadowgrounds-SDL2

**Comment by d10sfan** [comment]
I've already tried this port, it does not work with Steam assets from what I can tell. If anyone is able to fix that, I will look into this.

**Comment by rea987** [comment]
> I've already tried this port, it does not work with Steam assets from what I can tell.

Same applies for SDL2 port I presume?

**Comment by d10sfan** [comment]
> > I've already tried this port, it does not work with Steam assets from what I can tell.
> 
> Same applies for SDL2 port I presume?
> 
> Some HB ports contain OpenGL specific assets for Linux and Mac builds; such as the original Torchlight. Perhaps existing Mac version on Steam might be compatible with the source port? Have you kept previously build source port, so I can test with Mac version assets?

Yes, from my understanding the underlying game didn't change for the sdl2 port, just the windowing part.

And no I don't have it. You can try building it and seeing if it works for you.
