### ISSUE TITLE
XCom & TFD - Add cross links to OpenXcom Extended 

### ISSUE THREAD

**Issue by ScrambleTheRamble** [luxtorpeda-dev/packages#336]
Some mods require datafiles from both XCom & TFD to be present, a quick solution to that would be to add soft links to XCom & TFTD in "openxcom-oxce".

**Comment by d10sfan** [comment]
As mentioned before, package questions or requests need to go into the packages repository, not this one. 

For this what names do the links need to have for oxce to see it and what files are you referring to?

**Comment by ScrambleTheRamble** [comment]
Please disregard, I misread some requirements. Also, sorry for using the wrong repository.
