### ISSUE TITLE
Doom 3 BFG soft shadows > white textures

### ISSUE THREAD

**Issue by dubigrasu** [luxtorpeda-dev/packages#339]
Tried recently Doom 3 BFG. and when soft shadows are enabled, the majority of the textures becomes white, similar (if not identical) with what is described here:
https://github.com/RobertBeckebans/RBDOOM-3-BFG/pull/486

I compiled the engine form the latest source and the issue seems to be gone.

**Comment by d10sfan** [comment]
Done in this pull request: https://github.com/luxtorpeda-dev/packages/pull/340

I normally watch for any new tagged releases, which it looks like hasn't happened in a while for this game. So thanks for the heads up, I've updated to the latest from the master branch.
