### ISSUE TITLE
Menu not visible in Portal Reloaded

### ISSUE THREAD

**Issue by D3SOX** [luxtorpeda-dev/packages#343]
**Describe the bug**
I can't see the menu in Portal Reloaded using Luxtorpeda

**To Reproduce**
Steps to reproduce the behaviour:
1. Start Portal Reloaded using Luxtorpeda
2. See menu

**Expected behaviour**
Menu should be visible

**Screenshots**
![Main Menu](https://user-images.githubusercontent.com/24937357/116392928-56e27180-a821-11eb-8dac-d072bc82b824.png)

**Additional context**
Using Arch Linux. I have an AMD GPU and I tried it with both the proprietary and open source drivers
- using open source drivers
   - Steam System Information: https://gist.github.com/D3SOX/3a18bcc5f959b5985d147908cb02e897
   - Steam terminal output: https://gist.github.com/D3SOX/b610f9ab0c1ff4bdb8c9d12b471d87a6
- using proprietary drivers (starting Steam via `progl steam`)
   -  Steam System Information: https://gist.github.com/D3SOX/d3c4a93540ce2c63aebb037831f7742f
   - Steam terminal output: https://gist.github.com/D3SOX/3405d464a6494530de31ff8460dc9fed
- I tried it with both [v25](https://github.com/luxtorpeda-dev/luxtorpeda/releases/tag/v25) and a self-compiled version from master at https://github.com/luxtorpeda-dev/luxtorpeda/commit/c57fa72af669457b9cb4232a29c63ee8c65035e3
- Not sure if that matters but Portal 2 and Portal Reloaded are on different Steam libraries (that are on different hard drivers)
- Using Proton I saw the menu

**Comment by d10sfan** [comment]
This works fine for me on nvidia, so possibly something specific to AMD.

Is Portal 2 downloaded with the native version? Does Portal 2 work and show the menu?

Are you using wayland or x11?

**Comment by D3SOX** [comment]
> Is Portal 2 downloaded with the native version? Does Portal 2 work and show the menu?

Yes, regular Portal 2 shows the menus. I think Portal Reloaded uses some type of custom menu. I also noticed this while playing it in Proton.

> Are you using wayland or x11?

KDE Plasma on X11

**Comment by d10sfan** [comment]
@D3SOX Can you delete the portalready.txt file in the portal reloaded folder and then run again and send the logs? This would help determine that the right files are being copied.

**Comment by D3SOX** [comment]
Do you mean the `portalpath.txt`?

**Comment by d10sfan** [comment]
Yes, that's correct.

**Comment by D3SOX** [comment]
Here's the log: https://gist.github.com/D3SOX/5ab587bd818066754da613d6fec8447e
I don't think it makes a difference if I'm using the open source or proprietary drivers for this case so I've used regular AMDGPU for this

**Comment by d10sfan** [comment]
Do you have any launch arguments for the game in steam? If so, what are they?

Also, you may want to try forcing a width and height in the launch options (%command% and then the source engine settings from there), it's possible the resolution isn't right for your desktop.

**Comment by D3SOX** [comment]
I did enable `-vulkan` for Portal 2, does this affect Portal Reloaded running via Luxtorpeda in any way?
![image](https://user-images.githubusercontent.com/24937357/116413811-3c67c280-a838-11eb-85ba-689d75bdc284.png)
In Portal Reloaded I only changed it to run with Luxtorpeda
![image](https://user-images.githubusercontent.com/24937357/116414379-b4ce8380-a838-11eb-9ad2-1668a750e386.png)

What are those launch options to run it with a fixed width/height? I have two 1920x1080 monitors

**Comment by d10sfan** [comment]
@D3SOX https://developer.valvesoftware.com/wiki/Command_Line_Options (-width and -height)

**Comment by D3SOX** [comment]
I tried it with `-w 1920 -h 1080 -window -refresh 144` but it's still the same problem

**Comment by d10sfan** [comment]
Have you tried disabling/unplugging your second monitor and seeing if it shows up?

**Comment by d10sfan** [comment]
Are you still encountering this issue?

**Comment by zaggynl** [comment]
I can reproduce this issue, have one monitor, AMD 5700XT.
Rest of the game seems to work as intended, just have to blind navigate the menu.
Followed this guide to start the mod: https://steamcommunity.com/sharedfiles/filedetails/?id=2463220837

**Comment by d10sfan** [comment]
@zaggynl By this, you mean you didn't use luxtorpeda and used that guide instead? The luxtorpeda method is based on that guide or a similar one.

You may want to try loading the game with the console enabled (I believe that's -console) and see if there's any errors.

**Comment by rea987** [comment]
@D3SOX @d10sfan @zaggynl

https://store.steampowered.com/news/app/1255980/view/3081002160253179742

> - Added preliminary macOS and Linux support

**Comment by d10sfan** [comment]
@rea987 Thanks for the heads-up. I just tried it and it worked great. You may need to uninstall the game completely as the first time I tried the time portals did not work.

https://github.com/luxtorpeda-dev/packages/commit/1bbbecfa6769dba3f88a36e62140210b90503304

**Comment by D3SOX** [comment]
Thanks for the information, I can confirm that it works with the native version!
