### ISSUE TITLE
Dynamic library build repo

### ISSUE THREAD

**Issue by d10sfan** [luxtorpeda-dev/packages#344]
* libraries folder in packages repo with folders for each build env (steam-runtime, ubuntu-1804, 32-bit, etc)
* new workflows for libraries folders with its own metadata/libraries.json to keep track of possible libraries
* chained deps would request the built library (if standalone) in env, then those deps would be provided in the final artifact
* engines would have in env request to use these packages, nodejs workflow would be created to look those up and provide download array that the start_build script would use to put into "$pfx_libs" folder that would be included by engine build step
* workflow that updates the download area in packages.json would also update the downloads array with libraries, with library true for download so it knows to overwrite all of them. would also need a way to handle games with custom extraction areas, or multiple engines supported in one game. Either this or bundle all of the necessary libraries in the archive artifact like today

**Comment by Frenzied-Pop** [comment]
Did you not want to try appimage? I learned about it from the Diablo project
https://appimage.org/

**Comment by d10sfan** [comment]
@Frenzied-Pop This is more about how to get a docker image with all the right dependencies and then provide that. AppImage may help with some of that, and I am always on the lookout for when engines support them upstream.

**Comment by d10sfan** [comment]
Tracking in https://github.com/luxtorpeda-dev/packages/pull/313
