### ISSUE TITLE
Serious Sam 2 multiplayer menu doesn't function

### ISSUE THREAD

**Issue by rea987** [luxtorpeda-dev/packages#348]
**After recent updates, SS2's mp menu stopped functioning**

Online MP of SS2 on Linux is defunct as GameSpy's master servers are long gone. Steam version for Windows has received numerous updates that also fixed that issue by implementing a new master server. Retail out of dated Windows version can be patched to use master server but unofficial native Linux version cannot to my best knowledge. However, there is version parity (v2.070.00 : 65824) between retail Windows version, unofficial native Linux version as well as [old] branch on Steam; hence they can play multiplayer on LAN. However, after a recent update, when Luxtorpeda is activated with default branch on Steam, Linux native version of SS2's MP menu cannot be reached. If the game is switched to [old] branch MP menu can be reached.

**To Reproduce**
Steps to reproduce the behaviour:
1. Activate Luxtorpeda for SS2
2. Install and run the game as usual.
3. Attempt to click Multiplayer.

**Expected behaviour**
Multiplayer menu to open, Local Area and Internet.

**Additional context**
Can the script force the game to use [old] branch instead of default, or is that something outside of the tool itself, so the player has to do it manually? In that case, can that info be added to the comments section in the package list?

https://luxtorpeda-dev.github.io/packages.html

**Comment by d10sfan** [comment]
If you look at the script, there are files I'm deleting from the recent patches, it's possible one of them was missed. Can you try deleting other recent packages in the ss2 directory to see if that fixes it?

The luxtorpeda client does not have any knowledge of the steam updates if that's what you mean. So people could switch to a branch but it'd have to be done manually, so the files would be better if possible.

**Comment by rea987** [comment]
I will touch upon 2 points regarding Linux version of Serious Sam 2:

### Branch differences on Steam

By conduction more tests, I detected more differences between [default] and [old] branches of SS2. Without a doubt, [old] branch is the latest pre-Steam version of the game which is compatible with unofficial Linux version.

- Default branch added Patch_02_080_x files, InSamnity2 mod and changed content of `../Content/SeriousSam2/Menus` directory.

_Meld_ comparison of default and old branches:

![Ekran Görüntüsü 2021-05-03 20-54-16](https://user-images.githubusercontent.com/1547646/116919641-3c156000-ac5a-11eb-8c05-dd9d9a419ccd.png)
![Ekran Görüntüsü 2021-05-03 20-54-40](https://user-images.githubusercontent.com/1547646/116919655-40da1400-ac5a-11eb-9600-3e30a8a32cc6.png)
![Ekran Görüntüsü 2021-05-03 20-55-05](https://user-images.githubusercontent.com/1547646/116919684-49324f00-ac5a-11eb-9f6e-7bb42bd2f3d9.png)

- Removing `Patch_02_080_210639.gro` and `Patch_02_080_252822.gro` brings the Multiplayer menu back.
- Removing `Patch_02_080_243026.gro`, `Patch_02_080_243893.gro` and `Patch_02_080_244138.gro` brings Video Options menu back. Though, it's not extensive as it supposed to be. For wider resolutions and aspect ration, users still need to edit `../Serious Sam 2/Content/SeriousSam2/Sam2.ini`.

https://wiki.ubuntuusers.de/Archiv/Spiele/Serious_Sam_2/#Konfigurationsdatei

![Ekran Görüntüsü 2021-05-03 21-05-52](https://user-images.githubusercontent.com/1547646/116920040-d675a380-ac5a-11eb-80b9-65968f809e7b.png)

- I say it is safe to also remove `Patch_02_080_244697.gro` as it was also added in 31 May 2019 just like most other Patch_02_080_x files.

https://steamdb.info/depot/204341/history/

- My suggestion is to remove all Patch_02_080_x files and inform players to switch to [old] branch in the in the Comments section of package list as it features some Menu files which would be more compatible with Linux version.

https://luxtorpeda-dev.github.io/packages.html

### Potential custom master server fix

Retail version of SS2 and old branch on Steam can be patched for custom master servers. " GameSpy Master-Server Patcher by Louva-Deus" involves hex editing `OnlineGS.dll`. Unfortunately, I am unable to locate any .so equivalent of that library in `Linux-Dynamic-Release` of the Linux version. As far as understand, hex editing involves replacing `"2E 67 61 6D 65 73 70 79 2E 63 6F 6D 00"` values of `OnlineGS.dll` with `"2E 6F 73 74 61 70 2E 65 75 00 00 00 00"` in order to force a custom master server.

https://42amsterdam.net/samforum/downloads.php?do=file&id=325

I wonder if one of Linux libraries or files of the game feature such values to be replaced with given values to enable custom master server? Can that be done? Thank you!

**Comment by d10sfan** [comment]
@rea987 Is it feasible to make the game work without having to switch branches? As in delete the right patch files on the current one and make it work?

**Comment by rea987** [comment]
> @rea987 Is it feasible to make the game work without having to switch branches? As in delete the right patch files on the current one and make it work?

It does, removing all Patch_02_080_x files makes Multiplayer and Video Settings accessible. I don't know to what extend old Menu files affect the Linux version.

**Comment by d10sfan** [comment]
Ok, just pushed up that change to clear those patch files: https://github.com/luxtorpeda-dev/packages/commit/60d9c6c240d30d3642ffa48f8449bf4a5a05d479

**Comment by rea987** [comment]
Serious Sam 2 package seems to not have Steam Overlay enabled. Can this be enabled?

**Comment by d10sfan** [comment]
@rea987 The overlay works for me, you may have it disabled for that game in particular.
