### ISSUE TITLE
ArxLibertatis Bad Default Resolution

### ISSUE THREAD

**Issue by JoshuaFern** [luxtorpeda-dev/packages#35]
**Describe the bug**
When running ArxLibertatis, the default video mode sets the resolution very small, yet the desktop the same size which activates a "scrolling mode" where moving your mouse cursor around the edges of the screen scrolls the screen space. The game is not playable in this state. You then have to run an xrandr command to fix the desktop resolution (on i3 at least).

**To Reproduce**
Simply start the game for the first time with no existing config.

**Expected behaviour**
To avoid this I suggest running in windowed mode by default and allowing the user to set their resolution and activate fullscreen themselves.

**Screenshots**
https://steamcommunity.com/sharedfiles/filedetails/?id=2150172304

**Additional context**
On the i3 window manager either windowed mode or fullscreen at my native resolution works fine.
Luxtorpeda v6

**Comment by d10sfan** [comment]
Game now uses borderless fullscreen, with a patch in the engines files. Completed with https://github.com/luxtorpeda-dev/packages/pull/36
