### ISSUE TITLE
GTA III, Vice City

### ISSUE THREAD

**Issue by FearlessQuality** [luxtorpeda-dev/packages#351]
* Project link: https://github.com/td512/re3
* Project license: *e.g. GPLv3 or BSD or link if it's a custom license*
* Does it work on 64-bit only Linux: *YES/NO/MAYBE*
* Is source code available?: *YES*
* Is source code stored in Git?: *YES*
* List of Steam AppIds of supported games:
    - https://steamdb.info/app/12100
    - https://steamdb.info/app/12110
    - etc…

## Additional information

a fork of re3 on git has been restored, but not sure worth re-adding package to lux

**Comment by d10sfan** [comment]
Considering this got taken off github last time, I don't want to have this project get caught in the crossfire. So I won't be using that engine again.

**Comment by rea987** [comment]
Greetings @d10sfan,

It looks like the author of the fork challenged the DMCA and GitHub restored it.

https://www.gamingonlinux.com/2021/05/github-restores-a-fork-of-the-cross-platform-reverse-engineered-gta-iii-and-vice-city-code

In this case, would you reconsider readding the port to Luxtorpeda, please? Thank you!

**Comment by dubigrasu** [comment]
Let's hope that the engine will be found free of legal issues, though it may take some time for the situation to stabilize (one way or another).

**Comment by d10sfan** [comment]
I'd prefer to wait until it's known more if this is valid to use or not. I'll keep an eye on it.

**Comment by yasink21** [comment]
hello, is there way to get luxtorpeda to use this engine if I place the files into the directory manually by myself?

**Comment by d10sfan** [comment]
> hello, is there way to get luxtorpeda to use this engine if I place the files into the directory manually by myself?

Yes, you can see how this could work here: https://github.com/luxtorpeda-dev/luxtorpeda/issues/65#issuecomment-808634850

**Comment by rea987** [comment]
> hello, is there way to get luxtorpeda to use this engine if I place the files into the directory manually by myself?

PM me on Reddit.

**Comment by dubigrasu** [comment]
The original repo is back, good signs...I hope?
https://github.com/GTAmodding/re3

**Comment by rea987** [comment]
> The original repo is back, good signs...I hope?
> https://github.com/GTAmodding/re3

@d10sfan As the original repo has been cleared from DMCA strike, would you reconsider readding the port please? Thank you!

**Comment by d10sfan** [comment]
I've re-added them for now. If it gets taken down again, that'll be for the last time, but so far so good.
