### ISSUE TITLE
Sonic 3 A.I.R. for Sonic 3 & Knuckles

### ISSUE THREAD

**Issue by NerosTie** [luxtorpeda-dev/packages#352]
* Project link: https://sonic3air.org/
* Project license: "It is freeware and may not be sold." (from Manual PDF)
* Does it work on 64-bit only Linux: YES
* Is source code available?: NO
* Is source code stored in Git?: NO
* List of Steam AppIds of supported games:
~~https://store.steampowered.com/app/71162/Sonic_3__Knuckles/~~
https://store.steampowered.com/app/34270/SEGA_Mega_Drive_and_Genesis_Classics/

## Additional information

The game is compatible with the ROM on Steam.

> Before downloading, please make sure you have the Steam version of Sonic 3 & Knuckles  installed on your PC.

**Comment by d10sfan** [comment]
It looks like the only launch option is to the game hub, so there wouldn't be a straight forward way to make this work in luxtorpeda from what I can see, especially since it means downloading the Windows versions of all of the launchers instead of Linux.
