### ISSUE TITLE
Enemy Territory: Quake Wars Demo 2.0 and potentially full version

### ISSUE THREAD

**Issue by rea987** [luxtorpeda-dev/packages#353]
* Project link: *https://www.splashdamage.com/games/enemy-territory-quake-wars/*
* Project license: *Proprietary* https://store.steampowered.com/eula/eula_etqw
* Does it work on 64-bit only Linux: *NO*
* Is source code available?: *NO*
* Is source code stored in Git?: *NO*
* List of Steam AppIds of supported games:
    - https://steamdb.info/app/10050/
    - https://steamdb.info/app/10000/

## Additional information

ETQW full version has been delisted from Steam long time ago. Yet, "Demo 2.0" can still be obtained and installed via Steam.

https://steamcommunity.com/app/10000/discussions/0/143388511227759615/

As there exists a functional native demo version, can this be added to repos?

https://cdn.splashdamage.com/downloads/games/etqw/ETQW-demo2-client-full.r1.x86.run

Also, although it's not possible to purchase the full game on Steam any longer, can users be offered option to provide existing ETQW full version installation to play full version as demo version via Luxtorpeda? Thank you!

**Comment by d10sfan** [comment]
I'll probably only do this for the demo, but offer two options. One is launching the demo and the other would be putting the full game in a sub directory and launching it from there.

**Comment by d10sfan** [comment]
Implemented in https://github.com/luxtorpeda-dev/packages/commit/dfd2b9537ad7f1c82376f6014dd76ab195ae6a7a

User will be expected to provide demo and/or retail binaries. Demo run file cannot be automated, so you will have to follow the steps manually and copy it into the correct place.

**Comment by rea987** [comment]
Currently, **Enemy Territory: QUAKE Wars Demo** (`10010`) is supported. Can **Enemy Territory: QUAKE Wars Demo 2.0** (`10050`) which is the most recent demo version be supported?

https://steamdb.info/app/10050/

Also, can SDL2 support via SDLCL added? Thank you!

**Comment by d10sfan** [comment]
@rea987 Is there a version of this demo for Linux as well? Or is the .run file the correct one?

Have you been able to use sdlcl with etqw before?

**Comment by rea987** [comment]
> Is there a version of this demo for Linux as well?

- Enemy Territory: QUAKE Wars Demo (`10010`) is is outdated **v1.0**. Oldest Linux demo I could locate is v1.1 which I am unable to install:

http://dukeworld.com/idgames2/idstuff/etqw/old/ETQW-demo-client-1.1-full.r5.x86.run
http://dukeworld.com/idgames2/idstuff/etqw/old/

- Enemy Territory: QUAKE Wars Demo 2.0 (`10050`) is the most recent demo release which is **v1.4**. Most recent Windows and Linux demos have version parity.

https://cdn.splashdamage.com/downloads/games/etqw/ETQW-demo2-client-full.r1.x86.run
http://dukeworld.com/idgames2/idstuff/etqw/ETQW-demo2-client-full.r1.x86.run
http://dukeworld.com/idgames2/idstuff/etqw/

I suggest dropping support for 10010, instead supporting 10050.

> Have you been able to use sdlcl with etqw before?

Yes, I regularly use SDLCL with ETQW. It has a minor black screen issue but as SDLCL is essential to avoid many issues on Linux, I say it's safe to use SDLCL with ETQW. Notice disadvantage info below:

https://www.pcgamingwiki.com/wiki/Enemy_Territory:_Quake_Wars#SDL_Compatibility_Library_.28SDLCL.29

**Comment by d10sfan** [comment]
@rea987 Done in https://github.com/luxtorpeda-dev/packages/commit/289440626280cb82bdf910ffc223dd1463e2f940 and https://github.com/luxtorpeda-dev/packages/commit/1d0cbfa96e16797166e7235c62a3a3f7ed4af46e

**Comment by jm2** [comment]
Could this be tweaked so owners of the full version can use the Linux engine as well? The full version uses AppID 10000 so it's currently not picked up by the commits for the demo here.

**Comment by d10sfan** [comment]
@jm2 Do you own the full version to help test?

**Comment by jm2** [comment]
@d10sfan yes I do and happy to test.

**Comment by d10sfan** [comment]
@jm2 I'll take a look at this when I have a chance and get back to you once there's something ready to test. I don't own it, so it may take a few tries.

**Comment by rea987** [comment]
Liflg's etqw 1.5 installer's data has been uploaded to GitHub while ago;

https://github.com/liflg/etqw_1.5-multilingual_x86

**Comment by d10sfan** [comment]
@rea987 It looks like that will not be useful because of the way github's downloading works (it does not provide a download size), so there'll need to be some manual steps involved, but will update once I have a solution for that.

**Comment by rea987** [comment]
@d10sfan  Here are mirrors for `etqw_1.5-multilingual_x86.mojo.run`:

- https://files.holarse-linuxgaming.de/native/Spiele/Enemy%20Territory%3A%20Quake%20Wars/LIFLG-Installer/etqw_1.5-multilingual_x86.mojo.run
- http://etqw.taw.net/qw/etqw_1.5-multilingual_x86.mojo.run

Renamig the file as `etqw_1.5-multilingual_x86.mojo.zip` makes its content accesable for copying.

**Comment by rea987** [comment]
It is also worth noting to use system's own or Steam Linux Runtime's libraries instead of included following libraries;

- libgcc_s.so.1
- libjpeg.so.62
- libstdc++.so.6
- libSDL-1.2.id.so.0 (better be sdl12-compat)

**Comment by d10sfan** [comment]
@jm2 

I've added possible support for this here: https://github.com/luxtorpeda-dev/packages/commit/04472619ed34046070b8096594e6d1aa977cac26

Let me know how it goes and if you run into any issues. This requires manual steps which are described in the packages list website, mainly getting the linux binaries and manually putting them in the correct location. This is because I have been unable to cause the run files to run without user interaction automatically, unlike some of the others I've encountered.

**Comment by jm2** [comment]
Would using the client installer from the AUR package help automate this better? https://aur.archlinux.org/packages/etqw, specifically https://slashbunny.com/aur/etqw/ETQW-client-1.5-full.x86.run, which is the proper last full client release.

**Comment by jm2** [comment]
FWIW after copying all the client files from that runfile and deleting known-breaking libraries (libgcc_s.so.1, libstdc++.so.6), it does work as expected, so thanks! I'll see if I can update this to install automatically as that'll greatly help for the Steam Deck.

**Comment by rea987** [comment]
@d10sfan luxtorpeda-dev.github.io entry of the full game mentions ETQW-demo2-client-full.r1.x86 as its version. Is that a typo or does it utilize demo version?

**Comment by d10sfan** [comment]
@rea987 It does not use any particular version, because it requires the user to manually copy the files. That's because I've been unable to cause the run command to work and extract without needing user input (other run files I have been able to do that with).

I've updated the data to note that it expects the full version.

**Comment by rea987** [comment]
@d10sfan In luxtorpeda-dev.github.io entry of the full game and the demo version, following info seems to be a leftover from SDLCL; sdl12-compat no longer as such issue;

>  Applying settings in Settings menu might result black screen; return to desktop, exit and restart the game.

**Comment by d10sfan** [comment]
@rea987 Can you confirm that this no longer occurs?

**Comment by rea987** [comment]
@d10sfan In demo version (10050) it no longer occurs since the switch to sdl12-compat.

**Comment by d10sfan** [comment]
@rea987 Ok thanks, I've removed those lines: https://github.com/luxtorpeda-dev/packages/commit/da9f73a3abf649aa4976e3e68305b590af5ecf9a
