### ISSUE TITLE
RPG Maker 2000/2003 Games via EasyRPG Player (Yume Nikki)

### ISSUE THREAD

**Issue by gel-crabs** [luxtorpeda-dev/packages#354]
* Project link: https://github.com/EasyRPG/Player
* Project license: GPLv3
* Does it work on 64-bit only Linux: YES
* Is source code available?: YES
* Is source code stored in Git?: YES
* List of Steam AppIds of supported games:
    - https://steamdb.info/app/650700/
    - There may be more, but I'm only aware of Yume Nikki

## Additional information

Yume Nikki is free on Steam. I can personally confirm that EasyRPG Player works flawlessly with this game, as well as not requiring the RTP package (default RPG Maker assets) as it's already prepackaged with Yume Nikki.

For any games that require the RTP package (which uses a non-free license), EasyRPG made a replacement package with freely licensed assets (https://github.com/EasyRPG/RTP). However, I doubt any RPG Maker 2000/2003 games on Steam wouldn't already package it with the game as it would require an external download.

Running the games themselves are pretty straightforward (running "easyrpg-player" in the game's directory).

**Comment by JoshuaFern** [comment]
Here's a few more potential games for this engine: 
Ara Fell Demo https://steamdb.info/app/441750/
DEEP 8 https://steamdb.info/app/1037460/
Desolate City: The Bloody Dawn Enhanced Edition https://steamdb.info/app/965410/
Fantasya Final Definitiva REMAKE https://steamdb.info/app/656120/
Firon https://steamdb.info/app/1024250/
GALER: Plague of Heroes https://steamdb.info/app/508330/
Grimm's Hollow https://steamdb.info/app/1170880/
Island sky RPG https://steamdb.info/app/955730/
Ludu https://steamdb.info/app/563400/
LunarLux Chapter 1 https://steamdb.info/app/1258970/
Melon Journey 2 https://steamdb.info/app/1074030/
Metal Quest https://steamdb.info/app/754300/
Metallic Metronome https://steamdb.info/app/1260830/
Mystic Ruin: A New Dawn https://steamdb.info/app/1203950/
Nyanco Project https://steamdb.info/app/1122290/
Orpheus https://steamdb.info/app/959960/
Super Crystal Hunter https://steamdb.info/app/1208460/
Tales from Zilmurik https://steamdb.info/app/1423610/
Three Treason Theories RPG https://steamdb.info/app/955850/
TinkerQuarry https://steamdb.info/app/651280/
Toymaker https://steamdb.info/app/607780/

There's undoubtedly more, RPG Maker is popular.

**Comment by d10sfan** [comment]
Looks like it may make sense for this to be created as a "default" engine, similar to scummvm or dosbox-staging, where lux does not have each one defined, but you can pick from the default list, including easyrpg player.

**Comment by d10sfan** [comment]
Added in https://github.com/luxtorpeda-dev/packages/pull/391
