### ISSUE TITLE
Add a zenity dialog before the file selection box

### ISSUE THREAD

**Issue by JoshuaFern** [luxtorpeda-dev/packages#358]
**Describe the bug**
Right now the only description of what we're supposed to be picking using the file selection box is in the title bar, users running minimal window managers like i3 often disable their title bars. 

Affects at least MINERVA: Metastasis, and probably other games with the source engine.

**Expected behaviour**
Don't rely on the title bar to provide directions, just show a zenity dialog prior specifically stating what file/folder needs to be selected.

**Screenshots**
![Image](https://cdn.discordapp.com/attachments/692074733474152509/842430437200363550/fileselector.png)

**Additional context**
https://discord.com/channels/514567252864008206/692074733474152509/842426436606230528

**Comment by d10sfan** [comment]
Added in:

https://github.com/luxtorpeda-dev/packages/commit/f493996b55093b0d43d44ecaf20314a9ff6a2d9c
https://github.com/luxtorpeda-dev/packages/commit/aaa4127d770338b588ef730ee803cae3769b348b
https://github.com/luxtorpeda-dev/packages/commit/47223fe2111cc6538c06e80ac6b50686a10a67f7

**Comment by JoshuaFern** [comment]
Thanks, I just tested it and it's working.
