### ISSUE TITLE
Quake III Arena Demo

### ISSUE THREAD

**Issue by rea987** [luxtorpeda-dev/packages#359]
* Project link: *https://ioquake3.org/*
* Project license: *GPLv2*
* Does it work on 64-bit only Linux: *YES*
* Is source code available?: *YES*
* Is source code stored in Git?: *YES*

https://github.com/ioquake/ioq3/

* List of Steam AppIds of supported games:
    - https://steamdb.info/app/9080/

## Additional information

ioquake3 demo version info:
https://ioquake3.org/help/players-guide/#demo
https://ioquake3.org/help/players-guide/#sharedlibraries

I couldn't make the demo version work with ioquake3. But following person seems to have managed;

https://slackalaxy.com/2015/07/05/quake-iii-demo/

**Comment by d10sfan** [comment]
Steam is not allowing me to download the demo to test this, probably because I own the game. Do you not own this game currently?

**Comment by rea987** [comment]
I own Quake III, yet I also can download and play the demo version. I requested demo via Steam console:

`app_license_request 9080`
`app_install 9080`

**Comment by d10sfan** [comment]
I am unable to. Are you able to create a pull request with the changes necessary to make it work?

**Comment by d10sfan** [comment]
As mentioned in the other ticket, I'm unable to download these demos.

Are you able to provide steps as to how to get the demo to work with ioquake3? As in the commands needed to get it to load and run?
