### ISSUE TITLE
DOOM 3 Demo

### ISSUE THREAD

**Issue by rea987** [luxtorpeda-dev/packages#360]
* Project link: *https://dhewm3.org/*
* Project license: *GPLv3*
* Does it work on 64-bit only Linux: *YES*
* Is source code available?: *YES*
* Is source code stored in Git?: *YES*

https://github.com/dhewm/dhewm3

* List of Steam AppIds of supported games:
    - https://steamdb.info/app/9100/

## Additional information

https://dhewm3.org/#using-the-doom3-demo-gamedata

**Comment by d10sfan** [comment]
Steam is not allowing me to download the demo to test this, probably because I own the game. Do you not own this game currently?

**Comment by rea987** [comment]
I do not own regular Doom 3. I requested demo via Steam console:

`app_license_request 9100`
`app_install 9100`

**Comment by d10sfan** [comment]
Ok, are you able to make a pull request with the changes necessary to make the demo work?

**Comment by rea987** [comment]
> Ok, are you able to make a pull request with the changes necessary to make the demo work?

Unfortunately I am completely dumb in case of coding. I can give some information regarding demo versions;

- Quake 2, Quake 3 and Quake 3: Team Arena's demo versions are visible on the store of full versions of these games. They can also be found in Steam game search page;
https://store.steampowered.com/search/?sort_by=Name_ASC&term=quake&ignore_preferences=1&category1=10

- Doom 3 and ETQW's demo versions are hidden but available. Users need to launch Steam with `-console` argument; request app license and install the game via Steam console manually. After that, Luxtorpeda can do its job.

**Comment by d10sfan** [comment]
As I said, steam is not letting me download the demos. I've tried all the options that I can find, including the console, clicking the demo button in the store, and using steamdb. Other demos work fine, so it seems to be specific to these for some reason.

If you can send me any steps as to how you are able to get the demo working with the engine, I can work on replicating it.

**Comment by rea987** [comment]
> As I said, steam is not letting me download the demos. I've tried all the options that I can find, including the console, clicking the demo button in the store, and using steamdb. Other demos work fine, so it seems to be specific to these for some reason.

In that case, I would speculate that we are using different regional packages of same games and/or bundles; US ve EU/ROW which might have package conflict with demos of the games already owned. Pure speculation though.

Can you at least download ETQW demos via Steam console?

-  Enemy Territory: QUAKE Wars Demo 2.0 (10050)
-  Enemy Territory: QUAKE Wars Demo (10010)

**Comment by d10sfan** [comment]
I have the etqw demo, yes. So if you're able to get some commands that I could use as a starting point i could look at these, otherwise would need to wait for a pull request.
