### ISSUE TITLE
Additional GZDoom Games

### ISSUE THREAD

**Issue by JoshuaFern** [luxtorpeda-dev/packages#362]
The Forestale: https://steamdb.info/app/817220/
Fury's Sky: https://steamdb.info/app/1118550/
Hedon: https://steamdb.info/app/1072150/
Lycanthorn II - Rain of Beasts: https://steamdb.info/app/1546440/
Selaco: https://steamdb.info/app/1592280/
Shrine: https://steamdb.info/app/1271050/
Shrine II: https://steamdb.info/app/1417010/

## Additional information

Here's a list of additional games on Steam that use the GZDoom Engine, several of which are free.

**Comment by d10sfan** [comment]
Hedon is already native and Selaco isn't out yet, but I'll look at the others when I have time. Do you have a list of the commands needed for each one?

**Comment by JoshuaFern** [comment]
Hedon runs an older version of the engine, it would be useful to have the option to use modern vanilla gzdoom.

Simply running gzdoom while in the game's folder is enough. Here's a list of subfolders containing the game:
The Forestale: `./`
Fury's Sky: `./`
Hedon: `./hgzdoom`
Lycanthorn II - Rain of Beasts: `./`
Selaco: Unknown, but probably `./`
Shrine: `./`
Shrine II: `./shrine2`

So to launch Shrine would be simply `gzdoom`, but Shrine II would need to be `cd ./shrine2 && gzdoom`

**Comment by d10sfan** [comment]
From my testing, it was required to add the iwad command so that gzdoom would not show up the GUI launcher.

I've implemented these in this commit: https://github.com/luxtorpeda-dev/packages/commit/32c69019206772dcec5ea4ed8eb8c28881284a4c

**Comment by JoshuaFern** [comment]
One side effect of specifying `-iwad` is that the default configuration file for the game isn't always loaded.

The Forestale: Seems to work.
Fury's Sky: Seems to work.
Hedon: Non-functional, should be `-iwad hgzdoom/Hedon.ipk3`
Lycanthorn II - Rain of Beasts: Config isn't being loaded `-config gzdoom.ini`
Shrine: Config isn't being loaded, specify with `-config gzdoom.ini`
Shrine II: Config isn't being loaded, specify with `-config shrine2/gzdoom.ini`

**Comment by d10sfan** [comment]
Ok, this should work: https://github.com/luxtorpeda-dev/packages/commit/9d065e569f4fe873b187bf9dfe6bfbd34c22b343

**Comment by JoshuaFern** [comment]
The Forestale: Tested working.
Fury's Sky: Tested working.
Hedon: See below.
Lycanthorn II - Rain of Beasts: Tested working.
Shrine: Tested working.
Shrine II: Tested working.

Hedon right now is mostly working, but there's a few small problems:

- The path I gave earlier `-iwad hgzdoom/Hedon.ipk3` is for the *linux* depot of the game. For some reason the Windows version has the flies in `-iwad ./Hedon.ipk3` instead. Despite this incorrect path the game autodiscovers the files and runs anyways.
- Hedon doesn't ship with a configuration file, but rather it's generated on launch. I have ran Hedon in Proton to generate the file, [hedon-steamuser.ini](https://gist.github.com/JoshuaFern/05c7825a786776df3f4b00a9bdde42cc). I suggest including this file as `gzdoom.ini` and specifying `-config gzdoom.ini` so it works out of the box.

**Comment by d10sfan** [comment]
@JoshuaFern I've fixed the path here: https://github.com/luxtorpeda-dev/packages/commit/dfe4e064bdbf12f030f45d8bbf0a366c41915ae0

For the config, are you saying that the normal gzdoom does not generate that file? And this one is needed for the game to function properly?

**Comment by JoshuaFern** [comment]
> For the config, are you saying that the normal gzdoom does not generate that file? And this one is needed for the game to function properly?

Most games just ship their customized `gzdoom.ini` along with the game files. Hedon uses a lightly modified fork of gzdoom called hgzdoom to generate the configuration on launch similar to how gzdoom does normally - but with two differences. One, the file is named `hedon-steamuser.ini` rather than the usual `gzdoom.ini`, and two, the file generated is not the standard generic config for gzdoom but rather a config specific to Hedon.

To ensure Hedon works properly out of the box we can't rely on `hedon-steamuser.ini` being in the directory, as the game must be launched for it to generate - so instead I propose shipping the hgzdoom generated file that I supplied and naming it `gzdoom.ini` so it won't conflict in the event that the user wants to play without Luxtorpeda.

**Comment by d10sfan** [comment]
@JoshuaFern I did this in: https://github.com/luxtorpeda-dev/packages/commit/325b48c530eec3538647a813a36c5a82bc1b6b26

**Comment by JoshuaFern** [comment]
Great, the configuration file exists, now Hedon just needs to use it with `-config gzdoom.ini`

Also I like the way you copied hedon.ini to gzdoom.ini only if the file doesn't exist, this allows users to easily modify the config without Luxtorpeda trying to replace it every launch. Maybe rename hedon.ini to hedon_template.ini so folks don't get confused and think it's shipped with the game. They could end up manually modifying hedon.ini and get confused why it's not having an effect in-game.

**Comment by d10sfan** [comment]
@JoshuaFern Done in https://github.com/luxtorpeda-dev/packages/commit/01cee1cc650d6601ee8b754dc5731bc32cc29f24

**Comment by JoshuaFern** [comment]
Working perfectly now, thanks.
