### ISSUE TITLE
Achievement crashes RealRTCW

### ISSUE THREAD

**Issue by rea987** [luxtorpeda-dev/packages#365]
**RealRTCW fails to play single player chapters**
RealRTCW launches fine, first chapter's cinematic loads fine, the game fails to load the level.

**To Reproduce**

1. Launch RealRTCW
2. Start a SP chapter
3. The game returns `Error (line 343): unknown action: achievement_speedrun.` error.

https://gist.github.com/rea987/350b8f6ee68d0c37da47410ee890b4ed

**Expected behaviour**
The game to load SP chapters

**Screenshots**
![20210524200656_1](https://user-images.githubusercontent.com/1547646/119384194-00a40980-bccd-11eb-91f9-1c1324648616.jpg)

**Additional context**
RealRTCW is functional as it managed to run another mod **The Dark Army: Uprising** v1.50 via `fs_game` launch argument just fine.

https://www.moddb.com/mods/tda/downloads/remaster
https://www.moddb.com/mods/tda/downloads/remaster-patch

**Comment by d10sfan** [comment]
Looks like this one now needs the full non-steam client files. I'll work on this when I have a chance.

**Comment by d10sfan** [comment]
This is fixed in this commit: https://github.com/luxtorpeda-dev/packages/commit/bc02379fb115647e968c59f175e716b9205dcb0a

A few things changed, one is that it downloads the files from moddb into nosteam/Main, since the steam files no longer work with this version (since it requires achivements).

It'll also ask you for the rtcw directory again just once, and then should work as normal. Mods can still go in the root realrtcw directory and it should see them.

**Comment by rea987** [comment]
realrtcw Version 9 crashes at launch, it doesn't ask for RTCW installation, instead shows `Request failed. Status code: 410` error.

https://gist.github.com/rea987/cfb25c1e83f6c3ec662535bb5bc83a3c

![Screenshot at 2021-05-27 11-48-44](https://user-images.githubusercontent.com/1547646/119796408-04f54000-bee2-11eb-9f92-ec4cb951aaf9.png)

**Comment by FearlessQuality** [comment]
appears to be fixed now, i stopped getting the 410 code and game launches when i direct it to rtcw directory

**Comment by d10sfan** [comment]
@rea987 It looks like this was because the moddb mirror links expire, so manually downloading the zip and extracting it to a folder called nosteam inside realrtcw is required (so that ```./nosteam/!copy the content of this folder into rtcw root directory``` exists)

This is done in this commit: https://github.com/luxtorpeda-dev/packages/commit/28f10e174f536d2c6d34a33689c7a2ac5c8d60f2

**Comment by rea987** [comment]
Something weird going on with RealRTCW installation from Mod DB.

I put `!copy the content of this folder into rtcw root directory` folder in `/.local/share/Steam/steamapps/common/RealRTCW/nosteam` directory. It worked fine with existing RTCW and RealRTCW installations. But when I did the same with clean installation by uninstalling and clearing directories of those games, the end result is a bit different. Luxtorpeda does launch RealRTCW but the main menu and in-game UI seems like vanilla RTCW instead of RealRTCW.

https://gist.github.com/rea987/a630b1709b8fd2e61ca785c79fce134f

![Screenshot at 2021-05-30 18-37-30](https://user-images.githubusercontent.com/1547646/120111229-cd082a00-c179-11eb-8dd4-9ba6a6b4ef0f.png)
![20210530184433_1](https://user-images.githubusercontent.com/1547646/120111243-dbeedc80-c179-11eb-8860-e6fa483caac1.jpg)

**Comment by d10sfan** [comment]
@rea987 What does the directory structure of the realrtcw/nosteam directory look like?

**Comment by rea987** [comment]
> @rea987 What does the directory structure of the realrtcw/nosteam directory look like?

https://gist.github.com/rea987/d03ec69ec4cf77bda0beb1b1b5a91423
https://gist.github.com/rea987/f69149df7c925801375fbe9e897193ee
https://gist.github.com/rea987/2ae2af79d206d116d36fb0b81ec4812d

It looks like the pk3s in `~/.local/share/Steam/steamapps/common/RealRTCW/nosteam/!copy the content of this folder into rtcw root directory` were either transferred into `~/.local/share/Steam/steamapps/common/RealRTCW/Main` or removed.

**Comment by d10sfan** [comment]
@rea987 Yes, it's supposed to move them into nosteam/Main, but for some reason it looks like it went a directory below that. 

Try putting the files back, then deleting the ready file in nosteam. And see if this most recent change works.

https://github.com/luxtorpeda-dev/packages/commit/83743787e893570c82ecff9677ccab39c170e601

**Comment by rea987** [comment]
**RealRTCW doesn't apply Steam launch options:**

I used to be able to use Steam launch options to run mods with _RealRTCW_, but after switching to Mod DB release, the launch options of the mod are coded into `~/.cache/luxtorpeda/packages.json` of Luxtorpeda. I tried to edit the file but it resets every time I launch the game:


```
],
        "commands": {
            ".*RealRTCW.x64.exe": {
                "cmd": "./nosteam/RealRTCW.x86_64",
                "args": [
                    "+set",
                    "com_basegame",
                    "Main"
                ]
```

**Comment by d10sfan** [comment]
@rea987 Those args have been there since the beginning, that is not new. It's possible that the mod is now not in the right place for it to be found. Where did you end up putting it? I'm able to play mods if I put them in the nosteam directory

**Comment by rea987** [comment]
> I'm able to play mods if I put them in the nosteam directory

That was my mistake, thanks for pointing it out!
