### ISSUE TITLE
Quake 3 arena engines invalid key

### ISSUE THREAD

**Issue by FearlessQuality** [luxtorpeda-dev/packages#367]
**Describe the bug**
ioquake3 and quake3e give an invalid key error from the key it pulls from steam, restricts single player maps except for demo map

**To Reproduce**
Steps to reproduce the behaviour:
1. install quake 3 arena
2. pick an engine
3. check options for cd key info

**Expected behaviour**
cd key should work
**Screenshots**

**Additional context**

**Comment by d10sfan** [comment]
@FearlessQuality That would most likely be an issue with your cd key and/or how it was entered. There should be a baseq3/q3key file with your key.

I tried the single player just now and it'll show access denied if you haven't started it before. Is that what you are referring to? If so, that just means that you haven't finished the tutorial or the particular tier.

The issue template is there to help diagnose issues, so screenshots should be provided if you are seeing a particular error. If you are seeing "Access Denied" and have not finished the tutorial yet, that is normal behavior.

![20210527175238_1](https://user-images.githubusercontent.com/4337981/119906727-5d453580-bf14-11eb-87d0-3dd5098e6aa0.jpg)
![20210527175239_1](https://user-images.githubusercontent.com/4337981/119906730-5dddcc00-bf14-11eb-8c7e-c7788e742fd8.jpg)

**Comment by FearlessQuality** [comment]
thanks, didn't realize i had to do intro first before tier 1 unlocked
