### ISSUE TITLE
SNKRX

### ISSUE THREAD

**Issue by Alzarath** [luxtorpeda-dev/packages#369]
* Project link: https://github.com/a327ex/SNKRX
* Project license: MIT
* Does it work on 64-bit only Linux: MAYBE (Untested)
* Is source code available?: YES
* Is source code stored in Git?: YES
* List of Steam AppIds of supported games:
    - https://steamdb.info/app/915310/

## Additional Comments

Project is the game itself, made by the developer, but not published on Steam for non-Windows.

**Comment by Alzarath** [comment]
Turns out I under-estimated the ability for the repo to run on Linux. Getting it running is still fairly trivial, being a matter of acquiring `love`, `luasteam.so`, and `libsteam_api.so`.

**Comment by d10sfan** [comment]
It looks like if the steam_api library is required that we won't be able to package it.

https://github.com/a327ex/SNKRX/blob/986db10053e25e0f892b4b60122faaf2cba97872/engine/init.lua#L49 seems to indicate that the steam API is required for it to launch. If the game had a non-steam mode then it'd be possible, but does not seem likely.

Let me know if anything changes on this though.
