### ISSUE TITLE
Shared Engine Packages Between Games

### ISSUE THREAD

**Issue by JoshuaFern** [luxtorpeda-dev/packages#38]
**Describe the bug**
Right now, each game downloads duplicate packages of the same engine. It would be nice to have engine packages shared between games for faster launch times, less bandwidth usage, and lower disk consumption.

**Expected behaviour**
Each game should share the same engine files, perhaps by linking the engine package to the game's appid directory.

**Additional context**
A list of games share engines include:

- Arx Fatalis and the Demo (arxlibertatis)
- DOOM (gzdoom)
- Quake 2 (yquake2)
- Jedi Knight (openjk)

**Comment by d10sfan** [comment]
Packages portion is complete. Need to add the configuration support for the engines that need it, then make the luxtorpeda piece live

**Comment by d10sfan** [comment]
Engine List:

- dhewm3
- arxlibertatis
- gzdoom
- yquake2
- ioquake3

For openjk, it has different files for each game, so it makes sense to keep it unique. I'm working on the above list next.

**Comment by d10sfan** [comment]
Completed with Luxtorpeda version 9. All of the above engines have been modified to use this new form.

**Comment by d10sfan** [comment]
Completed with Luxtorpeda version 9. All of the above engines have been modified to use this new form.
