### ISSUE TITLE
PCExhumed and Raze for Powerslave

### ISSUE THREAD

**Issue by NerosTie** [luxtorpeda-dev/packages#385]
* Project link: 
https://github.com/nukeykt/NBlood
https://github.com/coelckers/Raze
* Project license: ?
* Does it work on 64-bit only Linux: YES
* Is source code available?: YES
* Is source code stored in Git?: YES
* List of Steam AppIds of supported games:
https://store.steampowered.com/app/1260020/

**Comment by McMarius11** [comment]
@d10sfan i can gift you the game

**Comment by d10sfan** [comment]
@McMarius11 Thanks that'd be great! My steam name is the same, d10sfan

**Comment by d10sfan** [comment]
Added raze support in https://github.com/luxtorpeda-dev/packages/commit/73570a581b77a1e854c357602cb97f3f687a7450

nblood support is in progress

**Comment by d10sfan** [comment]
exhumed/nblood support added in https://github.com/luxtorpeda-dev/packages/pull/394

**Comment by d10sfan** [comment]
Tried out both they've been released and built. They should be good to go! Thanks for the game gift

**Comment by McMarius11** [comment]
Thanks d10sfan, both work great!
one minor detail in the launch options exhumed i think should be named pcexhumed

in the PWRSLAVE/pcexhumed.cfg the mouse sensitivity can be changed to double the normal speed
MouseAnalogScale0 = 131072
MouseAnalogScale1 = 131072

vsync i think does not work, the command should be r_vsync 1
