### ISSUE TITLE
Entropy : Zero crashes Steam

### ISSUE THREAD

**Issue by rea987** [luxtorpeda-dev/packages#389]
**Describe the bug**
Entropy : Zero crashes Steam during the first launch. The game launches fine with 2nd attempt.

**To Reproduce**
Steps to reproduce the behaviour:
1. Install Entropy : Zero enable Luxtorpeda
2. Launch the game, it fails to launch and crashes Steam client
3. Relaunch Steam and the game

**Expected behaviour**
Game to launch in the first attempt without crashing Steam.

**Additional context**
Game download: https://gist.github.com/rea987/80829e12f9d91596c0086beb275a96cb
Failed launch: https://gist.github.com/rea987/aa260785d5c9ec9f72f6e757d969d093
Successful launch: https://gist.github.com/rea987/2b2b0d3c1eda9802f246f3543fcdda31

Such first launch Steam crash doesn't happen with Minerva, Quake 3: Arena and Resistance Element. Also, same issue used to happen with Luxtorpeda 25.

**Comment by d10sfan** [comment]
@rea987 

Try going into the cached download for this game (in ~/.cache/luxtorpeda) and find the run-entropy-zero.sh file and replace what's in it with the following:

```
#!/bin/bash


if [ ! -f "sdkpath.txt" ]; then
    "$STEAM_ZENITY" --info --text="Browse to Source SDK Base 2013 Singleplayer Installation" --title="Information"
    HL_PATH=$("$STEAM_ZENITY" --file-selection --title="Browse to Source SDK Base 2013 Singleplayer Installation" --directory)

    if [ -z "$HL_PATH" ]; then
        "$STEAM_ZENITY" --error --title="Setup Error" --text="Path to Half Life not given"
        exit 1
    fi

    if [ ! -d "$HL_PATH/sdktools" ]; then
        "$STEAM_ZENITY" --error --title="Setup Error" --text="Path to Source SDK 2013 incorrect"
        exit 1
    fi
    
    echo "$HL_PATH" >> sdkpath.txt
    
    pushd "Entropy Zero/EntropyZero"
    # from z33ky script
    for d in sound materials resource; do
		LD_PRELOAD="" find "${d}/" -exec sh -eux -c "echo {} | grep -q '[A-Z]' && ln -vs \"\$(basename {})\" \"\$(echo {}|tr '[A-Z]' '[a-z]')\"" \;
	done
    popd
fi

sdkpath=`cat sdkpath.txt`

pushd "Entropy Zero/EntropyZero"
    cp -rfv ../../weapon_manhacktoss.txt scripts/
popd

"$sdkpath"/hl2.sh -game "$PWD/Entropy Zero/EntropyZero" -steam
```

Then remove the sdkpath.txt file in the installation directory of entropy zero and try launching the game again.

Also, give me the output of this command:  ulimit -aH

**Comment by d10sfan** [comment]
I believe this may be fixed by the changes coming soon in 29: https://github.com/luxtorpeda-dev/luxtorpeda/pull/80

Once that releases, see if it fixes your issues. Part of the fixes there involve removing the steam overlay attempt to access all of the processes created by luxtorpeda.

**Comment by rea987** [comment]
I retried Entropy : Zero with clean game and Luxtorpeda 29 installation and it did crash the Steam during the first launch.

Game download:
https://gist.github.com/rea987/4db20a1fa679a0b8d879c8e8a5853381

Game first launch that crashed Steam:
https://gist.github.com/rea987/94a9b21c4e8a3084af4e33f1972d0ac5

Game second launch that is successful:
https://gist.github.com/rea987/293a74294b41d4785632220ecb379e41

After this, uninstalled the game, cleared its directory, redownloaded the game, edited `~/.cache/luxtorpeda/714070/source-sdk-2013-714070-11.tar.xz/run-entropy-zero.sh`, then launched the game which started fine without crashing Steam:

https://gist.github.com/rea987/2bd8bb0948ea450a7abcb5246a7a0c4a

`ulimit`:
https://gist.github.com/rea987/b2407852eeda68b9c95a3c387bff38e6

**Comment by d10sfan** [comment]
@rea987 Ok thanks, if you launch again it should be fixed with the updated versions (https://github.com/luxtorpeda-dev/packages/commit/ab881839817e750cc8f10eedb2f6c03170b63de4).

I also updated the other  source gamelaunch scripts as well.
