### ISSUE TITLE
SiN: Gold

### ISSUE THREAD

**Issue by rea987** [luxtorpeda-dev/packages#393]
* Project link: *https://github.com/NightDive-Studio/sin-ex-game*
* Project license: *LIMITED SOFTWARE WARRANTY AND LICENSE AGREEMENT*

https://github.com/NightDive-Studio/sin-ex-game/blob/master/license.txt

* Does it work on 64-bit only Linux: *MAYBE*
* Is source code available?: *YES*
* Is source code stored in Git?: *YES*
* List of Steam AppIds of supported games:
    - https://steamdb.info/app/1313/

## Additional information

GitHub page of the NightDive's source code release refers DLL; not sure whether the code can be compile on or for Linux.

**Comment by d10sfan** [comment]
@rea987 Can you see if you're able to compile this engine with the source and run it? It does not look like it has a Linux version.

**Comment by d10sfan** [comment]
From looking at the source, this does not appear to have a Linux port.

Please feel free to comment if you find out otherwise.
