### ISSUE TITLE
OldUnreal without WINE installer

### ISSUE THREAD

**Issue by rea987** [luxtorpeda-dev/packages#399]
* Project link: *https://github.com/vide0hanz/unreal-gold*
* Project license: *Unknown*
* Does it work on 64-bit only Linux: *NO*
* Is source code available?: *Partially*
* Is source code stored in Git?: *Partially*
* List of Steam AppIds of supported games:
    - https://steamdb.info/app/13250/

## Additional information

This repo features extracted OldUnreal libs (unreal-linux.tar.bz2) for Unreal Gold from the .exe installer. If it can be incorporated the Luxtorpeda package of Unreal Gold, there would be no need for WINE and .exe installer.

**Comment by d10sfan** [comment]
I don't think this is a good idea license wise. The exe was created because of some license issues by Epic so it's probably best to keep that mode, unless the unreal gold people are able to create a linux archive.
