### ISSUE TITLE
Dimension of the Past and Dimension of the Machine episodes for the new Quake

### ISSUE THREAD

**Issue by rea987** [luxtorpeda-dev/packages#402]
* Project link: *http://quakespasm.sourceforge.net/*
* Project license: *e.g. GPLv2*
* Does it work on 64-bit only Linux: *YES*
* Is source code available?: *YES*
* Is source code stored in Git?: *YES*

https://github.com/sezero/quakespasm

* List of Steam AppIds of supported games:
    - https://steamdb.info/app/2310/

## Additional information

The new big update added Dimension of the Past and Dimension of the Machine episode to the base game as episodes. Location of those should be;

- **Dimension of the Past:** `~/.local/share/Steam/steamapps/common/Quake/rerelease/dopa`
- **Dimension of the Machine:** `/.local/share/Steam/steamapps/common/Quake/rerelease/mg1`

**Comment by d10sfan** [comment]
The new packs have been added. dopa needed to use the original pak, so I downloaded it as part of the install process. The one provided in the re-release has issues with the source ports (crashes trying to pick up armor for example).

The machine pak seems to work well other than some missing localization.

Done in:

https://github.com/luxtorpeda-dev/packages/commit/7dfcec775ca7f0929d65d0887a4343ede279260c
https://github.com/luxtorpeda-dev/packages/commit/731cf14ef4bd675521bbea6a40ecd194ae1a7f1c
https://github.com/luxtorpeda-dev/packages/commit/3442642e3b630c7ee0e787242f08e5aaf82f378c
https://github.com/luxtorpeda-dev/packages/commit/faa71c8c31bf56256df4ecf3cb80ef3ec92a5e66
https://github.com/luxtorpeda-dev/packages/commit/06890b2d43ca703063d812543f72d9f191c38cf7
https://github.com/luxtorpeda-dev/packages/commit/38d8e98d62c53f8b11e2e8c32aa0b9cd375a685b
https://github.com/luxtorpeda-dev/packages/commit/2b803c84e910151752bdae7ab357f82dba6659ba
https://github.com/luxtorpeda-dev/packages/commit/bb313483d6fc3862d257fd451ac9dd6b24994dbc
