### ISSUE TITLE
FTE for Quake

### ISSUE THREAD

**Issue by rea987** [luxtorpeda-dev/packages#404]
* Project link: *https://fte.triptohell.info/*
* Project license: *Unknown*
* Does it work on 64-bit only Linux: *YES*
* Is source code available?: *YES*
* Is source code stored in Git?: *YES*

https://github.com/mdeguzis/ftequake

* List of Steam AppIds of supported games:
    - https://steamdb.info/app/2310/

## Additional information

FTE claims to support splitscreen multiplayer that the new Quake also offers.

**Comment by d10sfan** [comment]
Added in https://github.com/luxtorpeda-dev/packages/pull/406

**Comment by rea987** [comment]
@d10sfan Is that possible to enable FTE for Dimension of the Past and Dimension of the Machine episodes as well?

**Comment by d10sfan** [comment]
Yes, I added that in https://github.com/luxtorpeda-dev/packages/commit/3d8ef96ebc97c7dcbd8fdcce57a6f04f118749ac

**Comment by rea987** [comment]
FTE claims to support Quake 2 mods, Quake 3, Hexen 2 mods:

> Quake 2
> The vanilla quake2 gamecode is specific to 32bit windows, and has a bug that causes saved games to fail with ASLR etc.
For this reason, replacement gamecode can be installed via the downloads menu, and will be used in preference to the baseq2 gamecode when installed. This gamecode is from yamagi quake2, so it fixes the saved game issue and is thus useful even on x86.
**FTE uses the vanilla API so mods mods should still work if they're compiled for your cpu+system. FTE still does not provide gamecode for the mission packs.**

> Quake III Arena
> FTE has support for running Quake3. The mission pack is not supported at this time, and this also means that mods are likely to not work.
To run, simply place fteqw.exe into your quake3 dir and then just run it.
FTE is unable to connect to punkbuster-enabled servers, and general network connectivity is not well tested (see: mods).
Thanks to Quake3's preferential use of qvm files instead of dlls, there is not normally any issue with operating system / cpu type.

> Hexen, Two
> FTE has support for both Hexen2 and its mission pack (Portals of Praevus). Just place fteqw.exe into your hexen2 directory and run it.
Note that FTE is not network-compatible with other hexen2 engines, at all. Most mods and maps should work though (its mostly just a glorified quake mod). For best results use the missionpack - it has numerous fixes for bugs in the original's gamecode.

https://fte.triptohell.info/readme

I am unable to enable split screen for Quake 3, am I doing something wrong?

Also, can we get FTE support for Quake 2 mission packs, Hexen 2?

**Comment by d10sfan** [comment]
@rea987 Not sure how it is supposed to work with Quake 3. I will look into quake 2 mission packs and hexen 2.

**Comment by d10sfan** [comment]
Done in https://github.com/luxtorpeda-dev/packages/commit/bab26ae69ef747a94336e988fb91d2df4ed72acf

Quake 2 Expansions and Hexen 2 has been added.
