### ISSUE TITLE
Quake II with VKQuake2 won't open (but keeps running)

### ISSUE THREAD

**Issue by jorgicio** [luxtorpeda-dev/packages#409]
**Describe the bug**
I try to run Quake II using VKQuake2 as engine, and it shows it's running, but no window is open. I have to stop it manually from Steam.

**To Reproduce**
Steps to reproduce the behaviour:
1. Run Quake II from Steam and select VKQuake2 as engine.
2. Nothing happens, but it shows it keeps running
3. Tried over and over and nothing changes.

**Expected behaviour**
Quake II should run with VKQuake 2 and a window should open.

**Additional context**
Using Nvidia GTX 1650 with privative drivers, which supports Vulkan. I use Manjaro as distro.
In the meantime, I'm using Yamagi Quake 2 with Vulkan support and works flawlessly.

**Comment by jorgicio** [comment]
The only log I can leave here is this output, which is repeated infinitely until I stop the game from the Steam library:

`------- Loading ref_vk.so -------
LoadLibrary("ref_vk.so") failed: libXxf86dga.so.1: cannot open shared object file: No such file or directory
Only Vulkan renderer is supported on Linux.
`

I guess is the `ref_vk.so` inside the vkQuake2 directory, because I don't have the same issue with Yamagi Quake 2, which it has its own `ref_vk.so` (which I had to compile it apart).

**Comment by d10sfan** [comment]
Ok, that's been fixed in this https://github.com/luxtorpeda-dev/packages/pull/410

It looks like libXxf86dga is not included on all systems, it's a x11 package. I added compilation steps so that it is included with the engine.

Next time you launch it should work. Let me know if you have any issues.

**Comment by jorgicio** [comment]
Hi, now it launches, and I noticed that I haven't installed libxxf86dga, so I did it and now it works. Thank you!
