### ISSUE TITLE
Quake (2310) uses wrong basedir by default

### ISSUE THREAD

**Issue by NeoTheFox** [luxtorpeda-dev/packages#411]
When using luxtorpeda to play the original Quake it tries to use the `id1` folder in the game folder, but Steam installs this folder as `Id1`, with an uppercase I, and that means any filesystem that is case-dependent would cause it to instantly crash. Just renaming the folder manually is enough to make it work.

**Comment by d10sfan** [comment]
Also issues related to engines should be created in this repository.

**Comment by d10sfan** [comment]
I've made the changes in these commits. Next time you launch it should work if it's Id1 or id1.

https://github.com/luxtorpeda-dev/packages/commit/19396e49d7886f256fdf6276dab9043994fa938b
https://github.com/luxtorpeda-dev/packages/commit/8f01720b7c8b701bc547edb9610a4a230a2ddcf4
https://github.com/luxtorpeda-dev/packages/commit/f9333b6e5deae97a9769f372dbd11ffa38cf56e8
https://github.com/luxtorpeda-dev/packages/commit/d23e11389d19cd8a0be9f8a027bc332cfd79e044
