### ISSUE TITLE
System Shock Remake Demo

### ISSUE THREAD

**Issue by rea987** [luxtorpeda-dev/packages#414]
* Project link: *https://www.systemshock.com/*
* Project license: *Proprietary*
* Does it work on 64-bit only Linux: *YES*
* Is source code available?: *NO*
* Is source code stored in Git?: *NO*
* List of Steam AppIds of supported games:
    - https://steamdb.info/app/487390/

## Additional information

System Shock Remake had multiple demo releases. First of whom is Unity Engine based pre-alpha demo whose Linux version is still accessible on GOG. Around 2018/2019, Nightdive Studios switched to Unreal Engine and rebooted the development. Currently Unreal Engine based demo for Windows is available on Windows, GOG and Epic Store but I am unable to find it for Linux.

During my investigation on SteamDB repos, I found out that Linux repo with Unreal Engine based demo has been emptied on 25th Feb 2021.

https://steamdb.info/depot/487393/history/

By using DepotDownloader, I managed to download previous Manifest (7282696849817161137) for Linux repo.

https://archive.org/download/system_shock_remake_demo/SystemReShock.7z
https://archive.org/details/system_shock_remake_demo

However, I am unable to run the game properly. When I launched `SystemShock.sh` on Vega 7 with Mesa the game runs but after loading, it gives only white screen while the game is running fine. When I run it on GeForce 940M with proprietary drivers, it crashes, cannot launch. 

I wonder if it can be run properly and be added to Luxtorpeda?

**Comment by d10sfan** [comment]
@rea987 If you're unable to launch the game, there's probably nothing that can be done. I'm not too comfortable with using re-hosted closed source for this and downloading depots is outside the scope of luxtorpeda directly.

If you wanted to play this one with luxtorpeda, you could use the user packages feature. 

Let me know if anything else can be done for this one.
