### ISSUE TITLE
RetroArch

### ISSUE THREAD

**Issue by JoshuaFern** [luxtorpeda-dev/packages#427]
### Project Link

https://github.com/libretro/RetroArch

### Project License

GPL-3.0

### Steam App Ids

https://steamdb.info/app/1118310/

### Additional Context

RetroArch has been released to steam and we have some options for adding to luxtorpeda-dev:

#### Non-Steam RetroArch

We can add the non-steam version of RetroArch as an option for RetroArch. This would be if they picked our "Luxtorpeda (Runtime)" compatibility tool for RetroArch in steam, then they could download that version. This could let them use the nightly cores that can be downloaded with that version.  This could be either the nightly version or a stable version. Both versions appear to download the nightly cores: https://buildbot.libretro.com/nightly/linux/x86_64/latest. We would want to download from the buildbot and not build the cores or RetroArch itself ourselves.

#### RetroArch as an Engine
It would be cool if RetroArch was an engine for Luxtorpeda as well. Many of the existing projects that lux-dev supports are also provided as libretro cores. Doom, Quake, EasyRPG, ScummVM, OpenLaura, DOSBox, and more. Players could then take advantage of Libretro features like AI Service, Run Ahead, Shaders, Touchscreen Support, Cheat/Rumble Codes, and other goodies. Also Retroarch has a [command line interface](https://docs.libretro.com/guides/cli-intro/).

When the game is launched via Luxtorpeda we can support Steam features for that particular game like time tracking and screenshots whereas running the game data from RetroArch normally would attribute that time and screenshots to RetroArch instead.

**Comment by d10sfan** [comment]
@JoshuaFern 

For the appimage part, luxtorpeda switches to the windows depot, so that the windows version will be downloaded. So we wouldn't be getting the linux appimage in this case.

We could either take the retroarch nightly appimage and extract that, or attempt to build it, although not sure all that is involved there, and if the steam version is different (to support the steam dlcs).

As for building non-steam engines, I'm not sure if luxtorpeda would be able to help with that. Normally you can pick an engine, which could be used to download dlc I suppose, but retroarch will be communicating with the various core developers to add them to steam from what I know.

As well, the buildbot has a captcha behind it, so not sure if it'd be possible to use that automatically.

One way to solve both issues would be to use the outside steam version of retroarch for the lux version, meaning it could use the core downloading that it sounds like the original retroarch uses. Let me know if that would make sense for this.

For using retroarch as an engine, I suppose it'd depend on if those cores could be downloaded inside retroarch and if there was a way to automate that.

**Comment by JoshuaFern** [comment]
> AppImage

It seems that RetroArch won't be distributing as an AppImage much longer: https://steamcommunity.com/games/1118310/announcements/detail/2873849978168865590

> buildbot has a captcha behind it

Interesting, I've never had a captcha on buildbot and I'm pretty sure RetroArch fetches cores from there itself (there's clearly no way to enter a captcha in the RetroArch UI)

> One way to solve both issues would be to use the outside steam version of retroarch for the lux version, meaning it could use the core downloading that it sounds like the original retroarch uses. Let me know if that would make sense for this.

Yeah, that seems like a good option if it'll work. Just having normal RetroArch that you can download cores for would be an upgrade compared to the nerfed Steam version.

Retroarch on Steam is compiled with the `HAVE_STEAM` parameter which only seems to disable built-in the core download and update functionality. A limited selection of cores are then distributed via Steam itself. I believe these Steam DLC cores would work with Retroarch if it was compiled without  `HAVE_STEAM`, it's just a matter of putting the file in the cores directory.

We probably should avoid building all of libretro, that seems like a major undertaking. 

> For using retroarch as an engine, I suppose it'd depend on if those cores could be downloaded inside retroarch and if there was a way to automate that.

Cores can be downloaded inside of the original retroarch, but to automate lux would have to download it.

**Comment by d10sfan** [comment]
@JoshuaFern Yes, it was strange the first time I went to the site, it brought up what I think was a cloudflare screen, where it had me solve a captcha before I went to the actual site. Hasn't happened since so not sure if it'd be an issue.

Do you know if there's a way with the command line to tell retroarch to download one of it's cores? Similar to the non-steam version where you can use the GUI? As a way to automate that download step. If not, it could be downloaded if we wanted to have retroarch as a option for certain games and we had the paths. Looks like this may be a path to the cores: https://buildbot.libretro.com/nightly/linux/x86_64/latest/

For the non-steam version, it looks like this would be a good path: https://buildbot.libretro.com/stable/1.9.10/linux/x86_64/RetroArch.7z

Then would need to provide 7z (have done that for others in the past) and extract the appimage.

**Comment by JoshuaFern** [comment]
Ah Cloudflare, that would do it.

I don't see a way to automate downloading via a cli parameter. Checking the default config of retroarch, it just fetches the cores from `http://buildbot.libretro.com/nightly/linux/x86_64/latest/`

The cores can be in `~/.config/retroarch/cores` or the `./cores` folder in the application directory I believe. The current AppImage based implementation on Steam places DLC cores in `RetroArch-Linux-x86_64-Nightly.AppImage.config/retroarch/cores/genesis_plus_gx_libretro.so`, but I assume that will be moved to the normal `./cores` directory when the transition happens.

**Comment by d10sfan** [comment]
@JoshuaFern It looks like for the stable release, they have a zip of all cores, which ends up being about 1 gb of data unzipped. Do you know what the stable version uses, or is that the one?

It's possible to use the nightly instead, since it looks like they are using using whatever is in the nightly latest to download the cores. If there was an issue at some point, there may have to be some manual steps for someone to download the latest nightly (deleting the cached nightly would do it, if we set the download path to the latest nightly download)

**Comment by d10sfan** [comment]
@JoshuaFern Also, if you could compile a list of cores that would use useful for steam games (what games they apply to and the name of the core), and any information that would be helpful as to launching them.

**Comment by JoshuaFern** [comment]
> It looks like for the stable release, they have a zip of all cores, which ends up being about 1 gb of data unzipped. Do you know what the stable version uses, or is that the one?

Retroarch doesn't install all the cores in one-go like that, the built in downloader fetches cores from `http://buildbot.libretro.com/nightly/linux/x86_64/latest/`. I realize these cores are in the nightly branch, but this is what the stable version of Retroarch downloads. Rather than downloading that entire archive, I think lux should only download the single core being used if it's missing. Then the user can add or update any additional cores they choose from the built-in downloader.

> It's possible to use the nightly instead, since it looks like they are using using whatever is in the nightly latest to download the cores.

Yep.

> Also, if you could compile a list of cores that would use useful for steam games (what games they apply to and the name of the core), and any information that would be helpful as to launching them.

I'll see if I can compile a list.

**Comment by JoshuaFern** [comment]
### Cave Story (NXEngine)
Cave Story https://steamdb.info/app/200900/
```
# This one requires some data.
wget https://buildbot.libretro.com/assets/cores/Cave%20Story/Cave%20Story%20%28En%29.zip && unzip *.zip
retroarch -L ~/.local/share/Steam/steamapps/common/retroarch/cores/nxengine_libretro.so ./Cave\ Story\ \(en\)/Doukutsu.exe
```

### Doom (PrBoom)
The Ultimate DOOM https://steamdb.info/app/2280/
```
retroarch -L ~/.local/share/Steam/steamapps/common/retroarch/cores/prboom_libretro.so base/DOOM.WAD
```
Final DOOM https://steamdb.info/app/2290/
```
retroarch -L ~/.local/share/Steam/steamapps/common/retroarch/cores/prboom_libretro.so base/TNT.WAD
retroarch -L ~/.local/share/Steam/steamapps/common/retroarch/cores/prboom_libretro.so base/PLUTONIA.WAD
```
DOOM II: Hell on Earth https://steamdb.info/app/2300/
```
retroarch -L ~/.local/share/Steam/steamapps/common/retroarch/cores/prboom_libretro.so base/DOOM2.WAD
```

### Doom 3 (Boom3)
DOOM 3 https://steamdb.info/app/9050/
```
retroarch -L ~/.local/share/Steam/steamapps/common/retroarch/cores/boom3_libretro.so .
```

### Doom 3 Resurrection of Evil (Boom3-ex)
DOOM 3: Resurrection of Evil https://steamdb.info/app/9070/
```
retroarch -L ~/.local/share/Steam/steamapps/common/retroarch/cores/boom3_xp_libretro.so .
```

### DOS (DOSBox-core, DOSBox-Pure, DOSBox-SVN)
You can either load an exe/com/bat file or a *.conf file. Hundreds of games for this but here's an example for DOOM:

The Ultimate DOOM https://steamdb.info/app/2280/
```
retroarch -L ~/.local/share/Steam/steamapps/common/retroarch/cores/dosbox_pure_libretro.so ./ultimate\ +\ mouse.bat
```

### Pico8 (Retro8)
miniStrike https://steamdb.info/app/1354460/
Sakura Stars https://steamdb.info/app/1282710/
Slime Fantasy: the search for the lost sword https://steamdb.info/app/1472810/

I don't own any of these games but they're distributed via PNG files. Launch with something like:
`retroarch -L ~/.local/share/Steam/steamapps/common/retroarch/cores/retro8_libretro.so game.png`

### Quake 1 (TyrQuake)
Quake https://steamdb.info/app/2310
```
# The engine doesn't recognize the capital in the folder name, let's copy and rename it.
cp -r Id1 id1
retroarch -L ~/.local/share/Steam/steamapps/common/retroarch/cores/tyrquake_libretro.so ./
```

There's undoubtedly many more, but this is a start.

**Comment by d10sfan** [comment]
Thanks for the list, looks like a good starting point.

Note for future reference that the script itself should not use unzip, and rely on the client's decode_as_zip function to extract the library.

**Comment by JoshuaFern** [comment]
I sometimes wonder why use Retroarch on Steam instead of just the standalone version, here's some of my thoughts:

Cons:
* No built in core downloader.

Pros:
* Ability to use Remote Play Together
* Steam Cloud Features: Saves, Screenshots, Game-Time Tracking
* Officially supported: I think the only other officially supported version is the flatpak version.
* And maybe, in the future, the ability to easily play your bought games on Steam in Retroarch using Luxtorpeda.

**Comment by d10sfan** [comment]
@JoshuaFern 

Ok, it sounds like what you're saying is leave the RetroArch application as is, and then for games where there are retroarch cores for, create scripts for launching the games through the native RetroArch from the store? And then either point people in the right direction to download the cores, or use the ones provided by steam where possible?

I think that sounds pretty doable. Would what you mentioned above for the games above still apply?

**Comment by ToughGuyKunio** [comment]
If we make scripts, they should, if possible, be universal so that games on Steam that contain ROMs could work with RetroArch and other emulators such as 3dSen.

- 3dSen: https://steamdb.info/app/1147940/
- 3dSen VR: https://steamdb.info/app/954280/

**Comment by JoshuaFern** [comment]
> Ok, it sounds like what you're saying is leave the RetroArch application as is, and then for games where there are retroarch cores for, create scripts for launching the games through the native RetroArch from the store? And then either point people in the right direction to download the cores, or use the ones provided by steam where possible?

Yeah absolutely, just use the app detection concept that source engine already uses to detect RetroArch itself. Then launch the core or show an error if the core's file is missing.

> I think that sounds pretty doable. Would what you mentioned above for the games above still apply?

Yes, although those cores are not in the Steam version of Retroarch yet. Here's a list of games I made and the cores they should work with: https://steamcommunity.com/sharedfiles/filedetails/?id=2678538760

**Comment by d10sfan** [comment]
@JoshuaFern @Jpxe 

I added retroarch support in this commit: https://github.com/luxtorpeda-dev/packages/commit/8bba438eb715d42cf3f64f5720d7689cd5fe98b3

I tested it with Super 3-D Noah's Ark, and Viper. Thanks for sponsors for providing funds for the games.

The way it works is there are default options for snes9x, PCSX ReARMed, and "Other". The first two will try to automatically load the game using the core and looking for a particular file extension, with the ability to override the extension and relative path with command line arguments in the steam launch options (see the other documentation). Other provides a way where you can provide the core, extension type, and optionally the relative path for any core.
