### ISSUE TITLE
Terminal Velocity / terminal-recall

### ISSUE THREAD

**Issue by ToughGuyKunio** [luxtorpeda-dev/packages#474]
### Project Link

https://github.com/jtrfp/terminal-recall

### Project License

Apache 2.0

### Steam App Ids

- https://steamdb.info/app/358370/

### Additional Context

Also supports Fury3 which is not available on Steam. I don't own Terminal Velocity myself yet, I'll get it on the next sale and test it out if needed. Nightly builds: https://sourceforge.net/projects/terminal-recall/files/

**Comment by d10sfan** [comment]
Thanks for the request, currently don't own the game, so would need that to proceed.

**Comment by ToughGuyKunio** [comment]
Can I send you a key?

**Comment by ToughGuyKunio** [comment]
I think I need the numbers after, you can add me at: Jpx#0937

**Comment by d10sfan** [comment]
@ToughGuyKunio Thanks for the game. I've added this in https://github.com/luxtorpeda-dev/packages/pull/504

If you use the luxtorpeda (runtime) version and launch the game, it'll download openjdk and this engine and then run the game. You'll need to pick where the game asset files in the configuration menu, as I didn't see a way to give that information in the command line. But it seems to work pretty well.

**Comment by ToughGuyKunio** [comment]
Works great, thank you!
