### ISSUE TITLE
RCT2 does not work upon installation

### ISSUE THREAD

**Issue by spacecowgirl314** [luxtorpeda-dev/packages#503]
### Game

RCT2

### Engine

OpenRCT2

### Linux Distribution

Garuda

### Luxtorpeda Version

commit fdbdf737b92fa56f3ba36c6e6ba3e1ab72915756

### Bug description

Using the luxtorpeda-git AUR package and I installed RCT2. It tells me it can't find Data/g1.dat however it is there. I had to rename the "data" folder to uppercase "Data" for it to work otherwise it would continually ask me for the folder of the game. Once I rename it, it works fine on Luxtorpeda (Runtime). I suspect this may be a bug on OpenRCT's side as I looked and it appears to be hardcoded this way (https://github.com/OpenRCT2/OpenRCT2/blob/77141f57b0a91aa4321bc6908027168fe883a784/src/openrct2/cmdline/RootCommands.cpp#L368) even though Steam installs the folder as lowercase data out of the box for me.

### Steps To Reproduce

Use Luxtorpeda (Runtime). Install RCT2. Press Play.

### Expected Behavior

Game plays.

### Additional Context

I'm using btrfs as my filesystem. Not sure if this is a contributing factor. Edit: It may very well be. I can have both a "data" and a "Data" folder so it seems it's case-sensitive. After renaming "data" to "Data" and opening the game, a new "data" folder can be seen containing a few game files after closing the game. Very odd.

**Comment by spacecowgirl314** [comment]
Addendum: I'm using btrfs as my filesystem. Not sure if this is a contributing factor.

**Comment by d10sfan** [comment]
@spacecowgirl314 

Interesting, is the file system you're using case sensitive? The game is supposed to download a "Data" directory, from what steamdb is saying and what I see when I play the game myself- https://steamdb.info/depot/285331/

The engine will download a lowercase "data" directory which is what openrct2 uses for its own data. It expects a "Data" directory that would contain the original game assets. So it would make sense for there to be a "Data" directory and a "data" directory.

I may be able to do a workaround, where if "Data" does not exist, to do a symlink from "data" to "Data". This could be done during the normal startup sequence automatically.

After you run the game, does the "Data" directory have both g1.dat and g2.dat. From my understand, g1 is the original game asset, and g2 is the openrct2 asset. Mostly just curious if the engine is ok with them being in the same directory.

**Comment by spacecowgirl314** [comment]
g2.dat is not present in "Data" just "data". Here's tree results excluding file names. The "data" folder and it's entire contents show up after every launch.
`.
├── data
│   ├── language
│   ├── object
│   │   ├── official
│   │   │   ├── footpath_item
│   │   │   ├── ride
│   │   │   ├── scenery_group
│   │   │   ├── scenery_small
│   │   │   ├── station
│   │   │   ├── wall
│   │   │   └── water
│   │   ├── rct1
│   │   │   └── terrain_edge
│   │   ├── rct2
│   │   │   ├── footpath
│   │   │   ├── footpath_banner
│   │   │   ├── footpath_item
│   │   │   ├── park_entrance
│   │   │   ├── ride
│   │   │   ├── scenery_group
│   │   │   ├── scenery_large
│   │   │   ├── scenery_small
│   │   │   ├── scenery_wall
│   │   │   ├── station
│   │   │   ├── terrain_edge
│   │   │   ├── terrain_surface
│   │   │   └── water
│   │   ├── rct2tt
│   │   │   ├── footpath
│   │   │   ├── footpath_item
│   │   │   ├── park_entrance
│   │   │   ├── ride
│   │   │   ├── scenery_group
│   │   │   ├── scenery_large
│   │   │   ├── scenery_small
│   │   │   └── scenery_wall
│   │   └── rct2ww
│   │       ├── park_entrance
│   │       ├── ride
│   │       ├── scenery_group
│   │       ├── scenery_large
│   │       ├── scenery_small
│   │       └── scenery_wall
│   ├── sequence
│   └── shaders
├── Data
│   ├── language
│   ├── object
│   │   ├── official
│   │   │   ├── footpath_item
│   │   │   ├── ride
│   │   │   ├── scenery_group
│   │   │   ├── scenery_small
│   │   │   ├── station
│   │   │   ├── wall
│   │   │   └── water
│   │   ├── rct1
│   │   │   └── terrain_edge
│   │   ├── rct2
│   │   │   ├── footpath
│   │   │   ├── footpath_banner
│   │   │   ├── footpath_item
│   │   │   ├── park_entrance
│   │   │   ├── ride
│   │   │   ├── scenery_group
│   │   │   ├── scenery_large
│   │   │   ├── scenery_small
│   │   │   ├── scenery_wall
│   │   │   ├── station
│   │   │   ├── terrain_edge
│   │   │   ├── terrain_surface
│   │   │   └── water
│   │   ├── rct2tt
│   │   │   ├── footpath
│   │   │   ├── footpath_item
│   │   │   ├── park_entrance
│   │   │   ├── ride
│   │   │   ├── scenery_group
│   │   │   ├── scenery_large
│   │   │   ├── scenery_small
│   │   │   └── scenery_wall
│   │   └── rct2ww
│   │       ├── park_entrance
│   │       ├── ride
│   │       ├── scenery_group
│   │       ├── scenery_large
│   │       ├── scenery_small
│   │       └── scenery_wall
│   ├── sequence
│   └── shaders
├── Install
│   ├── Autorun
│   │   └── Art
│   ├── DirectX
│   ├── Manual
│   ├── RCT3_PREVIEW
│   │   └── RCT3 Wallpapers
│   └── Scenarios
├── Landscapes
├── lib
├── license
├── ObjData
├── Saved Games
├── Scenarios
└── Tracks

105 directories`

**Comment by d10sfan** [comment]
@spacecowgirl314 I pushed a new change (https://github.com/luxtorpeda-dev/packages/commit/ca2ca449151d049d3215d33234e3cb9b9c4aa114) to the runtime version that checks if the "Data" directory does not exist, and if so creates a link from "data" to "Data". I tested it by manually renaming my "Data" directory to "data" and it seemed to work well.

The next time you run the game once the build finishes (should be about 20 minutes from this commit) it should have this change, let me know if that fixes it.

**Comment by d10sfan** [comment]
There's a dependency issue where one of the servers is down, so I'll update this ticket once the build actually finishes.

**Comment by d10sfan** [comment]
@spacecowgirl314 

The build is complete, let me know if that fixes your issue.

**Comment by spacecowgirl314** [comment]
Just reinstalled RCT2. It doesn't work. It still asks me for the installation directory.

**Comment by d10sfan** [comment]
@spacecowgirl314 Ah I forgot to mention, inside the game directory there is a "ready" file. Try removing that and then re-running the game. If that does not work, please provide a log, where you run steam inside a Terminal window and then send the output here.
