### ISSUE TITLE
AvP crash when language is not english

### ISSUE THREAD

**Issue by cyberconan** [luxtorpeda-dev/packages#514]
### Game

Aliens versus Predator

### Engine

AvP

### Linux Distribution

Archlinux

### Luxtorpeda Version

luxtorpeda-git-37.0.0.r292.5cf7383-1

### Bug description

Hi!!
In first place, thank you so much, your work is incredible and was a great discover for me.
There is a minor issue with AvP, but neuromancer git is archived and I don't know if he will return:
https://github.com/neuromancer/avp/issues/8
This issue happens only in no-english AvP versions like german (issue reported), spanish (confirmed by me) and maybe in french or italian, I think the problem is with special characters in those languages.
There is a dirty-fix than is comment this Render line in avp_menus.c:

```
`static void RenderHelpString()
{
	AVPMENU_ELEMENT *elementPtr = &AvPMenus.MenuElements[AvPMenus.CurrentlySelectedElement];

	if(elementPtr->HelpString!=TEXTSTRING_BLANK && AvPMenus.MenusState != MENUSSTATE_INGAMEMENUS)
	{
		RECT area;
		//draw the attached string at the bottom of the screen

		area.left=MENU_LEFTXEDGE;
		area.right=MENU_RIGHTXEDGE;
		area.top=420;
		area.bottom=ScreenDescriptorBlock.SDB_Height;

		//RenderSmallFontString_Wrapped(GetTextString(elementPtr->HelpString),&area,BRIGHTNESS_OF_HIGHLIGHTED_ELEMENT,0,0);
		
	}
}`
```

Is possible than you'll send a different avp compiled file with this fix to steam clients than no have english language configured for this game in Steam?
Thank you and go ahead with all project!! Is incredible!!  

### Steps To Reproduce

Change AvP language in Steam to spanish or german.
Launch game and move to the third menu section, it have a special character in the help section.
Crash!

### Expected Behavior

No crash :)

**Comment by d10sfan** [comment]
@cyberconan 

Thanks for the report. What does commenting out that line do visually, if anything? Mainly curious for the english version.

**Comment by cyberconan** [comment]
Only hides the bottom message in main main, better this than a crash :)
![Screenshot_20210929_193553](https://user-images.githubusercontent.com/1497109/135320929-32dcf9f2-dec0-423b-95ed-374ae9dfd5a2.png)

**Comment by d10sfan** [comment]
@cyberconan Ah ok, thank you. I'm working on creating a build for testing now. I'll update with my findings soon.

**Comment by cyberconan** [comment]
Wonderful @d10sfan ! Thanks!!
