### ISSUE TITLE
(SH-2006) Use of legacy backtick

### ISSUE THREAD

**Issue by d10sfan** [luxtorpeda-dev/packages#517]
## Description
Consider using the `$(...)` notation instead. Backtick command substitution `\`...\`` is legacy syntax with several issues. * It has a series of undefined behaviors related to quoting in POSIX.

## Occurrences
There are 11 occurrences of this issue in the repository.

See all occurrences on DeepSource &rarr; [deepsource.io/gh/luxtorpeda-dev/packages/issue/SH-2006/occurrences/](https://deepsource.io/gh/luxtorpeda-dev/packages/issue/SH-2006/occurrences/)

**Comment by OBITORASU** [comment]
Seems like a quick fix going through the logs can I work on this?

**Comment by d10sfan** [comment]
@OBITORASU Sure, that's fine, thanks! As part of that, test what engines you can when those changes has been done. Then feel free to create a pull request and I'll look it over.

**Comment by OBITORASU** [comment]
So that would mean I need around 5 PRs each for 5 of the affected engines right?

**Comment by d10sfan** [comment]
> So that would mean I need around 5 PRs each for 5 of the affected engines right?

Yes, that's right.

**Comment by OBITORASU** [comment]
Did the testing as per the guidelines on `ja2-stracciatella` engine locally since it was the easiest to handle and was probably the least affected. Both the commands from the testing guide seem to have exited with exit code 0 inside the docker container so thought might as well drop the PR if the local tests pass.

**Comment by d10sfan** [comment]
@OBITORASU Thanks for working on these items.
