### ISSUE TITLE
Putt-Putt and Fatty Bear's Activity Pack: Not detected.

### ISSUE THREAD

**Issue by JoshuaFern** [luxtorpeda-dev/packages#544]
### Game

Putt-Putt® and Fatty Bear's Activity Pack 294720

### Engine

ScummVM

### Linux Distribution

Flatpak/NixOS

### Luxtorpeda Version

43

### Bug description

The game isn't being detected and doesn't show up in the ScummVM menu as a selectable title.

### Steps To Reproduce

Run the game.

### Expected Behavior

The game should have been detected and shown in the menu.

### Additional Context

This is the only Humongous Entertainment game I own, if we're having problems with this one it may affect the others as well. See: https://www.scummvm.org/compatibility/

### Relevant log output

```shell
dropping: "/run/user/1000/luxtorpeda/294720.pid"
sending close to run context thread
run: "./scum/run-scummvm.sh" with args: [] ["--no-console", "-c", "scummvm-ppafbactivitypack.ini", "activ
/bin/bash: /usr/lib/pressure-vessel/overrides/lib/x86_64-linux-gnu/libtinfo.so.6: no version information
pid 94518 != 94517, skipping destruction (fork without exec?)
Added 0 games
WARNING: SDL mixer output buffer size: 512 differs from desired: 1024!
Installing breakpad exception handler for appid(gameoverlayui)/version(20211029022127)
Installing breakpad exception handler for appid(gameoverlayui)/version(1.0)
Installing breakpad exception handler for appid(gameoverlayui)/version(1.0)
Installing breakpad exception handler for appid(gameoverlayui)/version(1.0)
```

**Comment by d10sfan** [comment]
@JoshuaFern 

Issue was that scummvm was installed inside a "ScummVM_Windows" directory and so was unable to find the actual game path, needed to go up two levels instead of one.

I've pushed up a fix that detects if the level above is that and updates the path accordingly: https://github.com/luxtorpeda-dev/packages/commit/e9c7dcd650a1303046e72ed48db4019d234c4e70

**Comment by JoshuaFern** [comment]
Thanks, seems to be working now.
