### ISSUE TITLE
OpenKrush for Krush Kill 'N Destroy 1 / 2

### ISSUE THREAD

**Issue by rea987** [luxtorpeda-dev/packages#545]
### Project Link

https://github.com/IceReaper/OpenKrush

### Project License

GPLv3

### Steam App Ids

- https://steamdb.info/app/1292170/
- https://steamdb.info/app/1292180/

### Additional Context

The engine is derived from OpenRA and requires original game data.

**Comment by d10sfan** [comment]
Engine currently only detects in ~/.steam. Once that has been updated to support multiple libraries, I'll come back to this.

**Comment by d10sfan** [comment]
Closing for now, will re-open once this has changed.
