### ISSUE TITLE
Unreal Gold installation fails on a "not found" error

### ISSUE THREAD

**Issue by AsciiWolf** [luxtorpeda-dev/packages#550]
### Game

Unreal Gold

### Engine

Proprietary Engine

### Linux Distribution

Fedora 35 (with Flatpak Steam on Wayland session)

### Luxtorpeda Version

Pre-release 44.0

### Bug description

This happens when trying to install Unreal using Luxtorpeda:

![not-found](https://user-images.githubusercontent.com/2339930/139542465-bb0c30c1-522d-49b1-af85-23b31dead66f.png)

Unfortunately, there is nothing useful in log.

### Steps To Reproduce

1. Install Unreal Gold.
2. Try to launch it using Luxtorpeda.

### Expected Behavior

Game is installed and can be played without any issues.

**Comment by d10sfan** [comment]
This one requires manual steps to run. Did you see the readme the error talks about?

**Comment by d10sfan** [comment]
Let me know if it does not work after the steps are run. The reason for the manual steps is that the installer is required due to licensing.

**Comment by AsciiWolf** [comment]
Oops, sorry. It does indeed work after the steps are run. :-)
