### ISSUE TITLE
Duke Nukem Megaton Edition Symlink addons to gameroot

### ISSUE THREAD

**Issue by VortexAcherontic** [luxtorpeda-dev/packages#560]
### Feature Request

Hey there,

 I was testing out Luxtorpeda + raze / eduke32 on Duke Nukem 3D: Megaton Edition and found that I couldn't play the Addons: Life's a Beach, Nuclear Winter and Duke it out in D.C.

After referring to raze and eduke32 installation guides I quickly figured out that both engines are expecting the addon files and maps to be in the same directory as the engine itself.

All addons are located at gameroot/addons/[dc/nw/vacation].

Providing eduke32 and raze with symlinks to all files in those folders solved the issue.

### Solution

What I'd like to ask if it would be possible to automate this process.
Therfore that Luxtorpeda checks if the folder addons/[dc/nw/vacation] do exist and symlink all files to the gameroot directory?

Since both engines seem not to look up these folders on their own.

### Additional Context

I apologize if this would be more appropriate for the actual package and not the luxtorpeda client.

Kind regards,
Vortex :)

**Comment by d10sfan** [comment]
@VortexAcherontic 

Thanks for the issue report, and this would be a package issue, so I've moved it over here.

Sadly, I don't own this game and looks like it isn't for sale anymore. Could you describe the symlink you're doing? As in what the folder paths would be and where you're trying to put them?

These scripts are the ones that run eduke32 and raze:

https://github.com/luxtorpeda-dev/packages/blob/master/engines/raze/assets/run-raze.sh
https://github.com/luxtorpeda-dev/packages/blob/master/engines/eduke32/assets/run-eduke32.sh

So those would be the places to change, if you can either send me some commands for the symlink or create a pull request for each one individually, then that should help.

Thanks

**Comment by VortexAcherontic** [comment]
Hey there currently I am debuging this issue as I noticed that the packages should evaluate the star game by a number. I suspect the nubers are wrong or not set at all and raze and eduke32 scripts do default to `LD_LIBRARY_PATH="lib:$LD_LIBRARY_PATH" ./raze` or `LD_LIBRARY_PATH="lib:$LD_LIBRARY_PATH" ./eduke32`

How can I tell luxtorpeda to not fetch the package script from `https://github.com/luxtorpeda-dev/packages/releases/download/raze-24/` but to use my modified local shell script?

**Comment by d10sfan** [comment]
@VortexAcherontic 

There should be a ~/.cache/luxtorpeda directory with a eduk32 and raze folders. If you open the .xz file that it is using, then you can edit the files there. When you do this, the client will extract the files you changed.

**Comment by VortexAcherontic** [comment]
@d10sfan Found the issue, fixed the issue and created a PR #561 :)

**Comment by d10sfan** [comment]
Closing this to continue discussion in pull request
