### ISSUE TITLE
NW.js for RPG Maker MV games

### ISSUE THREAD

**Issue by HenrikHolst** [luxtorpeda-dev/packages#563]
### Project Link

https://nwjs.io/

### Project License

MIT

### Steam App Ids

https://steamdb.info/app/457570/

This was just the game that I tested out this method with but there are probably hundreds of games om Steam built with RPG Maker MV, will do a more thorough search later if inclusion of this "engine" looks viable.

### Additional Context

Games created by RPG Maker MV are just wrappers around nw.js/chrome but of course exported mostly for Windows only...  The protondb reports for those kinds of games often show a completely broken game, see e.g https://www.protondb.com/app/457570 and can be made to run with only a very old version of Proton once libglesv2.dll is disabled and the result is a huge performance hit.

However, one can simply download NW.js built for Linux, say https://dl.nwjs.io/v0.58.0/nwjs-v0.58.0-linux-x64.tar.gz extract the contents over the steam game folder, "chmod +x nw" and then just execute nw and the game should run natively (Camp Sunshine which is the first I tried this method with worked straight away with this method).

**Comment by d10sfan** [comment]
@HenrikHolst 

It looks like for this one the packaged version will not work, since we are running inside the steam runtime (not your host libraries) and it does not have cups  support, which nwjs has a dependency on.

I will look and see if there's a way to compile it without that dependency.

**Comment by HenrikHolst** [comment]
Yeah I can see how that might mess things up. In any case if you need me to gift you the game to test it out just let me know.

**Comment by d10sfan** [comment]
@HenrikHolst I've added 0.54 for now, which works fine with the cups in steam runtime. https://github.com/luxtorpeda-dev/packages/commit/1f34faebc68502925e3693dc7add818c2f5bc2b8

let me know if you run into any issues.

**Comment by ToughGuyKunio** [comment]
@HenrikHolst did you find any other games that worked with this? I'm compiling a list of working games

**Comment by HenrikHolst** [comment]
> @HenrikHolst did you find any other games that worked with this? I'm compiling a list of working games

Haven't had time to build and test yet, but there should be tons of RPG Maker MV games out there.

**Comment by HenrikHolst** [comment]
> @HenrikHolst I've added 0.54 for now, which works fine with the cups in steam runtime. [1f34fae](https://github.com/luxtorpeda-dev/packages/commit/1f34faebc68502925e3693dc7add818c2f5bc2b8)
> 
> let me know if you run into any issues.

Just tested it and it worked flawless! Huge thanks for this.

**Comment by Revival8697** [comment]
@d10sfan May I know why you decided to use v0.54 in particular? Or you just grab whatever was the latest at the time?

**Comment by d10sfan** [comment]
Not sure what you're asking here. Are you saying the version is too new?

**Comment by Revival8697** [comment]
> Not sure what you're asking here. Are you saying the version is too new?

I'm asking if there is any reason v0.54 was used instead of anything else.

**Comment by d10sfan** [comment]
The reason at the time was it was the newest version of nw.js that did not have cups issues. But I don't quite understand what you're really asking, in terms of what you're wanting to see different?
