### ISSUE TITLE
Ruffle for Flash games

### ISSUE THREAD

**Issue by ToughGuyKunio** [luxtorpeda-dev/packages#571]
### Project Link

https://github.com/ruffle-rs/ruffle

### Project License

Apache 2.0 or MIT

### Steam App Ids

- https://steamdb.info/app/214790/
- https://steamdb.info/app/92/
- https://steamdb.info/app/1580970/
- https://steamdb.info/app/40720/

### Additional Context

There's a huge amount of Flash games on Steam. 

I've tested a few and got some of them to work in Ruffle.
- The basement collection: Meat Boy works out-of-the-box, just run `ruffle meatboy.swf`. Also: meatboymappack.swf, Welting.swf, Welting2.swf, Dumpling.swf and Clubbe The Seal.swf works out-of-the-box. aether and tri-archnid doesn't work yet.
- Codename Gordon: Needs to be extracted from exe first, then just run `00000003.swf`. After that it worked fine from what I've played except for a bug when you pick up the gun, but it's nothing major. I believe this one doesn't work with Proton, so would be great to have Luxtorpeda support.
- Samarost 1: freeware that can be downloaded from https://archive.org/download/samorost-1/samorost-1.swf and works in Ruffle. Steam ver doesn't work
- Samarost 2: needs to be extracted from exe in "Samorost 2 Original (2005)" folder first, then just run `ruffle 00000003.swf`. Seems to work fine after that.

**How to handle SWF bundled in EXE**
There's several options:
- Download the original swf file
- extract the swf from the exe: https://bluemaxima.org/flashpoint/datahub/Extracting_Flash_Games#Extract_SWFs_from_EXEs

I've tested both [exe2swf](https://sourceforge.net/projects/swf2exe/files/swf2exe/swf2exe_src_0.1/) (with wine) and [JPEXS Flash Decompiler](https://github.com/jindrapetrik/jpexs-decompiler) (native) and they both worked with Steam games.

**Potential flash games on steam:**
- https://www.pcgamingwiki.com/wiki/Engine:Flash
- https://www.pcgamingwiki.com/wiki/The_big_list_of_DRM-free_games_on_Steam#Flash_.26_AIR
- https://www.newgrounds.com/bbs/topic/1376206
- https://www.reddit.com/r/gamingsuggestions/comments/cj7v0v/flash_games_that_are_remade_and_available_on_steam/
- https://store.steampowered.com/curator/9018518-dna%2527s-list-of-old-flash-games/

**Comment by JoshuaFern** [comment]
<details>
  <summary>A long list of AppIDs that are probably Flash games:</summary>

https://steamdb.info/app/113200/
https://steamdb.info/app/668630/
https://steamdb.info/app/1089980/
https://steamdb.info/app/363970/
https://steamdb.info/app/248860/
https://steamdb.info/app/293260/
https://steamdb.info/app/359310/
https://steamdb.info/app/629910/
https://steamdb.info/app/245550/
https://steamdb.info/app/257170/
https://steamdb.info/app/317820/
https://steamdb.info/app/335000/
https://steamdb.info/app/389570/
https://steamdb.info/app/434170/
https://steamdb.info/app/610080/
https://steamdb.info/app/275200/
https://steamdb.info/app/207690/
https://steamdb.info/app/269310/
https://steamdb.info/app/909080/
https://steamdb.info/app/397460/
https://steamdb.info/app/711660/
https://steamdb.info/app/532110/
https://steamdb.info/app/744190/
https://steamdb.info/app/233470/
https://steamdb.info/app/331670/
https://steamdb.info/app/505640/
https://steamdb.info/app/94300/
https://steamdb.info/app/218410/
https://steamdb.info/app/263980/
https://steamdb.info/app/1145960/
https://steamdb.info/app/740260/
https://steamdb.info/app/435120/
https://steamdb.info/app/495990/
https://steamdb.info/app/209830/
https://steamdb.info/app/645760/
https://steamdb.info/app/669580/
https://steamdb.info/app/284390/
https://steamdb.info/app/295590/
https://steamdb.info/app/393190/
https://steamdb.info/app/331440/
https://steamdb.info/app/1281800/
https://steamdb.info/app/466910/
https://steamdb.info/app/402840/
https://steamdb.info/app/346250/
https://steamdb.info/app/1292940/
https://steamdb.info/app/346810/
https://steamdb.info/app/205020/
https://steamdb.info/app/234900/
https://steamdb.info/app/393530/
https://steamdb.info/app/668210/
https://steamdb.info/app/469720/
https://steamdb.info/app/703950/
https://steamdb.info/app/314240/
https://steamdb.info/app/490220/
https://steamdb.info/app/533950/
https://steamdb.info/app/562010/
https://steamdb.info/app/435060/
https://steamdb.info/app/462240/
https://steamdb.info/app/589670/
https://steamdb.info/app/1615100/
https://steamdb.info/app/270630/
https://steamdb.info/app/353360/
https://steamdb.info/app/269490/
https://steamdb.info/app/220860/
https://steamdb.info/app/350480/
https://steamdb.info/app/248330/
https://steamdb.info/app/465710/
https://steamdb.info/app/272600/
https://steamdb.info/app/251430/
https://steamdb.info/app/307640/
https://steamdb.info/app/325090/
https://steamdb.info/app/493370/
https://steamdb.info/app/214790/
https://steamdb.info/app/522030/
https://steamdb.info/app/290970/
https://steamdb.info/app/1055430/
https://steamdb.info/app/319560/
https://steamdb.info/app/629960/
https://steamdb.info/app/502550/
https://steamdb.info/app/365350/
https://steamdb.info/app/272040/
https://steamdb.info/app/207080/
https://steamdb.info/app/416450/
https://steamdb.info/app/573170/
https://steamdb.info/app/344860/
https://steamdb.info/app/264730/
https://steamdb.info/app/836480/
https://steamdb.info/app/252130/
https://steamdb.info/app/369290/
https://steamdb.info/app/359960/
https://steamdb.info/app/665330/
https://steamdb.info/app/408120/
https://steamdb.info/app/290040/
https://steamdb.info/app/322080/
https://steamdb.info/app/339130/
https://steamdb.info/app/283080/
https://steamdb.info/app/1120700/
https://steamdb.info/app/863420/
https://steamdb.info/app/360730/
https://steamdb.info/app/524970/
https://steamdb.info/app/211360/
https://steamdb.info/app/265330/
https://steamdb.info/app/345090/
https://steamdb.info/app/359400/
https://steamdb.info/app/436160/
https://steamdb.info/app/461810/
https://steamdb.info/app/295750/
https://steamdb.info/app/288290/
https://steamdb.info/app/504400/
https://steamdb.info/app/1516240/
https://steamdb.info/app/1019250/
https://steamdb.info/app/420070/
https://steamdb.info/app/311700/
https://steamdb.info/app/503210/
https://steamdb.info/app/882940/
https://steamdb.info/app/418040/
https://steamdb.info/app/967330/
https://steamdb.info/app/797430/
https://steamdb.info/app/295850/
https://steamdb.info/app/328730/
https://steamdb.info/app/1407420/
https://steamdb.info/app/209950/
https://steamdb.info/app/388620/
https://steamdb.info/app/329020/
https://steamdb.info/app/233410/
https://steamdb.info/app/379530/
https://steamdb.info/app/285840/
https://steamdb.info/app/391580/
https://steamdb.info/app/293880/
https://steamdb.info/app/1073810/
https://steamdb.info/app/328500/
https://steamdb.info/app/345460/
https://steamdb.info/app/37600/
https://steamdb.info/app/98100/
https://steamdb.info/app/248270/
https://steamdb.info/app/250030/
https://steamdb.info/app/846670/
https://steamdb.info/app/649600/
https://steamdb.info/app/422910/
https://steamdb.info/app/342100/
https://steamdb.info/app/227280/
https://steamdb.info/app/476880/
https://steamdb.info/app/1169100/
https://steamdb.info/app/686440/
https://steamdb.info/app/635790/
https://steamdb.info/app/278440/
https://steamdb.info/app/661470/
https://steamdb.info/app/363500/
https://steamdb.info/app/230150/
https://steamdb.info/app/562670/
https://steamdb.info/app/105100/
https://steamdb.info/app/460250/
https://steamdb.info/app/314630/
https://steamdb.info/app/386600/
https://steamdb.info/app/1336250/
https://steamdb.info/app/545690/
https://steamdb.info/app/1302590/
https://steamdb.info/app/487700/
https://steamdb.info/app/337630/
https://steamdb.info/app/387850/
https://steamdb.info/app/230980/
https://steamdb.info/app/347950/
https://steamdb.info/app/303940/
https://steamdb.info/app/35600/
https://steamdb.info/app/422920/
https://steamdb.info/app/342890/
https://steamdb.info/app/770070/
https://steamdb.info/app/270310/
https://steamdb.info/app/235720/
https://steamdb.info/app/286120/
https://steamdb.info/app/436470/
https://steamdb.info/app/924780/
https://steamdb.info/app/402210/
https://steamdb.info/app/279540/
https://steamdb.info/app/397870/
https://steamdb.info/app/561450/
https://steamdb.info/app/300320/
https://steamdb.info/app/389120/
https://steamdb.info/app/356560/
https://steamdb.info/app/1085970/
https://steamdb.info/app/1650290/
https://steamdb.info/app/444480/
https://steamdb.info/app/495780/
https://steamdb.info/app/1521020/
https://steamdb.info/app/315650/
https://steamdb.info/app/304500/
https://steamdb.info/app/447210/
https://steamdb.info/app/354950/
https://steamdb.info/app/1121720/
https://steamdb.info/app/353280/
https://steamdb.info/app/1751480/
https://steamdb.info/app/351240/
https://steamdb.info/app/453990/
https://steamdb.info/app/599060/
https://steamdb.info/app/873960/
https://steamdb.info/app/308440/
https://steamdb.info/app/336680/
https://steamdb.info/app/957440/
https://steamdb.info/app/366670/
https://steamdb.info/app/258070/
https://steamdb.info/app/364450/
https://steamdb.info/app/356550/
https://steamdb.info/app/364960/
https://steamdb.info/app/453880/
https://steamdb.info/app/453820/
https://steamdb.info/app/1018040/
https://steamdb.info/app/1518730/
https://steamdb.info/app/767960/
https://steamdb.info/app/758880/
https://steamdb.info/app/560790/
https://steamdb.info/app/356540/
https://steamdb.info/app/546100/
https://steamdb.info/app/586280/
https://steamdb.info/app/566200/
https://steamdb.info/app/537130/
https://steamdb.info/app/307270/
https://steamdb.info/app/1128910/
https://steamdb.info/app/1054660/
https://steamdb.info/app/1172140/
https://steamdb.info/app/349780/
https://steamdb.info/app/510380/
https://steamdb.info/app/873970/
https://steamdb.info/app/381340/
https://steamdb.info/app/761640/
https://steamdb.info/app/393270/
https://steamdb.info/app/1173230/
https://steamdb.info/app/551930/
https://steamdb.info/app/1429040/
https://steamdb.info/app/323020/
https://steamdb.info/app/280500/
https://steamdb.info/app/709290/
https://steamdb.info/app/571020/
https://steamdb.info/app/857410/
https://steamdb.info/app/692190/
https://steamdb.info/app/586270/
https://steamdb.info/app/551080/
https://steamdb.info/app/846340/
https://steamdb.info/app/571870/
https://steamdb.info/app/579150/
https://steamdb.info/app/879220/
https://steamdb.info/app/1110560/
https://steamdb.info/app/651520/
https://steamdb.info/app/1253180/
https://steamdb.info/app/1720220/
https://steamdb.info/app/1103400/
https://steamdb.info/app/312860/
https://steamdb.info/app/984510/
https://steamdb.info/app/397050/
https://steamdb.info/app/1707040/
https://steamdb.info/app/1707050/
https://steamdb.info/app/1171640/
https://steamdb.info/app/879210/
https://steamdb.info/app/709520/
https://steamdb.info/app/303760/
https://steamdb.info/app/1677040/
https://steamdb.info/app/1621820/
https://steamdb.info/app/1439140/
https://steamdb.info/app/1312560/
https://steamdb.info/app/1185050/
https://steamdb.info/app/1185040/
https://steamdb.info/app/1169550/
https://steamdb.info/app/1142700/
https://steamdb.info/app/942460/
https://steamdb.info/app/704240/
https://steamdb.info/app/597080/
https://steamdb.info/app/534970/
https://steamdb.info/app/432970/
https://steamdb.info/app/401400/
https://steamdb.info/app/395970/
https://steamdb.info/app/379970/
https://steamdb.info/app/374540/
https://steamdb.info/app/363810/
https://steamdb.info/app/355870/
https://steamdb.info/app/344150/
https://steamdb.info/app/337640/
https://steamdb.info/app/318780/
https://steamdb.info/app/303740/
https://steamdb.info/app/270680/
https://steamdb.info/app/246440/
https://steamdb.info/app/235740/
https://steamdb.info/app/212350/
https://steamdb.info/app/70310/
https://steamdb.info/app/823790/

</details>

**Comment by d10sfan** [comment]
@JoshuaFern @ToughGuyKunio 

I added initial support for this, so far Codename Gordon basically works, although with some errors (probably due to ruffle being in progress. Also Samarost 2 seems to load.

It looks like a good chunk of the games are air games, with many of them using action script 3, which isn't supported yet in ruffle.

I won't be able to download a swf from archive automatically, but you can put an swf in the folder and call it "run.swf" and it'll be run by the ruffle script next time you launch through steam.

The script currently will look for the run.swf, then that specific case of S2, or it'll attempt to extract an swf from the launched exe. Help with any additional games that may work, as well as any common threads that may be possible would be appreciated.

**Comment by JoshuaFern** [comment]
I did some testing on my games. As you mentioned, most of the games in that list are actually running Adobe Air, which Ruffle doesn't support. However, even the games that are pure Flash need to be written in ActionScript 1 or 2. AS3 games just show an error followed by a black screen.

Here's a few games that I found to be at least somewhat working:

[Restricted-RPS - Hope Annihilation Arc](https://steamdb.info/app/364960/) 
[Lume](https://steamdb.info/app/105100/)
[The Old Tree](https://steamdb.info/depot/346251/)

**Comment by ToughGuyKunio** [comment]
@d10sfan Nice work and thank you! As for Samarost 2 the swf I extracted with exe2swf mostly works in Ruffle, the one in luxtorpeda extracted with JPEX doesn't seem to want to load past the menu. Maybe there's a difference in the extraction or is there something else going on?

@JoshuaFern @d10sfan I'll be doing some testing of the games I have [in this google docs spreadsheet](https://docs.google.com/spreadsheets/d/1qxMMl1AbEzp-KjbcAk7g22Ms_WzNTsEEZjxYMVEwXEo/edit#gid=1906222584) and documenting if I find something of interest. It's editable for all if someone else finds it useful.

**Comment by d10sfan** [comment]
@ToughGuyKunio That probably means there's an issue with how jpex extracts it or how I'm running it. If you're able to find a working one with jpex, let me know and what the command would be.

**Comment by JoshuaFern** [comment]
> I can't use exe2swf because it's wine-based and I do not want to deal with a need for packaging wine.

What if instead of packaging Wine you just used Proton that Steam already has? I'm pretty sure it can be launched externally to Steam.

**Comment by d10sfan** [comment]
@JoshuaFern @ToughGuyKunio 

True, that could be doable. What is the command that you all have used with exe2swf that works to extract from the exe and run?

**Comment by ToughGuyKunio** [comment]
@d10sfan I found the issue for Samarost 2, there's nothing wrong with jpex, the swf needed to be in the Samarost 2 orginal subfolder, I submitted a pull request but I'm not sure I did it right because I wasn't sure how to test it in Steam and I've never done a pull request before :sweat_smile:

**Comment by d10sfan** [comment]
@ToughGuyKunio 

I merged your change so let me know how that goes.

@JoshuaFern From discord, I changed the path it uses to the path instead of the file. Let me know how that goes.

Closing for now, but feel free to let me know if there's any additional improvements that can be made.

**Comment by ToughGuyKunio** [comment]
@d10sfan everything seems to work okay on my end. Is it possible to call the EGUI from the run script? I'm thinking about making a selection menu for The Basement Collection

**Comment by d10sfan** [comment]
@ToughGuyKunio I think for that one, it'd make the most sense to have a entry in the packagesruntime.json file to show the choices, and then either with the same ruffle script or a new one just for this game, react to different command arguments sent by the choices and load the correct swf. If you can, create a pull request for that as i don't believe I own that game. Let me know if you have any questions about how that would work.
