### ISSUE TITLE
"The Force Engine" for Dark Forces and Outlaws

### ISSUE THREAD

**Issue by NerosTie** [luxtorpeda-dev/packages#574]
### Project Link

https://github.com/luciusDXL/TheForceEngine

### Project License

GPL 2.0

### Steam App Ids

- https://steamdb.info/app/32400/
- https://steamdb.info/app/559620/

**Comment by d10sfan** [comment]
From my understanding this one does not have Linux support yet: https://github.com/luciusDXL/TheForceEngine/issues/89

Has that changed? Would be interested in adding it and I'm subscribed to that ticket but there's nothing I can do unless there's Linux support available.

**Comment by d10sfan** [comment]
Also, this one looks like it's got reverse engineering in it, which has some legal confusion around it: https://github.com/luciusDXL/TheForceEngine#copyright

Because of that, not sure if this one would be a good candidate for supporting.
