### ISSUE TITLE
OpenJKDF2 for Jedi Knight: Dark Forces II

### ISSUE THREAD

**Issue by rea987** [luxtorpeda-dev/packages#576]
### Project Link

https://github.com/shinyquagsire23/OpenJKDF2

### Project License

Unknown

### Steam App Ids

https://steamdb.info/app/32380/

### Additional Context

https://github.com/shinyquagsire23/OpenJKDF2/blob/master/BUILDING.md
https://github.com/shinyquagsire23/OpenJKDF2#platforms
https://github.com/shinyquagsire23/OpenJKDF2#linux-partial-compilation-mmap-blobs

**Comment by d10sfan** [comment]
Looks like this one is still in progress on Linux. a known license would be needed to implement this. Can you do some research or ask about the licensing for this project?

**Comment by d10sfan** [comment]
@rea987 

Since it looks like this is a reverse engineering project with an unclear license, I won't be implementing this. This is mainly due to the legal confusion around projects like this.

**Comment by rea987** [comment]
License has been added:

https://github.com/shinyquagsire23/OpenJKDF2/blob/master/LICENSE.md
https://github.com/shinyquagsire23/OpenJKDF2/issues/10#issuecomment-973226957

**Comment by rea987** [comment]
@d10sfan Flatpak release of OpenJKDF2 has been shipped with [0BSD License](https://opensource.org/licenses/0BSD). It seems to be working fine. Can this be added to Luxtorpeda in its current form?

https://flathub.org/apps/details/org.openjkdf2.OpenJKDF2
