### ISSUE TITLE
ScummVM for Sanitarium

### ISSUE THREAD

**Issue by rea987** [luxtorpeda-dev/packages#578]
### Project Link

https://github.com/scummvm/scummvm

### Project License

GPLv2

### Steam App Ids

https://steamdb.info/app/284050/

### Additional Context

https://www.scummvm.org/news/20211118

**Comment by d10sfan** [comment]
@rea987 This should be supported by default when the next version of scummvm is out. Once they create a new version, I'll work on updating to it.
