### ISSUE TITLE
Little Big Adventure 1 & 2

### ISSUE THREAD

**Issue by ToughGuyKunio** [luxtorpeda-dev/packages#584]
### Project Link

- https://github.com/2point21/lba1-classic-community
- https://github.com/2point21/lba2-classic-community

### Project License

GPLv2

### Steam App Ids

- https://steamdb.info/app/397330/
- https://steamdb.info/app/398000/

### Additional Context

Official engine source code. The games have two code repositories, one for the orginal developers and one dedicated to the community for pull requests. All available at: https://github.com/2point21/

- https://blog.2point21.com/p/devlog-releasing-lba-open-source - blog post about open sourcing the engine
- http://lbafileinfo.kaziq.net/index.php/Main_Page - wiki
- https://lba-classic-doc.readthedocs.io/en/latest/ - documentation, doesn't seem to be of any use yet.
- The first game potentially also works in ScummVM.

**Comment by d10sfan** [comment]
@ToughGuyKunio I don't see anything in regards to compile for Linux. Do you have any further information on that?

**Comment by ToughGuyKunio** [comment]
There's a PR working on a compile guide here: https://github.com/2point21/lba-classic-doc/pull/1/files

**Comment by ToughGuyKunio** [comment]
I'll ask on their Discord if there's any other options

**Comment by ToughGuyKunio** [comment]
There was talk on discord about testing to compile with https://github.com/JWasm/JWasm on Linux but I'm not sure if anyone has tested it yet and there is no guide. Otherwise I guess we have to wait until there's an easier way to compile or there's a more modern port.

**Comment by ToughGuyKunio** [comment]
There's also this project for LBA2: https://github.com/agrande/lba2remake but it's not in a playable state yet.

**Comment by d10sfan** [comment]
Ok I'll close this for now. Feel free to comment here if things change
