### ISSUE TITLE
One Hour One Life

### ISSUE THREAD

**Issue by ToughGuyKunio** [luxtorpeda-dev/packages#585]
### Project Link

https://github.com/jasonrohrer/OneLife

### Project License

Public Domain

### Steam App Ids

- https://steamdb.info/app/595690/

**Comment by d10sfan** [comment]
@ToughGuyKunio it looks like this one requires an email address and key from the windows version being run. Not sure if theres a way around that to find this. https://github.com/jasonrohrer/OneLife/issues/164

Do you have any further information?

**Comment by ToughGuyKunio** [comment]
Not sure about the email address, but user could be prompted for the key. The user needs to right click on the game > select manage > select CD Keys

**Comment by ToughGuyKunio** [comment]
The email should be <steamid>@steamgames.com
So the user could be prompted to enter their Steam ID and CD Keys, with instructions on how to get them.

**Comment by d10sfan** [comment]
Tracking progress in https://github.com/luxtorpeda-dev/packages/pull/593
