### ISSUE TITLE
SNKRX

### ISSUE THREAD

**Issue by ToughGuyKunio** [luxtorpeda-dev/packages#586]
### Project Link

https://github.com/a327ex/SNKRX

### Project License

MIT

### Steam App Ids

- https://steamdb.info/app/915310/

### Additional Context
- Official engine source code.
- https://github.com/a327ex/SNKRX/pull/6

**Comment by d10sfan** [comment]
@ToughGuyKunio I don't think this one will be possible as it requires the libsteam so which I can't distribute.

Let me know if there's a alternative way to do this.
