### ISSUE TITLE
Use #!/usr/bin/env bash instead of #!/bin/bash

### ISSUE THREAD

**Issue by JoshuaFern** [luxtorpeda-dev/packages#589]
`#!/usr/bin/env bash` searches the `$PATH` to find the `bash` binary.

The `#!/bin/bash` shebang assumes that bash is always located in `/bin` which can cause issues. Specifically this improves compatibility with operating systems where `bash` is not located in `/bin`. e.g. NixOS, GNU Guix(?)

**Comment by d10sfan** [comment]
Since everything is running inside the steam runtime now, is there a case where this is an issue?

**Comment by JoshuaFern** [comment]
It was never a serious issue, as Nix itself runs Steam in a sort of runtime. However I'm suggesting this change as best practices for the future. Maybe just change the shebang on new scripts, or old scripts if you happen to be editing them anyways.

**Comment by d10sfan** [comment]
Ok, I'll take this into consideration for future engines. Since we run into the steam runtime all the time, there shouldn't ever be environment changes, but good to think about.
