### ISSUE TITLE
UT2004 Missing OpenAL

### ISSUE THREAD

**Issue by JoshuaFern** [luxtorpeda-dev/packages#59]
**Describe the bug**
When running UT2004 I receive a dialog: `OpenAL not found. Exiting.`

**Additional context**
Running Steam in a Flatpak, installing OpenAL system wide will not work.

**Comment by d10sfan** [comment]
I've updated the package, so now it'll compile and provide openal and libstdc++5, so all necessary deps should now be provided.

For the script itself, need to remove the dependency on wget and iconv

**Comment by d10sfan** [comment]
@JoshuaFern This should be fixed now, as luxtorpeda client will be providing all the necessary pieces to download the data and show the EULA. So there shouldn't be an dependency on certain binaries being available.

You'll need luxtorpeda 13 to re-test.
