### ISSUE TITLE
Shadowgrounds and Shadowgrounds Survivor

### ISSUE THREAD

**Issue by ToughGuyKunio** [luxtorpeda-dev/packages#591]
### Project Link

https://github.com/vayerx/shadowgrounds

### Project License

Custom non-commercial

### Steam App Ids

- https://steamdb.info/app/2500/
- https://steamdb.info/app/11200/
- https://steamdb.info/app/2510/ (demo)
- https://steamdb.info/app/11220/ (demo)

### Additional Context

I've tried to compile this myself but I couldn't get it to work, but it should be doable.

Compile instructions are here: https://github.com/vayerx/shadowgrounds/wiki/Build

Here's an installer for Gentoo that might help: https://github.com/vayerx/vayerx-gentoo/blob/master/games-action/shadowgrounds/shadowgrounds-9999.ebuild
There's also this SDL2 port: https://github.com/Chaduke/shadowgrounds-SDL2 but I don't know if it works or if it's better or worse than the main one.

**Comment by d10sfan** [comment]
From what I remember this does not work with the steam assets. There should be some dicussion about that in some older issues here.

**Comment by ToughGuyKunio** [comment]
Ah okay I missed that
