### ISSUE TITLE
Not able to set soundfont with prboom-plus

### ISSUE THREAD

**Issue by lucascoelho07** [luxtorpeda-dev/packages#592]
### Game

Ultimate Doom

### Engine

prboom-plus

### Linux Distribution

Arch

### Luxtorpeda Version

48

### Bug description

Soundfont option not working

### Steps To Reproduce

1. Set the MIDI player to fluidsynth
2. Get a soundfont
3. Set the path to the soundfont in the engine's config file
4. Open the game and see that nothing has canged

### Expected Behavior

The chosen soundfont will be used

### Additional Context

I don't understand much of this stuff, but could it be that the version of fluidsynth bundled with the engine is old? I tried to hyperlink it but everytime I launch the game it gets replaced

**Comment by d10sfan** [comment]
@lucascoelho07 What path is the soundfont in? All of the games are running under the steam runtime, so it has to be a path that is accessible. The library files are installed every launch. Fluid synth is 2.1.3, so fairly recent.

**Comment by lucascoelho07** [comment]
The soundfont is in .prboom-plus (same folder as prboom-plus.cfg)
I set it like this `snd_soundfont    "roland.sf2"` and it works fine with the normal version, but not with luxtorpeda

**Comment by d10sfan** [comment]
@lucascoelho07 Ok, can you describe a bit further what you are attempting to do?

1. Where did the soundfont come from and if possible could you provide it?
2. What version are you using for the "normal" version, both of prboom and fluidsynth?
3. What behavior inside prboom-plus are you expecting?
4. Can you provide logs showing the difference between the two attempts, as in using lux and using the "normal" version?

**Comment by d10sfan** [comment]
Feel free to comment if you continue to need help.

**Comment by JoshuaFern** [comment]
Try adding yourself to the `audio` group.

**Comment by lucascoelho07** [comment]
Sorry for taking so long to answer

> @lucascoelho07 Ok, can you describe a bit further what you are attempting to do?
> 
>     1. Where did the soundfont come from and if possible could you provide it?
I don't remember where I got it, but it's the Roland SC-55 by EmperorGrieferus
> 
>     2. What version are you using for the "normal" version, both of prboom and fluidsynth?
For prboom-plus I've tested the version from the AUR and for libfluidsynth I'm using version 3.0.4 that comes with the fluidsynth package from the Extra repository on Arch
> 
>     3. What behavior inside prboom-plus are you expecting?
I expect it to use the soundfont I set in prboom-plus.cfg
> 
>     4. Can you provide logs showing the difference between the two attempts, as in using lux and using the "normal" version?
Could you give me information on where to grab the logs?

Let me try to explain better:
When I launch prboom-plus(the one from AUR) from terminal using `prboom-plus -iwad "/home/myuser/.local/share/Steam/steamapps/common/Doom 2/base/DOOM2.WAD"` it works as intended, but when I launch the luxtorpeda version it uses some other soundfont that is not the one I set.
Also if I let snd_soundfont empty the version from the AUR uses the same generic sounding soundfont as the luxtorpeda package
The soundfont file is in the same folder as the config file (/home/myuser/.prboom-plus)

>Try adding yourself to the `audio` group.
Tried but no success

**Comment by d10sfan** [comment]
@lucascoelho07 

By behavior, I was mainly wondering is it that the sound isn't working at all, or that it's not playing against the soundfont you expect?

For logs, the best way is running steam in terminal. Then you can copy and paste it into a file and upload it here.

Do other settings seem to be working between the prboom-plus you are using and the luxtorpeda one, like controls and graphics?

Also, have you tried setting in the config file a full path instead of the relative path?

**Comment by d10sfan** [comment]
@lucascoelho07 

Also just to see if it helps, I did an upgrade PR where you can download the new version and see if it helps: https://github.com/luxtorpeda-dev/packages/suites/5105111019/artifacts/152802430

You can use this by going to ~/.cache/luxtorpeda/appid and replacing the latest .tar.xz file with the one inside the zip file given.

**Comment by lucascoelho07** [comment]
Everything seems to be working perfectly with the exception of music that plays but not as intended.
I tried this new version, but the game won't start (I renamed it to prboom-plus-common-6.tar.xz, is that right?)
[prboom-plus log](https://github.com/luxtorpeda-dev/packages/files/7965017/prboom-plus.log)
[steam log](https://github.com/luxtorpeda-dev/packages/files/7965018/steam.log)

**Comment by d10sfan** [comment]
@lucascoelho07 

Could you try downloading the latest and trying again? I believe I've gotten it fixed, if  you put the filename to a soundfont and then drop the soundfont in the "steamapps/common/Ultimate Doom/prboom-plus/" directory, it should see it. 

I was able to put a soundfont and then use fluidsynth and the music played as expected.

If you still have issues, let me know and please provide a log file.

**Comment by lucascoelho07** [comment]
IT WORKS!!!!!!!
THANK YOU SO MUCH
it also works on ~/ and ~/.prboom-plus
