### ISSUE TITLE
CivCTP2 has switched repo

### ISSUE THREAD

**Issue by ToughGuyKunio** [luxtorpeda-dev/packages#595]
The old repo is deprecated, new versions are here: https://github.com/civctp2/civctp2

confirmed here on orginal (used in lux) repo: https://github.com/ptitSeb/ctp2

**Comment by d10sfan** [comment]
@ToughGuyKunio Yes, the reason why is because I've been unable to build the latest one, similar to this issue: https://github.com/civctp2/civctp2/issues/352

Let me know if you're able to find a workaround.
