### ISSUE TITLE
Change Ren'Py to default

### ISSUE THREAD

**Issue by ToughGuyKunio** [luxtorpeda-dev/packages#596]
### Feature Request

There seems to be [at least 348 Ren'Py games](https://steamdb.info/instantsearch/?refinementList%5Boslist%5D%5B0%5D=-Linux&refinementList%5Btechnologies%5D%5B0%5D=Engine.RenPy) on Steam that are not Linux native. 

### Solution

Maybe Ren'Py could be changed to a default engine to support all Ren'Py games?

### Additional Context

btw, wasn't sure where to put this, engine bug didn't really fit, maybe add feature request/enhancement to package issues?

**Comment by d10sfan** [comment]
Currently, Ren'Py isn't being built, so that'd end up being a new engine. Would you be interested in implementation?

**Comment by ToughGuyKunio** [comment]
Sure I'll take a look at it
