### ISSUE TITLE
Redneck Rampage Rides Again doesn't start

### ISSUE THREAD

**Issue by eukara** [luxtorpeda-dev/packages#598]
### Game

Redneck Rampage Rides Again

### Engine

rednukem, raze

### Linux Distribution

OpenSUSE Tumbleweed

### Luxtorpeda Version

Version 48

### Bug description

The expansion/sequel to Redneck Rampage doesn't run, whereas the main game does.
The launch script keeps getting its permission reset as not executable.

### Steps To Reproduce

1. Try to run the game with either raze of rednukem.
2. It will fail because the package's scripts don't have the right permissions set?

### Expected Behavior

The game would launch.

### Relevant log output

```shell
run: "./run-rr-again.sh" with args: [] []
thread 'main' panicked at 'failed to execute process: Os { code: 13, kind: PermissionDenied, message: "Permission denied" }', src/main.rs:225:13
```

**Comment by d10sfan** [comment]
@eukara This should be fixed with this https://github.com/luxtorpeda-dev/packages/commit/fe6f749ee28d3d9661b3338ae3aa03ff39154bc3

The permissions on the file weren't setup correctly. Next time you launch it should be good to go.
