### ISSUE TITLE
OpenRCT2 doesn't load game data correctly

### ISSUE THREAD

**Issue by TCHORGO** [luxtorpeda-dev/packages#599]
### Game

RollerCoaster Tycoon 2

### Engine

OpenRCT2

### Linux Distribution

Linux Mint 20.2

### Luxtorpeda Version

48

### Bug description

When the game is started only the menus, background music and the logo appears, the background park appears as just a grey empty screen. Any attempt to start a scenario will result in a message informing that specific sprites are missing.

### Steps To Reproduce

1. Make a fresh install of RollerCoaster  Tycoon 2
2. Just run it with the the Luxtorpeda run time.

### Expected Behavior

After starting the game a sequence of parks should appears as background and being able to play any scenario.

### Additional Context

A temporary fix I found is to download the same version provided in the packages repository on the OpenRCT2 repository. I used the "tar.gz" package from OpenRCT2 repository to fix and noticed that a library called "libopenrct2.so" is missing in the luxtorpeda provided package.

**Comment by d10sfan** [comment]
@TCHORGO Thanks for the report. It should be fixed the next time you launch.

https://github.com/luxtorpeda-dev/packages/pull/603

**Comment by TCHORGO** [comment]
It's working just fine now. Thanks.
