### ISSUE TITLE
Prospekt

### ISSUE THREAD

**Issue by rea987** [luxtorpeda-dev/packages#600]
### Project Link

https://github.com/ValveSoftware/source-sdk-2013

### Project License

Source SDK Copyright(c) Valve Corp.

### Steam App Ids

https://steamdb.info/app/399120/

### Additional Context

That is a standalone HL2 mod that works fine with Source SDK 2013 natively. Steps:

- Install **Prospekt**
- Switch `upcoming` branch of **Source SDK Base 2013 Singleplayer** and install it 
- Copy `~/.local/share/Steam/steamapps/common/Prospekt/prospekt` into `~/.local/share/Steam/steamapps/sourcemods`
- Run `find ./ | sort -r | sed 's/\(.*\/\)\(.*\)/mv "\1\2" "\1\L\2"/' |sh` within  `~/.local/share/Steam/steamapps/sourcemods/prospekt`
- Edit `~/.local/share/Steam/steamapps/sourcemods/prospekt/gameinfo.txt` > replace _399120_ with _243730_
- Copy _**client.so**_ and _**server.so**_ from `~/.local/share/Steam/steamapps/common/Source SDK Base 2013 Singleplayer/sourcetest/bin` into `~/.local/share/Steam/steamapps/sourcemods/prospekt/bin`
- Restart Steam and run Prospekt mod.

**Comment by d10sfan** [comment]
Add https://github.com/luxtorpeda-dev/packages/commit/f2beba092019824646761b91663b8c5297d99ccd

**Comment by rea987** [comment]
@d10sfan Prospekt is a retail, standalone game that doesn't require Half-Life 2 to run. Source SDK Base 2013 Singleplayer and its client.so, server.so libraries would be sufficient. Would it be possible to remove Half-Life 2: Episode 2 from requirements? Thank you!

https://store.steampowered.com/app/399120/Prospekt/

**Comment by d10sfan** [comment]
@rea987 Ok, I've changed that: https://github.com/luxtorpeda-dev/packages/commit/43defa05d9baf2367712796a7d278cd502ef6055
