### ISSUE TITLE
BuildGDX v1.16 update

### ISSUE THREAD

**Issue by jesperjackson** [luxtorpeda-dev/packages#601]
New BuildGDX release is out with command-line support, World Tour is now working on Linux and Blood: Fresh supply Cryptic Passage addon is supported.

Some suggestions:
- Add direct game start: -path "gamepath", -silent (starts the game without showing launcher frame)
- Add https://steamdb.info/app/434050/

**Comment by d10sfan** [comment]
Implemented in https://github.com/luxtorpeda-dev/packages/commit/5799bc32b22c256c503c853ccf23808539525db3

I tried the blood fresh cryptic passage but it just crashes, but looks to be a game issue.
