### ISSUE TITLE
Update Quake3e to Latest Release

### ISSUE THREAD

**Issue by bluestang2006** [luxtorpeda-dev/packages#609]
### Project Link

https://github.com/ec-/Quake3e/

### Project License

https://github.com/ec-/Quake3e/blob/master/COPYING.txt

### Steam App Ids

https://steamdb.info/app/2200/

### Additional Context

Quake3e had some recent PRs that fixed the video output using SDL2 >= v2.0.18 under its wayland driver.

This is the commit for the latest release - https://github.com/ec-/Quake3e/commit/2baea1875307230b49b087af57215e2463ace8ba

**Comment by d10sfan** [comment]
https://github.com/luxtorpeda-dev/packages/commit/42985f3591018945a1d63cc733cade77d604d4d2

Normally, I wait for the official release to come out, but I've gone ahead and updated to the latest. It should be available soon
