### ISSUE TITLE
Fast Detect

### ISSUE THREAD

**Issue by rea987** [luxtorpeda-dev/packages#610]
### Project Link

https://github.com/ValveSoftware/source-sdk-2013

### Project License

Source SDK Copyright(c) Valve Corp.

### Steam App Ids

https://steamdb.info/app/353220/

### Additional Context

That is a free HL2 mod that works fine with Source SDK 2013 natively. Steps:

- Install **Fast Detect**
- Switch `upcoming` branch of **Source SDK Base 2013 Singleplayer** and install it 
- Copy `~/.local/share/Steam/steamapps/common/Fast Detect/FastDetect` into `~/.local/share/Steam/steamapps/sourcemods` ; rename the folder as `fastdetect`
- Apply `LANG=en_US.UTF-8 bash` within  `~/.local/share/Steam/steamapps/sourcemods/fastdetect`
- Run `find ./ | sort -r | sed 's/\(.*\/\)\(.*\)/mv "\1\2" "\1\L\2"/' |sh` within  `~/.local/share/Steam/steamapps/sourcemods/fastdetect`
- Edit `~/.local/share/Steam/steamapps/sourcemods/fastdetect/gameinfo.txt` > replace _353220_ with _243730_
- Copy _**client.so**_ and _**server.so**_ from `~/.local/share/Steam/steamapps/common/Source SDK Base 2013 Singleplayer/sourcetest/bin` into `~/.local/share/Steam/steamapps/sourcemods/fastdetect/bin`
- Restart Steam and run Fast Detect mod.

**Comment by d10sfan** [comment]
Added in https://github.com/luxtorpeda-dev/packages/commit/fe61bf5e7e6673c4c61c1819d0574a1ffeed713e

Thanks for the suggestion.
