### ISSUE TITLE
ETQW OSS and potential SDL issue

### ISSUE THREAD

**Issue by rea987** [luxtorpeda-dev/packages#613]
### Game

Enemy Territory: Quake Wars

### Engine

id Tech 4

### Linux Distribution

Ubuntu Mate 21.04

### Luxtorpeda Version

49

### Bug description

Luxtorpeda allows users to play retail version of ETQW as Enemy Territory: QUAKE Wars Demo 2.0 on Steam. As of late I am unable to receive OSS sound from ETQW retail via osspd. However, when I launch ETQW without Steam separately, I can get OSS sound with osspd. I suspect that Luxtorpeda forces libpulsedsp on ETQW but I am unable to find any code on the Luxtorpeda's launcher script for ETQW retail.

Also, I noticed that SDLCL library shipped with Luxtorpeda's ETQW package is named `libSDL-1.2.so.0`; ETQW's SDL implementation has extra patch to enable threaded renderer that has already been incorporated into SDLCL. SDL lib of ETQW should be named as `libSDL-1.2.id.so.0`. I am not sure whether that is related with OSS issue of ETQW retail of Luxtorpeda.

### Steps To Reproduce

1. Edit `~/.etqwcl/base/etqwconfig.cfg` > edit `seta s_driver "alsa"` line as `seta s_driver "oss"`
2. Launch game
3. The game returns following sound warning;

```
----- Initializing Sound System ------
sound system initialized.
--------------------------------------
------ OSS Sound Initialization ------
WARNING: failed to open output sound device '/dev/dsp': Input/output error
WARNING: sound subsystem disabled
```

### Expected Behavior

The game has sound have following sound info:

```
> ----- Initializing Sound System ------
> sound system initialized.
> --------------------------------------
> ------ OSS Sound Initialization ------
> opened sound device '/dev/dsp'
> ioctl SNDCTL_SYSINFO failed: Invalid argument
> this ioctl is only available in OpenSound.com's OSS implementation. If you run Linux kernel OSS or Alsa OSS, don't bother.
> /dev/dsp - bit rate: 16, channels: 2, frequency: 44100
> allocated a mix buffer of 16384 bytes
> --------------------------------------
> -------- OSS Microphone Init ---------
> WARNING: SNDCTL_DSP_GETCAPS reports this device doesn't support input
> (some implementations don't report this flag)
> bit rate: 16, channels: 1, frequency: 22050
> Microphone successfully initialized
> --------------------------------------
```

**Comment by d10sfan** [comment]
@rea987 What is the issue with using pulse? The reason why oss does not work most likely is because the game is running in the steam runtime, which does not have access to anything that you are installing on your host system.

The launch script is here: https://github.com/luxtorpeda-dev/packages/blob/master/engines/etqw/assets/run-retail.sh

You'll notice it copies the sdl file into the right spot

**Comment by rea987** [comment]
@d10sfan

> What is the issue with using pulse?

ETQW is such an old game with outdated libraries that its both ALSA and OSS implementations are problematic on current distros. I need to use OSS to be able to use VoIP in the game. On current Ubuntu based systems there is no 32 bit padsp package, it's 64 bit only. Back in the day when padsp was available for 32 bit, I find it delayed comparing to osspd for ETQW.

Can't there be way to let the game use osspd? Can there be way to not use Steam Runtime? Thank you!

**Comment by d10sfan** [comment]
@rea987 From my understanding, osspd requires a service running on the host system, so it's not something that could be included as part of the package.

There might be a way to link your host osspd to the steam runtime, although I'm not sure how that would be done.

There wouldn't be a way to not run inside steam runtime. You could try running the older non-runtime luxtorpeda if you want, although note that that does not get any updates.

**Comment by rea987** [comment]
> You could try running the older non-runtime luxtorpeda if you want, although note that that does not get any updates.

Is v39 the latest release that allows non-runtime?

**Comment by d10sfan** [comment]
Yes that's correct

**Comment by rea987** [comment]
Switching to v39 did the trick. However, as you pointed out, it doesn't support the game that are added after v39.

Is there a way to have multiple Luxtorpeda installed just like Steam allows multiple Proton releases? As of now, even if I rename v39's folder as luxtorpeda39 and latest one luxtorpeda49; it looks like the latter release interferes even with clean ~/.cache and ~/.config.

**Comment by d10sfan** [comment]
@rea987 In the folder, you would want to change the compatibilitytool.vdf file and change the internal name and display name (so you could rename the old one to luxtorpeda-39) and keep the current one alone.

Note that the config file will be re-downloaded whenever you switch back and forth, but that should not cause any issues.

**Comment by rea987** [comment]
@d10sfan

> In the folder, you would want to change the compatibilitytool.vdf file and change the internal name and display name (so you could rename the old one to luxtorpeda-39) and keep the current one alone.

Yes, that worked! Thanks!
