### ISSUE TITLE
NXEngine-evo for Cave Story

### ISSUE THREAD

**Issue by rea987** [luxtorpeda-dev/packages#615]
### Project Link

https://github.com/nxengine/nxengine-evo

### Project License

GPL-3.0

### Steam App Ids

https://steamdb.info/app/200900/

### Additional Context

**Dōkutsu Monogatari** is freeware platformer from 2004; it arrived to Steam with an enhanced edition named **Cave Story+** in 2011. Cave Story+ offered remastered as well as original textures and music; 2 additionally difficulty modes; challenges. In 2017, Cave Story+ arrived to Nintendo Switch with native widescreen support whereas Steam version didn't receive that upgrade.

NXEngine-evo utilizes the freeware version to apply modern libraries and features like SDL2, 64 bit and native widescreen support;

https://github.com/nxengine/nxengine-evo#differences-from-the-original-version-of-nxengine

Pros:

- Widescreen support that would help during boss fights greatly as it does on Switch
- Mod support
- Custom soundtrack support

Cons:

- No Easy or Hard mode
- Locked to 50 FPS as it is based on freeware version
- No challenges or Steam Achievements

Notes:

1) Latest AppImage release of the engine fails to launch on Linux. tar.xz release of v2.6.4 run on Linux fine. (I needed to install `libsdl2-mixer-2.0-0` on Ubuntu 21.04.)

2) Copying `~/.local/share/Steam/steamapps/common/Cave Story+/data/base/Ogg11` directory into `data` folder of NXEngine-evo enables enhanced soundtrack.

**Comment by d10sfan** [comment]
It looks like this engine does not support Cave Story+, unless I'm misunderstanding: https://github.com/nxengine/nxengine-evo/issues/254
