### ISSUE TITLE
Doom Retro

### ISSUE THREAD

**Issue by vaibhavrmahadevan** [luxtorpeda-dev/packages#616]
### Project Link

https://github.com/bradharding/doomretro

### Project License

GNU General Public License v3+

### Steam App Ids

https://steamdb.info/app/2280/
https://steamdb.info/app/2290/
https://steamdb.info/app/2300/
https://steamdb.info/app/9160/

**Comment by d10sfan** [comment]
Thanks for the suggestion, I'm tracking additional work here: https://github.com/luxtorpeda-dev/packages/pull/618

**Comment by vaibhavrmahadevan** [comment]
Thank you so much! 💗

**Comment by d10sfan** [comment]
Implemented in the PR linked above
