### ISSUE TITLE
[Suggestion] Switching to sdl12-compat from SDLCL

### ISSUE THREAD

**Issue by rea987** [luxtorpeda-dev/packages#625]
[SDLCL](https://github.com/MrAlert/sdlcl) hasn't been updated since 2018. Although it does its job pretty well most of the times, it has a crucial black screen [bug](https://github.com/MrAlert/sdlcl/issues/14#issuecomment-388630899) with ETQW that has never been fixed.

On the other hand, [sdl12-compat](https://github.com/libsdl-org/sdl12-compat) has recently been reached a milestone [release](https://github.com/libsdl-org/sdl12-compat/releases) that works fantastic and happened to fix ETQW's black screen issue.

Would it be possible to switch SDL1 games packages from SDLCL to sdl12-compat? Such change would be extremely beneficial for id Tech 4 and UE2 games such as **Enemy Territory: Quake Wars**, **Quake 4**, **Prey** (2006) and **Unreal Tournament 2004**.

**Comment by d10sfan** [comment]
@rea987 Good suggestion.

I've started working on that. So far, ut2004 is done with this: https://github.com/luxtorpeda-dev/packages/pull/626

**Comment by d10sfan** [comment]
Prey done here: https://github.com/luxtorpeda-dev/packages/commit/fa7af26b350dd4a78c8d5921d59f84e64a8f781e

**Comment by d10sfan** [comment]
Quake 4 done here: https://github.com/luxtorpeda-dev/packages/pull/628

**Comment by rea987** [comment]
By checking [packages list](https://luxtorpeda-dev.github.io/packages.html), I noticed that some games have their Steam Overlay disabled. I theorize that some might be related with SDL incompability.

- [ctp2](https://github.com/ptitSeb/ctp2) for [Call to Power II](https://store.steampowered.com/app/572050/Call_to_Power_II/) seems to be quite an old port which uses SDL1. Using sdl12-compat might help it to enable Steam Overlay.

**Comment by d10sfan** [comment]
@rea987 

That is already done: https://github.com/luxtorpeda-dev/packages/blob/master/engines/ctp2/env.sh

SDL 1 isn't available in the new steam runtime, so I needed to use sdl12-compat in those cases, like for that and avp. I'm not sure why the steam overlay does not work for that one.

**Comment by d10sfan** [comment]
Unreal gold here: https://github.com/luxtorpeda-dev/packages/pull/629

**Comment by d10sfan** [comment]
ETQW is here: https://github.com/luxtorpeda-dev/packages/commit/0de77e900a83fbe2459b0441d689c426ab22f6a6

I think that should be all of them. sdlcl is now no longer used at all, replaced by sdl12-compat. Let me know if you run into any issues.

**Comment by d10sfan** [comment]
@rea987 Thanks for the notice, looks like there was a bug in the build script. It's fixed here, should be live in a few minutes: https://github.com/luxtorpeda-dev/packages/commit/62d004e46c6b6e26efb39ba404e3da7a16324370
