### ISSUE TITLE
NetDuke32 for Duke Nukem 3D

### ISSUE THREAD

**Issue by rea987** [luxtorpeda-dev/packages#630]
### Project Link

https://voidpoint.io/StrikerTheHedgefox/eduke32-csrefactor/-/releases/

### Project License

GPLv2

### Steam App Ids

- https://steamdb.info/app/434050/
- https://steamdb.info/app/225140/
- https://steamdb.info/app/359850/

### Additional Context

https://forums.duke4.net/topic/11826-netduke32-enhanced-duke3d-netplay/

Also, I noticed that original DN3D release on Steam isn't supported by Luxtorpeda. Would it be possible to provide EDuke32, BuildGDX, Raze and NetDuke32 for it? Here is file structure;

https://steamdb.info/app/359850/depots/

**Comment by d10sfan** [comment]
@rea987 

The original release isn't on the store anymore, so I would have no way to test it. Do you have that one?

I'll look into this engine though, thanks

**Comment by rea987** [comment]
> The original release isn't on the store anymore, so I would have no way to test it. Do you have that one?

Unfortunately I don't have that one. By the looks of depots, it utilizes DOSBox on Linux, Windows and macOS.

**Comment by d10sfan** [comment]
@rea987 

I added this for megaton edition here: https://github.com/luxtorpeda-dev/packages/pull/632

eduke32 does not seem to work with World Tour, at least the version that this project is using.

**Comment by rea987** [comment]
@d10sfan It looks like NetDuke32 has been added for Megaton Edition but not for World Tour. As Megaton is no longer on sale, would it be possible to add NetDuke32 fpr World Tour? Thank you!

**Comment by d10sfan** [comment]
@rea987 As I mentioned above, it does not seem like this supports world tour. If you find out if there's any fixes for that, please let me know.

When I tried to run it, it came up with errors that it did not understand the con files.

**Comment by rea987** [comment]
Yeah, it looks like those who wish to play that port and happened to not own Megaton should go for Atomic Edition in Zoom Platform. Thanks for the explanation.

https://www.zoom-platform.com/product/duke-nukem-3d-atomic-edition
