### ISSUE TITLE
Launcher Request - DoomRunner for GZDOOM & Other Doom Source Ports

### ISSUE THREAD

**Issue by tlneondo** [luxtorpeda-dev/packages#633]
### Project Link

https://github.com/Youda008/DoomRunner

### Project License

GPL-3.0 License 

### Steam App Ids

https://steamdb.info/app/2280/
https://steamdb.info/app/2300/
https://steamdb.info/app/2360/
https://steamdb.info/app/2390/

### Additional Context

This would just make it easier to launch Doom Mods on the Steam Deck, as editing launch arguments would be a pain.

This is how it looks under windows when I'm loading mods:

![image](https://user-images.githubusercontent.com/12129080/159097784-fc16b57f-d3a4-4d9e-881a-d453949bda39.png)

**Comment by d10sfan** [comment]
@tlneondo Thanks for the request on this! I was able to get it working, and test it with Brutal Doom. I tested with Ultimate Doom.

The way it works is that it'll pre-fill the relative location to where gzdoom and the iwads are, and then you can pick which wad to use and what mods to use.

It's live now, so you should be good to go to try it out.
