### ISSUE TITLE
Launcher Request - ZDL

### ISSUE THREAD

**Issue by vaibhavrmahadevan** [luxtorpeda-dev/packages#635]
### Project Link

https://github.com/lcferrum/qzdl

### Project License

GPL-3.0 License

### Steam App Ids

https://steamdb.info/app/2280/
https://steamdb.info/app/2290/
https://steamdb.info/app/2300/
https://steamdb.info/app/9160/
https://steamdb.info/app/2360/
https://steamdb.info/app/2390/

### Additional Context

Hi d10sfan!

I was happy to find out that DoomRunner was now available and would love to see ZDL :)

I feel its simple UI would make it a good alternative to DoomRunner.

![Screenshot from 2022-03-19 21-54-30](https://user-images.githubusercontent.com/74069989/159129629-d9f88e4a-b86c-4caa-a63b-57cd8b20a822.png)

**Comment by d10sfan** [comment]
@vaibhavrmahadevan Thanks for the suggestion, I've added it here: https://github.com/luxtorpeda-dev/packages/pull/636

I ended up using https://github.com/qbasicer/qzdl as it looks like it was updated more recently and this one compiled easier. Was able to test it with Ultimate Doom, but should work for the ones listed in https://luxtorpeda-dev.github.io/

It should be live in about an hour from this message.

**Comment by vaibhavrmahadevan** [comment]
Hi @d10sfan!

In the past few days, I have noticed that qzdl does not launch for Final DOOM but the application does run when opened outside of steam :(

**Comment by d10sfan** [comment]
@vaibhavrmahadevan 

Can you run steam in Terminal and send the output of that attempt of running qzdl here?

Did you move Final DOOM between tries? As well, do other engines like running gzdoom directly work?

**Comment by vaibhavrmahadevan** [comment]
[Final DOOM.txt](https://github.com/luxtorpeda-dev/packages/files/8404552/Final.DOOM.txt)

Tried to move it to the home directory and the ext4 partition (where Ultimate DOOM and DOOM II are installed) between tries but got the same result :(

Other engines and Doom Runner work perfectly though

**Comment by d10sfan** [comment]
@vaibhavrmahadevan I believe that should be fixed by this change: https://github.com/luxtorpeda-dev/packages/commit/e9e9febe4f67f6ec5ca09acd7d26a38811145202

It should be live in a few hours, if  you can try it out then.

**Comment by d10sfan** [comment]
@vaibhavrmahadevan The new build is now live.
