### ISSUE TITLE
DoomRunner and QZDL for Master Levels for DOOM II

### ISSUE THREAD

**Issue by vaibhavrmahadevan** [luxtorpeda-dev/packages#640]
### Project Link

https://github.com/qbasicer/qzdl

### Project License

GPL-3.0 License

### Steam App Ids

https://steamdb.info/app/9160/

### Additional Context

Hi d10sfan!

Really appreciated the inclusion of wadsmoosh and thought it would be really helpful to have both launchers as it would make launching GZDoom with other wads and midi-packs such as [Vanilla Essence](https://forum.zdoom.org/viewtopic.php?t=59412) and [Master Levels for Doom II - 25th Anniversary MIDI Pack](https://www.doomworld.com/forum/topic/118804-master-levels-for-doom-ii-25th-anniversary-midi-pack/) among others much easier.

**Comment by d10sfan** [comment]
@vaibhavrmahadevan Thanks for the suggestion.

doom-runner has been added here: https://github.com/luxtorpeda-dev/packages/commit/071370548d8d2d41e93056bb2fdb6cb6185cbd6a

And qzdl here: https://github.com/luxtorpeda-dev/packages/commit/75e867ed85356f2046ddf2a4a2cb3758a6846a1c

They should be live about an hour after this comment.

**Comment by vaibhavrmahadevan** [comment]
yay! 

Sadly though both qzdl and doom-runner both seem not be launching as earlier seen in Final Doom

**Comment by vaibhavrmahadevan** [comment]
yay! 

Sadly though both qzdl and doom-runner both seem to be not launching as earlier seen in Final Doom :(

**Comment by vaibhavrmahadevan** [comment]
@d10sfan yay!

Sadly though both qzdl and doom-runner both seem to be not launching as earlier seen in Final Doom :(

**Comment by d10sfan** [comment]
@vaibhavrmahadevan The actions to build it are still running, hopefully will be done soon.

**Comment by d10sfan** [comment]
@vaibhavrmahadevan It should be live now. Github actions look longer than normal for whatever reason

**Comment by vaibhavrmahadevan** [comment]
@d10sfan Thank you so much! 💗
