### ISSUE TITLE
Raze for Shadow Warrior Classic (1997)

### ISSUE THREAD

**Issue by rea987** [luxtorpeda-dev/packages#641]
### Project Link

https://github.com/coelckers/Raze

### Project License

Various Licenses

### Steam App Ids

https://steamdb.info/app/238070/

### Additional Context

As I have tried, free to play Shadow Warrior Classic (1997) works fine with Raze. Extracting Raze .zip into `gameroot` folder of the game and running `raze` binary is enough.

**Comment by d10sfan** [comment]
Thanks for the ticket, added in https://github.com/luxtorpeda-dev/packages/commit/fc71ad81c880b8cc73c2372cb02d7a18a46243d1
