### ISSUE TITLE
ET: Legacy

### ISSUE THREAD

**Issue by rea987** [luxtorpeda-dev/packages#653]
### Project Link

https://github.com/etlegacy/etlegacy

### Project License

GPLv3

### Steam App Ids

https://steamdb.info/app/1873030/depots/

**Comment by d10sfan** [comment]
This is already implemented, but will look into adding the 64 bit version

**Comment by d10sfan** [comment]
Added 64-bit in this commit: https://github.com/luxtorpeda-dev/packages/commit/5cb43d61d4a2addf27e920f9709e47364a4e9d72
