### ISSUE TITLE
Engine Request: Daggerfall Unity Engine Remake

### ISSUE THREAD

**Issue by Aftonstjarna** [luxtorpeda-dev/packages#654]
### Project Link

https://github.com/Interkarma/daggerfall-unity/

### Project License

MIT License

### Steam App Ids

https://steamdb.info/app/1812390/

### Additional Context

Daggerfall is now available on Steam
The Unity version has a good Linux build
This is the best way to experience TESII + all the mods made for it
Has controller support

**Comment by d10sfan** [comment]
Thanks for the ticket. This is being worked ok, but on hold for the moment while waiting for a bug to be resolved. You can see this PR for more information and feel free to comment there if you'd like: https://github.com/luxtorpeda-dev/packages/pull/651
