### ISSUE TITLE
Add more supported scummvm games (using stable and unstable releases)

### ISSUE THREAD

**Issue by neuromancer** [luxtorpeda-dev/packages#655]
### Project Link

https://www.scummvm.org/

### Project License

https://github.com/scummvm/scummvm/blob/master/COPYING

### Steam App Ids

The list is too long, but it can fetched from here:

https://store.steampowered.com/curator/35667778-Powered-by-ScummVM/

Additionally, there are more games which are not listed here, such as Sanitarium or Crusader no remorse, which run in an recent nightly build.

### Additional Context

There is a long list of supported games which are not yet integrated into luxtorpeda. The officially compatibility list from scummvm is here: https://www.scummvm.org/compatibility/

Additionally, there the unstable scummvm releases contains a good number of upcoming games which could use more testing (and hopefully bug requests).  However, if an engine to play some game was already included in some scummvm release, the stable version should be preferred.

**Comment by d10sfan** [comment]
@neuromancer Is there any need for special treatment for all of the supported games, when the default scummvm option can be used? If that works the majority of the time, it probably isn't needed to add support for each individual title and ones could be added for any title that has unique needs.

For unstable versions, it may make sense to have a untested version of scummvm available as another default, although that would turn into a moving target, which is why I normally try and wait until there's an official release. Along with "Sanitarium or Crusader no remorse", are there others that you're interested in that don't work in the last offocial reelease?

**Comment by neuromancer** [comment]
> Is there any need for special treatment for all of the supported games, when the default scummvm option can be used? If that works the majority of the time, it probably isn't needed to add support for each individual title and ones could be added for any title that has unique needs.

I believe most of the games should work out of box, however, in some cases, games using dosbox are distributed with iso images that should be mounted in order to detect the game data. These are not going to work out of the box (all the needed files for each game are detailed in the scummvm wiki. For instance: https://wiki.scummvm.org/index.php?title=Bud_Tucker_in_Double_Trouble )

> For unstable versions, it may make sense to have a untested version of scummvm available as another default, although that would turn into a moving target, which is why I normally try and wait until there's an official release. Along with "Sanitarium or Crusader no remorse", are there others that you're interested in that don't work in the last offocial reelease?

Yes, let me get back to you with a list of them. Very excited to see extended scummvm support!

**Comment by d10sfan** [comment]
@neuromancer  Interesting, I may be able to do another generic scummvm option for iso support, where it tries to mount or extract the files that are required. I've used xorriso with OpenLara in the past to extract an iso, so something similar could work here.

Do you have an example of a steam game with an iso like that?

**Comment by neuromancer** [comment]
Uhm, I cannot find a good example from the stable release (I know a few from GOG, but nothing that I own on Steam). However, I know that [Wetlands](https://store.steampowered.com/app/1367160/Wetlands/) requires to mount the ISO to detect it using scummvm (it's the [hypno engine](https://wiki.scummvm.org/index.php?title=Hypno)). This engine is not finished yet, but it will be in testing phase very soon (in a week or two), but I guess we are not in a rush to have the iso support for most of the games. 

Btw "Crusader No Remorse" is not on Steam, but on GOG. Apologies for the confusion!

**Comment by d10sfan** [comment]
@neuromancer Could you update this ticket when Wetlands is ready for testing?

**Comment by neuromancer** [comment]
Sure, this should be out for testing in a week or two.

**Comment by neuromancer** [comment]
Wetlands is officially in [testing](https://www.scummvm.org/news/20220506/). I can test the luxtorpeda package when it is available to see if it detects the game properly in steam.

**Comment by d10sfan** [comment]
@neuromancer 

I've added the logic for iso support, so it'll extract it if it finds it, and then adds the path to scummvm. This is implemented for the "scummvm" option, which is the one that changes based on official scummvm releases. You can see that logic here: https://github.com/luxtorpeda-dev/packages/blob/master/engines/scummvm/assets/run-scummvm.sh

I've added a scummvm-latest, which uses the latest commit from git. That one will only be updated on request. You can pick on the default option either scummvm or scummvm-latest.

Wetlands has been added and tested, so if you have the game on Steam, it'll download scummvm-latest and launch automatically.

Let me know if you run into any issues.

**Comment by neuromancer** [comment]
A few comments:

* Extracting the iso works fine, as the game is detected later, but there is no indication on screen, which can be confusing for users (it takes around 20 seconds here?)
* Scummvm latest starts (well, sometimes), but always crashes when running the game. This was confirmed with Wetlands and Sanitarium. For instance:
```
User picked target 'asylum' (engine ID 'asylum', game ID 'asylum')...
   Looking for a plugin supporting this target... Sanitarium
munmap_chunk(): invalid pointer
./scum-latest/run-scummvm.sh: line 47: 12178 Aborted                 (core dumped) LD_LIBRARY_PATH="lib:$LD_LIBRARY_PATH" ./bin/scummvm -c scummvm.ini --fullscreen --gfx-mode=opengl --themepath=./share/scummvm
```

Running the game directly outside steam, using the `bin/scummvm` works in ArchLinux, so it could be an issue with one linked library in the steam runtime.

**Comment by neuromancer** [comment]
Forcing the game to run with the sdl output fixes this crash. I think this mode is recommended, since the opengl one has known issues with dpi (fonts can be very small and the mouse pointers are not scaled properly)

**Comment by d10sfan** [comment]
@neuromancer 

I've made a change, just for scummvm-latest for now, that sets sdlsurface as the default, if the scummvm.ini file does not exist: https://github.com/luxtorpeda-dev/packages/commit/6ab6df6815fe644632566884758246146cc3ff21

That should be live in about half an hour from this message. I wasn't able to replicate a crash with the normal default, but that may be due to different resolutions and scaling. 

For the initial setup, that only happens once (launches after uses the already extracted data). There's certain things like the downloads that show a progress bar. I may be able to do something similar for setup items like this, where it shows a spinner until complete, but would need to do some more research into how that could be done.

**Comment by neuromancer** [comment]
Can you please update the unstable release to use the latest commit in master or at least the 2.6.0 RC branch? There are some number of Wetlands fixes there (as well as other games, of course). Also, what is the most effective way to ask for rebuilding this code?

**Comment by d10sfan** [comment]
@neuromancer 

I've updated scummvm-latest to use the latest from branch-2-6 on github. It's done in this: https://github.com/luxtorpeda-dev/packages/pull/689

For future updates, the best option would be to comment in this issue if it's related to scummvm, or if there's some other engine that could use updates, feel free to create an issue about it.

**Comment by atomic1fire** [comment]
I didn't know where else to put this but Sam and Max's hit the road uses ScummVM but doesn't work as is.

https://steamdb.info/app/355170/depots/

I think they have their ini file named samandmax.ini

**Comment by d10sfan** [comment]
@atomic1fire Thanks for the request, I got it working with this: scummvm - Add support for Sam & Max Hit the Road

It should be live in about half an hour, let me know if you have any issues.
