### ISSUE TITLE
Support for delisted versions of Duke 3D, Shadow Warrior?

### ISSUE THREAD

**Issue by Arkaium** [luxtorpeda-dev/packages#656]
### Feature Request

Hi friend,

I LOVE this compatibility plugin btw, it’s amazing how seamlessly it works with Steam
Deck.

I’ve noted that my versions of Duke Nukem 3D and Shadow Warrior, classic/legacy versions that may have been delisted, are not detected correctly by Luxtorpeda. I assume if it gave me Raze as one of the default options on the “I don’t recognize this game” generic list, it would work fine because all the data files are there?

### Solution

is there any chance raze could ever work with these older versions through luxtorpeda?

**Comment by d10sfan** [comment]
@Arkaium 

Thanks! 

Do you have steam ids for the ones you are referring to? I could try adding the ones you're referring to, but I would have no way of testing them, so if you'd be willing to test, that'd be great.

**Comment by Arkaium** [comment]
Omg, you’re amazingly fast, they weren’t kidding on Reddit when they said you were. Thank you!

I’m not sure where to find that anymore but under updates in desktop mode:

Duke Nukem 3D
App ID: 359850
Build ID: 621777

Shadow Warrior Classic
App ID: 358400
Build ID: 613173

I didn’t create a new one for it since the other github I saw you comment on had it there, but Daggerfall Unity for the newly released steam version of the game would be a dream!

I just wish I hadn’t missed GTA and GTA VC before take two pulled the r3 engine :(

**Comment by d10sfan** [comment]
@Arkaium Thanks I'll take a look at that and see if I can make it work. For daggerfall unity, I'm waiting for an upstream fix before implementing it. You can see when it's available if you follow this: https://github.com/luxtorpeda-dev/packages/pull/651

**Comment by Arkaium** [comment]
This app and the amount of work you’ve put into it is crazy impressive. I was almost getting frustrated you weren’t getting more chatter, and that folks didn’t seem to understand what Luxtorpeda was vs Lutris. Thank you!

Getting OpenMW running was so smooth and easy compared to trying to get the dedicated flatpak, then adding as a custom non-steam app, etc.

Looking forward to your continued progress.

**Comment by d10sfan** [comment]
@Arkaium Thanks I appreciate that!

I created an untested change that I believe will make the games work: https://github.com/luxtorpeda-dev/packages/commit/7bd17db211b3e0bf9e55a3329eb0c3a74264e176

Next time you launch them if you pick Luxtorpeda, it should launch those with raze. Let me know how it goes for you.

**Comment by Arkaium** [comment]
Omg, wow. How are you so fast??

I have to download a new version of Luxtorpeda from ProtonQT-Up, or… it will just work? That’s fucking MAGIC if it just works. I’m not really savvy on compiling builds but I can figure it out if it needs to be a Linux terminal thing.

**Comment by d10sfan** [comment]
For this, the package information is downloaded automatically, so it does not need to update Luxtorpeda itself. I'm hoping it works, but I don't own the games to try it myself. But it should be some straightforward debugging if needed.

**Comment by Arkaium** [comment]
THEY BOTH WORK!! Holy shit man, amazing. I’m going to start telling everyone who gets a Deck to install Luxtorpeda, it’s a MUST.

**Comment by d10sfan** [comment]
@Arkaium Great! I'll go ahead and close this then. Thanks for the new game suggestion.
