### ISSUE TITLE
Classic-RBDoom3BFG for Doom 3: Bethesda.net Edition

### ISSUE THREAD

**Issue by wof8317** [luxtorpeda-dev/packages#659]
### Project Link

https://github.com/MadDeCoDeR/Classic-RBDOOM-3-BFG

### Project License

GPL-3.0

### Steam App Ids

https://steamdb.info/app/1898710/

### Additional Context

For context: Doom 3: Bethesda.net Edition was a discounted version of Doom 3 BFG Edition that originally released in 2019 for then-current-gen consoles and exclusively on the Bethesda.net Client for PC. Since the retirement of said client, Bethesda added that version of Doom 3 on Steam for those who owned it prior to the closure of the Bethesda client. The only major differences between this version and BFG Edition is that it's multiplayer was stripped out in its entirety, it does not include Doom or Doom II and its expansions, the in-game console and the ability to activate it was removed, and has Slayers Club functionality so that one can get an exclusive skin for use in Doom Eternal. Since this uses the same engine as BFG edition, it would make sense to add the Doom BFA (Classic-RBDoom3-BFG) package since it also supports the 2019 rerelease as well as BFG edition (though obviously no Slayers club functionality). There are instructions to make it work on Bethesda.net edition on the project's site itself, so it shouldn't be difficult to integrate.

**Comment by d10sfan** [comment]
@wof8317 

Do you own this game? It does not look like there's a way to get a license at this point, so I wouldn't have any way of testing.

If you own it and are willing, I can push something up to try it and would need some further help debugging if there's any issues.

**Comment by wof8317** [comment]
Yes, I do own it myself, and am willing to help out with testing if needed.

**Comment by d10sfan** [comment]
@wof8317 

I've added it in this commit: https://github.com/luxtorpeda-dev/packages/commit/ed023bc55db7b74e5b276657b88d813c1f4eddf3

It should be live now. Could you test it and let me know if it works? If it does not, please describe the errors and run steam ina  terminal window and copy the log into a file and attach it here.
