### ISSUE TITLE
scummvm engine will read the global/home configuration if it was also installed outside steam

### ISSUE THREAD

**Issue by neuromancer** [luxtorpeda-dev/packages#660]
### Game

Any scummvm game

### Engine

scummvm

### Linux Distribution

ArchLinux

### Luxtorpeda Version

eb07b6ed5dd6e35d703d1b962742e0a6910da254

### Bug description

When luxtorpeda starts scummvm, it reads from the global/home config. So if you have scummvm installed, you can change your local configuration.

### Steps To Reproduce

1. Install scummvm in your OS and change the configuration
2. Close scummvm
3. Start any game using the scummvm engine in luxtorpeda
4. Check the used configuration to see that it can read your global configuration

### Expected Behavior

I expect that luxtorpeda engines will have a separated configuration file and they will not interfere with any other game installed outside steam.

**Comment by d10sfan** [comment]
@neuromancer 

That mainly depends on if scummvm has a way to set where the configuration should be. Some engines like gzdoom provide a -config parameter that allows it to be changed. Do you know if scummvm has something similar?

It looks like this may work: https://docs.scummvm.org/en/latest/advanced_topics/command_line.html

Have you used --config before?

**Comment by neuromancer** [comment]
I haven't use it, but it should work. In fact, it was used [in roberta](https://github.com/dreamer/roberta/blob/master/run-vm#L62) (if it fails for some reason, I will be happy to open an issue in the scummvm issue tracker). The suggested workflow should be:

1. Start with a unique (empty or non-existent) config file per game.
2. Detect any game in the directory where the game is downloaded (usually using `--recursive`)
3. If there is a known game, run it immediately
4. If there is no game at all, then show an error.
5. If there is an unknown version of a game, ask the user to submit a bug report: scummvm will provide the information for that (steam releases for some games are updated from time to time and the hashes will change, so this can happen).

**Comment by d10sfan** [comment]
@neuromancer 

You can see the launch script here if you're interested: https://github.com/luxtorpeda-dev/packages/blob/master/engines/scummvm/assets/run-scummvm.sh

There's a few places it looks to grab paths, and then all of them for the --add step use the recursive flag.

I've added the change that sets the config file to a local one, it will go into ./scum/scummvm.ini:

https://github.com/luxtorpeda-dev/packages/commit/6db852daca305f9f5949b176eeb946be8eb82f59
https://github.com/luxtorpeda-dev/packages/commit/cfa82cac2d2eb87a8ae3b2cd2d52dd74a651a308

So that should complete this item. Let me know if you run into any issues or have any questions.

**Comment by neuromancer** [comment]
I just tested it and this seems to work fine. I will prefer a unique file for every game, but this is fine since it allows to use scummvm without having to worry to change the global config. Thanks!

**Comment by neuromancer** [comment]
Oh, my mistake. This is actually implemented per game, creating a file inside the corresponding folder. That's great!

**Comment by d10sfan** [comment]
> Oh, my mistake. This is actually implemented per game, creating a file inside the corresponding folder. That's great!

Great, glad it worked for you! And yeah it writes it to every game folder, so each game will have their own unique config file.

**Comment by neuromancer** [comment]
Uhm, it seems that this lines `LD_LIBRARY_PATH="lib:$LD_LIBRARY_PATH" ./bin/scummvm -c scummvm.ini --fullscreen --gfx-mode=opengl --themepath=./share/scummvm` produces an override in the gfx-mode, and causes any game to crash during start, even if the game itself is configured using sdlsurface. Removing the `--gfx-mode` option fixes the issue.

**Comment by d10sfan** [comment]
@neuromancer Ah good catch, I've removed that line as well: https://github.com/luxtorpeda-dev/packages/commit/f647180dec39957a39fc4d2bb4f51bef1aecaf3b
