### ISSUE TITLE
Serious Sam TFE Crashes

### ISSUE THREAD

**Issue by daemonspudguy** [luxtorpeda-dev/packages#665]
### Game

Serious Sam Classic: The First Encounter

### Engine

Serious Engine

### Linux Distribution

Arch Linux

### Luxtorpeda Version

53

### Bug description

When launching Serious Sam TFE, the game crashes with the error code "Illegal Instruction" being outputted in Terminal.

### Steps To Reproduce

1. Launch Serious Sam TFE
2. It crashes

### Expected Behavior

The game launches

### Relevant log output

```shell
Illegal instruction (core dumped)
```

**Comment by d10sfan** [comment]
@daemonspudguy 

I just tried it on Arch (Endeavor) Linux and it worked ok.

Could you provide a larger log from the starting point of starting the game? That'll show what the luxtorpeda client was attempting to do at the time.

Also, do you see a popup message about reporting issues? mainly curious if it gets to that point (that's from the engine, not the luxtorpeda client).

**Comment by daemonspudguy** [comment]
No, it doesn't get to that point. And that is legitimately the log output when running the binary.

**Comment by d10sfan** [comment]
Can you try running steam in terminal and then launching the game? The sending a file with the terminal output

**Comment by daemonspudguy** [comment]
`steam.sh[233376]: Running Steam on arch rolling 64-bit
steam.sh[233376]: STEAM_RUNTIME is enabled automatically
setup.sh[233450]: Steam runtime environment up-to-date!
steam.sh[233376]: Steam client's requirements are satisfied
[2022-05-16 15:10:08] Startup - updater built May 14 2022 00:02:57
Installing breakpad exception handler for appid(steam)/version(1652488014)
Looks like steam didn't shutdown cleanly, scheduling immediate update check
[2022-05-16 15:10:09] Loading cached metrics from disk (/home/daemonspudguy/.local/share/Steam/package/steam_client_metrics.bin)
[2022-05-16 15:10:09] Using the following download hosts for Public, Realm steamglobal
[2022-05-16 15:10:09] 1. https://cdn.cloudflare.steamstatic.com, /client/, Realm 'steamglobal', weight was 100, source = 'update_hosts_cached.vdf'
[2022-05-16 15:10:09] 2. https://cdn.akamai.steamstatic.com, /client/, Realm 'steamglobal', weight was 100, source = 'update_hosts_cached.vdf'
[2022-05-16 15:10:09] 3. http://media.steampowered.com, /client/, Realm 'steamglobal', weight was 1, source = 'baked in'
Installing breakpad exception handler for appid(steam)/version(1652488014)
[2022-05-16 15:10:09] Checking for update on startup
[2022-05-16 15:10:09] Checking for available updates...
[2022-05-16 15:10:09] Downloading manifest: https://cdn.cloudflare.steamstatic.com/client/steam_client_ubuntu12
[2022-05-16 15:10:09] Manifest download: send request
Installing breakpad exception handler for appid(steam)/version(1652488014)
[2022-05-16 15:10:09] Manifest download: waiting for download to finish
[2022-05-16 15:10:09] Manifest download: finished
[2022-05-16 15:10:09] Download skipped: /client/steam_client_ubuntu12 version 1652488014, installed version 1652488014, existing pending version 0
[2022-05-16 15:10:09] Nothing to do
[2022-05-16 15:10:09] Verifying installation...
[2022-05-16 15:10:09] Performing checksum verification of executable files
[2022-05-16 15:10:14] Verification complete
Loaded SDL version 2.0.22-7215337
Gtk-Message: Failed to load module "topmenu-gtk-module"
Gtk-Message: Failed to load module "appmenu-gtk-module"
ComputeStartupMode: found registry default startup mode: 0steamwebhelper.sh[233527]: Runtime for steamwebhelper: defaulting to /home/daemonspudguy/.local/share/Steam/ubuntu12_64/steam-runtime-heavy
steamwebhelper.sh[233527]: glibc >= 2.34, partially disabling sandbox until CEF supports clone3()
Installing breakpad exception handler for appid(steam)/version(1652488014)
Fontconfig warning: line 5: unknown element "description"
Fontconfig warning: "/etc/fonts/conf.d/10-hinting-slight.conf", line 4: unknown element "description"
Fontconfig warning: "/etc/fonts/conf.d/10-scale-bitmap-fonts.conf", line 4: unknown element "description"
Fontconfig error: "/etc/fonts/conf.d/10-scale-bitmap-fonts.conf", line 72: non-double matrix element
Fontconfig error: "/etc/fonts/conf.d/10-scale-bitmap-fonts.conf", line 72: non-double matrix element
Fontconfig warning: "/etc/fonts/conf.d/10-scale-bitmap-fonts.conf", line 80: saw unknown, expected number
Fontconfig warning: "/etc/fonts/conf.d/11-lcdfilter-default.conf", line 4: unknown element "description"
Fontconfig warning: "/etc/fonts/conf.d/20-unhint-small-vera.conf", line 4: unknown element "description"
Fontconfig warning: "/etc/fonts/conf.d/30-metric-aliases.conf", line 4: unknown element "description"
Fontconfig warning: "/etc/fonts/conf.d/40-nonlatin.conf", line 4: unknown element "description"
Fontconfig warning: "/etc/fonts/conf.d/45-generic.conf", line 4: unknown element "description"
Fontconfig warning: "/etc/fonts/conf.d/45-latin.conf", line 4: unknown element "description"
Fontconfig warning: "/etc/fonts/conf.d/48-spacing.conf", line 4: unknown element "description"
Fontconfig warning: "/etc/fonts/conf.d/49-sansserif.conf", line 4: unknown element "description"
Fontconfig warning: "/etc/fonts/conf.d/50-user.conf", line 4: unknown element "description"
Fontconfig warning: "/etc/fonts/conf.d/51-local.conf", line 4: unknown element "description"
Fontconfig warning: "/etc/fonts/conf.d/60-generic.conf", line 4: unknown element "description"
Fontconfig warning: "/etc/fonts/conf.d/60-latin.conf", line 4: unknown element "description"
Fontconfig warning: "/etc/fonts/conf.d/65-nonlatin.conf", line 4: unknown element "description"
Could not connect to X session manager: None of the authentication protocols specified are supported
Installing breakpad exception handler for appid(steam)/version(1652488014)
Installing breakpad exception handler for appid(steam)/version(1652488014)
Installing breakpad exception handler for appid(steam)/version(1652488014)
Installing breakpad exception handler for appid(steam)/version(1652488014)
Installing breakpad exception handler for appid(steam)/version(1652488014)
Installing breakpad exception handler for appid(steam)/version(1652488014)
CAppInfoCacheReadFromDiskThread took 78 milliseconds to initialize
Installing breakpad exception handler for appid(steam)/version(1652488014)
Installing breakpad exception handler for appid(steam)/version(1652488014)
Warning: failed to set thread priority: set failed for 8: -1: setpriority() failed
Warning: failed to set thread priority: set failed for priority 8
Warning: support for elevated priorities is most likely unavailable, suppressing future warnings
Installing breakpad exception handler for appid(steam)/version(1652488014)
Warning: failed to set thread priority: set failed for 8: -1: setpriority() failed
Installing breakpad exception handler for appid(steam)/version(1652488014)
Installing breakpad exception handler for appid(steam)/version(1652488014)
Installing breakpad exception handler for appid(steam)/version(1652488014)
Installing breakpad exception handler for appid(steam)/version(1652488014)
Installing breakpad exception handler for appid(steam)/version(1652488014)
Installing breakpad exception handler for appid(steam)/version(1652488014)
Installing breakpad exception handler for appid(steam)/version(1652488014)
Warning: failed to set thread priority: set failed for 8: -1: setpriority() failed
Installing breakpad exception handler for appid(steam)/version(1652488014)
Installing breakpad exception handler for appid(steam)/version(1652488014)
Could not connect to X session manager: None of the authentication protocols specified are supported
Installing breakpad exception handler for appid(steam)/version(1652488014)
Could not connect to X session manager: None of the authentication protocols specified are supported
Installing breakpad exception handler for appid(steam)/version(1652488014)

(steam:233502): Gtk-WARNING **: gtk_disable_setlocale() must be called before gtk_init()
Installing breakpad exception handler for appid(steam)/version(1652488014)
WARNING: radv is not a conformant Vulkan implementation, testing use only.
Installing breakpad exception handler for appid(steam)/version(1652488014)
Installing breakpad exception handler for appid(steam)/version(1652488014)
WARNING: radv is not a conformant Vulkan implementation, testing use only.
roaming config store loaded successfully - 379 bytes.
migrating temporary roaming config store
BRefreshApplicationsInLibrary 1: 10ms
Could not connect to X session manager: None of the authentication protocols specified are supported
Could not connect to X session manager: None of the authentication protocols specified are supported
Could not connect to X session manager: None of the authentication protocols specified are supported
Could not connect to X session manager: None of the authentication protocols specified are supported
Could not connect to X session manager: None of the authentication protocols specified are supported
Could not connect to X session manager: None of the authentication protocols specified are supported
Could not connect to X session manager: None of the authentication protocols specified are supported
Could not connect to X session manager: None of the authentication protocols specified are supported
Installing breakpad exception handler for appid(steam)/version(1652488014)
Could not connect to X session manager: None of the authentication protocols specified are supported
Could not connect to X session manager: None of the authentication protocols specified are supported
Could not connect to X session manager: None of the authentication protocols specified are supported
Could not connect to X session manager: None of the authentication protocols specified are supported
Could not connect to X session manager: None of the authentication protocols specified are supported
Could not connect to X session manager: None of the authentication protocols specified are supported
Installing breakpad exception handler for appid(steam)/version(1652488014)
Could not connect to X session manager: None of the authentication protocols specified are supported
Could not connect to X session manager: None of the authentication protocols specified are supported
Could not connect to X session manager: None of the authentication protocols specified are supported
Could not connect to X session manager: None of the authentication protocols specified are supported
Could not connect to X session manager: None of the authentication protocols specified are supported
Could not connect to X session manager: None of the authentication protocols specified are supported
Could not connect to X session manager: None of the authentication protocols specified are supported
Could not connect to X session manager: None of the authentication protocols specified are supported
Could not connect to X session manager: None of the authentication protocols specified are supported
Could not connect to X session manager: None of the authentication protocols specified are supported
Could not connect to X session manager: None of the authentication protocols specified are supported
Could not connect to X session manager: None of the authentication protocols specified are supported
Failed to init SteamVR because it isn't installed
Could not connect to X session manager: None of the authentication protocols specified are supported
Could not connect to X session manager: None of the authentication protocols specified are supported
Installing breakpad exception handler for appid(steam)/version(1652488014)
Could not connect to X session manager: None of the authentication protocols specified are supported
Could not connect to X session manager: None of the authentication protocols specified are supported
Could not connect to X session manager: None of the authentication protocols specified are supported
Could not connect to X session manager: None of the authentication protocols specified are supported
Could not connect to X session manager: None of the authentication protocols specified are supported
Could not connect to X session manager: None of the authentication protocols specified are supported
Could not connect to X session manager: None of the authentication protocols specified are supported
Could not connect to X session manager: None of the authentication protocols specified are supported
Could not connect to X session manager: None of the authentication protocols specified are supported
Could not connect to X session manager: None of the authentication protocols specified are supported
Could not connect to X session manager: None of the authentication protocols specified are supported
Could not connect to X session manager: None of the authentication protocols specified are supported
Could not connect to X session manager: None of the authentication protocols specified are supported
Could not connect to X session manager: None of the authentication protocols specified are supported
Could not connect to X session manager: None of the authentication protocols specified are supported
Could not connect to X session manager: None of the authentication protocols specified are supported
Could not connect to X session manager: None of the authentication protocols specified are supported
Could not connect to X session manager: None of the authentication protocols specified are supported
Could not connect to X session manager: None of the authentication protocols specified are supported
Could not connect to X session manager: None of the authentication protocols specified are supported
ExecCommandLine: "'/home/daemonspudguy/.local/share/Steam/ubuntu12_32/steam'"
Installing breakpad exception handler for appid(steam)/version(1652488014)
Installing breakpad exception handler for appid(steam)/version(1652488014)
System startup time: 20.47 seconds
Installing breakpad exception handler for appid(steam)/version(1652488014)
Installing breakpad exception handler for appid(steam)/version(1652488014)
Installing breakpad exception handler for appid(steam)/version(1652488014)
Installing breakpad exception handler for appid(steam)/version(1652488014)
Installing breakpad exception handler for appid(steam)/version(1652488014)
Installing breakpad exception handler for appid(steam)/version(1652488014)
BuildCompleteAppOverviewChange: 222
RegisterForAppOverview 1: 50ms
RegisterForAppOverview 2: 50ms
Installing breakpad exception handler for appid(steam)/version(1652488014)
Installing breakpad exception handler for appid(steam)/version(1652488014)
Installing breakpad exception handler for appid(steam)/version(1652488014)
Installing breakpad exception handler for appid(steam)/version(1652488014)
Installing breakpad exception handler for appid(steam)/version(1652488014)
Installing breakpad exception handler for appid(steam)/version(1652488014)
Installing breakpad exception handler for appid(steam)/version(1652488014)
Installing breakpad exception handler for appid(steam)/version(1652488014)
Installing breakpad exception handler for appid(steam)/version(1652488014)
Installing breakpad exception handler for appid(steam)/version(1652488014)
Installing breakpad exception handler for appid(steam)/version(1652488014)
Installing breakpad exception handler for appid(steam)/version(1652488014)
Installing breakpad exception handler for appid(steam)/version(1652488014)
Installing breakpad exception handler for appid(steam)/version(1652488014)
Installing breakpad exception handler for appid(steam)/version(1652488014)
Installing breakpad exception handler for appid(steam)/version(1652488014)
Installing breakpad exception handler for appid(steam)/version(1652488014)
CAPIJobRequestUserStats - Server response failed 2
Installing breakpad exception handler for appid(steam)/version(1652488014)
Installing breakpad exception handler for appid(steam)/version(1652488014)
Installing breakpad exception handler for appid(steam)/version(1652488014)
Could not connect to X session manager: None of the authentication protocols specified are supported
Could not connect to X session manager: None of the authentication protocols specified are supported
Could not connect to X session manager: None of the authentication protocols specified are supported
Could not connect to X session manager: None of the authentication protocols specified are supported
Installing breakpad exception handler for appid(steam)/version(1652488014)
Installing breakpad exception handler for appid(steam)/version(1652488014)
Installing breakpad exception handler for appid(steam)/version(1652488014)
Installing breakpad exception handler for appid(steam)/version(1652488014)
Installing breakpad exception handler for appid(steam)/version(1652488014)
Installing breakpad exception handler for appid(steam)/version(1652488014)
Installing breakpad exception handler for appid(steam)/version(1652488014)
Installing breakpad exception handler for appid(steam)/version(1652488014)
Installing breakpad exception handler for appid(steam)/version(1652488014)
Installing breakpad exception handler for appid(steam)/version(1652488014)
Installing breakpad exception handler for appid(steam)/version(1652488014)
Installing breakpad exception handler for appid(steam)/version(1652488014)
Installing breakpad exception handler for appid(steam)/version(1652488014)
Installing breakpad exception handler for appid(steam)/version(1652488014)
Installing breakpad exception handler for appid(steam)/version(1652488014)
Installing breakpad exception handler for appid(steam)/version(1652488014)
Installing breakpad exception handler for appid(steam)/version(1652488014)
Could not connect to X session manager: None of the authentication protocols specified are supported
Could not connect to X session manager: None of the authentication protocols specified are supported
Could not connect to X session manager: None of the authentication protocols specified are supported
Could not connect to X session manager: None of the authentication protocols specified are supported
Could not connect to X session manager: None of the authentication protocols specified are supported
Installing breakpad exception handler for appid(steam)/version(1652488014)
GameAction [AppID 41050, ActionID 1] : LaunchApp changed task to ShowLaunchOption with ""
GameAction [AppID 41050, ActionID 1] : LaunchApp waiting for user response to ShowLaunchOption ""
Could not connect to X session manager: None of the authentication protocols specified are supported
Could not connect to X session manager: None of the authentication protocols specified are supported
GameAction [AppID 41050, ActionID 1] : LaunchApp continues with user response "0"
GameAction [AppID 41050, ActionID 1] : LaunchApp changed task to ProcessingInstallScript with ""
Installing breakpad exception handler for appid(steam)/version(1652488014)
Installing breakpad exception handler for appid(steam)/version(1652488014)
Installing breakpad exception handler for appid(steam)/version(1652488014)
Installing breakpad exception handler for appid(steam)/version(1652488014)
Installing breakpad exception handler for appid(steam)/version(1652488014)
Error: Custom { kind: Other, error: "iscriptevaluator ignoring" }
GameAction [AppID 41050, ActionID 1] : LaunchApp changed task to SiteLicenseSeatCheckout with ""
GameAction [AppID 41050, ActionID 1] : LaunchApp changed task to CreatingProcess with ""
GameAction [AppID 41050, ActionID 1] : LaunchApp waiting for user response to CreatingProcess ""
GameAction [AppID 41050, ActionID 1] : LaunchApp continues with user response "CreatingProcess"
/bin/sh\0-c\0/home/daemonspudguy/.local/share/Steam/ubuntu12_32/reaper SteamLaunch AppId=41050 -- '/home/daemonspudguy/.local/share/Steam/steamapps/common/SteamLinuxRuntime_soldier'/_v2-entry-point --verb=waitforexitandrun -- '/home/daemonspudguy/.local/share/Steam/compatibilitytools.d/luxtorpeda'/luxtorpeda.sh waitforexitandrun  '/home/daemonspudguy/.local/share/Steam/steamapps/common/Serious Sam Classic The First Encounter/Bin/SeriousSam.exe'\0
Game process added : AppID 41050 "/home/daemonspudguy/.local/share/Steam/ubuntu12_32/reaper SteamLaunch AppId=41050 -- '/home/daemonspudguy/.local/share/Steam/steamapps/common/SteamLinuxRuntime_soldier'/_v2-entry-point --verb=waitforexitandrun -- '/home/daemonspudguy/.local/share/Steam/compatibilitytools.d/luxtorpeda'/luxtorpeda.sh waitforexitandrun  '/home/daemonspudguy/.local/share/Steam/steamapps/common/Serious Sam Classic The First Encounter/Bin/SeriousSam.exe'", ProcID 234178, IP 0.0.0.0:0
chdir /home/daemonspudguy/.local/share/Steam/steamapps/common/Serious Sam Classic The First Encounter
ERROR: ld.so: object '/home/daemonspudguy/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
ERROR: ld.so: object '/home/daemonspudguy/.local/share/Steam/ubuntu12_64/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS64): ignored.
ERROR: ld.so: object '/home/daemonspudguy/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
ERROR: ld.so: object '/home/daemonspudguy/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
ERROR: ld.so: object '/home/daemonspudguy/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
pid 234182 != 234179, skipping destruction (fork without exec?)
GameAction [AppID 41050, ActionID 1] : LaunchApp changed task to WaitingGameWindow with ""
GameAction [AppID 41050, ActionID 1] : LaunchApp changed task to Completed with ""
LD_PRELOAD found with /tmp/pressure-vessel-libs-2Z0RM1/${PLATFORM}/gameoverlayrenderer.so
pid 234333 != 234332, skipping destruction (fork without exec?)
turning virtual gamepad off
SDL_IGNORE_DEVICES not found: environment variable not found
update_packages_json. found hash: f13bd17edd089131592c39090150b17c224a7c96
update_packages_json. found hash and remote hash: f13bd17edd089131592c39090150b17c224a7c96 ad079dc301bdfe3e98faa2101ebde650761b67ef
update_packages_json. hash does not match. downloading
update_packages_json. downloading new packagesruntime.json
update_packages_json. new downloaded hash matches
creating: "/run/user/1000/luxtorpeda/41050.pid"
luxtorpeda version: 53.0.0
steam_app_id: "41050"
original command: ["/home/daemonspudguy/.local/share/Steam/steamapps/common/Serious Sam Classic The First Encounter/Bin/SeriousSam.exe"]
working dir: Ok("/home/daemonspudguy/.local/share/Steam/steamapps/common/Serious Sam Classic The First Encounter")
tool dir: "/home/daemonspudguy/.local/share/Steam/compatibilitytools.d/luxtorpeda"
user_packages_file not found
user_packages_file not found
serious-engine-41050-2.tar.xz found in cache (skip)
json:
{
    "game_name": "Serious Sam Classic: The First Encounter",
    "download": [
        {
            "name": "serious-engine",
            "url": "https://github.com/luxtorpeda-dev/packages/releases/download/serious-engine-2/",
            "file": "serious-engine-41050-2.tar.xz"
        }
    ],
    "command": "./Bin/ssam-tfe",
    "engine_name": "Serious-Engine",
    "cloudNotAvailable": true
}
installing: serious-engine-41050-2
install: "SE1_10.gro"
install: "license"
install: "license/LICENSE.serious-engine"
install: "Bin"
install: "Bin/ssam-tfe"
install: "Bin/libShaders.so"
install: "Bin/libGame.so"
install: "Bin/libEntities.so"
dropping: "/run/user/1000/luxtorpeda/41050.pid"
sending close to run context thread
run: "./Bin/ssam-tfe" with args: [] []
run returned with signal: 4 (core dumped)
Game process removed: AppID 41050 "/home/daemonspudguy/.local/share/Steam/ubuntu12_32/reaper SteamLaunch AppId=41050 -- '/home/daemonspudguy/.local/share/Steam/steamapps/common/SteamLinuxRuntime_soldier'/_v2-entry-point --verb=waitforexitandrun -- '/home/daemonspudguy/.local/share/Steam/compatibilitytools.d/luxtorpeda'/luxtorpeda.sh waitforexitandrun  '/home/daemonspudguy/.local/share/Steam/steamapps/common/Serious Sam Classic The First Encounter/Bin/SeriousSam.exe'", ProcID 234178 
ThreadGetProcessExitCode: no such process 234428
ThreadGetProcessExitCode: no such process 234332
ThreadGetProcessExitCode: no such process 234180
ThreadGetProcessExitCode: no such process 234179
Uploaded AppInterfaceStats to Steam
Installing breakpad exception handler for appid(steam)/version(1652488014)
Installing breakpad exception handler for appid(steam)/version(1652488014)
Could not connect to X session manager: None of the authentication protocols specified are supported
Could not connect to X session manager: None of the authentication protocols specified are supported

`

**Comment by daemonspudguy** [comment]
[steam log.txt](https://github.com/luxtorpeda-dev/packages/files/8702810/steam.log.txt)

**Comment by d10sfan** [comment]
@daemonspudguy Can you also send over what steam outputs for the system information? Are you able to play other opengl games and other luxtorpeda games?

**Comment by daemonspudguy** [comment]
How do I get system info from steam?

**Comment by daemonspudguy** [comment]
[steam system log.txt](https://github.com/luxtorpeda-dev/packages/files/8702992/steam.system.log.txt)

**Comment by daemonspudguy** [comment]
I'm able to play Doom 3 with the dhewm3 engine.

**Comment by d10sfan** [comment]
The vram seems a bit low, but other than that seems pretty normal.

You may want to create a ticket on the Serious-Engine repo (https://github.com/ptitSeb/Serious-Engine), as it looks to be some sort of issue with the engine itself.

You may also want to try building it yourself as well, for reference this is what I'm using to build it: https://github.com/luxtorpeda-dev/packages/blob/master/engines/serious-engine/build.sh

You should be able to run it with gdb and get a backtrace, which may help debug where it's crashing. The luxtorpeda downloaded one should be doable there as well.

If you find anything on any of those paths, please let me know. For now, I'll close this but let me know if there's anything else I can do.

**Comment by daemonspudguy** [comment]
Running the binary with GDB outputs this:
Using host libthread_db library "/usr/lib/libthread_db.so.1".

Program received signal SIGILL, Illegal instruction.
_GLOBAL__sub_I_DepthCheck.cpp(void) () at /__w/packages/packages/engines/serious-engine/source/Sources/Engine/Graphics/DepthCheck.cpp:293
293	in /__w/packages/packages/engines/serious-engine/source/Sources/Engine/Graphics/DepthCheck.cpp

**Comment by daemonspudguy** [comment]
@d10sfan just an update, I tried a compiled version with your script and it segfaults. Seems to be a known issue upstream. Shame the developer seems to have fallen of the face of the planet.

**Comment by d10sfan** [comment]
@daemonspudguy Ah ok, if anyone fixes it or if you find a fork that works better, feel free to ping me here.

**Comment by daemonspudguy** [comment]
I did at least get the game running with Proton. What you have to do to get the textures to not be fucked on an AMD GPU is bring down the console and run the following: gap_iDepthBits=24

ApplyVideoMode()
