### ISSUE TITLE
TES3: Morrowind - OpenMW Nightly With Zesterer's PBR Shaders

### ISSUE THREAD

**Issue by tlneondo** [luxtorpeda-dev/packages#670]
### Project Link

https://github.com/zesterer/openmw-shaders.git

### Project License

NA

### Steam App Ids

https://steamdb.info/app/22320/

### Additional Context

No license is available for the shaders, but OpenMW spends a LONG TIME between releases, and the post processing backend has just been merged. It would be very helpful to have a functioning more up to date build, even if the shaders need to be manually installed.

A periodically updated build would be greatly appreciated.

**Comment by d10sfan** [comment]
I asked about the license for the shaders. Once I have some more information there, I'll look over this again.

**Comment by d10sfan** [comment]
Further progress tracked here: https://github.com/luxtorpeda-dev/packages/pull/671
