### ISSUE TITLE
OpenMW fails to extract

### ISSUE THREAD

**Issue by Fancy2209** [luxtorpeda-dev/packages#675]
### Game

The Elder Scrolls 3: Morrowind

### Engine

OpenMW

### Linux Distribution

Pop!_OS 22.04

### Luxtorpeda Version

v55

### Bug description

After selecting either OpenMW or OpenMW-Launcher, I get this error:
 ``Error unpacking openmw-22320-14.tar.xz: failed to unpack 'dist/include/QTLinuxAccessibilitySupport/5.12.11/QTLinuxAccessibilitySupport/private/atspiadaptor_p' into 'include/QTLinuxAccessibilitySupport/5.12.11/QTLinuxAccessibilitySupport/private/atspiadaptor_p'``

### Steps To Reproduce

1. Try to open Morrowind with Luxtorpeda as the Compatibility Tool
2. Choose either openmw or openmw-launcher (both fail)
3. Get the error while luxtorpeda unpacks openmw

### Expected Behavior

The Package would sucessfully extract and the game would open with openmw

### Additional Context

I  haven't tested with openmw-multiplayer

### Relevant log output

```shell
# I don't know where logs are located, so here's the error it spat:

Error unpacking openmw-22320-14.tar.xz: failed to unpack 'dist/include/QTLinuxAccessibilitySupport/5.12.11/QTLinuxAccessibilitySupport/private/atspiadaptor_p' into 'include/QTLinuxAccessibilitySupport/5.12.11/QTLinuxAccessibilitySupport/private/atspiadaptor_p'
```

**Comment by d10sfan** [comment]
@Fancy2209 What file system are you using?

Also, if you can follow the log instructions in this section - https://github.com/luxtorpeda-dev/luxtorpeda#configuration

And attach the file here, that would be helpful as well.

**Comment by Fancy2209** [comment]
ext4, steam is running out of a external NTFS Drive
Manually extracting with 7z didn't seem to fail, but luxtorpeda will ignore anything it didn't extract.

Here's the log
[luxtorpeda.log](https://github.com/luxtorpeda-dev/packages/files/8808713/luxtorpeda.log)

**Comment by d10sfan** [comment]
@Fancy2209 Ok, this may be related to the steam game folders being used on an NTFS drive, the paths that are needed by qt may be an issue.

I'd recommend trying to install morrowind on an ext4 drive and seeing if it still happens.

**Comment by d10sfan** [comment]
@Fancy2209 Ah ok, I don't think there's anything I can do about that, and you may run into other issues trying to run linux applications on an ntfs drive (like permissions and the like). You could try re-partitioning part of the drive to be ext4, if you have enough space. If you have any further issues or suggestions, please let me know.

**Comment by Fancy2209** [comment]
> @Fancy2209 Ah ok, I don't think there's anything I can do about that, and you may run into other issues trying to run linux applications on an ntfs drive (like permissions and the like). You could try re-partitioning part of the drive to be ext4, if you have enough space. If you have any further issues or suggestions, please let me know.

Ok!
Thanks for all the help
