### ISSUE TITLE
Package Request: doukutsu-rs

### ISSUE THREAD

**Issue by Fancy2209** [luxtorpeda-dev/packages#676]
### Project Link

https://github.com/doukutsu-rs/doukutsu-rs

### Project License

Modified MIT License

### Steam App Ids

https://store.steampowered.com/app/200900/Cave_Story

### Additional Context

While it comes packaged with game data, it is possible to run it with Cave Story+ data by having only the doukutsu-rs executable on the Cave Story+ Folder.
While Cave Story+ has a native linux version, this version provides a load of Improvements and Fixes, at the cost of achivements.

**Comment by d10sfan** [comment]
Thanks for the request and the information. I've added it in https://github.com/luxtorpeda-dev/packages/commit/bc876b7bf6e5126c0b84c91c176beb32619146bd
