### ISSUE TITLE
Serious Sam Classic titles not working

### ISSUE THREAD

**Issue by dragon99919** [luxtorpeda-dev/packages#695]
### Game

Serious Sam Classic: The First Encounter/Serious Sam Classic: The Second Encounter

### Engine

serious-engine

### Linux Distribution

SteamOS on SteamDeck (Desktop Mode)

### Luxtorpeda Version

55

### Bug description

Engine downloads after starting game but then crashes without any error. Trying to launch game again makes it crash again.

### Steps To Reproduce

1. Download Serious Sam Classic FE or SE on Steam.
2. Change compatibility tool to Luxtorpeda.
3. Install and launch game.

### Expected Behavior

Game launching.

**Comment by d10sfan** [comment]
@dragon99919 

I've switched the project used with a different one that's vulkan based, that is more up to date. That should fix the crashing as well (https://github.com/luxtorpeda-dev/packages/commit/479e7f10883abb9cd66b53d178bb5fd695b00266).

Let me know if you still have issues. It should be live about 10-15 minutes after this comment.

**Comment by dragon99919** [comment]
Both games work like a charm now, thanks a lot! : )
