### ISSUE TITLE
Eduke32 for Duke Nukem 3D: 20th Anniversary World Tour 

### ISSUE THREAD

**Issue by cyberconan** [luxtorpeda-dev/packages#698]
### Project Link

https://voidpoint.io/terminx/eduke32

### Project License

https://voidpoint.io/terminx/eduke32/-/blob/master/source/duke3d/gpl-2.0.txt

### Steam App Ids

https://store.steampowered.com/app/434050/Duke_Nukem_3D_20th_Anniversary_World_Tour/

### Additional Context

Hello d10sfan!
Duke Nukem 3D: Megaton Edition is no longer available for purchase on Steam. Instead, I have the 20th anniversary edition and I play eduke32 on archlinux outside of steam without problems using the GRP it provides. Can you include eduke32 among the available engines for this edition in luxtorpeda?
Thank you!!

**Comment by d10sfan** [comment]
@cyberconan Thanks for the issue, I've added it in https://github.com/luxtorpeda-dev/packages/commit/6e0a45bf98fbf81eb244e75418ba216b362f4889

Let me know if you run into any issues.

**Comment by cyberconan** [comment]
Hi d10sfan, the eduke32 version than use luxtorpeda is from 2019, is almost compatible with 20th edition but have some issues and chapters can't be selected, only individual maps. 
![Screenshot_20220701_164718](https://user-images.githubusercontent.com/1497109/176917537-3c3fc4b7-12f9-4900-949c-033c6f226552.png)

Latest Eduke32 versions works perfect. Thanks!!

**Comment by d10sfan** [comment]
@cyberconan The commit that is in use is from 7 months ago. Are you saying that the most recent master branch (https://voidpoint.io/terminx/eduke32) works better?

**Comment by d10sfan** [comment]
@cyberconan I updated eduke32 to the latest master, is it working for you now?

**Comment by cyberconan** [comment]
I have found the problem. Eduke32 don't need GAME.CON and USER.CON files and those files generate the issue.
https://wiki.eduke32.com/wiki/Installation_and_configuration
A dirty trick is rename those files and now Eduke32 runs well and shows the Duke Nukem chapters.
Regards!!

**Comment by d10sfan** [comment]
@cyberconan Thanks for the help! I've fixed this in https://github.com/luxtorpeda-dev/packages/commit/1bc1623f96d77288d6653902f969f32f908801fe

It should work next time you launch the game. Let me know if that works for you as well.
