### ISSUE TITLE
Homeworld SDL for Homeworld Classic

### ISSUE THREAD

**Issue by rea987** [luxtorpeda-dev/packages#701]
### Project Link

https://github.com/HomeworldSDL/HomeworldSDL

### Project License

Relic EULA

### Steam App Ids

https://steamdb.info/app/244160/

### Additional Context

License:
https://github.com/HomeworldSDL/HomeworldSDL/blob/master/LICENSE.txt

Additional info:
https://www.reddit.com/r/homeworld/comments/1u3w1r/homeworld_open_source_projects_and_free/

Homeworld Remastered Collection contains Homeworld Classic which should be compatible with Homeworld SDL.

**Comment by d10sfan** [comment]
@rea987 

It looks like this project is not compatible with the steam version of the assets. I created an issue here to see if there's a resolution: https://github.com/HomeworldSDL/HomeworldSDL/issues/11

My progress so far on the building of the project: https://github.com/luxtorpeda-dev/packages/pull/704

**Comment by d10sfan** [comment]
I found a different project (https://github.com/GardensOfKadesh/Homeworld) that has support for the remaster. Working on supporting it instead.

**Comment by d10sfan** [comment]
@rea987 Added in https://github.com/luxtorpeda-dev/packages/commit/e06e322d2f5a1617c77cef7157970b9fdf765a8d

**Comment by rea987** [comment]
@d10sfan Gardens of Kadesh utilizes Homeworld Classic, right? Also, I am unable to make the game fullscreen with `F11` or `Alt+Enter`; which button(s) switch to fullscreen?

**Comment by d10sfan** [comment]
@rea987 Yes, this uses homeworld classic. it does not look like there's a way to go fullscreen, I'm able with kde to remove the window decoration. I tried setting the ~/.homeworld config file to say fullscreen but that does not do anything either. That would have to be something to be added by the upstream project.
