### ISSUE TITLE
Save file is created for Witchaven 1 & 2, but can't be accessed from in-game load menu

### ISSUE THREAD

**Issue by vasdfj** [luxtorpeda-dev/packages#705]
### Game

Witchaven 1 & 2

### Engine

BuildGDX

### Linux Distribution

KDE neon User - 5.25 x86_64

### Luxtorpeda Version

55

### Bug description

When attempting to save a file in either Witchaven 1 or 2, the .sav file is created, and exists along with the .ini file, which is itself read correctly at startup. When saving, and then accessing the load screen, the save file is actually displayed in the same session as it was created, but any attempts to load from it fail. Subsequent sessions in Witchaven fail to have the save file display in the load menu at all. Absolute path for .sav, .ini, & .log = "/home/$USER/.local/share/Steam/steamapps/common/Witchaven/Enhanced/GAME/"

### Steps To Reproduce

1. Create a save game
2. If in the same session, attempt to load save game
3. The save will fail to load
4. Upon exiting the game, after creating a save
5. Re-launch the game, and attempt to load the previously made save
6. The save file will fail to appear in the menu

### Expected Behavior

The save is created, and is able to be loaded from; either from the same session, or any and all future game sessions, provided the save file hasn't been deleted.

### Additional Context

Witchaven 2 behaves the exact same way, and the file paths are virtually the same. 

Thank you to the devs, I appreciate your work! Everything else I've used so far via luxtorpeda has worked without issue. I don't know if I've provided enough information to help resolve this issue, but I'm willing to try again if necessary. :)

### Relevant log output

```shell
BUILD engine by Ken Silverman (http://www.advsys.net/ken) 
WitchavenGDX v1.16(BuildGdx v21.113) by [M210???] (http://m210.duke4.net)
Current date Jul 05, 2022 02:48:10
Running on Linux (version 5.13.0-52-generic)
	 with JRE version: 11.0.12

Initializing resource archives
Initializing Build 3D engine
Loading palettes
Loading gamma correction tables
Loading translucency table
Polymost renderer is initialized
AMD Radeon RX 580 Series (polaris10, LLVM 14.0.5, DRM 3.41, 5.13.0-52-generic) 4.6 (Compatibility Profile) Mesa 22.1.2 - kisak-mesa PPA
TextureCache uninited!
Found controller: "Microsoft X-Box 360 pad" [buttons: 17 axises: 6 povs: 1]
Found controller: "Corsair CORSAIR GLAIVE RGB PRO Gaming Mouse" [buttons: 32 axises: 0 povs: 0]
Initializing on-screen display system
Initializing fade effects
OpenAL Soft initialized
	with max voices: 32
	OpenAL version: 1.1 ALSOFT 1.15.1
ALC_EXT_EFX enabled.
AL_SOFT_Source_Resampler not supported!
Gervill initialized
Initializing def-scripts...
Found 124 files in whgdx.dat archive
Loading whgdx.dat...
Initializing autoload folder
Initializing cutscenes
TextureCache uninited!
```

**Comment by d10sfan** [comment]
I am able to replicate this. This appears to be an issue with the upstream engine as this is just using the built version from the BuildGDX project. I'm not sure as to a resolution as this time.

**Comment by d10sfan** [comment]
@vasdfj 

I attempted to get some help from upstream and have done some stuff myself as well, to no avail. For now, I've removed BuildGDX as an engine, but will add it back if this gets resolved. In the meantime, Witchaven games are now supported by dosbox-staging. If  BuildGDX works again, I'll have both as engine choices for those games.
