### ISSUE TITLE
RVGL for Re-Volt

### ISSUE THREAD

**Issue by NerosTie** [luxtorpeda-dev/packages#707]
### Project Link

https://gitlab.com/re-volt/rvgl-base

### Project License

Unknown 

### Steam App Ids

- https://steamdb.info/app/287310/

### Additional Context

Official websites: 
- https://rvgl.org/
- https://re-volt.io/downloads/game

**Comment by d10sfan** [comment]
@NerosTie Thanks for the request, I've implemented this and it should also work on the steam deck.

**Comment by Gotolei** [comment]
The [main download link for this](https://github.com/luxtorpeda-dev/packages/blob/41e7a93f1a3a03addc460ec769c0a876ecae236b/metadata/packagessniper.json#L5263) now 404s, as the game itself has been updated from 21.0930a-1 to 23.0602a1. This particular link will change every time the game updates.

A more durable way to take care of it would be to use the [rvgl_linux](https://distribute.re-volt.io/packs/rvgl_linux.zip) and [rvgl_assets](https://distribute.re-volt.io/packs/rvgl_assets.zip) downloads from distribute.re-volt.io: those are the same downloads rvgl's official launcher uses, and the only difference between the two of those together and the versioned links used currently in luxtorpeda are four empty folders which are created automatically when the game is run.

```
$ diff -qr 'versioned link' 'from dist'
Only in versioned link: cache
Only in versioned link: profiles
Only in versioned link: replays
Only in versioned link: times
```

**Comment by d10sfan** [comment]
@Gotolei Thanks for the heads up, I've updated it to use those downloads, so it should work now.

https://github.com/luxtorpeda-dev/packages/commit/6fdfb126652ed1e41f4b0e20a6046309b4403f1c
https://github.com/luxtorpeda-dev/packages/commit/60d9cb9dcf51c3b903703d1b6e779374221c6fcd
