### ISSUE TITLE
Update dxx-rebirth to newest build

### ISSUE THREAD

**Issue by agibson2** [luxtorpeda-dev/packages#711]
### Feature Request

The current version of Descent 2 that people are using on the Descent and Descent Rangers Discord seem to be version 0.61.0 and that matches luxtorpeda but the multiplayer protocol mismatches.  They are just downloading the windows exe from the dxx-rebirth website.  They seem to have protocol 14 and what is included with luxtorpeda is 12.  Likely it needs to be rebuilt for the newest build.  (I haven't tested Descent 1 multiplayer yet to test that but likely the same). 

### Solution

Update to latest build from the dxx-rebirth source.  Someone on the Descent discord mentioned that it might be known about linux vs windows protocol mismatch.  Maybe that is because the linux version just hasn't been recompiled as often as the windows version and they just aren't bumping the version.

**Comment by d10sfan** [comment]
Since this is related to a game/engine, this has been moved to the packages repo.

Looks like this is the latest commit that was used for Windows, I'll work on updating to that: https://github.com/dxx-rebirth/dxx-rebirth/commit/d1ed53ebd9cb9bad753c5e25331a184461338d9e

**Comment by agibson2** [comment]
Thanks!  I didn't realize there was a packages repo... I should have checked.  I just want to say a big thank you for this work.  I have been playing a lot Steam Deck because of your work.  Playing a good updated version of d1 and d2 on Steam Deck is really amazing and was super easy with luxtorpeda.  Windows needs a windorspeda to get rebirth to the rest of the masses :).

**Comment by d10sfan** [comment]
No worries :)

And thanks, I appreciate that!

The updated build is now live, let me know how that goes.

**Comment by agibson2** [comment]
It works.  I was able to join others on the Descent Discord channel without a protocol error.  Thanks!
