### ISSUE TITLE
Doom64

### ISSUE THREAD

**Issue by neuromancer** [luxtorpeda-dev/packages#717]
### Project Link

https://github.com/atsb/Doom64EX-Plus

### Project License

GPL2

### Steam App Ids

https://store.steampowered.com/app/1148590/DOOM_64/

### Additional Context

It could require a few steps to convert the provided data into the format needed by this reimplementation.

**Comment by d10sfan** [comment]
@neuromancer I dont see how this could be used with the Steam version, do you know of a way that could convert the data from the steam version into something that this could use?

I saw that someone created a Windows exe a while back to convert for doom64ex, but it's out of date from last I saw, and that wouldn't be easily run, since it isn't native.

**Comment by neuromancer** [comment]
Let me do a little research on this one

**Comment by neuromancer** [comment]
I already asked for a [feature request](https://github.com/atsb/Doom64EX-Plus/issues/5). In the meantime, I did some experiment with binary patching using xdelta. The file provided by Steam has around 15MB and the one required by Doom64ex is around 8MB (it features less content, in fact). A binary patch between these is 2.3 MB so they clearly share a lot, but I don't know if this is an acceptable solution for you or not.

**Comment by d10sfan** [comment]
@neuromancer If we have to somehow have the one required by the engine, then probably not, since that would make it unusable for most people. If this is doable with some script that can do it to the steam wad, without needing the one that is normally used from the rom, that's preferred.

**Comment by neuromancer** [comment]
The binary patch allows to obtain the required WAD for Doom64ex0 from the one provided in Steam. The question is if distributing a 2.3 MB file which will contain some part required WAD file (which is part of the original Doom64 ROM) is legal or not in this context.

**Comment by d10sfan** [comment]
I don't think so personally, hopefully there's another way.

**Comment by d10sfan** [comment]
Closing this for now, but feel free to comment if you find a way that'll be workable.

**Comment by dpanter** [comment]
From the readme on the project page, it seems to work with the provided IWAD found in the game directory without any modification.
> Support for the IWAD from Nightdive Studios' official remaster.

So `DOOM64.WAD` is provided by the game and the other two required files (`doom64ex-plus.wad` & `doomsnd.sf2`) are provided by Doom64EX-Plus. Good to go?

**Comment by d10sfan** [comment]
It's been added, it may take a bit longer to take affect since github actions are running into issues.

**Comment by d10sfan** [comment]
Let me know once it's available if you run into any issues.

**Comment by d10sfan** [comment]
It should be live now!
