### ISSUE TITLE
Sonic Mania

### ISSUE THREAD

**Issue by KawaiiDinosaur** [luxtorpeda-dev/packages#719]
### Project Link

https://github.com/Rubberduckycooly/Sonic-Mania-Decompilation

### Project License

None

### Steam App Ids

https://steamdb.info/app/584400/

### Additional Context

Native > Proton

**Comment by d10sfan** [comment]
These sort of projects are in a strange place legally so I prefer not to use them, especially since there is no license. You can if you want use their releases or build their code and then use the user packages feature to add custom games to the client.
