### ISSUE TITLE
Daggerfall unity not launching

### ISSUE THREAD

**Issue by DuendeInexistente** [luxtorpeda-dev/packages#722]
### Game

The Elder Scrolls: Daggerfall

### Engine

Daggerfall Unity

### Linux Distribution

Ubuntu 22, 64 bits

### Luxtorpeda Version

57

### Bug description

Daggerfall isn't launching. 

### Steps To Reproduce

Trying to launch it.

### Expected Behavior

It launching.

### Relevant log output

```shell
16:27:29 [INFO] install: "../DaggerfallUnity_Data/resources.assets.resS"
16:27:29 [INFO] install: "../DaggerfallUnity_Data/globalgamemanagers.assets"
16:27:30 [INFO] install: "../DaggerfallUnity.x86_64"
16:27:30 [INFO] install: "../UnityPlayer_s.debug"
16:27:30 [INFO] install: "../UnityPlayer.so"
16:27:30 [INFO] install: "../LinuxPlayer_s.debug"
16:27:30 [INFO] installing: daggerfall-unity-1812390-4
16:27:30 [INFO] install: "license"
16:27:30 [INFO] install: "license/LICENSE.daggerfall-unity"
16:27:30 [INFO] install: "run-daggerfall-unity.sh"
16:27:30 [INFO] run: "./run-daggerfall-unity.sh" with args: [] ["-noconsole", "-conf", "df.conf", "-fullscreen"]
./run-daggerfall-unity.sh: line 30: /scout-on-soldier-entry-point-v2: No such file or directory
pid 16518 != 16516, skipping destruction (fork without exec?)
16:27:30 [INFO] run returned with exit status: 127
Game process removed: AppID 1812390 "/media/cammera/ExtStor/Juegos/.steam/debian-installation/ubuntu12_32/reaper SteamLaunch AppId=1812390 -- '/media/cammera/ExtStor/Juegos/SteamLibrary/steamapps/common/SteamLinuxRuntime_soldier'/_v2-entry-point --verb=waitforexitandrun -- '/media/cammera/ExtStor/Juegos/.steam/debian-installation/compatibilitytools.d/luxtorpeda'/luxtorpeda.sh waitforexitandrun  '/media/cammera/ExtStor/Juegos/.steam/debian-installation/steamapps/common/The Elder Scrolls Daggerfall/DOSBox-0.74/DOSBox.exe' -noconsole -conf df.conf -fullscreen", ProcID 16269 
ThreadGetProcessExitCode: no such process 16517
ThreadGetProcessExitCode: no such process 16516
ThreadGetProcessExitCode: no such process 16479
ThreadGetProcessExitCode: no such process 16272
ThreadGetProcessExitCode: no such process 16271
ThreadGetProcessExitCode: no such process 16270
Uploaded AppInterfaceStats to Steam
Gtk-Message: 13:28:11.937: Failed to load module "xapp-gtk3-module"
Gtk-Message: 13:28:11.984: Failed to load module "xapp-gtk3-module"
src/steamexe/main.cpp (254) : Assertion Failed: reaping pid: 16571 -- steam
```

**Comment by d10sfan** [comment]
@DuendeInexistente It looks like for both Daggerfall and Entropy Zero, the issue is that the scout-on-soldier-entry-point-v2 file is missing. You should have this installed  - https://steamdb.info/app/1070560/history/

which provides a SteamLinuxRuntime folder. This should be detected by an automatic steam app installation detection, to find the right folder, where when it asks you is a fallback.

Can you see if the Steam Linux Runtime is installed and if not try installing it? For future use, if it wasn't installed, I can provide some clearer error messages if it does not exist at all.

**Comment by DuendeInexistente** [comment]
Oh, I had SLR- Soldier installed but not the base package. Installing it let daggerfall launch just fine.

For anyone else who wanders here, clicking the steamdb link above's Install didn't make anything happen, I had to go to steam and manually enable tools in the library to get the runtime appear for installation.

**Comment by d10sfan** [comment]
@DuendeInexistente Thanks for the update, I've added an error that'll show up for the future for this case, so it'll be easier to see what the issue is. Glad it's working for you now!
