### ISSUE TITLE
Luxtorpeda/ScummVM, running Thief I

### ISSUE THREAD

**Issue by garrett85** [luxtorpeda-dev/packages#729]
Some games I'm able to run just fine with Luxtorpeda, I just got through playing Blood on my Linux system using Luxtorpeda and it worked fine. After setting the compatability mode to Lux in the Manage settings in Steam all I had to do was click Play and the game launched, I'm not having the same kind of luck with Thief I. When I try the same thing with Thief I, after clicking Play a menu comes up called ScummVM. So I click Add Game and it opens a brows windows and the windows is already in the game's wine install directory. After click select directory/folder I get an error message telling me that here's now game in the specified directory. That might now be the exact working but that's the gist of it. Any ideas? Anyone else go this to work? Thanks.

**Comment by d10sfan** [comment]
@garrett85 Are you talking about Thief Gold, or a different game? I had to transfer this to the packages repo, as this is related to a engine package, not the client.

Can you send some information showing that ScummVM supports that game?
