### ISSUE TITLE
Update dxx-rebirth (Descent 1 and Descent 2) to git commit 366b048 (fix protocol mismatch on multiplayer games)

### ISSUE THREAD

**Issue by agibson2** [luxtorpeda-dev/packages#731]
### Game

dxx-rebirth (Descent 1 and Descent 2 on Steam)

### Engine

Native?

### Linux Distribution

SteamOS 3.3 (Steam Deck)

### Luxtorpeda Version

Not sure how to check Luxtorpeda version on Steam Deck

### Bug description

Dxx-rebirth has published a new Windows build on their website.  They reference git commit on (https://github.com/dxx-rebirth/dxx-rebirth/commit/366b048879d62a3096357509fc856dde1abfb7ff) of https://github.com/dxx-rebirth/dxx-rebirth where they changed the multiplayer protocol. The current Luxtorpeda dxx-rebirth for D1 and D2 multiplayer is now not compatible with the officially published dxx-rebirth windows build on the dxx-rebirth website. Any chance to get it updated again? Please :).

### Steps To Reproduce

Run Descent 1 or Descent 2 and try to host a multiplayer game.  When someone with the latest official dxx-rebirth Windows exe build connects to your hosted game (Luxtorpeda build), a protocol mismatch is shown (protocol 14 for Luxtorpeda and 16 for current build on dxx-rebirth site).

### Expected Behavior

Protocols to match and allow clients to connect multiplayer.

**Comment by agibson2** [comment]
There is a discussion about how dxx-rebirth handles updates and how they post them.  They are asking if there are any minor changes that might help Luxtorpeda be able to keep things updated to the current build.  I don't have enough experience in either projects to comment on that but wanted to make it know in case someone at Luxtorpeda would have an opinion.

https://github.com/dxx-rebirth/dxx-rebirth/issues/660

**Comment by d10sfan** [comment]
@agibson2 I've updated dxx-rebirth to the commit you gave. It should be live about 20-30 minutes after this comment. I rely on github releases to email me and/or people notifying me when there's new releases. I'll comment on that ticket to see if they could do github releases in the future.

In the meantime, if they have a release, feel free to comment in this ticket about it.

**Comment by d10sfan** [comment]
@agibson2 There's a compile issue with the most recent release, so it may take more time than I thought. I'll update here once I've completed it.

**Comment by d10sfan** [comment]
@agibson2 You can use this PR to track the progress of it, once it's merged it'll be live: https://github.com/luxtorpeda-dev/packages/pull/732

**Comment by d10sfan** [comment]
@agibson2 I've fixed the compile issue, so it should be ready in a few hours ([dxx-rebirth - Update to 366b048879d62a3096357509fc856dde1abfb7ff](https://github.com/luxtorpeda-dev/packages/commit/2ba088de0e703cbcaab8758d2ef7a2f57b7e5da9)).

Once this action is complete (https://github.com/luxtorpeda-dev/packages/actions/runs/2966717501), it will be live.

**Comment by agibson2** [comment]
I got the update and tested it.  Works great multiplayer with the official .exe build on the dxx-rebirth website.  Multiplayer protocol 16 matches.  Thanks!
