### ISSUE TITLE
OpenXRay is feature complete for S.T.A.L.K.E.R.: Call of Pripyat

### ISSUE THREAD

**Issue by Xottab-DUTY** [luxtorpeda-dev/packages#734]
Hi there!

Is it possible to mark the OpenXRay engine as feature complete for Call of Pripyat? (it always was, we don't need to update the package to a new engine version)

Clear Sky support implementation is not finished, though, so for this game it's not feature complete.

![image](https://user-images.githubusercontent.com/2989212/187576868-36b12f1c-047e-4eca-8a1e-362d08b9123e.png)

**Comment by d10sfan** [comment]
@Xottab-DUTY Thanks for the issue and sure, I can do that! I'll update the issue once that's completed.

**Comment by d10sfan** [comment]
@Xottab-DUTY The change should be live now. You may need to clear cache to see it.

**Comment by Xottab-DUTY** [comment]
@d10sfan thanks :)

**Comment by neuromancer** [comment]
It seems that OpenXRay is down? https://old.reddit.com/r/stalker/comments/191za99/gsc_has_issued_dmca_takedowns_for_all/

**Comment by d10sfan** [comment]
Looks like it may be a false claim https://www.reddit.com/r/stalker/comments/192271z/gsc_twitter_confirms_open_xray_dmca_was_false/?utm_source=reddit&utm_medium=usertext&utm_name=stalker&utm_content=t1_kgzhqf3
