### ISSUE TITLE
OpenMW Launcher woes

### ISSUE THREAD

**Issue by dmrickey** [luxtorpeda-dev/packages#736]
### Linux Distribution

Steam Deck 3.3.1

### Luxtorpeda Version

59

### Bug description

I set Morrowind to launch "OpenMW Launcher (latest) with zoraster's shader". Every time I launch it asks if I want to run the importer wizard which should only happen the first time. If I skip the wizard, it takes me to an instance of the launcher that's different than if I go into the wizard and hit cancel.

I can tell this is different because if I skip the wizard, the "current content list" only has one option (and not the one I'm wanting), whereas if I go into the wizard and cancel, then it has the choices I'm expecting and I can choose the right list from the mod list.

Well, at least that's what I thought was happening, after trying a few more times, it seems like it doesn't always load the lists I'm expecting. Also when I actually launch the game, it's completely ignoring the content list and just loading Morrowind/Bloodmoon/Tribunal

### Steps To Reproduce

1. Set morrowind to one of the OMW launcher options
2. It asks to import mods, if you've got morrowind configured with mods, do this
3. Configure some extra mods
4. Launch the game
5. None of the mods are loaded
6. Quit and restart morrowind - opens the launcher back up
7. It again asks to import mods

### Expected Behavior

The launcher should launch the games with the chosen mods and not prompt to reimport settings every time its launched.

Is it downloading the latest every time it's launched? If that's what's happening, is there a way to make it download the latest _once_ and then just use what it's already downloaded? (that doesn't really explain why it's not actually launching with mods, though)

**Comment by d10sfan** [comment]
@dmrickey Since this is related to an engine, I've moved it to the packages repo.

The "latest" has a specific version in mind, so it won't be updating to a new one if that's what you mean.

When you say you skip the wizard, did you let the wizard complete at least once? Because that would be required for it to work, but it shouldn't ask you after that if it's successful.

Could you send a screenshot of what your mods/launcher settings look like?

Also, does the same thing happen with the non-latest launcher?

**Comment by dmrickey** [comment]
The wizard completed, it wouldn't have known where the Morrowind installation location was otherwise. But it kept prompting me to run the wizard even though it had run the first time. 

I tried the "latest with zetesters shaders launcher" and "latest with zetesters _just openmw_" (non-launcher) to see if just running the executable would use the mods configured (it didn't). I didn't try any of the other luxtorpeda compatibility options.

In the end I found a v0.48 build that was posted on the openmw forums and just dropped it in my desktop and ran that and it worked just fine for be.

Which specific part do you want a screenshot of? (There are a lot of different tabs for the openmw launcher's various settings). I configured it just how I was used to in Windows and the same as I did for the build I dropped on my desktop. But like I said it was like it was ignoring the selectedb plugins when I ran the launcher through luxtorpeda -- openmw itself worked fine including all of the stuff I tweaked in the launcher (except no mods).

Which part do you want a screenshot of?

I'll try to get time tonight to take some pictures and upload those but I'm leaving for vacation tonight and won't have access to internet for a while after I leave, so I may not have time to take screenshots before then.

And just in case I didn't state it clearly above, I did not try the non-latest launcher. I can also give that a try to see how that behaves for me

**Comment by d10sfan** [comment]
@dmrickey Yes, if you can try the non-latest launcher as a comparsion, that would be helpful.

**Comment by d10sfan** [comment]
@dmrickey I had a chance to look at it again and found the same issue, from a fresh start. Thanks for your patience on the fix.

I've got a commit (https://github.com/luxtorpeda-dev/packages/commit/5b0eb5c312ca12b7b20819a59a09719d5fc8047b) that should fix the issue.

Once this action (https://github.com/luxtorpeda-dev/packages/actions/runs/3034402977) is complete, which should be about two hours from this comment, it should be live.

 Let me know if you continue to have any issues. You may want to try deleting the openmw-latest folder inside the Morrowind installation.

**Comment by dmrickey** [comment]
Thanks. I wasn't able to try the different options before I didn't have internet before I left.  I'm back in "phone land" but don't have access to stable internet yet. I'm glad you were able to repro it without me. I'll try it out this next weekend when I'm back home and report back
