### ISSUE TITLE
Heretic: Shadow of The Serpent Riders modern port: Crispy Heretic

### ISSUE THREAD

**Issue by hfc2x** [luxtorpeda-dev/packages#738]
### Project Link

https://github.com/fabiangreffrath/crispy-doom

### Project License

GPLv2

### Steam App Ids

https://steamdb.info/app/2390/

### Additional Context

This engine is vanilla-compatible, and therefore is compatible with Steam Cloud for saves. It's also multiplayer-compatible with Chocolate Heretic. It features enhancements like higher resolution, permanent mouselook, and totals in the in-game map for completionists.

**Comment by d10sfan** [comment]
@hfc2x Thanks for the request. I've finished this in https://github.com/luxtorpeda-dev/packages/commit/27aca86dcabbb2facc7f1d0cc63da3aa18b2a701

The next time you launch the game(s), it should show as an option. Let me know if you run into any issues.

**Comment by hfc2x** [comment]
I launched the game, but there's no music, even though it's configured (using FluidSynth). It seems the game is not detecting that FluidSynth is installed, and it's ignoring it, but only when launching through Steam.

**Comment by d10sfan** [comment]
@hfc2x Strange, I can hear the music just fine, both in the menu and in-game.

Did you change any settings in the setup? If so, can you try a fresh start and see if you can hear the music?

**Comment by hfc2x** [comment]
Yes, I've been playing this game for years, so I know how to configure it. I'll explain how I have it set up:

I've set up the Steam launch options with the following arguments:
`-config ./crispy-doom/heretic.cfg -extraconfig ./crispy-doom/crispy-heretic.cfg -savedir ./base/savegames`

Screenshot:
![Heretic launch options](https://user-images.githubusercontent.com/8249996/189742666-12ec78fb-7730-4a10-b6b1-9ff338b10467.png)


**-config ./crispy-doom/heretic.cfg**
What this does is load the local configuration file for the source port from the "crispy-doom" folder, which is located inside the "Heretic Shadow of the Serpent Riders" folder. The relative path is set like that, because Steam takes the latter as the base folder for launching the game, so every parameter is relative to this folder. If the `-config` parameter is not specified, it will try looking for the configuration file located at `/home/[user]/.local/share/crispy-doom/` instead. `-config` applies only to the configuration file expected by Heretic as a game, while `-extraconfig` is for the configuration that pertains to settings that are exclusive to the Crispy Doom/Heretic source port.

**-savedir ./base/savegames**
This parameter specifies the directory where the Steam saves for this game are. If this is not specified, the program will use the folder `/home/[user]/.local/share/crispy-doom/savegames/heretic.wad` instead. Same logic regarding relative paths as above applies.

Here are my configuration files, which are the ones I specified above (changed the extension from *.cfg to *.txt):
[heretic.txt](https://github.com/luxtorpeda-dev/packages/files/9551237/heretic.txt)
[crispy-heretic.txt](https://github.com/luxtorpeda-dev/packages/files/9551236/crispy-heretic.txt)

When running Steam from the terminal, it outputs the following:
```
19:39:33 [INFO] setup_logging success
19:39:33 [INFO] turning virtual gamepad off
19:39:33 [INFO] update_packages_json. found hash: 44b562368cddf1282d965036d729f446e6a16a66
19:39:33 [INFO] update_packages_json. found hash and remote hash: 44b562368cddf1282d965036d729f446e6a16a66 44b562368cddf1282d965036d729f446e6a16a66
19:39:33 [INFO] luxtorpeda version: 56.0.0
19:39:33 [INFO] steam_app_id: "2390"
19:39:33 [INFO] original command: ["/home/redacted/Press F/Steam/steamapps/common/Heretic Shadow of the Serpent Riders/base/dosbox.exe", "base\\heretic.exe", "-conf", "base\\heretic.conf", "-fullscreen", "-exit", "-config", "./crispy-doom/heretic.cfg", "-extraconfig", "./crispy-doom/crispy-heretic.cfg", "-savedir", "./base/savegames"]
19:39:33 [INFO] working dir: Ok("/home/redacted/Press F/Steam/steamapps/common/Heretic Shadow of the Serpent Riders")
19:39:33 [INFO] tool dir: "/home/redacted/.local/share/Steam/compatibilitytools.d/luxtorpeda-dev"
19:39:33 [INFO] user_packages_file not found
19:39:33 [INFO] user_packages_file not found
19:39:33 [INFO] showing engine choices
19:39:33 [INFO] show choice. found default choice.
19:39:33 [INFO] show choice. found default choice. choice is "Crispy Doom"
19:39:33 [INFO] LUX_DISABLE_DEFAULT_CONFIRM not found: environment variable not found
19:39:33 [INFO] window is on display_index: 0 on_steam_deck: false steam_deck_gaming_mode: false
19:39:33 [INFO] found dpi: (141.67935, 141.76744, 141.40207) using dpi: 141.76744
19:39:33 [INFO] using scaled_width: 705 scaled_height: 211
19:39:33 [INFO] using dpi scaling of 1.8459301
19:39:34 [INFO] 0 joysticks available
found dpi: (141.67935, 141.76744, 141.40207)
using dpi_value: 141.76744
19:39:38 [INFO] engine choice complete
19:39:38 [INFO] crispy-doom-common-1.tar.xz found in cache (skip)
19:39:38 [INFO] engine choice complete
19:39:38 [INFO] json:
19:39:38 [INFO] {
    "game_name": "Heretic: Shadow of the Serpent Riders",
    "download": [
        {
            "name": "crispy-doom",
            "url": "https://github.com/luxtorpeda-dev/packages/releases/download/crispy-doom-1/",
            "file": "crispy-doom-common-1.tar.xz",
            "cache_by_name": true
        }
    ],
    "cloudAvailable": true,
    "command": "./crispy-doom/run-crispy-heretic.sh",
    "command_args": [
        "-iwad",
        "../base/HERETIC.WAD"
    ],
    "download_config": {
        "crispy-doom": {
            "extract_location": "./crispy-doom"
        }
    }
}
19:39:38 [INFO] installing: crispy-doom-common-1
19:39:38 [INFO] install changing extract location with config ./crispy-doom
19:39:38 [INFO] install: "./crispy-doom/crispy-heretic"
19:39:38 [INFO] install: "./crispy-doom/crispy-hexen-setup"
19:39:38 [INFO] install: "./crispy-doom/lib"
19:39:38 [INFO] install: "./crispy-doom/lib/libfluidsynth.so"
19:39:38 [INFO] install: "./crispy-doom/lib/libfluidsynth.so.3"
19:39:38 [INFO] install: "./crispy-doom/lib/libfluidsynth.so.3.0.5"
19:39:38 [INFO] install: "./crispy-doom/crispy-doom-setup"
19:39:38 [INFO] install: "./crispy-doom/run-crispy-hexen.sh"
19:39:38 [INFO] install: "./crispy-doom/crispy-server"
19:39:38 [INFO] install: "./crispy-doom/crispy-heretic-setup"
19:39:38 [INFO] install: "./crispy-doom/run-crispy-heretic-setup.sh"
19:39:38 [INFO] install: "./crispy-doom/crispy-hexen"
19:39:38 [INFO] install: "./crispy-doom/license"
19:39:38 [INFO] install: "./crispy-doom/license/fluidsynth.LICENSE"
19:39:38 [INFO] install: "./crispy-doom/license/LICENSE.crispy-doom"
19:39:38 [INFO] install: "./crispy-doom/run-crispy-hexen-setup.sh"
19:39:38 [INFO] install: "./crispy-doom/crispy-doom"
19:39:38 [INFO] install: "./crispy-doom/run-crispy-heretic.sh"
19:39:38 [INFO] run: "./crispy-doom/run-crispy-heretic.sh" with args: ["-iwad", "../base/HERETIC.WAD"] ["base\\heretic.exe", "-conf", "base\\heretic.conf", "-fullscreen", "-exit", "-config", "./crispy-doom/heretic.cfg", "-extraconfig", "./crispy-doom/crispy-heretic.cfg", "-savedir", "./base/savegames"]
pid 1917296 != 1917295, skipping destruction (fork without exec?)
                          Crispy Doom 5.12.0
V_Init: allocate screens.
Using /home/redacted/.local/share/crispy-doom/ for configuration and saves
M_LoadDefaults: Load system defaults.
        default file: ./crispy-doom/heretic.cfg
saving config in ./crispy-doom/heretic.cfg
        extra configuration file: ./crispy-doom/crispy-heretic.cfg
Z_Init: Init zone memory allocation daemon.
zone memory: 0x7feaa7dfe010, 32 MiB allocated for zone
W_Init: Init WADfiles.
  adding /home/redacted/Press F/Steam/steamapps/common/Heretic Shadow of the Serpent Riders/crispy-doom/../base/HERETIC.WAD
Save directory changed to ./base/savegames/.
===========================================================================
                 Heretic: Shadow of the Serpent Riders
===========================================================================
 Crispy Doom is free software, covered by the GNU General Public
 License.  There is NO warranty; not even for MERCHANTABILITY or FITNESS
 FOR A PARTICULAR PURPOSE. You are welcome to change and distribute
 copies under certain conditions. See the source for more information.
===========================================================================
I_SDL_InitMusic: FluidSynth unavailable.
I_InitSound: SDL audio driver is pulseaudio
NET_Init: Init network subsystem.
MN_Init: Init menu system.
Installing breakpad exception handler for appid(gameoverlayui)/version(20220820011708)
Installing breakpad exception handler for appid(gameoverlayui)/version(1.0)
Installing breakpad exception handler for appid(gameoverlayui)/version(1.0)
R_Init: Init Heretic refresh daemon..........
P_Init: Init Playloop state.
I_Init: Setting up machine state.
S_Init: Setting up sound.
I_SDL_PrecacheSounds: Precaching all sound effects..........................
D_CheckNetGame: Checking network game status.
SB_Init: Loading patches.
Installing breakpad exception handler for appid(gameoverlayui)/version(1.0)
CAPIJobRequestUserStats - Server response failed 2
Error loading midi: Couldn't open timidity.cfg
19:39:48 [INFO] run returned with exit status: 0
Game process removed: AppID 2390 "/home/redacted/.local/share/Steam/ubuntu12_32/reaper SteamLaunch AppId=2390 -- '/home/redacted/.local/share/Steam/steamapps/common/SteamLinuxRuntime_soldier'/_v2-entry-point --verb=waitforexitandrun -- '/home/redacted/.local/share/Steam/compatibilitytools.d/luxtorpeda-dev'/luxtorpeda.sh waitforexitandrun  '/home/redacted/Press F/Steam/steamapps/common/Heretic Shadow of the Serpent Riders/base/dosbox.exe' base\\heretic.exe -conf base\\heretic.conf -fullscreen -exit -config ./crispy-doom/heretic.cfg -extraconfig ./crispy-doom/crispy-heretic.cfg -savedir ./base/savegames", ProcID 1917298 
ThreadGetProcessExitCode: no such process 1917298
ThreadGetProcessExitCode: no such process 1917297
ThreadGetProcessExitCode: no such process 1917295
ThreadGetProcessExitCode: no such process 1917271
ThreadGetProcessExitCode: no such process 1917158
ThreadGetProcessExitCode: no such process 1917157
Uploaded AppInterfaceStats to Steam
```

Notice how it reports `I_SDL_InitMusic: FluidSynth unavailable.`, which does not happen when I launch the same executable with the same parameters as I listed before, and loading the exact same config files listed, presumably because the executable detects FluidSynth is installed in my system. It also atttempts to load Timidity as fallback, but fails (`Error loading midi: Couldn't open timidity.cfg`).

**Comment by d10sfan** [comment]
@hfc2x That is what I was referring to when I mentioned configuration differences, because I was using the base game configuration with no changes, so I needed to know if you had anything different.

It looks like the issue was that fluidsynth is not the default in use and I hadn't tested that originally. The problem was that the built sdl2 mixer that is provided as part of the steam runtime did not know that the fluidsynth libraries were there. I've made changes (https://github.com/luxtorpeda-dev/packages/pull/744) that create a build with sdl2 mixer included and that looks to fix the issue.

Thanks for the report and let me know if that fixes it for you.

**Comment by hfc2x** [comment]
This did fix the music, however, it introduced a freeze and crash as soon as any level is loaded, be it from the new game menu, loading a saved game, or letting the internal demo play. Terminal output for this:

```
(snipped for brevity)

===========================================================================
                 Heretic: Shadow of the Serpent Riders
===========================================================================
 Crispy Doom is free software, covered by the GNU General Public
 License.  There is NO warranty; not even for MERCHANTABILITY or FITNESS
 FOR A PARTICULAR PURPOSE. You are welcome to change and distribute
 copies under certain conditions. See the source for more information.
===========================================================================
I_SDL_InitMusic: Using FluidSynth.
I_InitSound: SDL audio driver is pulseaudio
NET_Init: Init network subsystem.
MN_Init: Init menu system.
Installing breakpad exception handler for appid(gameoverlayui)/version(20220820011708)
Installing breakpad exception handler for appid(gameoverlayui)/version(1.0)
Installing breakpad exception handler for appid(gameoverlayui)/version(1.0)
R_Init: Init Heretic refresh daemon..........
P_Init: Init Playloop state.
I_Init: Setting up machine state.
S_Init: Setting up sound.
I_SDL_PrecacheSounds: Precaching all sound effects..........................
D_CheckNetGame: Checking network game status.
SB_Init: Loading patches.
Installing breakpad exception handler for appid(gameoverlayui)/version(1.0)
./crispy-doom/run-crispy-heretic.sh: line 6: 1920461 Killed                  "$DIR/crispy-heretic" "$@"
00:06:49 [INFO] run returned with exit status: 137
Game process removed: AppID 2390 "/home/redacted/.local/share/Steam/ubuntu12_32/reaper SteamLaunch AppId=2390 -- '/home/redacted/.local/share/Steam/steamapps/common/SteamLinuxRuntime_soldier'/_v2-entry-point --verb=waitforexitandrun -- '/home/redacted/.local/share/Steam/compatibilitytools.d/luxtorpeda-dev'/luxtorpeda.sh waitforexitandrun  '/home/redacted/Press F/Steam/steamapps/common/Heretic Shadow of the Serpent Riders/base/dosbox.exe' base\\heretic.exe -conf base\\heretic.conf -fullscreen -exit -config ./crispy-doom/heretic.cfg -extraconfig ./crispy-doom/crispy-heretic.cfg -savedir ./base/savegames", ProcID 1920461 
ThreadGetProcessExitCode: no such process 1920461
ThreadGetProcessExitCode: no such process 1920460
ThreadGetProcessExitCode: no such process 1920458
ThreadGetProcessExitCode: no such process 1920439
ThreadGetProcessExitCode: no such process 1920329
ThreadGetProcessExitCode: no such process 1920328
Uploaded AppInterfaceStats to Steam
```

**Comment by d10sfan** [comment]
@hfc2x Ah sorry about that. It looks like the sdl2 mixer version that I was using had a bug in it. Updating to the latest version looks to have fixed it. Let me know how that does and  if you run into anything else.

**Comment by hfc2x** [comment]
Okay, it's working perfectly now. The only issue that I'm seeing is that Inter Heretic and Crispy Heretic are trying to use each other's configuration files when launched with the default options. This makes sense, considering Inter [Doom] is a fork of Crispy [Doom].

Could it be possible to keep in the launch script for Crispy Heretic/Hexen the `-config` and `-extraconfig` parameters to point to the respective *.cfg files their own working directories? I imagine it would also be useful for most players to have the `-savedir` parameter pointing to their Steam saves folder, but if they don't want this, they could just change them in the Steam launch options.

International Doom only uses the `-config` parameter to point to a specific inter-[game].ini file. In theory, it shouldn't even try to load a *.cfg file, but it's actually doing it, so it's probably a bug that I need to report on the corresponding repositories. Adding the parameter to the launch script to point to inter-[game].ini would at least be a workaround. I don't think `-savedir` is necessary in this case, since the save format is incompatible with the DOS engine.

**Comment by d10sfan** [comment]
@hfc2x Great! I've added the changes to set a local config path for both crispy and inter doom. Let me know if you run into any issues.

**Comment by hfc2x** [comment]
Sorry for not responding.

It's working perfectly now, no conflicts. I was thinking of to trying and submitting a pull request for all these Doom engine games to set the default save directories to their Steam save directory, at least for the "Chocolate" and "Crispy" ports because of compatibility.

**Comment by d10sfan** [comment]
@hfc2x Sure, a pull request would be welcome :)
