### ISSUE TITLE
HeXen modern port: Crispy HeXen

### ISSUE THREAD

**Issue by hfc2x** [luxtorpeda-dev/packages#739]
### Project Link

https://github.com/fabiangreffrath/crispy-doom

### Project License

GPLv2

### Steam App Ids

- https://steamdb.info/app/2360/
- https://steamdb.info/app/2370/

### Additional Context

This engine is vanilla-compatible, and therefore is compatible with Steam Cloud for saves. It's also multiplayer-compatible with Chocolate HeXen. It features enhancements like higher resolution, permanent mouselook, and totals in the in-game map for completionists.

**Comment by d10sfan** [comment]
@hfc2x Thanks for the request. I've finished this in https://github.com/luxtorpeda-dev/packages/commit/27aca86dcabbb2facc7f1d0cc63da3aa18b2a701

The next time you launch the game(s), it should show as an option. Let me know if you run into any issues.
