### ISSUE TITLE
Heretic: Shadow of The Serpent Riders modern port: International Heretic

### ISSUE THREAD

**Issue by hfc2x** [luxtorpeda-dev/packages#740]
### Project Link

https://github.com/JNechaevsky/inter-doom

### Project License

GPLv2

### Steam App Ids

https://steamdb.info/app/2390/

### Additional Context

Modern port for Heretic: Shadow of The Serpent Riders that features enhancements such as freelook, completely customizable key bindings, brightmaps, totals in automap, full widescreen support, and many other optional visual and gameplay enhancements while staying true to the original look and feel of the original. It features English and Russian languages. It's not compatible with Steam Cloud.

**Comment by d10sfan** [comment]
@hfc2x Thanks for the request. I've finished this in https://github.com/luxtorpeda-dev/packages/pull/743

The next time you launch the game(s), it should show as an option. Let me know if you run into any issues.
