### ISSUE TITLE
Doom modern port: International Doom

### ISSUE THREAD

**Issue by silentsudin** [luxtorpeda-dev/packages#746]
### Project Link

https://github.com/JNechaevsky/inter-doom

### Project License

GPLv2

### Steam App Ids

- https://steamdb.info/app/2300/
- https://steamdb.info/app/2290/
- https://steamdb.info/app/2280/
- https://steamdb.info/app/9160/

### Additional Context

Modern port for Doom that features enhancements such as freelook, completely customizable key bindings, brightmaps, totals in automap, full widescreen support, and many other optional visual and gameplay enhancements while staying true to the original look and feel of the original. It features English and Russian languages. It's not compatible with Steam Cloud.

**Comment by d10sfan** [comment]
@silentsudin Thanks for the request! I've added inter-doom support for the doom games here: https://github.com/luxtorpeda-dev/packages/pull/747

Let me know if you run into any issues.
