### ISSUE TITLE
Dethrace - Carmageddon Max Pack

### ISSUE THREAD

**Issue by neuromancer** [luxtorpeda-dev/packages#751]
### Project Link

https://github.com/dethrace-labs/dethrace

### Project License

Public domain

### Steam App Ids

- https://steamdb.info/app/282010/

### Additional Context

It should be playable, but it will require some updates until it reaches version 1.0.

**Comment by d10sfan** [comment]
@neuromancer It looks like this one has some license confusion/issues (https://github.com/dethrace-labs/dethrace/issues/62), along with being a decompatilion project, which I've been hesitant to support in the past (because of issues like re3 for example). Is this accurate?

**Comment by neuromancer** [comment]
This is correct. IMHO, the risk is very low, but this is entirely up to you. In any case, if you decided to support it, I will be happy to test it.

**Comment by d10sfan** [comment]
@neuromancer Thanks for the suggestion and the info, I think for now I'll hold off, but I'll be open in the future if things change.
