### ISSUE TITLE
OpenJKDF2 (Jedi Knight: Dark Forces II)

### ISSUE THREAD

**Issue by mattmaddux** [luxtorpeda-dev/packages#752]
### Project Link

https://github.com/shinyquagsire23/OpenJKDF2

### Project License

Other: “Permission to use, copy, modify, and/or distribute this software for any purpose without fee is hereby granted.”

### Steam App Ids

- https://steamdb.info/app/32380/

**Comment by d10sfan** [comment]
@mattmaddux It looks like this one is a reverse engineering project, instead of a re-implementation. I usually avoid projects like this. You can see https://github.com/luxtorpeda-dev/packages/issues/576 for more information.

For now, I won't be supporting this one.

**Comment by mattmaddux** [comment]
Ah, interesting. Thanks for looking into it.
