### ISSUE TITLE
Fallout 2 Community Edition

### ISSUE THREAD

**Issue by KawaiiDinosaur** [luxtorpeda-dev/packages#761]
### Project Link

https://github.com/alexbatalov/fallout2-ce

### Project License

https://github.com/alexbatalov/fallout2-ce/blob/main/LICENSE.md

### Steam App Ids

https://steamdb.info/app/38410/

**Comment by d10sfan** [comment]
@KawaiiDinosaur Thanks for the package request! 

Do you know what the current state of this project is, in terms of how playable it is?

Also, is this a reverse engineering project, or a re-implementation?

It looks like with the license, I'd probably consider this a non-free license if implemented, similar to a few other engines that I've done.

**Comment by KawaiiDinosaur** [comment]
@d10sfan the game is playable from start to finish, yes. 

The reverse engineered project by the same individual is in a separate repository (https://github.com/alexbatalov/fallout2-re). I understand that the "Community Edition" is a reimplementation of the former.
