### ISSUE TITLE
Odamex (A multiplayer focused source port)

### ISSUE THREAD

**Issue by vaibhavrmahadevan** [luxtorpeda-dev/packages#762]
### Project Link

https://sourceforge.net/projects/odamex/files/Odamex/10.2.0/

### Project License

GNU General Public License v2

### Steam App Ids

https://steamdb.info/app/2280/
https://steamdb.info/app/2290/
https://steamdb.info/app/2300/
https://steamdb.info/app/9160/

**Comment by d10sfan** [comment]
Progress tracking here: https://github.com/luxtorpeda-dev/packages/pull/764

**Comment by d10sfan** [comment]
@vaibhavrmahadevan 

I've added odamex, although having some crashing issues with the launcher (from their discord, it looks like others have had similar issues). So  you can use it with the console to connect manually, although it may be better with a browser launcher.

Do you have any recommendations? I did see https://doomseeker.drdteam.org/ as one option.

**Comment by vaibhavrmahadevan** [comment]
Thank you so much!

Doomseeker is awesome and I feel might be more stable :)

**Comment by d10sfan** [comment]
@vaibhavrmahadevan :) 
I'm working on that on https://github.com/luxtorpeda-dev/packages/pull/767

**Comment by d10sfan** [comment]
@vaibhavrmahadevan I've added doomseeker as well - https://github.com/luxtorpeda-dev/packages/commit/057228c755e7d53abf747480e853dee3aab5121e

It should be live about an hour or two after this comment.

**Comment by vaibhavrmahadevan** [comment]
@d10sfan you are the best! 💗
