### ISSUE TITLE
EternalJK hasn't been updated in years, let's use Vanilla OpenJK for JAMP

### ISSUE THREAD

**Issue by athendrix** [luxtorpeda-dev/packages#765]
So, OpenJK which is used for the SP of Jedi Outcast and Jedi Academy is continuously updated, while EternalJK used for the Jedi Academy Multiplayer hasn't been updated in years.
It also seems to change the types of games that can be joined.
I have a server on my local network that can be joined with standard Steam Jedi Academy, as well as OpenJK, but not with Luxtorpeda's EternalJK.
So while EternalJK is nice, I think a more maintained, more vanilla option like standard OpenJK would be more appropriate for general Linux use.

**Comment by d10sfan** [comment]
@athendrix 

Thanks for the request, I've replaced eternaljk with openjk. Outcast will use jk2mv since it's still being updated.
