### ISSUE TITLE
Cave Story+

### ISSUE THREAD

**Issue by xurich-xulaco** [luxtorpeda-dev/packages#768]
### Project Link

https://github.com/doukutsu-rs/doukutsu-rs

### Project License

MIT/doukutsu-rs License

### Steam App Ids

https://steamdb.info/app/200900/

### Additional Context

As far as I'm aware, this is a re-use of NXEngine (a rewrite of Cave Story's engine) in order to be used based on the files that are provided by Steam's "Cave Story+". Thus, from the start, it's an enhancement and a direct way to use the engine directly on linux (it's even supposed to be a out-of-the-box experience), yet, I'm not that aware if this project fully supports stuff like the Steam Achievements.
EDIT: my bad, I have read to the luxpedia packages too quickly... Could some one delete this issue?

**Comment by d10sfan** [comment]
@xurich-xulaco Thanks for the request, but this one is already implemented.
