### ISSUE TITLE
Quake Injector

### ISSUE THREAD

**Issue by vaibhavrmahadevan** [luxtorpeda-dev/packages#769]
### Project Link

https://github.com/hrehfeld/QuakeInjector

### Project License

GNU General Public License version 2.0 (GPLv2)

### Steam App Ids

https://steamdb.info/app/2310/

**Comment by d10sfan** [comment]
@vaibhavrmahadevan Thanks for the request! I've added it with https://github.com/luxtorpeda-dev/packages/commit/ee894ad75e6afca682965acf887f3cca375d99b3

It'll default to vkquake, but you can most likely change it to other engines with their configuration GUI.

**Comment by vaibhavrmahadevan** [comment]
@d10sfan Thank you so much!
