### ISSUE TITLE
Update needed for openxcom-oxce

### ISSUE THREAD

**Issue by dlpierce** [luxtorpeda-dev/packages#770]
Please update openxcom-oxce to version 7.7.6 (commit [3eb2a81](https://github.com/MeridianOXC/OpenXcom/commit/3eb2a81191ddda77947b4de31427eae1ec66f884)). Some mods like [The X-Com Files](https://github.com/SolariusScorch/XComFiles) require at least version 7.7. Thank you!

**Comment by d10sfan** [comment]
@dlpierce Thanks for the issue! I've updated with this PR: https://github.com/luxtorpeda-dev/packages/commit/6b7c3ed258a90a43933fbbc9c61b7ec8aba2b36f

It should be live about 20 minutes after this comment. Let me know if you need anything.

**Comment by dlpierce** [comment]
Thank you, works great!
