### ISSUE TITLE
NotBlood (a fork of NBlood)

### ISSUE THREAD

**Issue by vaibhavrmahadevan** [luxtorpeda-dev/packages#773]
### Project Link

https://github.com/clipmove/NotBlood

### Project License

GNU General Public License version 2.0 (GPLv2)

### Steam App Ids

https://steamdb.info/app/1010750/
https://steamdb.info/app/299030/

**Comment by d10sfan** [comment]
@vaibhavrmahadevan Thanks for the request, currently getting errors compiling, which I've submitted a ticket for: https://github.com/clipmove/NotBlood/issues/10

**Comment by d10sfan** [comment]
@vaibhavrmahadevan This is now live and looks to be working! Let me know if you run into any issues.
