### ISSUE TITLE
add a way to play the iwads for original doom that come with doom eternal

### ISSUE THREAD

**Issue by eskoONE** [luxtorpeda-dev/packages#787]
### Feature Request

doom eternal comes with the original doom iwads, which can be played in the game itself. i was wondering if it would be possible to launch doomrunner through luxtorpeda to be able to play the original games, either attached to doom eternal or gzdoom engines flatpack that is installed on the steam deck.

Or perhaps give us the option to add any runner to any game manually added. That way i could add doomrunner to gzdoom and use the iwads i got from my doom eternal installation.

### Solution

See above.

**Comment by d10sfan** [comment]
@eskoONE Can you see if this works? https://pastebin.com/vUW9dzM4

The way to use this is go into the compatibility tools folder and then luxtorpeda and find the config.json file. Then set "should_do_update" to false. Then take the contents of the pastebin link above and replace ~/.cache/luxtorpeda/packagesruntime.json

That should cause it to launch doom runner and then you can use the wads there.

**Comment by eskoONE** [comment]
yes, it starts but whenever i close the game and open it again, it seems to install gzdoom anew? i dont know if this is a problem or not yet. doomrunner is out of date. i get prompted to update it.

it also seems like the flatpack version of gzdoom is currently broken anyway with controls not working out of the box. trying to fix that rn.

**Comment by d10sfan** [comment]
@eskoONE If you mean that it does not download the engines anymore, but it shows the installing progress, that is normal. The client extracts the engine data each time you launch.

I'll look into updating doomrunner soon. Were you able to launch the wads with doom runner? gzdoom is included as an engine with this, so you shouldn't need to use a flatpak.

**Comment by eskoONE** [comment]
i was able to start doom.wad and doom2.wad. i just learned its not a flatpack issue per se but a problem with how gzdoom handles controller input. you can learn more about it if you are interested [here ](https://github.com/ZDoom/gzdoom/issues/1271). i havent tired running a mod yet. ill try and report back in a second.

**Comment by d10sfan** [comment]
@eskoONE It looks like they are working on releasing another doom runner  very soon, and I've setup a watch for the releases on github, so once it's released, I'll update here.

https://github.com/luxtorpeda-dev/packages/commit/431e861e885ca82b4b8c9b87bd293fdf2d58dc5e adds the support that you tested, so should be good to go there. Let me know if you run into any issues.

I have a custom gzdoom config that I'm setting up that has some stuff that can help with controller support (if you didn't already have a gzdoom.ini file), although it sounds like the engine could still use some work there.

**Comment by eskoONE** [comment]
> @eskoONE It looks like they are working on releasing another doom runner very soon, and I've setup a watch for the releases on github, so once it's released, I'll update here.
> 
> [431e861](https://github.com/luxtorpeda-dev/packages/commit/431e861e885ca82b4b8c9b87bd293fdf2d58dc5e) adds the support that you tested, so should be good to go there. Let me know if you run into any issues.
> 
> I have a custom gzdoom config that I'm setting up that has some stuff that can help with controller support (if you didn't already have a gzdoom.ini file), although it sounds like the engine could still use some work there.

Id be interested in your gzdoom.ini. Im kinda a bit overwhelmed with configuring it on the steam deck. Where and how would i even add it to my installation though?

Also, is there a reason gzdoom gets unpacked on every start? Can these files not be permanent? Im a bit concerned with the longevity of the ssd. Also, in the wads section in doomrunner there are other .pk3 files, which are mods i assume. Im not sure where they are coming from. They are not supposed to be in that section either i think. Did you add those?

**Comment by d10sfan** [comment]
@eskoONE I think since doom runner is being used, the config won't be setup automatically, but you can see it in the game directory (it'll be called [gzdoom_template.ini](https://github.com/luxtorpeda-dev/packages/blob/master/engines/gzdoom/assets/gzdoom_template.ini))

What wads are you seeing, can you send an example? Doom runner I believe searches for wads in the directory, the only ones that luxtorpeda includes is the ones that gzdoom needs.

The unpack happens each time mainly to ensure that the files are always there. It shouldn't have an issue on each launch, but it's something that could be disabled in the future, as a feature.

**Comment by d10sfan** [comment]
@eskoONE 

I added an issue here (https://github.com/luxtorpeda-dev/luxtorpeda/issues/182) to discuss the disabling of the install step on each run as an opt-in option. Whenever I have a chance to look into that further, I'll update that issue.

Also, doom-runner is being built, once this action is finished (https://github.com/luxtorpeda-dev/packages/actions/runs/3578800279), it should be live. It'll probably be a few hours after this comment.

**Comment by eskoONE** [comment]
> @eskoONE I think since doom runner is being used, the config won't be setup automatically, but you can see it in the game directory (it'll be called [gzdoom_template.ini](https://github.com/luxtorpeda-dev/packages/blob/master/engines/gzdoom/assets/gzdoom_template.ini))
> 
Im a bit confused here. Does this mean your gzdoom config is already shipping with the engine? If so, the linked template is your modified version?

> What wads are you seeing, can you send an example? Doom runner I believe searches for wads in the directory, the only ones that luxtorpeda includes is the ones that gzdoom needs.

Im seeing gzdoom.pk3, game_widescreen_gfx.pk3, brightmaps.pk3, lights.pk3 and game_support.pk3. These are under the "select iwad" section in doomrumner though. I never ran any of these mods in my games and never had any issues. Are you sure those are mandatory? 

Regardless of that, they should be listed under "add mods" in doomrunner, so you can actually enable them. 
> 
> The unpack happens each time mainly to ensure that the files are always there. It shouldn't have an issue on each launch, but it's something that could be disabled in the future, as a feature.

I saw you plan to add this as an option in the future. Thanks!

**Comment by d10sfan** [comment]
@eskoONE 

For those wads, they aren't mandatory to run, they are just part of the gzdoom download, so they shouldn't hurt anything.

For the config file, the template I linked is the one that gzdoom can use, but when you run through doom-runner, it does not take affect. My gzdoom config is only for luxtorpeda, but if you ran a game directly with gzdoom (such as the original doom), it would take affect if you didn't already have a config set at ~/.config/gzdoom
