### ISSUE TITLE
An update for Unreal Gold (227j)

### ISSUE THREAD

**Issue by daemonspudguy** [luxtorpeda-dev/packages#798]
### Feature Request

Unreal Gold has had an update since 227i, 227j.

### Solution

Point people torwards that, and package libxmp.so.4 in the unreal-libs tarball

### Additional Context

I created this here because I couldn't over at the other repo.

**Comment by d10sfan** [comment]
These sort of requests should go into the packages repo (I moved it here). What sort of problem did you have with it?

I will take a look soon

**Comment by d10sfan** [comment]
@daemonspudguy Where would the download for this be? 

According to this, https://www.oldunreal.com/downloads/unreal/oldunreal-patches-for-unreal-latest-ver.j/

It looks like it is not out yet.

**Comment by daemonspudguy** [comment]
https://www.oldunreal.com/phpBB3/viewtopic.php?f=51&t=10395

**Comment by daemonspudguy** [comment]
Also, I would suggest updating the included openAL library.

**Comment by daemonspudguy** [comment]
Wait, in the help folder there is a tarball called convience_libs, i would recommend using that tarball's libraries.

**Comment by d10sfan** [comment]
@daemonspudguy I will take a look, normally I prefer to wait until an official release, but will see if this is usable.

**Comment by d10sfan** [comment]
@daemonspudguy For the libraries, normally the steam runtime has the libraries needed, so that would be best to use. I'll see if any additional libraries are needed.

**Comment by daemonspudguy** [comment]
@d10sfan the 64-bit binary doesn't work, at least with my system. The 32-bit binary does.
Use that.

**Comment by d10sfan** [comment]
@daemonspudguy It worked fine for me, what sort of error are you seeing?

**Comment by daemonspudguy** [comment]
"Illegal instruction"

**Comment by daemonspudguy** [comment]
If you're getting Serious Sam Classic flashbacks, so am I.

**Comment by daemonspudguy** [comment]
Seriously, just use the 32-bit build. The 64-bit one is still experimental.

**Comment by daemonspudguy** [comment]
@d10sfan I think the compiler made a binary that certain older CPUs like mine don't support. I don't know what causes it, and I can't compile it myself because proprietary.

**Comment by d10sfan** [comment]
@daemonspudguy Does the 32-bit version of this version work for you on your system?

**Comment by daemonspudguy** [comment]
@d10sfan Yes.

**Comment by d10sfan** [comment]
@daemonspudguy You can track progress here: https://github.com/luxtorpeda-dev/packages/pull/803

Let me know if  you run into any issues once that has been merged.
