### ISSUE TITLE
UT99 Ini File Changes

### ISSUE THREAD

**Issue by d10sfan** [luxtorpeda-dev/packages#80]
GammaOffset=0.000000 - for opengl
Brightness=0.300000 - for [SDLDrv.SDLClient]

**Comment by JoshuaFern** [comment]
We ought to set the GUI to large by default, it might be really difficult for folks using 4k displays to navigate otherwise.
```
[UMenu.UMenuRootWindow]
GUIScale=2.000000
```

**Comment by d10sfan** [comment]
ld_preload use (instead of override) - to fix steam overlay
look at openrct2 to disable overlay automatically using ld_preload= ""

**Comment by d10sfan** [comment]
@JoshuaFern I put up a new archive with those ini changes and a new build with a fix for that issue with the overlay. Let me know if there's anything else needed (Feel free to re-open)
