### ISSUE TITLE
openMW doesn't seem to be using the latest version when chosing openMW (Latest)

### ISSUE THREAD

**Issue by pr0statitis** [luxtorpeda-dev/packages#809]
### Linux Distribution

SteamOS 3.4.2

### Luxtorpeda Version

v61

### Bug description

When using openMW (Latest) or openMW (Latest) Launcher Luxtorpeda seems to be downloading a different version than the actual latest version found on the official openMW page.

The biggest problem seems to be that the Script settings don't appear in the settings menu:

![Screenshot_20221228_082534](https://user-images.githubusercontent.com/77187095/209775039-dc79fcc4-174c-4386-a7ed-9850ab911bbb.png)

Also whenever I launch the game it seems to create a new content list here:
![Screenshot_20221228_082845](https://user-images.githubusercontent.com/77187095/209775221-bbda9f23-60e5-487c-ae34-bf4227587bb6.png)
That would probably make installing mods and maintaining load orders a nightmare but I haven't tried that yet because the first issue with the settings not showing seemed a bit more pressing to me.

Also the newest version has a Language settings category.

I have tried the RC4 from the openMW site and both these issues don't happen in that version. The Language option was also there.
Could there still be something wrong on my end? I installed Morrowind completely fresh multiple times and made sure that all the directories associated with the game and openMW were gone before reinstalling,
Honestly these might all not even be bugs and instead expected behaviour but I would expect "Latest" to use the most current version of the game, at the very least the most current RC.

### Steps To Reproduce

1. Launch game via Luxtopeda and choose openMW (Latest) or openMW (Latest) Launcher
2. Check content lists (a new one should have appeared since last launching the game)
3. Go into the game's settings menu and look for the Scripts option

### Expected Behavior

Luxtorpeda downloads latest version and the aforementioned features work as described.

### Relevant log output

```shell
I can provide logs but I didn't know which ones could be relevant.
```

**Comment by d10sfan** [comment]
@pr0statitis Since this is an issue with the package, not the client, I have moved it. In the future, these issues should be created in the packages repo.

I'm not sure what you mean by different version than on the website. Can you provide a screenshot or a link to what you are referring to?

The way (latest) works is that it is a commit from the development branch, since these features have not been officially released yet. So updating it requires manual updates, it is not an automatic thing, and I am not planning on updating it daily or as soon as RCs are created, since this all happens by me updating the build scripts to build the new version. Are there features or improvements you are wanting to see with the newer releases?

The no scripting is interesting, that was an issue a while back which I believe has been fixed. You may want to try doing a clean uninstall of morrowind, then deleting any files left over, and trying again.

On the content list, you should be able to pick the one you want, although it's strange that it keeps creating it, let me know if a fresh install keeps that happening.

**Comment by pr0statitis** [comment]
Thank you for you response!
Will do, sorry about that!

I've actually tried the [Linux x64 generic RC4](https://redfortune.de/openmw/rc/openmw-0.48.0-Linux-64BitRC4.tar.gz) using the link from [here](https://openmw.org/2022/openmw-0-48-0-is-now-in-rc-phase/).

All that was done on fresh clean installations of Morrowind, with everything wiped after uninstalling (went into all the folders manually and nuked everything).

I don't actually know of any differences feature-wise between the version Luxtorpeda creates and the RC4 version I used, apart from the things mentioned. Does it work as intended for you? It should no require anything else in terms of dependencies that I might be missing, right?

How difficult would it be to create a package for the RC? I would look into it myself but I'm pretty new to all of this.

**Comment by d10sfan** [comment]
@pr0statitis No worries :)

I've created an update pull request here - https://github.com/luxtorpeda-dev/packages/pull/810

Creating the change is pretty easy, provided that there wasn't any changes that could mess with the build. It takes about 2-3 hours to finish, but if it works, we can test it from there.

The last time I tried it with fresh it worked fine for me, but once this one is done building, I will try it again and see.

**Comment by pr0statitis** [comment]
Awesome! Thank you so much for your time and effort! :)

**Comment by d10sfan** [comment]
@pr0statitis There was an issue with the compilation, I'll be taking a look as soon as possible, and will let you know once I have a change.

**Comment by pr0statitis** [comment]
@d10sfan don't sweat it! Thank you so much.
I'm currently using the RC4 that I linked (which didn't require any compilation and works flawlessly by executing the openmw-launcher script it comes with). I used launch options in Steam to make this one my default for it.
That version uses the default paths for openMW on Linux but apart from that it's a pretty neat solution, so you can take all the time in the world. :)

**Comment by d10sfan** [comment]
Thanks for the issue, I'll track in https://github.com/luxtorpeda-dev/packages/pull/810

Once that is merged, it'll be updated.

**Comment by d10sfan** [comment]
@pr0statitis This is now completed, after migrating the build system to a newer runtime, to make it much easier/possible to build.

The client isn't released yet, but once https://github.com/luxtorpeda-dev/luxtorpeda/pull/197 is merged, and client 63 is out, if you use that, you'll be on the latest 0.48 RC.
