### ISSUE TITLE
The Force Engine for Star Wars - Dark Forces

### ISSUE THREAD

**Issue by rea987** [luxtorpeda-dev/packages#816]
### Project Link

https://github.com/luciusDXL/TheForceEngine

### Project License

GPL-2.0

### Steam App Ids

- https://steamdb.info/app/32400/

### Additional Context

The Linux build seems to need to be compiled by the user:

https://github.com/luciusDXL/TheForceEngine/pull/176

> Linux Port for 1.01. With these changes, the engine runs on 32bit and 64bit linux (tested x64 and MIPS32), Dark Forces is fully completable (tested english and german versions), with OpenGL rendering, Sound and Music (tested with fluidsynth). Mods are working as well (tested with Tie Defender Base)
> Loading savegames sometimes crashes, I'm still looking into that.

**Comment by d10sfan** [comment]
@rea987 It looks like this engine is a reverse engineering project, so sadly won't plan on supporting that: https://github.com/luciusDXL/TheForceEngine/blob/master/ProjectStructure.md#reverse-engineered-code
