### ISSUE TITLE
Unreal Tournament won't display additional models

### ISSUE THREAD

**Issue by Retrograde-i486** [luxtorpeda-dev/packages#820]
### Linux Distribution

Garuda Linux

### Luxtorpeda Version

luxtorpeda-61

### Bug description

When attempting to select a model that differs from the default 4 that are included with the base game (Female Commando, Female Soldier, Male Commando, Make Soldier) nothing is displayed. This occurs in Player Setup (Options --> Player Setup) as well as trying to configure individual bots. The following models are included in the list but selecting them does not work: Nali, Nali WarCow, Skaarj Hybrid, War Boss, Xan Mark II.

### Steps To Reproduce

1. Install game from steam
2. Setup Luxtorpeda compatibility tool
3. Change Unreal Tournament GOTY Edition compatibility to Luxtorpeda
4. Load up game and enter Player Setup
5. Try and select one of the following models for Class: Nali, Nali WarCow, Skaarj Hybrid, War Boss, Xan Mark II
6. No model is displayed
7. Attempting to setup a bot with one of the above models also shows no model in preview window. Attempting to start a match fails as the press fire to start message before the match can't be passed, assuming it's because the models can't be loaded. Game doesn't crash or freeze, you just can't get actually start the match after it loads.

### Expected Behavior

Able to select additional models in Player Setup and Bot Configuration

### Additional Context

Fresh Install, had another user test it and they got the same result. Possible configuration file error in the SteamLibrary/steamapps/common/Unreal Tournament/linuxdata-469c/System64/ maybe?

**Comment by d10sfan** [comment]
@Retrograde-i486 Thanks for the issue!

I've fixed the issue, turned out to be an issue with case sensitivity, so I was able to create a workaround. It's live now

Also, as a added side-bonus, I've added bonus pack 4 to the package, so that it can be used automatically. 

Let me know if you run into any further issues
