### ISSUE TITLE
Command and Conquer

### ISSUE THREAD

**Issue by ddlyarcher** [luxtorpeda-dev/packages#824]
### Project Link

https://www.openra.net/download/#linux

### Project License

GPL3

### Steam App Ids

https://store.steampowered.com/app/1213210/Command__Conquer_Remastered_Collection/

### Additional Context

Also does Dune 2000, but that's not on Steam.

Also there is,
https://github.com/MustaphaTR/Romanovs-Vengeance
For Red Alert2, but that games not on Steam.

**Comment by d10sfan** [comment]
@ddlyarcher It looks like currently, only Tiberian Dawn has had a project for implementing remaster support so far: https://github.com/pchote/TiberianDawnHD

I haven't seen anything for red alert. Implementing the tiberian dawn one should be pretty straight forward, so I'll look into that soon.

**Comment by d10sfan** [comment]
Added in https://github.com/luxtorpeda-dev/packages/commit/33738b52998cee14a8080f4f536354adc90e4395 for tiberian dawn, since it does not look like there's red alert support yet. Feel free to comment in this issue if that changes.

**Comment by rea987** [comment]
@d10sfan Vanilla Conquer seems to support cross-platform multiplayer for non-remastered version. Wouldn't it be good idea to add it for Tiberian Dawn and Red Alert?

https://github.com/TheAssemblyArmada/Vanilla-Conquer

**Comment by d10sfan** [comment]
@rea987 It looks like Remastered has the original cnc game data in it, and Vanilla Conquer does have support for the non-remastered on linux (but not the remastered content), so I'll look into it, basically having options for openra for remastered tiberian, then original for td and ra.

**Comment by d10sfan** [comment]
@rea987 You can see progress of this in here: https://github.com/luxtorpeda-dev/packages/pull/830

**Comment by d10sfan** [comment]
@rea987 This has been merged and should be live shortly. Note that like the notice says, the steam assets does not include campaign videos for the soviet campaign.

**Comment by rea987** [comment]
@d10sfan Nice! Would it be feasible to add OpenRA Playtest for Red Alert to use non-remastered assets? I understand that its current builds automatically downloads assets from a mirror featuring 2008 freeware release. For music and videos, user is expected to provide ISOs. Can this be made to use non-remastered assets of Steam release? If not, can it be added as it is? Thanks!

**Comment by d10sfan** [comment]
@rea987 Looking at OpenRA, it does not look like it detects the steam original game assets, so I don't think it'd make sense to add it as an option. If you find a way to do so, please let me know and I can implement that.
