### ISSUE TITLE
OpenRCT Package Update

### ISSUE THREAD

**Issue by ddlyarcher** [luxtorpeda-dev/packages#825]
### Project Link

https://github.com/Limetric/OpenRCT2.org

### Project License

Open Source

### Steam App Ids

https://store.steampowered.com/app/683900/RollerCoaster_Tycoon_Classic/

### Additional Context

As of patch 0.4.2 (2022-10-05) OpenRCT now supports RCT Classic as well as the original discs and the Deluxe version.

Currently it Luxtorpeda package for OpenRCT doesn't has the Steam App ID for RCT Classic.

**Comment by d10sfan** [comment]
@ddlyarcher Do you own this game?

If so, let me know and I can give you some steps to test to see how it works.

**Comment by d10sfan** [comment]
I've added this change, note that you may need to delete/change your config.ini file for the engine if you have both 2 and this in use.
