### ISSUE TITLE
Argentum 20

### ISSUE THREAD

**Issue by rea987** [luxtorpeda-dev/packages#829]
### Project Link

https://github.com/ao-org/argentum20-client

### Project License

AGPL-3.0

### Steam App Ids

https://steamdb.info/app/1956740/

### Additional Context

https://www.reddit.com/r/linux_gaming/comments/10kfsm4/help_with_an_old_visual_basic_game/

https://github.com/ao-org

https://www.ao20.com.ar/

**Comment by d10sfan** [comment]
It does not look like this game's source includes a linux version, just Windows only.

If someone ports this game to Linux, I'd be happy to support it. I'm not sure what version of Visual Basic this is written in. If they are using .NET, it's probably not too bad, depending on how much code is Windows-specific. If they're using vb6, that would most likely require major code changes.

Let me know if I'm missing anything there.
