### ISSUE TITLE
Pharaoh (1999)

### ISSUE THREAD

**Issue by ddlyarcher** [luxtorpeda-dev/packages#832]
### Project Link

https://github.com/Banderi/Ozymandias

### Project License

AGPL3

### Steam App Ids

https://store.steampowered.com/app/564530/Pharaoh__Cleopatra/

### Additional Context

The remake is coming out soon.  People will be wanting to play the old one as well.

**Comment by d10sfan** [comment]
@ddlyarcher Thanks, added in https://github.com/luxtorpeda-dev/packages/commit/70a6b68b953d416c98a8bf7b9a4959b391dec6e3
