### ISSUE TITLE
AGS-Engine Adventure Game Studio would be verry cool

### ISSUE THREAD

**Issue by SaschaVasarrhelyi** [luxtorpeda-dev/packages#834]
### Project Link

https://github.com/luxtorpeda-dev/luxtorpeda#installation-using-tarball

### Project License

I don't know

### Steam App Ids

https://github.com/luxtorpeda-dev/luxtorpeda#installation-using-tarball

Many Games

### Additional Context

I see the verry large set of different AGS Games and find it cool to have an option to set AGS Games manual, because of the many, many different games created with AGS. In the last build i don't can see an option for an AGS Game and thats sad.
I know that ScummVM had that feature but the Engine of AGS are often outdated.
I were be cool if the AGS- Engine from Snap can be use, because there you can install the dev- branch or stable or whatever and than the Engine are never outdated.
I have many AGS Games on Steam they run better with the native AGS- Engine as with Wine/ Proton.

**Comment by d10sfan** [comment]
@SaschaVasarrhelyi please update the issue description with the project link (usually GitHub or the website of the engine, not this project), along with some examples of games that would play with this engine.

**Comment by SaschaVasarrhelyi** [comment]
Hi d10sfan,

sorry for the late answer.

I see today an other User try to make the same question in 2019. I had overseen before i make the request.

The request from me can be close, but it's my foult, i couldn't find my request to close it.

Sorry for that.

Greetings

Sascha
