### ISSUE TITLE
Custom masterserver for UT2k4

### ISSUE THREAD

**Issue by rea987** [luxtorpeda-dev/packages#839]
### Game

Unreal Tournament 2004: Editor's Choice Edition

### Engine

Unreal Egine 2

### Linux Distribution

Mint 21

### Luxtorpeda Version

61

### Bug description

UT2k4 unable to list servers due to masterserver shutdown.

### Steps To Reproduce

- Launch the game.
- Attempt to list servers.

### Expected Behavior

Game listing mp servers.

### Additional Context

Applying custom masterservers into `~/.ut2004/System/UT2004.ini` enables online server listing:

```
[IpDrv.MasterServerLink]
MasterServerList=(Address="utmaster.openspy.net",Port=28902)
```

Source:

http://beta.openspy.net/en/howto/ut2k-engine/ut2004

**Comment by d10sfan** [comment]
@rea987 Do you see a System.ini file or similar in the ut2004 install directory or in linuxdata? I'm attempting to find where it sources it to store the System.ini file to try and change it automatically. Since for first launch that file will not exist yet (in the user direct0ry>

**Comment by d10sfan** [comment]
It looks like it is called "Default.ini"

Working on a script that'll do it automatically, still need to work on adding the new line for the gamespy (or replacing the url may be easier):

```
cp -rfv linuxdata/System/Default.ini linuxdata/System/Default.ini-backup
grep -v "MasterServerList" linuxdata/System/Default.ini > tmp.ini
mv tmp.ini linuxdata/System/Default.ini
sed -i '/[IpDrv.MasterServerLink]/a MasterServerList=(Address="utmaster.openspy.net",Port=28902)' linuxdata/System/Default.ini
```

**Comment by d10sfan** [comment]
Implemented in https://github.com/luxtorpeda-dev/packages/commit/eb791118d0a5c721dba456207fa08adbce85861c, thanks for the heads up.

**Comment by d10sfan** [comment]
Looks like compile failed for some reason so will look at that when I can

**Comment by d10sfan** [comment]
Fixed, let me know if you run into any issues.
