### ISSUE TITLE
Quake Injector package doesn't seem to set up correct directory structure

### ISSUE THREAD

**Issue by Bisc0tt1** [luxtorpeda-dev/packages#843]
### Game

Quake

### Engine

Quake Injector

### Linux Distribution

Arch Linux

### Luxtorpeda Version

v61

### Bug description

Let me preface this bug report by stating that I do not understand why Luxtorpeda symlinks the game data to share/quake when setting up any engine. I apologise for my ignorance.

When installing the Quake Injector package, Luxtorpeda sets it up within the root of the Quake installation, and then configures it to run the vkquake.sh script as the Quake exectuable, this script launches a native install of vkQuake with share/quake as its basedir. This, however, means that none of the maps downloaded and launched through Quake Injector can actually be loaded, as they are downloaded to the root of the Quake install, while vkQuake is looking within share/quake.

### Steps To Reproduce

1. Install Quake through Steam
2. Launch with Luxtorpeda
3. Choose Quake (original) as launch option
4. Pick Quake Injector as the engine
5. Install any map or map pack through the Quake Injector interface
6. Launch Quake through the same interface
7. You will be unable to play the content you downloaded as it cannot be loaded

### Expected Behavior

The content downloaded through Quake Injector can be accessed.

**Comment by d10sfan** [comment]
The main reason for that unique directory structure is to avoid changing/messing with the "original" game files, but that does lead to strangeness like this. I'll take a look and see what I can do. Does it work if you manually copy the map files to the share/quake directory?

**Comment by Bisc0tt1** [comment]
I took the approach of symlinking a downloaded directory to share/quake, after which launching the corresponding map through Quake Injector worked fine. So yes, copying them over should work as well.

Usually everything for a map/map pack is bundled into a single directory, but Quake Injector does some dependency management of its own and there might be edge cases that can lead to strange behavior if it isn't directly in charge of handling the installation of maps.

**Comment by d10sfan** [comment]
Ok, I should be able to fix this and have it point to the proper directories, I'll update once I have a fix.

**Comment by d10sfan** [comment]
@Bisc0tt1 This should be fixed now, note for the first launch after this, you'll need to delete the config.properties file inside the Quake directory.

Note that some of the packages downloaded could have case sensitivity issues, where the paks are not all lower case, those will have to be fixed manually, but the mods are now being downloaded into the correct directory.

Let me know if you run into any issues.

**Comment by Bisc0tt1** [comment]
Thank you! Everything is working correctly out of the box now.
