### ISSUE TITLE
Alien Vs Predator Save Limit

### ISSUE THREAD

**Issue by Lampwick** [luxtorpeda-dev/packages#846]
With the Windows Steam Version of AVP you can remove the save limit with the launch option "-unlimitedsaves".

Is there a way to add this with the native version and Luxtorpeda?

**Comment by d10sfan** [comment]
Not sure, I'm assuming the code for the saves is somewhere in here: https://github.com/neuromancer/avp/blob/2d5774781dd2ed959a83b2a98ab6f3f26e1dcc51/src/avp/savegame.c

For that limit, but that'd most likely require a code change to the source.

**Comment by d10sfan** [comment]
It looks like changing the areas where the game references NUM_SAVES_FOR_EASY_MODE (and hard, etc) may be the trick, mainly SaveGameAllowed.

Adding a command line switch would be a bit more difficult, so maybe either always allowing all saves, or having a second game option to have unlimited saves.

**Comment by d10sfan** [comment]
I've added that in https://github.com/luxtorpeda-dev/packages/pull/860, let me know if you run into any issues.
