### ISSUE TITLE
New game: Chip's Challenge

### ISSUE THREAD

**Issue by denilsonsa** [luxtorpeda-dev/packages#851]
### Project Link

https://www.muppetlabs.com/~breadbox/software/tworld/

### Project License

GPL2 or later

### Steam App Ids

- https://store.steampowered.com/app/346850/Chips_Challenge_1/
- https://store.steampowered.com/app/348300/Chips_Challenge_2/

### Additional Context

"Tile World" is an SDL re-implementation of the Chip's Challenge game engine. It supports both the Atari Lynx and the Windows releases. It's unknown if it works with the Steam release, but if that release includes `chips.dat` file, it should be good to go.

"Tile World 2" is a fork of the previous project, and it's a re-implementation using Qt. https://tw2.bitbusters.club/

There are even many community level packs (only playable in these re-implementations, because AFAIK the original game doesn't support custom levels): https://bitbusters.club/

Footnote: I haven't tried these projects myself. I just found out about them and I thought they would be a good addition to Luxtorpeda.

**Comment by d10sfan** [comment]
Thanks for the request! I'll take a look when I have a chance

**Comment by d10sfan** [comment]
Sadly it looks like there isn't a way to use this with the steam release. The steam release seems to use the second game's engine, and the steam release does not contain the chips.dat file. 

Let me know if there's anything I'm missing there.
