### ISSUE TITLE
Add support for dsda doom source port to Classic DOOM ports 

### ISSUE THREAD

**Issue by Velonex76** [luxtorpeda-dev/packages#856]
### Project Link

https://github.com/kraflab/dsda-doom

### Project License

GNU General Public 

### Steam App Ids

https://steamdb.info/app/2280/
https://steamdb.info/app/2300/
https://steamdb.info/app/9160/
https://steamdb.info/app/2290/

### Additional Context

This is a fork of prboom+ with many new features, including:

    Heretic, Hexen, MBF21, and Doom-in-Hexen support
    In-game console and scripting
    Full controller support
    Palette-based lightmode for opengl
    Debugging features for testing
    Strict mode for speedrunning
    Various quality of life improvements
    Advanced tools for TASing
    Rewind

**Comment by d10sfan** [comment]
Thanks for the request, I'll take a look at this soon

**Comment by Velonex76** [comment]
Thank you so much for this, I am so happy this works!
