### ISSUE TITLE
SeriousSamClassic-VK change commit 306f653 to ea6826b

### ISSUE THREAD

**Issue by tx00100xt** [luxtorpeda-dev/packages#862]
Hello.
I have removed some duplicate commits that update ci build.yml in https://github.com/tx00100xt/SeriousSamClassic-VK.git repository
Only later I saw that this affected the assembly https://github.com/luxtorpeda-dev/packages/blob/master/engines/serious-engine/build.sh
Commit 306f653 doesn't exist now.
Last commit ea6826b
I apologize for the inconvenience caused

**Comment by d10sfan** [comment]
Thanks, I've done it here: https://github.com/luxtorpeda-dev/packages/commit/6d7c83ee8a0c63ccf05734256a0b61e2fb97ba1f
