### ISSUE TITLE
Scheduled Actions for New Releases & Package Issues

### ISSUE THREAD

**Issue by d10sfan** [luxtorpeda-dev/packages#865]
This comes from https://github.com/luxtorpeda-dev/packages/issues/864#issuecomment-1499661363

RuneScape is one game where the link can become a 404 if the developers release a new version.

The idea here is to create a generic system for checking various engines for issues, and have a github action run scheduled daily (https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#schedule). 

Each engine can have in their env.sh file a list of scripts to run in scheduled mode. This could look like:

```
export ACTION_CHECK="./tests/version_download.sh"
```

These checks to make sure they're using the correct data should look at the json file and grab the download from there (could be something like jq to get the data in shell).

Then there'd be a script to run through and loop all the engines and check for any scripts, run them, and then move on to the next one. This should be done so that one failure would just let the rest keep running.

Success can be ignored, where no result file is stored. For an error, those should be stored in a JSON file. This could be done by the script itself if it encounters an error. All of these should be stored in a specific directory (parent script would give the name of it in a variable).

Then, a node action would be created and run to loop through the files in the folder, and create issues related to them. The name should be a good description (enginename - Issue encountered), coming from the JSON file. As well, any description, including error messages or what was happening. Tags should be created noting it's an engine bug or upgrade (for cases of new release). 

Process should be created to ensure that only one issue is created, so that if the issue is not resolved, we don't keep creating issues. This could be done by checking to see if an issue with the same name has already been created, and if so, refrain from creating.

Common things that asking for if a new release is available should be in a common script, then for the ENV, instead of ACTION_CHECK with a script path (for custom jobs), another variable could be ACTION_RELEASE_CHECK="".

**Comment by JoshuaFern** [comment]
Also don't always assume that a failed download is because the download link changed. It might sometimes be due to unforeseen internet issues. Maybe Runescape servers were down for an hour for maintenance, maybe they're detecting our checks as some sort of bot traffic, maybe there's a routing issue between servers. It could be a false alarm.

**Comment by d10sfan** [comment]
This is now complete, with the latest changes. It'll create an issue like this if it's discovered - https://github.com/luxtorpeda-dev/packages/issues/1017
