### ISSUE TITLE
G String [Source SDK 2013]

### ISSUE THREAD

**Issue by Oreolek** [luxtorpeda-dev/packages#866]
### Project Link

http://moddb.com/mods/g-string

### Project License

commercial

### Steam App Ids

https://store.steampowered.com/app/1224600/G_

**Comment by d10sfan** [comment]
This doesn't give much information. Do you know of a way for the source sdk to play this game natively on Linux? Not every source game can be done that way since many have their own libraries for features they coded in.

**Comment by d10sfan** [comment]
Closing for now,  but feel free to update, thanks!
