### ISSUE TITLE
ScummVM Support

### ISSUE THREAD

**Issue by JoshuaFern** [luxtorpeda-dev/packages#91]
* Project link: https://github.com/scummvm/scummvm
* Project license: GPLv2
* Does it work on 64-bit only Linux: YES
* Is source code available?: YES
* Is source code stored in Git?: YES
* List of Steam AppIds of supported games: https://store.steampowered.com/curator/35667778/

## Additional information

This represents an effort to merge Roberta into Luxtorpeda https://github.com/dreamer/roberta

One feature that was never implemented into Roberta was support for ResidualVM. I believe there's only 2 games currently on Steam that could be played with it at this time.

**Comment by d10sfan** [comment]
scummvm and residualvm support have been added. This adds The Longest Journey and Beneath a Steel Sky as supported games. The default engines have also been set, so if a game that is supported by one of those engines is not listed, then when the game is launched with luxtorpeda set, it'll ask which engine you want to use.

I tested both of those, plus the Broken Sword Original (has to load the DLC) and it seemed to work pretty well from a quick test.
