### ISSUE TITLE
Anodyne: FNA Edition

### ISSUE THREAD

**Issue by flibitijibibo** [luxtorpeda-dev/packages#917]
### Project Link

https://github.com/flibitijibibo/AnodyneFNA

### Project License

https://github.com/flibitijibibo/AnodyneFNA/blob/master/LICENSE.md

### Steam App Ids

- https://steamdb.info/app/234900/

### Additional Context

This is a port of a port of Anodyne 1, which originally shipped via Adobe AIR (yech). This is FNA-based and includes full support for controllers with no setup required, and includes support for Steam achievements.

See the [latest release](https://github.com/flibitijibibo/AnodyneFNA/releases/tag/23.05.17) for more details.

**Comment by d10sfan** [comment]
Thanks very much for the package request! And glad to see your interest in luxtorpeda

I've created a PR here https://github.com/luxtorpeda-dev/packages/pull/918, if you'd like to take a look. This uses the release binaries and I was able to test running the game locally and it worked well after this.
