### ISSUE TITLE
dosbox-staging Support

### ISSUE THREAD

**Issue by JoshuaFern** [luxtorpeda-dev/packages#92]
* Project link: https://github.com/dosbox-staging/dosbox-staging
* Project license: GPLv2
* Does it work on 64-bit only Linux: YES
* Is source code available?: YES
* Is source code stored in Git?: YES
* List of Steam AppIds of supported games: https://store.steampowered.com/curator/35328265/

## Additional information

This represents an effort to merge Boxtron into Luxtorpeda https://github.com/dreamer/boxtron

We could use the upcoming engine selector feature to support vanilla DOSBox or other forks.

**Comment by d10sfan** [comment]
Initial support has been added. There's a simple shell script that takes the arguments from the original dosbox load and formats them for Linux use and then runs it. So far, it seems to work well.
