### ISSUE TITLE
64 bit support for Unreal Gold

### ISSUE THREAD

**Issue by rea987** [luxtorpeda-dev/packages#922]
### Project Link

https://www.oldunreal.com/

### Project License

Proprietary

### Steam App Ids

- https://steamdb.info/app/13250/

### Additional Context

Latest version of OldUnreal patch (v227j) supports x64, SDL2 and ARM. XOpenGL, its default graphic renderer for Linux is a bit problematic though; better keep OpenGL renderer instead. Support for SDL2 makes _sdlcl_ and _sdl12-compat_ unnecessary for Unreal Gold. Also, v227j seems to offer better compatibility with new mods.

https://www.oldunreal.com/downloads/unreal/oldunreal-patches-for-unreal-latest-ver.j/

https://www.oldunreal.com/patch/unreal/oldunreal/UnrealPatch227j.7z

**Comment by d10sfan** [comment]
@rea987 It looks like people have some issues with the 64-bit version: https://github.com/luxtorpeda-dev/packages/issues/798

Are you able to run it?

**Comment by rea987** [comment]
> Are you able to run it?

@d10sfan Yes, after installing [libxmp4](https://packages.ubuntu.com/jammy/libxmp4) from distro repos and copying additional libraries from `../Unreal Gold/Help/convenience_libs/System64` into `../Unreal Gold/System64`, the game launch and runs fine by running `../Unreal Gold/System64/UnrealLinux.bin`.

For the additional libraries, you need to extract `../Unreal Gold/Help/convenience_libs.tar.bz2`.

Distro: Mint 21 (Ubuntu 22.04 based)
Kernel: 6.2.0-10007-tuxedo x86_64
CPU: AMD Ryzen 7 4800H
GPU: AMD Radeon RX Vega 6 (integrated)
Mesa: 22.0.5

**Comment by rea987** [comment]
Also, AA should be disabled for OpenGL and XOpenGL renderers as v227j contains a bug that renders wireframes for invisible objects when there's a lightning. At least for the systems using Mesa. Same goes for UT99 v469c.

https://www.oldunreal.com/phpBB3/viewtopic.php?p=101084#p10108
https://www.oldunreal.com/phpBB3/viewtopic.php?p=101132#p101132

**UnrealLinux.ini**

`[OpenGLDrv.OpenGLRenderDevice]`
`UseAA=False`

`[XOpenGLDrv.XOpenGLRenderDevice]`
`UseAA=False`

**Comment by d10sfan** [comment]
I'll work on adding an additional option for 64-bit

For AA, like the other one, this should be fixed in newer mesa versions.

**Comment by d10sfan** [comment]
I've added an option for this in https://github.com/luxtorpeda-dev/packages/commit/01f25871434f89c751a59655645e9c7e03a46080
