### ISSUE TITLE
Disabling AA for UT99

### ISSUE THREAD

**Issue by rea987** [luxtorpeda-dev/packages#923]
### Game

Unreal Tournament: Game of the Year Edition

### Engine

Unreal Engine 1

### Linux Distribution

Mint 21

### Luxtorpeda Version

63

### Bug description

UT99 v469c shows unintended wireframes for invisible objects when AA is active.

### Steps To Reproduce

1. Run UT99 with v469c patch.
2. Fire a gun causes lightning such as Shock Rifle into a wall.
3. Observe wireframes from the impact.

### Expected Behavior

No wireframes for invisible objects.

### Additional Context

https://github.com/luxtorpeda-dev/packages/issues/922#issuecomment-1566215742

**UnrealTournament.ini** within System64 should be edited like the following. It is not possible to disable AA withing in-game settings.

`[OpenGLDrv.OpenGLRenderDevice]`
`UseAA=False`

`[XOpenGLDrv.XOpenGLRenderDevice]`
`UseAA=False`

**Comment by d10sfan** [comment]
It looks like this is fixed in newer mesa versions, so this should be fine to keep enabled: https://gitlab.freedesktop.org/mesa/mesa/-/issues/7537

You can disable it locally if you need to.
