### ISSUE TITLE
Add Midnight Witch

### ISSUE THREAD

**Issue by Rathmox** [luxtorpeda-dev/packages#924]
### Feature Request

There is a new game named "Midnight Witch", made with ren'py with a native Linux version. It works the same as Doki Soki Litterature Club (but may need chmod +x)

### Solution

Adding the game to luxtorpeds

### Additional Context

Game page: https://store.steampowered.com/app/2336180/Midnight_Witch/

**Comment by d10sfan** [comment]
Nice!  Thanks for testing

I've added direct support for that game with https://github.com/luxtorpeda-dev/packages/commit/f9cccf3d15a229b4a1cd81de4b31792d7c43262a

so that if you launch it it should go into ren'py automatically.
