### ISSUE TITLE
Steam achievements not working in Doom 3: BFG Edition

### ISSUE THREAD

**Issue by EmperorPenguin18** [luxtorpeda-dev/packages#926]
### Linux Distribution

SteamOS

### Luxtorpeda Version

Latest

### Bug description

When choosing classic-rbdoom-3-bfg it says Steam achievements are supposed to work, but if I beat the first level of Ultimate Doom nothing happens. I think it might be related to this https://steamcommunity.com/app/208200/discussions/0/1752394282892669701/ which is the Open Platform Binaries but I tried that and it still didn't work.

### Steps To Reproduce

Beat the first level of Ultimate Doom

### Expected Behavior

Get the achievement "Neophyte"

**Comment by d10sfan** [comment]
I was able to get that achievement at one point. Can you provide a log of running steam in a terminal window and then copying the output to pastebin or a file and uploading it here?

**Comment by EmperorPenguin18** [comment]
https://pastebin.com/dTzMuTET

**Comment by EmperorPenguin18** [comment]
The lib folder does populate with a symlink, but now the game won't launch.
https://pastebin.com/9NdUc0uh

**Comment by d10sfan** [comment]
Thanks, I'll take a look and let you know once I have more information.

**Comment by d10sfan** [comment]
I created an issue related to this https://github.com/MadDeCoDeR/Classic-RBDOOM-3-BFG/issues/100, as I can replicate it on the latest and unsure where the problem is.

**Comment by d10sfan** [comment]
@EmperorPenguin18 For now, to ensure that the game launches, I've removed OpenPlatform from use in this commit: https://github.com/luxtorpeda-dev/packages/commit/d986617c2ec39d74c70fba3efb5cfd9f5da2b4b5

Note that there isn't anything stopping anyone from attempting to add it themselves, and if anyone figures out the issue, I'd be happy to add it back. It seems to be a crash somewhere in OpenPlatform, but there's nothing I can do about it from what I can tell.

Note to get the new updates, you'll need to be on luxtorpeda client 65 or above.

If this changes, I'll make sure to update this issue so you get notified. Let me know if there's anything else you need.

**Comment by d10sfan** [comment]
> A little note for Open Platform on Linux. For some reason the Steam Overlay doesn't work in desktop Mode, also if you want to make sure the Open Platform have been installed and loaded properly check DOOM 3's Multiplayer Menu. In that menu if you check your name it must be your Steam Public User Name and not you System user name

Thanks! That's a nice way to detect that the steam part is working, before I tried to test it with causing an achievement to work, but that's harder to replicate.

**Comment by d10sfan** [comment]
@EmperorPenguin18 I've updated the classic engine here and it's working now out of the box, and I've restore the text about the achievements. It looks like the lib directory wasn't being setup quite right, so I fixed that and it's working well now.
