### ISSUE TITLE
Duke Nukem 2 - Missing Game Data

### ISSUE THREAD

**Issue by JoshuaFern** [luxtorpeda-dev/packages#930]
### Game

240180

### Engine

rigelengine

### Linux Distribution

NixOS/Flatpak

### Luxtorpeda Version

65.0.1

### Bug description

Rigelengine is not able to find the game data automatically, prompting the user to find it. It resides in one directory up.

### Steps To Reproduce

1. Start the game.
2. The game now prompts you to select the game's data directory.
3. Go one directory up and start the game.
4. It now will remember the directory you picked in the future.

### Expected Behavior

It should automatically pick the correct data directory.

### Additional Context

Rigelengine is being installed in the Dosbox directory, perhaps it ought to be installed in the base directory instead.

**Comment by d10sfan** [comment]
I believe this should be fixed in https://github.com/luxtorpeda-dev/packages/commit/6de5e09e72e39e56794f161c87b7dd7d6d0672bf but I don't own the game. Can you try that and let me know if it's fixed? If not, if you could provide a log.

**Comment by JoshuaFern** [comment]
Thanks, seems to work fine.
