### ISSUE TITLE
Homeworld - Stretched Resolution

### ISSUE THREAD

**Issue by JoshuaFern** [luxtorpeda-dev/packages#932]
### Game

https://store.steampowered.com/app/244160/Homeworld_Remastered_Collection/

### Engine

HomeworldSDL

### Linux Distribution

NixOS/Flatpak

### Luxtorpeda Version

65.0.1

### Bug description

This engine starts in an unusable stretched aspect ratio. See the screenshot: https://steamcommunity.com/sharedfiles/filedetails/?id=2989866097

### Steps To Reproduce

Start the game.

### Expected Behavior

The game should not be stretched.

### Additional Context

* Using the window manager (i3) to try different modes, sizes, etc. no effect.
* As seen in the screenshot, resolution is blank in the menus and not changeable. 
* This is stretching across a 21:9 screen which makes it look awful.

**Comment by d10sfan** [comment]
Does the Gardens of Kadesh option work better? I remember that one having some more features.

**Comment by JoshuaFern** [comment]
> Does the Gardens of Kadesh option work better? I remember that one having some more features.

It absolutely does. Are you thinking of just removing HomeworldSDL and just having Gardens of Kadesh? I think that's acceptable unless there's something unique to HomeworldSDL that people could benefit having the option.

**Comment by d10sfan** [comment]
The two projects do have some parallel development, but Gardens does has a better feature set. I don't think it hurts anything to offer both, although Gardens does seem to be a better option.
