### ISSUE TITLE
Master of Orion 2 can be added with Dosbox as the default engine

### ISSUE THREAD

**Issue by JoshuaFern** [luxtorpeda-dev/packages#934]
### Game

https://store.steampowered.com/app/410980/Master_of_Orion_2/

### Engine

dosbox-staging

### Linux Distribution

NixOS/Flatpak

### Luxtorpeda Version

65.0.1

### Bug description

Seems to work fine with Dosbox.

**Comment by d10sfan** [comment]
Thanks, this has been added in https://github.com/luxtorpeda-dev/packages/commit/7f88a8615dca2a5fbe35e58fa8f6348f321a1941
