### ISSUE TITLE
Godot Engine for Cruelty Squad

### ISSUE THREAD

**Issue by rea987** [luxtorpeda-dev/packages#939]
### Project Link

https://github.com/godotengine/godot

### Project License

MIT License

### Steam App Ids

- https://steamdb.info/app/1388770/

### Additional Context

https://steamcommunity.com/sharedfiles/filedetails/?id=3002059746

https://www.reddit.com/r/CrueltySquad/comments/14vm65j/how_to_port_cruelty_squad_to_native_linux_awesome/

**Comment by d10sfan** [comment]
@rea987 Does this work with the current default Godot option, and copying those libraries it mentions into the right area?

**Comment by d10sfan** [comment]
Thanks for the game, I've added it in https://github.com/luxtorpeda-dev/packages/commit/87a8ce9c9502e4a76ee1ae262be9ad2f24df41a5

Let me know if you have any issues.
