### ISSUE TITLE
Support OpenMW-TES3MP

### ISSUE THREAD

**Issue by JoshuaFern** [luxtorpeda-dev/packages#96]
* Project link: https://github.com/TES3MP/openmw-tes3mp
* Project license:GPLv3
* Does it work on 64-bit only Linux: YES
* Is source code available?: YES
* Is source code stored in Git?: YES
* List of Steam AppIds of supported games:
    - https://steamdb.info/app/22320/

## Additional information

Multiplayer version of OpenMW, it should be very similar to package.

**Comment by d10sfan** [comment]
Complete
