### ISSUE TITLE
Chocolate Doom and Crispy Doom and related engines proper configuration for Steam Cloud support

### ISSUE THREAD

**Issue by hfc2x** [luxtorpeda-dev/packages#971]
### Game

Doom Engine Games (Doom, Doom 2, Final Doom, Heretic, HeXen, Hexen: Deathkings)

### Engine

Chocolate [Doom/Heretic/Hexen], Crispy [Doom/Heretic/Hexen]

### Linux Distribution

Fedora 38

### Luxtorpeda Version

65.1.1

### Bug description

At the time of writing, these games load the wrong configuration files and save game folders, because the engines are configured by default to load config files and saves from the user's `/home` directory.

Chocolate Doom saves its configuration and saves inside `/home/[user]/.local/share/chocolate-doom`, and Crispy Doom in `/home/[user]/.local/share/chocolate-doom`. However, this is a problem, because launching these engines through Steam with Luxtorpeda will load the user's configuration and saves, not the ones related to Steam Cloud. These engines are fully-compatible with the original executables, therefore they're able to make Steam Cloud-compatible save data.

For the games listed, the save files and configuration differ. Using the script that Luxtorpeda uses as a guide, should be as follows in the sections below. Please note that the executables will either be `chocolate-doom`, `chocolate-doom-setup`, `crispy-doom` or `crispy-doom-setup`, depending on what engine the player wants. The name of the config file can either be `chocolate-doom`, or `crispy-doom`:

### DOOM (1993) (https://steamdb.info/app/2280/)

When launching the game, the player is presented with the options "Play DOOM (1993)", which launches the 2019 Bethesda rerelease of the game for modern systems, "Launch DOS version", which is the original 1993 DOS executable (through DOSBox), and "Launch DOS version with classic controls" which launches the DOS executable with alternate keyboard mapping. No idea how Luxtorpeda is supposed to deal with this.

In any case, choosing to launch the game through Luxtorpeda, and using either Chocolate Doom or Crispy Doom (and their setup utilities), the command for using the proper configuration files and Steam saves locations should be as follows: `"$DIR/[executable]" -iwad "$DIR/../base/DOOM.WAD" -savedir "$DIR/../base" -config "$DIR/../base/MOUSE.CFG" -extraconfig "$DIR/[chocolate or crispy]-doom.cfg" "$@"`

If "classic controls" is selected, the launch command should be as follows:
`"$DIR/[executable]" -iwad "$DIR/../base/DOOM.WAD" -savedir "$DIR/../base" -config "$DIR/../base/DEFAULT.CFG" -extraconfig "$DIR/[chocolate or crispy]-doom-alternate.cfg" "$@"`

### DOOM II (https://steamdb.info/app/2300/)

This is a problematic game, because Bethesda decided to merge the above game with [Final Doom](https://steamdb.info/app/2290/info/) and [Master Levels](https://steamdb.info/app/9160/info/), and there's a big list of selectable options when launching the game. These latter games have also been delisted from Steam. When launching the game, the following options are presented, in order:
1. "Play DOOM II": launches Bethesda's 2019 rerelease of the game.
2. "Launch DOOM II (Original)": launches the original 1994 DOS version.
3. "Launch TNT: Evilution (Original)": launches DOS version of Final Doom's Evilution expansion.
4. "Launch The Plutonia Experiment (Original)": launches DOS version of Final Doom's Plutonia expansion.
5. "Launch Master Levels (Original)": launches DOS version of Master Levels for Doom 2.

The problem with all of these is that all of them require different launch parameters. For the original Doom 2, the Chocolate Doom parameters would be as follows:
`"$DIR/[executable]" -iwad "$DIR/../base/DOOM2.WAD" -savedir "$DIR/../base" -config "$DIR/../base/DEFAULT.CFG" -extraconfig "$DIR/[chocolate or crispy]-doom.cfg" "$@"`

TNT: Evilution would be the following:
`"$DIR/[executable]" -iwad "$DIR/../finaldoombase/TNT.WAD" -gameversion final -savedir "$DIR/../finaldoombase" -config "$DIR/../finaldoombase/DEFAULT.CFG" -extraconfig "$DIR/[chocolate or crispy]-doom.cfg" "$@"`

Plutonia would be the following:
`"$DIR/[executable]" -iwad "$DIR/../finaldoombase/PLUTONIA.WAD" -gameversion final -savedir "$DIR/../finaldoombase" -config "$DIR/../finaldoombase/DEFAULT.CFG" -extraconfig "$DIR/[chocolate or crispy]-doom.cfg" "$@"`

Master Levels requires a completely different engine, or to be ran through DOSBox, because it requires a separate launcher in itself (will make a separate issue for this one with an engine suggestion).

### Final Doom (https://steamdb.info/app/2290/)
As stated above, this game is delisted. However, it's still available to people who purchased the game beforehand. Launching the game presents 4 options, similar to Doom 2 above:
1. "Play Final DOOM": launches Plutonia expansion with original 1995 DOS executable.
2. "Launch Plutonia Mission with classic controls": same as above, but with alternate button mapping.
3. "Launch Final Doom TNT: Evilution": launches Evilution expansion with original 1995 DOS executable.
4. "Launch Final Doom TNT: Evilution with classic control": same as 2, but Evilution expansion.

The launch command for each of these should be (again, replace `[executable]` with either `chocolate-doom`, `chocolate-doom-setup`, `crispy-doom`, or `crispy-doom-setup`)"
1. `"$DIR/[executable]" -iwad "$DIR/../base/PLUTONIA.WAD" -gameversion final -savedir "$DIR/../base" -config "$DIR/../base/MOUSE.CFG" -extraconfig "$DIR/[chocolate or crispy]-doom.cfg" "$@"`
2. `"$DIR/[executable]" -iwad "$DIR/../base/PLUTONIA.WAD" -gameversion final -savedir "$DIR/../base" -config "$DIR/../base/DEFAULT.CFG" -extraconfig "$DIR/[chocolate or crispy]-doom-alternate.cfg" "$@"`
3. `"$DIR/[executable]" -iwad "$DIR/../base/TNT.WAD" -gameversion final -savedir "$DIR/../base" -config "$DIR/../base/MOUSE.CFG" -extraconfig "$DIR/[chocolate or crispy]-doom.cfg" "$@"`
4. `"$DIR/[executable]" -iwad "$DIR/../base/TNT.WAD" -gameversion final -savedir "$DIR/../base" -config "$DIR/../base/DEFAULT.CFG" -extraconfig "$DIR/[chocolate or crispy]-doom-alternate.cfg" "$@"`

No idea how these could be implemented, so probably 2 and 4 can be axed altogether.

### Heretic: Shadow of The Serpent Riders (https://steamdb.info/app/2390/)
Heretic follows a very similar logic to Doom, although it hasn't had a rerelease. Therefore the only version available to launch is the original 1994 DOS version.

The command to launch the game should be as follows, replacing [executable] with either `chocolate-heretic`, `chocolate-heretic-setup`, `crispy-heretic` or `crispy-heretic-setup`:

`"$DIR/[executable]" -iwad "$DIR/../base/HERETIC.WAD" -savedir "$DIR/../base" -config "$DIR/../base/HERETIC.CFG" -extraconfig "$DIR/[chocolate or crispy]-heretic.cfg" "$@"`

### Hexen: Beyond Heretic (https://steamdb.info/app/2360/)
There's not much different from Heretic to this one, except for the name of the executables and some of the parameters. The [executable] should be replaced by `chocolate-hexen`, `chocolate-hexen-setup`, `crispy-hexen` or `crispy-hexen-setup`. Launch command should be as follows:

`"$DIR/[executable]" -iwad "$DIR/../base/HEXEN.WAD" -savedir "$DIR/../base/HEXNDATA" -config "$DIR/../base/HEXEN.CFG" -extraconfig "$DIR/[chocolate or crispy]-hexen.cfg" "$@"`

### Hexen: Deathkings of the Dark Citadel (https://steamdb.info/app/2370/)
This is very similar to Hexen above, but with a different launch parameter:

`"$DIR/[executable]" -iwad "$DIR/../base/HEXEN.WAD" -file "$DIR/../base/HEXDD.WAD" -savedir "$DIR/../base/HEXNDATA" -config "$DIR/../base/HEXEN.CFG" -extraconfig "$DIR/[chocolate or crispy]-hexen.cfg" "$@"`

### Steps To Reproduce

1. Launch any of the games listed above with the configuration they currently come with.
2. Observe they save the game/change the settings to the `/home` directory instead of the mentioned Steam saves folder.

### Expected Behavior

The games should load their respective saves and configuration files, as listed above.

### Additional Context

I already tested all of these by modifying the scripts provided when these engines are downloaded, and then launching the games through the Steam launcher. After saving any game, Steam correctly uploads the new save files and updates the Cloud Saves.

**Comment by d10sfan** [comment]
Thanks for the details! I have a ticket that I've been tracking my work off and on of adding cloud support: https://github.com/luxtorpeda-dev/packages/issues/645

I was wondering the best way to handle games like this where there's lots of different options. It sounds like for the doom-based ones, the best option would be to take the engines that keep save game support (compared to something like gzdoom), and let those use the saves.

I could put some sort of note about the saves for these games showing that only those engines support, may be simple to just do a notice.

**Comment by hfc2x** [comment]
> I could put some sort of note about the saves for these games showing that only those engines support, may be simple to just do a notice.

Does this mean a pop up notice as the game is launching? I say because the UI for the Luxtorpeda launcher seems to already indicate if Cloud Saves are supported.

Also, this is unrelated but there's a problem with the provided Chocolate Doom version. It seems it's a very ancient build that had broken FluidSynth support. Should I open a new issue for this?

**Comment by d10sfan** [comment]
Yes, probably in that same popup where you can pick the engine.

I've updated chocolate doom to the latest from their branch, let me know how that goes, I was able to test it with a soundfont and worked well.

**Comment by hfc2x** [comment]
By the way, Crispy Doom is not showing for DOOM (1993), DOOM II and Final Doom. Is this a bug, or just that the engine suggestion was never made? (If it wasn't, I can make it in a separate issue, but seeing it's already added for other games, it shouldn't be a problem).

**Comment by d10sfan** [comment]
Great! For crispy doom, feel free to create a new issue in this repo for additional support and I'll take a look when I can

**Comment by d10sfan** [comment]
Thanks for all the details here, that helped. I've implemented cloud saves for all the games here but final doom. For this, enable the cloud saves feature in the client config or add the environment variable, and then it'll use the savedir.

Let me know if you run into any issues.

**Comment by hfc2x** [comment]
> I've implemented cloud saves for all the games here but final doom.

Is this because it's unlisted? If so, I can test it myself and then figure out how to make a pull request that enables the configuration for both Final Doom and Master Levels (#1009) , since I have them on my library.

**Comment by d10sfan** [comment]
Right, I don't have a way to test the unlisted ones, so a pull request would be welcome.

I've fixed the issue with crispy-doom not running the proper binary for hexen. is that save dir issue you're running into only with crispy doom and hexen, or for others as well?

**Comment by d10sfan** [comment]
I believe I've fixed the issue with the save dir for crispy doom and the heretic/hexen games. Can you try again and let me know? Thanks!

**Comment by hfc2x** [comment]
Okay, I've tested at the very least Doom 2 (https://steamdb.info/app/2300/), Heretic and Hexen with the Crispy engines. Heretic works perfectly now, no issues, and detects proper saves and is also able to update cloud saves.

Hexen is not working properly. The save folder is set to `../base` instead of `../base/HEXNDATA`, which is the actual cloud saves folder.

Doom 2 is not working properly. It's saving both its configuration and saves to `~/.local/crispy-doom`, therefore nothing is being updated on Steam cloud.

I haven't had time to test the other games yet.

**Comment by d10sfan** [comment]
Thanks for testing, I've fixed hexen games, if you can try those again.

I'm not switching the config files to be uploaded to steam cloud, since those could act differently on different systems (such as settings for a steam deck versus a desktop). But now the saves should work.

**Comment by hfc2x** [comment]
I'll test in a while and report back.

The configuration files are not actually uploaded to Steam cloud. It's just the save files (just checked this to make sure), so I don't think this should be an issue.
