### ISSUE TITLE
Crispy Doom for DOOM (1993), DOOM II and Final Doom

### ISSUE THREAD

**Issue by hfc2x** [luxtorpeda-dev/packages#974]
### Project Link

https://github.com/fabiangreffrath/crispy-doom

### Project License

GPL v2

### Steam App Ids

- https://steamdb.info/app/2280/
- https://steamdb.info/app/2300/
- https://steamdb.info/app/2290/

### Additional Context

Final Doom is currently delisted, but still available to users that had purchased it in the past.

Crispy Doom is a fork of Chocolate Doom, which remains fully-compatible with it in terms of save game files, configuration files, netplay, etc. It features rendering enhancements, such as higher resolutions and brightmaps, and also includes a plethora of optional quality-of-life enhancements to gameplay.

Crispy Doom is also fully-compatible with Steam Cloud saves, but requires specific configuration for this to work. See #971.

**Comment by d10sfan** [comment]
Thanks, looks like crispy doom is being built but isn't being supported for those games, should hopefully be a simple thing, I'll take a look when I have a chance

**Comment by d10sfan** [comment]
I've added this in https://github.com/luxtorpeda-dev/packages/commit/a475db0b3c4efe2ea16d85f38b133cfd31f51527

Let me know if you run into any issues
