### ISSUE TITLE
dhewm3 configuration for Steam Cloud support

### ISSUE THREAD

**Issue by hfc2x** [luxtorpeda-dev/packages#975]
### Game

Doom 3

### Engine

dhewm3

### Linux Distribution

Fedora 38

### Luxtorpeda Version

65.1.1

### Bug description

Not much of a bug, just that with the current default configuration provided with dhewm3, the engine uses a different save location than Steam, which prevents Steam Cloud saves from being used and updated. With the default settings, the save files are located in `/home/[user]/.local/share/dhewm3/[game]/savegames`, therefore Steam does not load these.

A disclaimer needs to be made, however, because while the saves I've tested and have worked with work fine for me (interchangeable between Doom3.exe and dhewm3), the author [has said](https://github.com/dhewm/dhewm3/issues/216#issuecomment-450608624) that they're not sure this won't cause any issues.

In any case, the `run-dhewm3.sh` file provided with Luxtorpeda needs to be rewritten as such:
```
#!/bin/bash

if ! [[ -z "${LUX_STEAM_DECK}" ]]; then
    if [ ! -f ~/.config/dhewm3/base/dhewm.cfg ]; then
        if [ ! -d ~/.config/dhewm3/base ]; then
            mkdir -p ~/.config/dhewm3/base
        fi

        echo -e "seta r_fullscreen \"1\"" >> ~/.config/dhewm3/base/dhewm.cfg
        echo -e "seta r_mode \"-1\"" >> ~/.config/dhewm3/base/dhewm.cfg
        echo -e "seta r_customHeight \"800\"" >> ~/.config/dhewm3/base/dhewm.cfg
        echo -e "seta r_customWidth \"1280\"" >> ~/.config/dhewm3/base/dhewm.cfg
    fi

    if [ ! -f ~/.config/dhewm3/d3xp/dhewm.cfg ]; then
        if [ ! -d ~/.config/dhewm3/d3xp ]; then
            mkdir -p ~/.config/dhewm3/d3xp
        fi

        echo -e "seta r_fullscreen \"1\"" >> ~/.config/dhewm3/d3xp/dhewm.cfg
        echo -e "seta r_mode \"-1\"" >> ~/.config/dhewm3/d3xp/dhewm.cfg
        echo -e "seta r_customHeight \"800\"" >> ~/.config/dhewm3/d3xp/dhewm.cfg
        echo -e "seta r_customWidth \"1280\"" >> ~/.config/dhewm3/d3xp/dhewm.cfg
    fi
fi

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"

export LD_LIBRARY_PATH="$DIR/lib:$LD_LIBRARY_PATH"
"$DIR/dhewm3" +set fs_basepath "$DIR" +set fs_savepath "$DIR" #+set fs_configpath "$DIR"
```

The final parameter (`fs_configpath`) is commented out because dhewm3 might use its own special settings, which are probably incompatible with Doom3.exe. However, even when uncommenting the `fs_configpath` parameter hasn't given me (or vanilla Doom3.exe) any apparent issues.

### Steps To Reproduce

1. Launch Doom 3 from Steam with forced compatibility with Luxtorpeda
2. Saves will be loaded from install folder at first, but will be copied over to `/home/[user]/.local/share/dhewm3/[game]/savegames` upon saving the game.

### Expected Behavior

Steam should be able to detect and update Steam Saves.

### Additional Context

I've extensively tested if this works, and it does. The saves created by dhewm3 seem to be fully compatible with Doom3.exe. They're detected by Steam and Steam Cloud gets properly updated when the game is saved. However, as the author of the source port has said, there's no guarantee this won't cause issues.

That being said, I have yet to encounter any issues with the saves created with dhewm3 when playing with the original Doom3.exe.

**Comment by d10sfan** [comment]
Thanks for figuring that out! I've added it in https://github.com/luxtorpeda-dev/packages/commit/2f0e61601a4042f947d13f6b79b2fa7dbe9d28d8

Should work for the main game and the expansion as well.

**Comment by d10sfan** [comment]
Note that to use the steam cloud feature, you'll need to follow the enable_steam_cloud option: https://github.com/luxtorpeda-dev/luxtorpeda#configuration
