### ISSUE TITLE
rottexpr for Rise of the Triad: Ludicrous Edition

### ISSUE THREAD

**Issue by rea987** [luxtorpeda-dev/packages#976]
### Project Link

https://github.com/LTCHIPS/rottexpr

### Project License

GPLv2

### Steam App Ids

https://steamdb.info/app/1421490/

**Comment by d10sfan** [comment]
It looks like `DARKWAR.RTL` is missing from the assets, if I look at the demo for this game at least. Do you own this game and are able to play it with rottr?

**Comment by rea987** [comment]
@d10sfan No, I am waiting a big enough discount.

**Comment by d10sfan** [comment]
Ok, for now, I'll close this, but if you find it working, let me know and I can add support
