### ISSUE TITLE
Raze (Blood, Duke3d, Shadow Warrior) won’t load, crashes SteamOS on Steam Deck

### ISSUE THREAD

**Issue by Arkaium** [luxtorpeda-dev/packages#980]
### Linux Distribution

Steam OS

### Luxtorpeda Version

Latest (66?)

### Bug description

Hi, not sure which version this was introduced in, but I recently installed a 2TB SSD in my Steam Deck and imaged from scratch. When I tried to play Build engine games using Luxtorpeda, Raze 39 is installed and the game boots, but it never shows any game content. It either stays black indefinitely or in the case of Duke3D it makes you pick the campaign first then stays black. Pressing ENTER seems to soft reset the system, or at least crash Steam OS in game mode. I also tried to do all of this in Desktop mode to no effect/difference.

I used to be able to play these games via Raze, and they work (albeit not as well) without compatibility mode, so something recent seems to have broken? Thank you!!!

### Steps To Reproduce

Installing and running any Raze compatible game using Luxtorpeda. None seem to run.

### Expected Behavior

I successfully ran all of these games using Raze and Luxtorpeda a few months ago

**Comment by d10sfan** [comment]
Moving this to the packages repo since its more related to that not the client.

I'll take a look at this when I have a chance and let you know what I find

**Comment by Arkaium** [comment]
Sorry I posted this to the other GitHub for luxtorpeda too and then saw you reply to a big post there that this was the right one so I double dipped. Appreciate luxtorpeda so much, thanks for maintaining it

**Comment by d10sfan** [comment]
Thanks and no worries :) 

I've been able to replicate this on my desktop but not sure about a fix at this point. I'll update when I know more

**Comment by d10sfan** [comment]
I was able to replicate this with the linux release from the raze project as well, so it does not seem related to lux directly. I created an issue with the upstream project, so hopefully that'll yield something.

https://github.com/ZDoom/Raze/issues/986

I'll close this for now, but I'll update once I have more information, thanks for reporting!

**Comment by d10sfan** [comment]
I discovered that raze version 1.6.2 does not have this issue, so I've downgraded luxtorpeda to use that version.

If you try to launch one of those games again it should work, while waiting for upstream to take a look. https://github.com/luxtorpeda-dev/packages/commit/1e7ef6915ef4f76c51721c762c8a4264684eb033
