### ISSUE TITLE
DREAMM game testing

### ISSUE THREAD

**Issue by Jpxe** [luxtorpeda-dev/packages#983]
## Works
- Escape from Monkey Island - Ok! - sound works, keyboard input works, starts in a window.

## Doesn't work. Arguments and path issues?
Seems to be issues with command line arguments and paths.

- Afterlife - Launching with DREAMM seems to crash Luxtorpeda. Error log: https://gist.github.com/Jpxe/c5d6007b0b059ea0a54ea558c3a88129
- Indiana Jones and the Infernal Machine - Also crashes. Error log: https://gist.github.com/Jpxe/3f60a812ba0d10e6549637c072e27029
- Maniac Mansion - Also crashes. Error log:  https://gist.github.com/Jpxe/0d44df4268a20528c1a76c2ef99289bf
- Star Wars: Dark Forces - Also crashes. Error log: https://gist.github.com/Jpxe/1d58508bcf642a9eb052aa83d89ccf2f
- Dark Forces II - Also crashes. Error log: https://gist.github.com/Jpxe/278c0cae749609a094b5ab3160e47a01
- Mysteries of the Sith - Crashes. Error log: https://gist.github.com/Jpxe/a908b5b7d5c5570f59b7c0bc734ca95f
- Rebel Assault - Crashes. Error log: https://gist.github.com/Jpxe/c3cc4d37b53f865faa891e9d53e3dcf5
- Tie Fighter - Also crashes. Error log: https://gist.github.com/Jpxe/0c66eeca3fe74cd7e819da13038c8834
- X-Wing - Crashes. Error log: https://gist.github.com/Jpxe/744b6ddf4a44ae63190935bc19bb6933

## Doesn't work. Missing files?
- Outlaws - Doesn't seem to work - "Sorry, DREAMM was unable to recognize any complete games in the provided folder or image files."
- Shadows of the Empire - Doesn't seem to work - "Sorry, DREAMM was unable to recognize any complete games in the provided folder or image files."

**Comment by d10sfan** [comment]
Yeah some/most of steam games may not work because of missing files. For example, scummvm games don't provide the original exe, dreamm needs.

For the crashes, I'll work on stripping out the command line arguments.

**Comment by d10sfan** [comment]
The latest should fix the issue of the crashes, by removing all cmd line arguments.

Let me know how that goes. thanks!
