### ISSUE TITLE
Escape from Monkey Island (2000)

### ISSUE THREAD

**Issue by Jpxe** [luxtorpeda-dev/packages#984]
### Game

https://store.steampowered.com/app/730830/

### Engine

ScummVM

### Linux Distribution

Nobara

### Luxtorpeda Version

66.1.0

### Bug description

ScummVM doesn't launch the game and gives a ""Escape from Monkey Island is not compiled in" error. 

### Steps To Reproduce

1. Launch with ScummVM

### Expected Behavior

To launch correctly

### Additional Context

Game works great in DREAMM so that engine could be added as the default for the game and ScummVM as another option if it's possible to get working.

**Comment by Jpxe** [comment]
Found this on the forum, it used to require the dev build, unsure if that still is the case: https://forums.scummvm.org/viewtopic.php?f=2&t=16399

**Comment by d10sfan** [comment]
It looks like this is because ENABLE_MONKEY4 I suppose is not enable by default. I could enable that, but not sure if there's a reason for it being off by default, stability wise.

Does dreamm work with the steam files?

**Comment by Jpxe** [comment]
Yes DREAMM works with the Steam files

**Comment by d10sfan** [comment]
Yeah it seems like it's not enabled by default on scummvm because it isn't finished, so it probably makes sense to not use it. So it sounds like dreamm works, I've added it as the engine for that game, let me know if that works. Thanks!

**Comment by Jpxe** [comment]
Works great thanks
