### ISSUE TITLE
DREAMM: Afterlife (1996)

### ISSUE THREAD

**Issue by Jpxe** [luxtorpeda-dev/packages#985]
### Game

https://store.steampowered.com/app/557240/

### Engine

DREAMM

### Linux Distribution

Nobara

### Luxtorpeda Version

66.1.0

### Bug description

Doesn't launch.

### Steps To Reproduce

Try to launch

### Expected Behavior

Should launch

### Additional Context

Currently the DREAMM executable is installed in `~/.local/share/Steam/steamapps/common/Afterlife/DOSBOX/`. This won't work since the game executable is in the Afterlife folder above and not in the DOSBOX folder. Either DREAMM needs to be launched with a command line parameter specifying the correct path, which is: `~/.local/share/Steam/steamapps/common/Afterlife/` or dream needs to be installed and launched directly from there. See documentation: https://aarongiles.com/dreamm/docs/v21/#install-standalone

With this fix the Steam version works fine with DREAMM, and it can be added as a default engine.

**Comment by d10sfan** [comment]
What is the command that you used for that? The document dosen't specify from what  I can tell.

**Comment by Jpxe** [comment]
Both of these work: `./dreamm "$HOME/.local/share/Steam/steamapps/common/Afterlife/"` or ` ./dreamm "../"`

**Comment by d10sfan** [comment]
Ok thanks, I've added it in a recent commit, let me know if that works

**Comment by Jpxe** [comment]
It doesn't work yet, there is no run-dreamm-one-up.sh file

**Comment by d10sfan** [comment]
Ah whoops :) I forgot to commit the file, it should work now. Let me know how it goes.

**Comment by Jpxe** [comment]
Now it works
