### ISSUE TITLE
DREAMM: Indiana Jones and the Infernal Machine (1999)

### ISSUE THREAD

**Issue by Jpxe** [luxtorpeda-dev/packages#986]
### Game

https://store.steampowered.com/app/904540/

### Engine

DREAMM

### Linux Distribution

Nobara

### Luxtorpeda Version

66.1.0

### Bug description

Doesn't launch, gives an error.

### Steps To Reproduce

Launch game with Luxtorpeda

### Expected Behavior

Should launch.

### Additional Context
So I was able to fix this error on my machine. According to the error given when running dreamm from the command line, it's looking for a RESOURCE folder and can't find it. In my installation it's  called "Resource" so seems like the regular capitalization error. Renaming it to "RESOURCE" in all caps fixed the issue and the game launches. After this fix the Steam version works fine and dreamm could be recommended as a default engine for this game.

There's another thing that could be considered with this game. When launching this version with dreamm the engine recommends that you should update the game with the latest patch. Steam ships the 1.0 version and dreamm recommends 1.2. I downloaded the patch from http://www.markusegger.at/Software/Games/Jones3D/J3DUpdate1.2.zip and dropped the zip on dreamm. It installed and worked correctly.  Would be neat if this could be automated in Luxtorpeda somehow.

### Relevant log output

```shell
./dreamm: /lib64/libcurl.so.4: no version information available (required by ./dreamm)
Error: File/path /home/jpx/.local/share/Steam/steamapps/common/Indiana Jones and the Infernal Machine/./RESOURCE not found
```

**Comment by d10sfan** [comment]
I can do the fix for the folder. I'm not sure about the patch, that depends if there's a way to give that without manually doing that. Did you see a way to do so?

I've added the fix for the path, let me know if that works for you.

**Comment by Jpxe** [comment]
> I can do the fix for the folder. I'm not sure about the patch, that depends if there's a way to give that without manually doing that. Did you see a way to do so?
I haven't found any way yet. I'll see if I can reach out to the developer and ask him directly.

> I've added the fix for the path, let me know if that works for you.
It works, thanks.

**Comment by d10sfan** [comment]
Great thanks, Feel free to comment here or open a new issue if you receive a response.
