### ISSUE TITLE
TES: Daggerfall not launching

### ISSUE THREAD

**Issue by cewbdex** [luxtorpeda-dev/packages#994]
### Game

TES: Daggerfall

### Engine

DaggerfallUnity

### Linux Distribution

Fedora 38

### Luxtorpeda Version

66

### Bug description

I can't launch the game. I have selected Luxtorpeda and started like with other games, but the game does not launch, I see the Luxtorpeda trying to launch, but then it closes and Steam states I have no game launching. I have tried to download and run DU manually and it works. I have found `last_error.txt` in game directory and attached it, I didn't change anything in regards to runtime, so it should be installed.

### Steps To Reproduce

1. Install TES2
2. Select Luxtorpeda
3. Run TES2

### Expected Behavior

Game should start

### Relevant log output

```shell
Steam Linux Runtime is not installed. Please ensure that it is installed and try again.
```

**Comment by d10sfan** [comment]
The error should have shown in the client, but it's saying that you do not have the steam Linux runtime installed. If you install that in steam and retry it should work. Let me know if you continue to have issues

**Comment by cewbdex** [comment]
![obrazek](https://github.com/luxtorpeda-dev/packages/assets/9021297/baaa27a8-4490-40ce-a260-2bfe1ecc387d)
Maybe it should state which version of runtime, only Scout is missing for me. Does it require that obsolete version?

**Comment by d10sfan** [comment]
Yes that one, that was the name of it before valve recently changed it in their UI, just steam Linux runtime. They recently changed it to have the code names as well, so I can update to match to make it easier to understand

**Comment by cewbdex** [comment]
Could you possibly make it to install it?

**Comment by Jpxe** [comment]
> Could you possibly make it to install it?

I think we could do this using console commands

**Comment by d10sfan** [comment]
> Could you possibly make it to install it?

Looking into that with https://github.com/luxtorpeda-dev/luxtorpeda/issues/238
